export const RIKA_QUAGSIRE = [
	{
		"id": 1,
		"x": "1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "1",
		"y": "0",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "-1",
		"y": "1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "-1",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "1",
		"y": "-2",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": "2",
		"y": "-3",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": "3",
		"y": "-4",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": "1",
		"y": "-3",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": "2",
		"y": "-4",
		"name": "Precipitous Cliffs Earth Power: Power +2",
		"description": "Precipitous Cliffs Earth Power: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 12,
		"x": "3",
		"y": "-5",
		"name": "Precipitous Cliffs Earth Power: Power +2",
		"description": "Precipitous Cliffs Earth Power: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 13,
		"x": "1",
		"y": "-4",
		"name": "Precipitous Cliffs Earth Power: Power +2",
		"description": "Precipitous Cliffs Earth Power: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 14,
		"x": "2",
		"y": "-5",
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": "3",
		"y": "-6",
		"name": "Triage Tank 9",
		"description": "Restores the user’s HP when it is hit by an attack move.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": "1",
		"y": "-5",
		"name": "Hit Poisoned Opp: Special Boost ↑1 9",
		"description": "Increases the user’s Special Moves ↑ Next effect by one rank when its attack move is successful against a poisoned or badly poisoned opponent.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": "2",
		"y": "-6",
		"name": "Grand Entry 2",
		"description": "Raises the user’s Sp. Atk by two stat ranks when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": "-1",
		"y": "2",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": "-2",
		"y": "3",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": "-3",
		"y": "4",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 21,
		"x": "-1",
		"y": "3",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 22,
		"x": "-2",
		"y": "4",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 23,
		"x": "-3",
		"y": "5",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 24,
		"x": "-1",
		"y": "4",
		"name": "Toxic: Accuracy +10",
		"description": "Toxic: Accuracy +10",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 25,
		"x": "-2",
		"y": "5",
		"name": "Toxic: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": "-3",
		"y": "6",
		"name": "Catalyst",
		"description": "Applies the Move Gauge Acceleration effect to the allied field of play the first time the user’s sync move is used each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": "-1",
		"y": "5",
		"name": "Brainpower",
		"description": "The more the user’s Sp. Atk is raised, the more it powers up its sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 28,
		"x": "-2",
		"y": "6",
		"name": "Soften Up 1",
		"description": "Critical hits land more easily when the user attacks with a sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": "2",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": "3",
		"y": "-1",
		"name": "Sand Shelter",
		"description": "Protects the user from damage from a sandstorm.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": "2",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 32,
		"x": "1",
		"y": "1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 33,
		"x": "3",
		"y": "0",
		"name": "Protect: Super Preparation 9",
		"description": "Applies the Supereffective ↑ Next effect to the user when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": "2",
		"y": "1",
		"name": "Sp. Atk +10",
		"description": "Sp. Atk +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 35,
		"x": "1",
		"y": "2",
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": "3",
		"y": "1",
		"name": "Impervious",
		"description": "The user’s stats cannot be lowered.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": "2",
		"y": "2",
		"name": "Ground Zone: P-Moves ↑ & S-Moves ↑ 3",
		"description": "Powers up the user’s moves and sync move when the zone is a Ground Zone.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": "-2",
		"y": "1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": "-3",
		"y": "1",
		"name": "Dauntless",
		"description": "Sp. Atk cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": "-2",
		"y": "0",
		"name": "Precipitous Cliffs Earth Power: Power +2",
		"description": "Precipitous Cliffs Earth Power: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 41,
		"x": "-1",
		"y": "-1",
		"name": "Precipitous Cliffs Earth Power: Power +2",
		"description": "Precipitous Cliffs Earth Power: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 42,
		"x": "-3",
		"y": "0",
		"name": "Precipitous Cliffs Earth Power: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": "-2",
		"y": "-1",
		"name": "I Know I’m Pretty!: Fleet Feet 2",
		"description": "Raises the user’s Speed by two stat ranks when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": "-1",
		"y": "-2",
		"name": "I Know I’m Pretty!: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": "-3",
		"y": "-1",
		"name": "Use Status P-Move: Special Boost ↑2 9",
		"description": "Increases the user’s Special Moves ↑ Next effect by two ranks when its Pokémon uses a status move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": "-2",
		"y": "-2",
		"name": "Adrenaline 1",
		"description": "Reduces the sync move countdown by one the first time the user’s sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": "0",
		"y": "-3",
		"name": "Rock Your World Ground Beam: Power +25",
		"description": "Rock Your World Ground Beam: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": "0",
		"y": "3",
		"name": "Rock Your World Ground Beam: Power +25",
		"description": "Rock Your World Ground Beam: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const ADAMAN_SYLVEON = [
	{
		"id": 1,
		"x": "1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "1",
		"y": "0",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "-1",
		"y": "1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "-1",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "1",
		"y": "-2",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": "2",
		"y": "-3",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": "3",
		"y": "-4",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": "1",
		"y": "-3",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": "2",
		"y": "-4",
		"name": "Giga Impact: Power +2",
		"description": "Giga Impact: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 12,
		"x": "3",
		"y": "-5",
		"name": "Giga Impact: Power +2",
		"description": "Giga Impact: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 13,
		"x": "1",
		"y": "-4",
		"name": "Giga Impact: Power +2",
		"description": "Giga Impact: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 14,
		"x": "2",
		"y": "-5",
		"name": "Attack +10",
		"description": "Attack +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 15,
		"x": "3",
		"y": "-6",
		"name": "Trip Up 9",
		"description": "Lowers the target’s Speed by one stat rank when the user’s attack move against it is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": "1",
		"y": "-5",
		"name": "Hit: Attack ↓ & Defense ↓ 9",
		"description": "Lowers the target’s Attack and Defense by one stat rank when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": "2",
		"y": "-6",
		"name": "Hit: Physical Boost ↑1 9",
		"description": "Increases the user’s Physical Moves ↑ Next effect by one rank when its attack move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": "-1",
		"y": "2",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": "-2",
		"y": "3",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": "-3",
		"y": "4",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 21,
		"x": "-1",
		"y": "3",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 22,
		"x": "-2",
		"y": "4",
		"name": "Baby Blue Play Rough: Power +2",
		"description": "Baby Blue Play Rough: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 23,
		"x": "-3",
		"y": "5",
		"name": "Baby Blue Play Rough: Power +2",
		"description": "Baby Blue Play Rough: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 24,
		"x": "-1",
		"y": "4",
		"name": "Baby Blue Play Rough: Power +2",
		"description": "Baby Blue Play Rough: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 25,
		"x": "-2",
		"y": "5",
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": "-3",
		"y": "6",
		"name": "Catalyst",
		"description": "Applies the Move Gauge Acceleration effect to the allied field of play the first time the user’s sync move is used each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": "-1",
		"y": "5",
		"name": "Haymaker",
		"description": "The more the user’s Attack is raised, the more it powers up the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 28,
		"x": "-2",
		"y": "6",
		"name": "Trainer Sync Redemption 1",
		"description": "Restores one MP for the user’s Trainer the first time its sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": "2",
		"y": "-1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": "3",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 31,
		"x": "2",
		"y": "0",
		"name": "Baby Blue Play Rough: Power +2",
		"description": "Baby Blue Play Rough: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 32,
		"x": "1",
		"y": "1",
		"name": "Baby Blue Play Rough: Power +2",
		"description": "Baby Blue Play Rough: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 33,
		"x": "3",
		"y": "0",
		"name": "Baby Blue Play Rough: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": "2",
		"y": "1",
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": "1",
		"y": "2",
		"name": "Whimsical Acceleration 2",
		"description": "Quickly charges the move gauge when the zone is a Fairy Zone.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": "3",
		"y": "1",
		"name": "Fierce Entry 2",
		"description": "Raises the user’s Attack by two stat ranks when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": "2",
		"y": "2",
		"name": "Fairy Zone Extension 3",
		"description": "Extends the duration of the Fairy Zone when the zone turns into a Fairy Zone while the user is on the field.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": "-2",
		"y": "1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": "-3",
		"y": "1",
		"name": "Unflappable",
		"description": "Prevents the user from flinching.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": "-2",
		"y": "0",
		"name": "Giga Impact: Power +2",
		"description": "Giga Impact: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 41,
		"x": "-1",
		"y": "-1",
		"name": "Giga Impact: Power +2",
		"description": "Giga Impact: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 42,
		"x": "-3",
		"y": "0",
		"name": "Giga Impact: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": "-2",
		"y": "-1",
		"name": "Hurry It Up!: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": "-1",
		"y": "-2",
		"name": "Hurry It Up!: Hit and Heal 9",
		"description": "Applies the Gradual Healing effect to the user when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": "-3",
		"y": "-1",
		"name": "Giga Impact: Move Gauge Refresh 9",
		"description": "Charges the user’s move gauge by one when its move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": "-2",
		"y": "-2",
		"name": "Sinnoh C (Phys) Extension 3",
		"description": "Extends the duration of Sinnoh Circle (Physical) when Sinnoh Circle (Physical) is applied to the allied field of play.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": "0",
		"y": "-3",
		"name": "Return the Favor Soon Fairy Impact: Power +25",
		"description": "Return the Favor Soon Fairy Impact: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": "0",
		"y": "3",
		"name": "Return the Favor Soon Fairy Impact: Power +25",
		"description": "Return the Favor Soon Fairy Impact: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const GRIMSLEY_HONCHKROW = [
	{
		"id": 1,
		"x": "1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "1",
		"y": "0",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "-1",
		"y": "1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "-1",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "1",
		"y": "-2",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": "2",
		"y": "-3",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": "3",
		"y": "-4",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": "1",
		"y": "-3",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": "2",
		"y": "-4",
		"name": "Brave Bird: Power +4",
		"description": "Brave Bird: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 12,
		"x": "3",
		"y": "-5",
		"name": "Brave Bird: Power +4",
		"description": "Brave Bird: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 13,
		"x": "1",
		"y": "-4",
		"name": "Brave Bird: Power +4",
		"description": "Brave Bird: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 14,
		"x": "2",
		"y": "-5",
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": "3",
		"y": "-6",
		"name": "Trip Up 4",
		"description": "Has a chance (50%) of lowering the target’s Speed by one stat rank when the user’s attack move against it is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": "1",
		"y": "-5",
		"name": "Fierce Entry 2",
		"description": "Raises the user’s Attack by two stat ranks when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": "2",
		"y": "-6",
		"name": "Furious Brawn",
		"description": "The more the user’s Attack is raised, the more it powers up the user’s moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": "-1",
		"y": "2",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": "-2",
		"y": "3",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": "-3",
		"y": "4",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 21,
		"x": "-1",
		"y": "3",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 22,
		"x": "-2",
		"y": "4",
		"name": "Fly: Power +4",
		"description": "Fly: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 23,
		"x": "-3",
		"y": "5",
		"name": "Fly: Power +4",
		"description": "Fly: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 24,
		"x": "-1",
		"y": "4",
		"name": "Fly: Power +4",
		"description": "Fly: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 25,
		"x": "-2",
		"y": "5",
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": "-3",
		"y": "6",
		"name": "Potion: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": "-1",
		"y": "5",
		"name": "Brawn Sync 5",
		"description": "Powers up the user’s sync move when its Attack is raised.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 28,
		"x": "-2",
		"y": "6",
		"name": "Super Sync 9",
		"description": "Applies the Supereffective ↑ Next effect to the user after using its sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": "2",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": "3",
		"y": "-1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 31,
		"x": "2",
		"y": "0",
		"name": "Fly: Power +4",
		"description": "Fly: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 32,
		"x": "1",
		"y": "1",
		"name": "Fly: Power +4",
		"description": "Fly: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 33,
		"x": "3",
		"y": "0",
		"name": "Fly: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": "2",
		"y": "1",
		"name": "Fly: Accuracy +5",
		"description": "Fly: Accuracy +5",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 35,
		"x": "1",
		"y": "2",
		"name": "Speed +10",
		"description": "Speed +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 36,
		"x": "3",
		"y": "1",
		"name": "Fly: MP Refresh 5",
		"description": "Has a chance (60%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": "2",
		"y": "2",
		"name": "Opp Fail: Physical Boost ↑2 9",
		"description": "Increases the user’s Physical Moves ↑ Next effect by two ranks when an opponent’s attack move targeting the user misses.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": "-2",
		"y": "1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": "-3",
		"y": "1",
		"name": "Headstrong",
		"description": "Attack cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": "-2",
		"y": "0",
		"name": "Brave Bird: Power +4",
		"description": "Brave Bird: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 41,
		"x": "-1",
		"y": "-1",
		"name": "Brave Bird: Power +4",
		"description": "Brave Bird: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 42,
		"x": "-3",
		"y": "0",
		"name": "Brave Bird: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": "-2",
		"y": "-1",
		"name": "Attack +10",
		"description": "Attack +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 44,
		"x": "-1",
		"y": "-2",
		"name": "It’s Fascinating!: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": "-3",
		"y": "-1",
		"name": "Overwhelm 9",
		"description": "Lowers the target’s Attack by one stat rank when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": "-2",
		"y": "-2",
		"name": "Gobsmack 9",
		"description": "Leaves the target confused when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": "0",
		"y": "-3",
		"name": "Winner Takes Everything Flying Impact: Power +25",
		"description": "Winner Takes Everything Flying Impact: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": "0",
		"y": "3",
		"name": "Winner Takes Everything Flying Impact: Power +25",
		"description": "Winner Takes Everything Flying Impact: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const AS_MISTY_STARMIE = [
	{
		"id": 1,
		"x": "1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "1",
		"y": "0",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "-1",
		"y": "1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "-1",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "0",
		"y": "-2",
		"name": "Sp. Atk +20",
		"description": "Sp. Atk +20",
		"energy": "0",
		"orb": "5",
		"level": "2",
		"color": "divine",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": "0",
		"y": "-3",
		"name": "Piercing Droplets Divine Bubble Beam: Power +50",
		"description": "Piercing Droplets Divine Bubble Beam: Power +50",
		"energy": "0",
		"orb": "5",
		"level": "3",
		"color": "divine",
		"icon": "sync"
	},
	{
		"id": 9,
		"x": "0",
		"y": "-4",
		"name": "1st S-Move: Rainy & Extension 3",
		"description": "Makes the weather rainy the first time the user’s sync move is used each battle. Extends the duration of rainy weather when the weather turns rainy while the user is on the field.",
		"energy": "0",
		"orb": "5",
		"level": "4",
		"color": "divine",
		"icon": "passive"
	},
	{
		"id": 10,
		"x": "0",
		"y": "-5",
		"name": "The Tomboyish Mermaid’s True Power",
		"energy": "0",
		"orb": "5",
		"level": "5",
		"color": "divine",
		"icon": "passive"
	},
	{
		"id": 11,
		"x": "1",
		"y": "-2",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 12,
		"x": "2",
		"y": "-2",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 13,
		"x": "3",
		"y": "-2",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 14,
		"x": "2",
		"y": "-3",
		"name": "Almighty Bubble Beam: Power +4",
		"description": "Almighty Bubble Beam: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 15,
		"x": "3",
		"y": "-3",
		"name": "Almighty Bubble Beam: Power +4",
		"description": "Almighty Bubble Beam: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 16,
		"x": "2",
		"y": "-4",
		"name": "Almighty Bubble Beam: Power +4",
		"description": "Almighty Bubble Beam: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 17,
		"x": "3",
		"y": "-4",
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": "3",
		"y": "-5",
		"name": "Curative Confusion 1",
		"description": "Restores the user’s HP when its attack move is successful against a confused opponent.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 19,
		"x": "1",
		"y": "-4",
		"name": "Baffle Buff 3",
		"description": "Powers up the user’s moves when the target is confused. Powers up the user’s sync move when the target is confused.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 20,
		"x": "2",
		"y": "-5",
		"name": "Kanto C (Spec) Extension 5",
		"description": "Extends the duration of Kanto Circle (Special) when Kanto Circle (Special) is applied to the allied field of play.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 21,
		"x": "-2",
		"y": "2",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 22,
		"x": "-1",
		"y": "2",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 23,
		"x": "-2",
		"y": "3",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 24,
		"x": "-1",
		"y": "3",
		"name": "Almighty Hydro Pump: Power +2",
		"description": "Almighty Hydro Pump: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 25,
		"x": "-1",
		"y": "4",
		"name": "Almighty Hydro Pump: Power +2",
		"description": "Almighty Hydro Pump: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 26,
		"x": "-3",
		"y": "3",
		"name": "Almighty Hydro Pump: Power +2",
		"description": "Almighty Hydro Pump: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 27,
		"x": "-3",
		"y": "4",
		"name": "Almighty Hydro Pump: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 28,
		"x": "-2",
		"y": "4",
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": "-3",
		"y": "5",
		"name": "Hit Confused Opp: Stat ↓2 9",
		"description": "Lowers one of the target’s following stats by two stat ranks at random when the user’s attack move is successful against a confused opponent: Attack, Defense, Sp. Atk, Sp. Def, Speed, accuracy, or evasiveness.",
		"energy": "9",
		"orb": "108",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 30,
		"x": "-2",
		"y": "5",
		"name": "Almighty Hydro Pump: Staggering 9",
		"description": "Makes the target flinch when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": "2",
		"y": "0",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 32,
		"x": "1",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 33,
		"x": "2",
		"y": "1",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": "1",
		"y": "2",
		"name": "Almighty Hydro Pump: Power +2",
		"description": "Almighty Hydro Pump: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 35,
		"x": "1",
		"y": "3",
		"name": "Almighty Hydro Pump: Power +2",
		"description": "Almighty Hydro Pump: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 36,
		"x": "3",
		"y": "0",
		"name": "Sync Regen",
		"description": "Applies the Gradual Healing effect to the user after using its sync move.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": "3",
		"y": "1",
		"name": "Sp. Atk +10",
		"description": "Sp. Atk +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 38,
		"x": "2",
		"y": "2",
		"name": "Hit: Sync Move Boost ↑1 9",
		"description": "Increases the user’s Sync Move ↑ Next effect by one rank when its attack move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 39,
		"x": "3",
		"y": "2",
		"name": "Brainpower",
		"description": "The more the user’s Sp. Atk is raised, the more it powers up its sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": "2",
		"y": "3",
		"name": "Soften Up 1",
		"description": "Critical hits land more easily when the user attacks with a sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 41,
		"x": "-2",
		"y": "0",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 42,
		"x": "-1",
		"y": "-1",
		"name": "Dauntless",
		"description": "Sp. Atk cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": "-3",
		"y": "1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 44,
		"x": "-3",
		"y": "0",
		"name": "Almighty Bubble Beam: Power +4",
		"description": "Almighty Bubble Beam: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 45,
		"x": "-2",
		"y": "-1",
		"name": "Almighty Bubble Beam: Power +4",
		"description": "Almighty Bubble Beam: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 46,
		"x": "-3",
		"y": "-1",
		"name": "Almighty Bubble Beam: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": "-2",
		"y": "-2",
		"name": "Circle: Attack Move DR 2",
		"description": "Reduces damage when the user is hit by an attack move while a circle applies to the allied field of play.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 48,
		"x": "-3",
		"y": "-2",
		"name": "Circle: HP Recovery 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action when a circle applies to the allied field of play.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 49,
		"x": "-1",
		"y": "-3",
		"name": "Team S-Move: Special Boost ↑2 9",
		"description": "Increases the user’s Special Moves ↑ Next effect by two ranks after your team’s sync pair uses their sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 50,
		"x": "-2",
		"y": "-3",
		"name": "Head Start 1",
		"description": "Reduces the user’s sync move countdown by one the first time it enters a battle each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 51,
		"x": "3",
		"y": "-1",
		"name": "Piercing Droplets Divine Bubble Beam: Power +25",
		"description": "Piercing Droplets Divine Bubble Beam: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 52,
		"x": "-3",
		"y": "2",
		"name": "Piercing Droplets Divine Bubble Beam: Power +25",
		"description": "Piercing Droplets Divine Bubble Beam: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const AS_BROCK_ONIX = [
	{
		"id": 1,
		"x": "1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "1",
		"y": "0",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "-1",
		"y": "1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "-1",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "0",
		"y": "-2",
		"name": "Attack +20",
		"description": "Attack +20",
		"energy": "0",
		"orb": "5",
		"level": "2",
		"color": "divine",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": "0",
		"y": "-3",
		"name": "Unbreakable Loyalty Divine Rock Slide: Power +50",
		"description": "Unbreakable Loyalty Divine Rock Slide: Power +50",
		"energy": "0",
		"orb": "5",
		"level": "3",
		"color": "divine",
		"icon": "sync"
	},
	{
		"id": 9,
		"x": "0",
		"y": "-4",
		"name": "1st S-Move: Restore B-Move MP 1",
		"description": "Restores one MP of the user’s buddy move the first time its sync move is used each battle.",
		"energy": "0",
		"orb": "5",
		"level": "4",
		"color": "divine",
		"icon": "passive"
	},
	{
		"id": 10,
		"x": "0",
		"y": "-5",
		"name": "1st Hit: Rock Zone & Extension 3",
		"description": "Turns the field of play’s zone into a Rock Zone the first time the user’s attack move is successful each battle. (A Rock Zone powers up Rock-type attacks.) Extends the duration of the Rock Zone when the zone turns into a Rock Zone while the user is on the field.",
		"energy": "0",
		"orb": "5",
		"level": "5",
		"color": "divine",
		"icon": "passive"
	},
	{
		"id": 11,
		"x": "1",
		"y": "-2",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 12,
		"x": "2",
		"y": "-2",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 13,
		"x": "3",
		"y": "-2",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 14,
		"x": "2",
		"y": "-3",
		"name": "Almighty Rock Slide: Power +2",
		"description": "Almighty Rock Slide: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 15,
		"x": "3",
		"y": "-3",
		"name": "Almighty Rock Slide: Power +2",
		"description": "Almighty Rock Slide: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 16,
		"x": "2",
		"y": "-4",
		"name": "Almighty Rock Slide: Power +2",
		"description": "Almighty Rock Slide: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 17,
		"x": "3",
		"y": "-4",
		"name": "Almighty Rock Slide: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": "3",
		"y": "-5",
		"name": "Overwhelm 9",
		"description": "Lowers the target’s Attack by one stat rank when the user’s attack move against it is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 19,
		"x": "1",
		"y": "-4",
		"name": "Aggravation 1",
		"description": "Raises the chance of inflicting the flinching, confused, or trapped condition with the additional effects of moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 20,
		"x": "2",
		"y": "-5",
		"name": "Sharpened Body 3",
		"description": "Powers up the user’s moves when its Attack is raised.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 21,
		"x": "-2",
		"y": "2",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 22,
		"x": "-1",
		"y": "2",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 23,
		"x": "-2",
		"y": "3",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 24,
		"x": "-1",
		"y": "3",
		"name": "Almighty Stone Edge: Power +2",
		"description": "Almighty Stone Edge: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 25,
		"x": "-1",
		"y": "4",
		"name": "Almighty Stone Edge: Power +2",
		"description": "Almighty Stone Edge: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 26,
		"x": "-3",
		"y": "3",
		"name": "Almighty Stone Edge: Power +2",
		"description": "Almighty Stone Edge: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 27,
		"x": "-3",
		"y": "4",
		"name": "Lithic Acceleration 2",
		"description": "Quickly charges the move gauge when the zone is a Rock Zone.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 28,
		"x": "-2",
		"y": "4",
		"name": "Sync Regen",
		"description": "Applies the Gradual Healing effect to the user after using its sync move.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": "-3",
		"y": "5",
		"name": "Team S-Move: Physical Boost ↑2 9",
		"description": "Increases the user’s Physical Moves ↑ Next effect by two ranks after your team’s sync pair uses their sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 30,
		"x": "-2",
		"y": "5",
		"name": "Haymaker",
		"description": "The more the user’s Attack is raised, the more it powers up the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": "2",
		"y": "0",
		"name": "Sand Shelter",
		"description": "Protects the user from damage from a sandstorm.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 32,
		"x": "1",
		"y": "1",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 33,
		"x": "2",
		"y": "1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": "1",
		"y": "2",
		"name": "Almighty Stone Edge: Power +2",
		"description": "Almighty Stone Edge: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 35,
		"x": "1",
		"y": "3",
		"name": "Almighty Stone Edge: Power +2",
		"description": "Almighty Stone Edge: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 36,
		"x": "3",
		"y": "0",
		"name": "Potion: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": "3",
		"y": "1",
		"name": "Potion: Master Healer 1",
		"description": "Increases the amount of HP restored by the user’s healing moves.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": "2",
		"y": "2",
		"name": "Almighty Stone Edge: Move Gauge Refresh 9",
		"description": "Charges the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 39,
		"x": "3",
		"y": "2",
		"name": "Sentry Entry 6",
		"description": "Raises the user’s Defense by six stat ranks when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": "2",
		"y": "3",
		"name": "Rock-Hard Bond!: Move: Physical Boost ↑2 & Sync Move Boost ↑4",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 41,
		"x": "-2",
		"y": "0",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 42,
		"x": "-1",
		"y": "-1",
		"name": "Headstrong",
		"description": "Attack cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": "-3",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 44,
		"x": "-3",
		"y": "0",
		"name": "Almighty Rock Slide: Power +2",
		"description": "Almighty Rock Slide: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 45,
		"x": "-2",
		"y": "-1",
		"name": "Almighty Rock Slide: Power +2",
		"description": "Almighty Rock Slide: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 46,
		"x": "-3",
		"y": "-1",
		"name": "Attack +10",
		"description": "Attack +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 47,
		"x": "-2",
		"y": "-2",
		"name": "Rock-Hard Bond!: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 48,
		"x": "-3",
		"y": "-2",
		"name": "Rejuvenate 6",
		"description": "Charges the user’s move gauge by six after using its sync move.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 49,
		"x": "-1",
		"y": "-3",
		"name": "Towering Force",
		"description": "The more the user’s Defense is raised, the more it powers up the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 50,
		"x": "-2",
		"y": "-3",
		"name": "Head Start 1",
		"description": "Reduces the user’s sync move countdown by one the first time it enters a battle each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 51,
		"x": "3",
		"y": "-1",
		"name": "Unbreakable Loyalty Divine Rock Slide: Power +25",
		"description": "Unbreakable Loyalty Divine Rock Slide: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 52,
		"x": "-3",
		"y": "2",
		"name": "Unbreakable Loyalty Divine Rock Slide: Power +25",
		"description": "Unbreakable Loyalty Divine Rock Slide: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]