export const ELIO_STAKATAKA = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 0,
		"y": -2,
		"name": "Circle: MG → 2",
		"description": "Quickly charges the move gauge when a circle applies to the allied field of play.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 8,
		"x": 0,
		"y": -4,
		"name": "First Aid 4",
		"description": "Restores the user’s HP by approximately 40% of its maximum HP the first time it is in a pinch each battle.",
		"energy": "10",
		"orb": "120",
		"level": "4",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 9,
		"x": -2,
		"y": -3,
		"name": "Alola C (Defensive) Extension 5",
		"description": "Extends the duration of Alola Circle (Defensive) when Alola Circle (Defensive) is applied to the allied field of play.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 10,
		"x": 0,
		"y": 2,
		"name": "Lithic Healing 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action when the zone is a Rock Zone.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 11,
		"x": 0,
		"y": 4,
		"name": "Rock Zone Extension 3",
		"description": "Extends the duration of the Rock Zone when the zone turns into a Rock Zone while the user is on the field.",
		"energy": "10",
		"orb": "120",
		"level": "4",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 12,
		"x": -2,
		"y": 5,
		"name": "Vigilance",
		"description": "Protects the user against critical hits.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": 1,
		"y": -2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 14,
		"x": 2,
		"y": -3,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 15,
		"x": 1,
		"y": -3,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 16,
		"x": 3,
		"y": -4,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 17,
		"x": 2,
		"y": -4,
		"name": "Smack Down: Power 4",
		"description": "Smack Down: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 18,
		"x": 1,
		"y": -4,
		"name": "Smack Down: Power 4",
		"description": "Smack Down: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 19,
		"x": 3,
		"y": -5,
		"name": "Smack Down: Power 4",
		"description": "Smack Down: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 20,
		"x": 2,
		"y": -5,
		"name": "Smack Down: Move Gauge Refresh 2",
		"description": "Move: Smack Down Has a chance (30%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 21,
		"x": 1,
		"y": -5,
		"name": "Rock Zone: Team Physical DR 2",
		"description": "Reduces physical attack move damage taken by allies when the zone is a Rock Zone.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 22,
		"x": 3,
		"y": -6,
		"name": "Defense 20",
		"description": "Defense 20",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 23,
		"x": 2,
		"y": -6,
		"name": "Smack Down: Move Gauge Refresh 9",
		"description": "Move: Smack Down Charges the user’s move gauge by one when its move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -2,
		"y": 2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 25,
		"x": -3,
		"y": 3,
		"name": "Sand Shelter",
		"description": "Protects the user from damage from a sandstorm.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -1,
		"y": 2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 27,
		"x": -2,
		"y": 3,
		"name": "Smack Down: Power 4",
		"description": "Smack Down: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 28,
		"x": -3,
		"y": 4,
		"name": "Smack Down: Power 4",
		"description": "Smack Down: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 29,
		"x": -1,
		"y": 3,
		"name": "HP 20",
		"description": "HP 20",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": -2,
		"y": 4,
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": -3,
		"y": 5,
		"name": "Alola Solidarity: MP Refresh 2",
		"description": "Move: Alola Solidarity Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 32,
		"x": -1,
		"y": 4,
		"name": "Ultra Endurance!: MP Refresh 3",
		"description": "Move: Ultra Endurance! Has a chance (40%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": 1,
		"y": 1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": 2,
		"y": 1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 35,
		"x": 1,
		"y": 2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 36,
		"x": 3,
		"y": 1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": 2,
		"y": 2,
		"name": "Ginormous Rock Tomb: Power 4",
		"description": "Ginormous Rock Tomb: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 38,
		"x": 1,
		"y": 3,
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 39,
		"x": 3,
		"y": 2,
		"name": "Ginormous Rock Tomb: Power 4",
		"description": "Ginormous Rock Tomb: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 40,
		"x": 2,
		"y": 3,
		"name": "Team Pinpoint Entry 1",
		"description": "Raises the accuracy of all allied sync pairs by one stat rank when the user enters a battle.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 41,
		"x": 1,
		"y": 4,
		"name": "Rock Zone: Team Special DR 2",
		"description": "Reduces special attack move damage taken by allies when the zone is a Rock Zone.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 42,
		"x": 3,
		"y": 3,
		"name": "Sp. Def 20",
		"description": "Sp. Def 20",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 43,
		"x": 2,
		"y": 4,
		"name": "Team Sharp Entry 1",
		"description": "Raises the critical-hit rate of all allied sync pairs by one stat rank when the user enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -2,
		"y": 0,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 45,
		"x": -1,
		"y": -1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 46,
		"x": -3,
		"y": 0,
		"name": "Ginormous Rock Tomb: Power 4",
		"description": "Ginormous Rock Tomb: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 47,
		"x": -2,
		"y": -1,
		"name": "Ginormous Rock Tomb: Power 4",
		"description": "Ginormous Rock Tomb: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 48,
		"x": -1,
		"y": -2,
		"name": "Speed 20",
		"description": "Speed 20",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 49,
		"x": -3,
		"y": -1,
		"name": "Ginormous Rock Tomb: Power 4",
		"description": "Ginormous Rock Tomb: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 50,
		"x": -2,
		"y": -2,
		"name": "HP 20",
		"description": "HP 20",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 51,
		"x": -1,
		"y": -3,
		"name": "Hit: Team Attack ↑ 9",
		"description": "Raises the Attack of all allied sync pairs by one stat rank when the user’s attack move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 52,
		"x": -3,
		"y": -2,
		"name": "Hit: Team Sp. Atk ↑ 9",
		"description": "Raises the Sp. Atk of all allied sync pairs by one stat rank when the user’s attack move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 53,
		"x": 0,
		"y": -3,
		"name": "Stacked-Up Emotions Continental Crush: Power 25",
		"description": "Stacked-Up Emotions Continental Crush: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 54,
		"x": 0,
		"y": 3,
		"name": "Stacked-Up Emotions Continental Crush: Power 25",
		"description": "Stacked-Up Emotions Continental Crush: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const IONO_WATTREL = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 1,
		"y": -2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 2,
		"y": -3,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 1,
		"y": -3,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": 3,
		"y": -4,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": 2,
		"y": -4,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 12,
		"x": 1,
		"y": -4,
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": 3,
		"y": -5,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 14,
		"x": 2,
		"y": -5,
		"name": "Lithe",
		"description": "Prevents the user from getting paralyzed.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 1,
		"y": -5,
		"name": "Clip This!: Barricade Buddies 1",
		"description": "Move: Clip This! Raises the Sp. Def of all allied sync pairs by one stat rank when the user’s move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": 3,
		"y": -6,
		"name": "Clip This!: MP Refresh 2",
		"description": "Move: Clip This! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": 2,
		"y": -6,
		"name": "Sp. Def 20",
		"description": "Sp. Def 20",
		"energy": "7",
		"orb": "84",
		"level": "3",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 18,
		"x": -2,
		"y": 2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -3,
		"y": 3,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": -1,
		"y": 2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 21,
		"x": -2,
		"y": 3,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 22,
		"x": -3,
		"y": 4,
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 23,
		"x": -1,
		"y": 3,
		"name": "Escape Artist",
		"description": "Prevents the user from becoming trapped.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -2,
		"y": 4,
		"name": "Protect: Move Gauge Refresh 3",
		"description": "Move: Protect Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": -3,
		"y": 5,
		"name": "Clip This!: Shielded 1",
		"description": "Move: Clip This! Raises the Defense of all allied sync pairs by one stat rank when the user’s move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -1,
		"y": 4,
		"name": "Protect: 1st Use Status P-Move: HP Recovery 2",
		"description": "Move: Protect Restores the user’s HP by approximately 20% of its maximum HP the first time its Pokémon uses a status move each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": 1,
		"y": 1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 2,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": 1,
		"y": 2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": 3,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 31,
		"x": 2,
		"y": 2,
		"name": "Thunder Shock: Power 4",
		"description": "Thunder Shock: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 32,
		"x": 1,
		"y": 3,
		"name": "Thunder Shock: Power 4",
		"description": "Thunder Shock: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 33,
		"x": 3,
		"y": 2,
		"name": "Thunder Shock: Power 4",
		"description": "Thunder Shock: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 34,
		"x": 2,
		"y": 3,
		"name": "Eerie Impulse: Move Gauge Refresh 2",
		"description": "Move: Eerie Impulse Has a chance (30%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 1,
		"y": 4,
		"name": "Sync Wall",
		"description": "Applies the Critical-Hit Defense effect to the allied field of play the first time the user’s sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": 3,
		"y": 3,
		"name": "Fast-Track 9",
		"description": "Raises the user’s Speed by one stat rank when its Pokémon uses a move.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": 2,
		"y": 4,
		"name": "Team Sync Regen",
		"description": "Applies the Gradual Healing effect to all allied sync pairs after the user uses a sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": -2,
		"y": 0,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -1,
		"y": -1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": -3,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 41,
		"x": -2,
		"y": -1,
		"name": "Thunder Shock: Power 4",
		"description": "Thunder Shock: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 42,
		"x": -1,
		"y": -2,
		"name": "Thunder Shock: Power 4",
		"description": "Thunder Shock: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 43,
		"x": -3,
		"y": -1,
		"name": "Thunder Shock: Move Gauge Refresh 2",
		"description": "Move: Thunder Shock Has a chance (30%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -2,
		"y": -2,
		"name": "HP 20",
		"description": "HP 20",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 45,
		"x": -1,
		"y": -3,
		"name": "Thunder Shock: Hostile Environment 4",
		"description": "Move: Thunder Shock Raises the chance of inflicting status conditions with the additional effects of moves.",
		"energy": "9",
		"orb": "108",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -3,
		"y": -2,
		"name": "Team Underhanded Heal 9",
		"description": "Restores the HP of all allied sync pairs when the user’s attack move is successful against targets that are affected by a status condition.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "Electrify ’Em Electric Beam: Power 25",
		"description": "Electrify ’Em Electric Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "Electrify ’Em Electric Beam: Power 25",
		"description": "Electrify ’Em Electric Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const BLUE_ALAKAZAM = [
	{
		"id": 1,
		"x": -1,
		"y": 0,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": -1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": 1,
		"y": 0,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": 1,
		"y": -1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 2,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 3,
		"y": -2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 2,
		"y": -2,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": 1,
		"y": -2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": 3,
		"y": -3,
		"name": "Thunder Wave: Move Gauge Refresh 3",
		"description": "Move: Thunder Wave Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 12,
		"x": 2,
		"y": -3,
		"name": "Sp. Atk 10",
		"description": "Sp. Atk 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 13,
		"x": 1,
		"y": -3,
		"name": "Thunder Wave: Accuracy 10",
		"description": "Thunder Wave: Accuracy ↑ 10",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 14,
		"x": 3,
		"y": -4,
		"name": "Shocked Hit Freebie 4",
		"description": "Has a chance (50%) of applying the Free Move Next effect to the user when its attack move is successful against a paralyzed opponent.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 2,
		"y": -4,
		"name": "Paralysis Synergy 3",
		"description": "Powers up the user’s moves when the target is paralyzed.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": -2,
		"y": 1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 17,
		"x": -3,
		"y": 2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 18,
		"x": -2,
		"y": 2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -1,
		"y": 2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": -3,
		"y": 3,
		"name": "Antitoxin",
		"description": "Prevents the user from getting poisoned or badly poisoned.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 21,
		"x": -2,
		"y": 3,
		"name": "Dire Hit +: MP Refresh 2",
		"description": "Move: Dire Hit + Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 22,
		"x": -1,
		"y": 3,
		"name": "Dire Hit +: Barricade 1",
		"description": "Move: Dire Hit + Raises the user’s Sp. Def by one stat rank when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 23,
		"x": -3,
		"y": 4,
		"name": "Sync Damage Guard",
		"description": "Applies the Damage Guard Next effect to the user the first time its sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -2,
		"y": 4,
		"name": "Satisfied Snicker 9",
		"description": "Lowers the target’s Sp. Atk by one stat rank when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": 1,
		"y": 1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 26,
		"x": 2,
		"y": 1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 27,
		"x": 3,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 1,
		"y": 2,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": 2,
		"y": 2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": 3,
		"y": 2,
		"name": "Psychic: Power 3",
		"description": "Psychic: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "psychic"
	},
	{
		"id": 31,
		"x": 1,
		"y": 3,
		"name": "Psychic: Power 3",
		"description": "Psychic: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "psychic"
	},
	{
		"id": 32,
		"x": 2,
		"y": 3,
		"name": "Escape Artist",
		"description": "Prevents the user from becoming trapped.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": 3,
		"y": 3,
		"name": "That All You Got?: Hit and Heal 9",
		"description": "Move: That All You Got? Applies the Gradual Healing effect to the user when its move is successful.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": 1,
		"y": 4,
		"name": "Befuddle 1",
		"description": "Lowers the Sp. Def of all opposing sync pairs by one stat rank when the user enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 2,
		"y": 4,
		"name": "Brainteaser",
		"description": "The more the target’s Sp. Def is lowered, the more it powers up the user’s moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": -1,
		"y": -1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": -2,
		"y": -1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 38,
		"x": -3,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -1,
		"y": -2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": -2,
		"y": -2,
		"name": "Psychic: Power 3",
		"description": "Psychic: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "psychic"
	},
	{
		"id": 41,
		"x": -3,
		"y": -2,
		"name": "Psychic: Power 3",
		"description": "Psychic: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "psychic"
	},
	{
		"id": 42,
		"x": -1,
		"y": -3,
		"name": "Psychic: Power 3",
		"description": "Psychic: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "psychic"
	},
	{
		"id": 43,
		"x": -2,
		"y": -3,
		"name": "Unflappable",
		"description": "Prevents the user from flinching.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -3,
		"y": -3,
		"name": "Psychic: Move Gauge Refresh 3",
		"description": "Move: Psychic Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -1,
		"y": -4,
		"name": "That All You Got?: MP Refresh 2",
		"description": "Move: That All You Got? Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -2,
		"y": -4,
		"name": "Smarty-Pants",
		"description": "The more the target’s Sp. Def is lowered, the more it powers up the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "Beat Them All Psychic Beam: Power 25",
		"description": "Beat Them All Psychic Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "Beat Them All Psychic Beam: Power 25",
		"description": "Beat Them All Psychic Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const SELENE_NIHILEGO = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 0,
		"y": -2,
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 8,
		"x": 0,
		"y": -4,
		"name": "Sync Damage Guard",
		"description": "Applies the Damage Guard Next effect to the user the first time its sync move is used each battle.",
		"energy": "9",
		"orb": "108",
		"level": "4",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 9,
		"x": -1,
		"y": -3,
		"name": "Alola C (Spec) Extension 3",
		"description": "Extends the duration of Alola Circle (Special) when Alola Circle (Special) is applied to the allied field of play.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 10,
		"x": 0,
		"y": 2,
		"name": "Circle: MG → 2",
		"description": "Quickly charges the move gauge when a circle applies to the allied field of play.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 11,
		"x": 0,
		"y": 4,
		"name": "Move: MG ↑2 9",
		"description": "Charges the user’s move gauge by two when its move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "4",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 12,
		"x": 1,
		"y": 3,
		"name": "Ally Sets Circle: Special Boost ↑1 9",
		"description": "Increases the user’s Special Moves ↑ Next effect by one rank when an ally applies a circle to the allied field of play.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": 1,
		"y": -2,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 14,
		"x": 2,
		"y": -3,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 15,
		"x": 3,
		"y": -4,
		"name": "Sand Shelter",
		"description": "Protects the user from damage from a sandstorm.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": 1,
		"y": -3,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 17,
		"x": 2,
		"y": -4,
		"name": "Acid: Power 4",
		"description": "Acid: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 18,
		"x": 3,
		"y": -5,
		"name": "Acid: Power 4",
		"description": "Acid: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 19,
		"x": 1,
		"y": -4,
		"name": "Acid: Power 4",
		"description": "Acid: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 20,
		"x": 2,
		"y": -5,
		"name": "Acid: Move Gauge Refresh 2",
		"description": "Move: Acid Has a chance (30%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 21,
		"x": 3,
		"y": -6,
		"name": "Sp. Atk 10",
		"description": "Sp. Atk 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 22,
		"x": 1,
		"y": -5,
		"name": "Head Start 1",
		"description": "Reduces the user’s sync move countdown by one the first time it enters a battle each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 23,
		"x": 2,
		"y": -6,
		"name": "Alola C (Spec): S-Moves ↑ 9",
		"description": "Powers up the user’s sync move when Alola Circle (Special) applies to the allied field of play.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -1,
		"y": 2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 25,
		"x": -2,
		"y": 3,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 26,
		"x": -3,
		"y": 4,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 27,
		"x": -1,
		"y": 3,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": -2,
		"y": 4,
		"name": "Dauntless",
		"description": "Sp. Atk cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": -3,
		"y": 5,
		"name": "Acid: Power 4",
		"description": "Acid: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 30,
		"x": -1,
		"y": 4,
		"name": "Sp. Atk 10",
		"description": "Sp. Atk 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 31,
		"x": -2,
		"y": 5,
		"name": "Acid: Power 4",
		"description": "Acid: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 32,
		"x": -3,
		"y": 6,
		"name": "Speed 10",
		"description": "Speed 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 33,
		"x": -1,
		"y": 5,
		"name": "Opp Sp. Def ↓: S-Moves ↑ 5",
		"description": "Powers up the user’s sync move when the target’s Sp. Def is lowered.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": -2,
		"y": 6,
		"name": "Ultra Opportunity!: Ramp Up 2",
		"description": "Move: Ultra Opportunity! Raises the user’s Sp. Atk by two stat ranks when its move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 2,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 36,
		"x": 3,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": 2,
		"y": 0,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 38,
		"x": 1,
		"y": 1,
		"name": "Nihil Meteor Beam: Power 2",
		"description": "Nihil Meteor Beam: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 39,
		"x": 3,
		"y": 0,
		"name": "Ultra Opportunity!: MP Refresh 2",
		"description": "Move: Ultra Opportunity! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": 2,
		"y": 1,
		"name": "Nihil Meteor Beam: Power 2",
		"description": "Nihil Meteor Beam: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 41,
		"x": 1,
		"y": 2,
		"name": "Toxic Hit (Speed ↑) 9",
		"description": "Raises the user’s Speed by one stat rank when its attack move is successful against a poisoned or badly poisoned opponent.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 42,
		"x": 3,
		"y": 1,
		"name": "Hit Poisoned Opp: Special Boost ↑1 4",
		"description": "Has a chance (50%) of increasing the user’s Special Moves ↑ Next effect by one rank when its attack move is successful against a poisoned or badly poisoned opponent.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": 2,
		"y": 2,
		"name": "Ramming Speed",
		"description": "The more the user’s Speed is raised, the more it powers up the user’s moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -2,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 45,
		"x": -3,
		"y": 1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 46,
		"x": -2,
		"y": 0,
		"name": "Nihil Meteor Beam: Power 2",
		"description": "Nihil Meteor Beam: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 47,
		"x": -1,
		"y": -1,
		"name": "Nihil Meteor Beam: Power 2",
		"description": "Nihil Meteor Beam: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 48,
		"x": -3,
		"y": 0,
		"name": "Nihil Meteor Beam: Power 2",
		"description": "Nihil Meteor Beam: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 49,
		"x": -2,
		"y": -1,
		"name": "Potent Toxin 2",
		"description": "Increases the amount of damage an opponent takes from being poisoned or badly poisoned.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 50,
		"x": -1,
		"y": -2,
		"name": "Acid: Move Gauge Refresh 2",
		"description": "Move: Acid Has a chance (30%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 51,
		"x": -3,
		"y": -1,
		"name": "Ready for Anything 5",
		"description": "Reduces damage when the user is hit by an attack move or sync move while it is in a counter attacking posture or ready to attack.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 52,
		"x": -2,
		"y": -2,
		"name": "Prep/Posture: Special Boost ↑1 9",
		"description": "Increases the user’s Special Moves ↑ Next effect by one rank when the user takes up a counter attacking posture or gets ready to attack.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 53,
		"x": 0,
		"y": -3,
		"name": "Cute Quirks Continental Crush: Power 25",
		"description": "Cute Quirks Continental Crush: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 54,
		"x": 0,
		"y": 3,
		"name": "Cute Quirks Continental Crush: Power 25",
		"description": "Cute Quirks Continental Crush: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const ARVEN_MABOSSTIFF = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 0,
		"y": -2,
		"name": "Unflappable",
		"description": "Prevents the user from flinching.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 8,
		"x": 0,
		"y": -4,
		"name": "Team Sentry Entry 2",
		"description": "Raises the Defense of all allied sync pairs by two stat ranks when the user enters a battle.",
		"energy": "9",
		"orb": "108",
		"level": "4",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 9,
		"x": -2,
		"y": -3,
		"name": "Healthy Buffer 5",
		"description": "Reduces damage when the user is hit by an attack move when its HP is full.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 10,
		"x": 0,
		"y": 2,
		"name": "Lithe",
		"description": "Prevents the user from getting paralyzed.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 11,
		"x": 0,
		"y": 4,
		"name": "Restrained Scope 5",
		"description": "Has a chance (60%) of lowering the target’s accuracy by one stat rank when the user’s attack move is successful against a restrained opponent.",
		"energy": "10",
		"orb": "120",
		"level": "4",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 12,
		"x": -2,
		"y": 5,
		"name": "Hit Restrained Opp: Attack ↓ & Sp. Atk ↓ 9",
		"description": "Lowers the target’s Attack and Sp. Atk by one stat rank when the user’s attack move is successful against a restrained opponent.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": 1,
		"y": -2,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 14,
		"x": 2,
		"y": -3,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 15,
		"x": 1,
		"y": -3,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 16,
		"x": 3,
		"y": -4,
		"name": "Unbending",
		"description": "Defense cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": 2,
		"y": -4,
		"name": "Bite: Power 4",
		"description": "Bite: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 18,
		"x": 1,
		"y": -4,
		"name": "Bite: Power 4",
		"description": "Bite: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 19,
		"x": 3,
		"y": -5,
		"name": "Bite: Power 4",
		"description": "Bite: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 20,
		"x": 2,
		"y": -5,
		"name": "Here You Go!: Team Hit and Heal",
		"description": "Move: Here You Go! Applies the Gradual Healing effect to all allied sync pairs when the user’s move is successful.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 21,
		"x": 1,
		"y": -5,
		"name": "1st S-Move: Team Physical Boost 2",
		"description": "Increases the Physical Moves ↑ Next effect of all allied sync pairs by two ranks the first time the user’s sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 22,
		"x": 3,
		"y": -6,
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 23,
		"x": 2,
		"y": -6,
		"name": "Bite: Aggravation 1",
		"description": "Move: Bite Raises the chance of inflicting the flinching, confused, or trapped condition with the additional effects of moves.",
		"energy": "8",
		"orb": "96",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -2,
		"y": 2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 25,
		"x": -3,
		"y": 3,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 26,
		"x": -1,
		"y": 2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 27,
		"x": -2,
		"y": 3,
		"name": "Bite: Power 4",
		"description": "Bite: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 28,
		"x": -3,
		"y": 4,
		"name": "Bite: Power 4",
		"description": "Bite: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 29,
		"x": -1,
		"y": 3,
		"name": "Bite: Move Gauge Refresh 3",
		"description": "Move: Bite Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 30,
		"x": -2,
		"y": 4,
		"name": "Here You Go!: MP Refresh 2",
		"description": "Move: Here You Go! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": -3,
		"y": 5,
		"name": "Sync Damage Guard",
		"description": "Applies the Damage Guard Next effect to the user the first time its sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 32,
		"x": -1,
		"y": 4,
		"name": "Team Sync Cure 9",
		"description": "Removes all status conditions from all allied sync pairs after using the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": 1,
		"y": 1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": 2,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 35,
		"x": 1,
		"y": 2,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 36,
		"x": 3,
		"y": 1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": 2,
		"y": 2,
		"name": "Bounce Back Jaw Lock: Power 4",
		"description": "Bounce Back Jaw Lock: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 38,
		"x": 1,
		"y": 3,
		"name": "Bounce Back Jaw Lock: Power 4",
		"description": "Bounce Back Jaw Lock: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 39,
		"x": 3,
		"y": 2,
		"name": "Bounce Back Jaw Lock: Power 4",
		"description": "Bounce Back Jaw Lock: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 40,
		"x": 2,
		"y": 3,
		"name": "Bite: Fast-Track 9",
		"description": "Move: Bite Raises the user’s Speed by one stat rank when its Pokémon uses a move.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 41,
		"x": 1,
		"y": 4,
		"name": "Hit Restrained Opp: Team 1 of 5 Stats ↑ 9",
		"description": "Raises one of the following stats of all allied sync pairs by one stat rank at random when the user’s attack move is successful against a restrained opponent: Attack, Defense, Sp. Atk, Sp. Def, or Speed.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 42,
		"x": 3,
		"y": 3,
		"name": "Bounce Back Jaw Lock: Move Gauge Refresh 3",
		"description": "Move: Bounce Back Jaw Lock Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": 2,
		"y": 4,
		"name": "Impervious",
		"description": "The user’s stats cannot be lowered.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -2,
		"y": 0,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 45,
		"x": -1,
		"y": -1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 46,
		"x": -3,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 47,
		"x": -2,
		"y": -1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 48,
		"x": -1,
		"y": -2,
		"name": "Bounce Back Jaw Lock: Power 4",
		"description": "Bounce Back Jaw Lock: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 49,
		"x": -3,
		"y": -1,
		"name": "Bounce Back Jaw Lock: Power 4",
		"description": "Bounce Back Jaw Lock: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 50,
		"x": -2,
		"y": -2,
		"name": "Sitrus Berry: Master Healer 1",
		"description": "Move: Sitrus Berry Increases the amount of HP restored by the user’s healing moves.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 51,
		"x": -1,
		"y": -3,
		"name": "Safety Net",
		"description": "Applies the Enduring effect to all allied sync pairs the first time the user’s sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 52,
		"x": -3,
		"y": -2,
		"name": "Vigilance",
		"description": "Protects the user against critical hits.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 53,
		"x": 0,
		"y": -3,
		"name": "Chef’s Spicy Comeuppance: Power 25",
		"description": "Chef’s Spicy Comeuppance: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 54,
		"x": 0,
		"y": 3,
		"name": "Chef’s Spicy Comeuppance: Power 25",
		"description": "Chef’s Spicy Comeuppance: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const OAK_NIDORINO = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 1,
		"y": -2,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 2,
		"y": -3,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 1,
		"y": -3,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": 3,
		"y": -4,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": 2,
		"y": -4,
		"name": "Poison Sting: Power 4",
		"description": "Poison Sting: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 12,
		"x": 1,
		"y": -4,
		"name": "Poison Sting: Power 4",
		"description": "Poison Sting: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 13,
		"x": 3,
		"y": -5,
		"name": "Poison Sting: Power 4",
		"description": "Poison Sting: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 14,
		"x": 2,
		"y": -5,
		"name": "Potent Toxin 2",
		"description": "Increases the amount of damage an opponent takes from being poisoned or badly poisoned.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 1,
		"y": -5,
		"name": "Satisfied Snicker 9",
		"description": "Lowers the target’s Sp. Atk by one stat rank when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": 3,
		"y": -6,
		"name": "Hit Poisoned Opp: HP Recovery 9",
		"description": "Restores the user’s HP when its attack move is successful against a poisoned or badly poisoned opponent.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": 2,
		"y": -6,
		"name": "Poison Sting: Move Gauge Refresh 9",
		"description": "Move: Poison Sting Charges the user’s move gauge by one when its move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": -2,
		"y": 2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -3,
		"y": 3,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": -1,
		"y": 2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 21,
		"x": -2,
		"y": 3,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 22,
		"x": -3,
		"y": 4,
		"name": "Poison Sting: Power 4",
		"description": "Poison Sting: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 23,
		"x": -1,
		"y": 3,
		"name": "Poison Sting: Power 4",
		"description": "Poison Sting: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 24,
		"x": -2,
		"y": 4,
		"name": "Protect: Move Gauge Refresh 3",
		"description": "Move: Protect Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": -3,
		"y": 5,
		"name": "Trip Up 9",
		"description": "Lowers the target’s Speed by one stat rank when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -1,
		"y": 4,
		"name": "Flag Bearer 9",
		"description": "Raises the Attack of all allied sync pairs by one stat rank when the user’s Pokémon uses a move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": 1,
		"y": 1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 2,
		"y": 1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": 1,
		"y": 2,
		"name": "Stalwart",
		"description": "Sp. Def cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 30,
		"x": 3,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 31,
		"x": 2,
		"y": 2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 32,
		"x": 1,
		"y": 3,
		"name": "Mini Potion All: MP Refresh 2",
		"description": "Move: Mini Potion All Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": 3,
		"y": 2,
		"name": "Antitoxin",
		"description": "Prevents the user from getting poisoned or badly poisoned.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": 2,
		"y": 3,
		"name": "HP 20",
		"description": "HP 20",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 35,
		"x": 1,
		"y": 4,
		"name": "Mini Potion All: Master Healer 1",
		"description": "Move: Mini Potion All Increases the amount of HP restored by the user’s healing moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": 3,
		"y": 3,
		"name": "Survivor Mentality 2",
		"description": "Reduces damage when the user is hit by a special attack move while it is in a pinch.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": 2,
		"y": 4,
		"name": "Persisting Barrier 3",
		"description": "Extends the duration of the Special Damage Reduction effect when the Special Damage Reduction effect is applied to the allied field of play.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": -2,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": -3,
		"y": 0,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 41,
		"x": -2,
		"y": -1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 42,
		"x": -1,
		"y": -2,
		"name": "Dreams and Adventures!: MP Refresh 3",
		"description": "Move: Dreams and Adventures! Has a chance (40%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": -3,
		"y": -1,
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -2,
		"y": -2,
		"name": "Sp. Def 10",
		"description": "Sp. Def 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 45,
		"x": -1,
		"y": -3,
		"name": "Dreams and Adventures!: Critical Squad 1",
		"description": "Move: Dreams and Adventures! Raises the critical-hit rate of all allied sync pairs by one stat rank when the user’s move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -3,
		"y": -2,
		"name": "Sync Wall",
		"description": "Applies the Critical-Hit Defense effect to the allied field of play the first time the user’s sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "Your Tale Unfolds Poison Impact: Power 25",
		"description": "Your Tale Unfolds Poison Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "Your Tale Unfolds Poison Impact: Power 25",
		"description": "Your Tale Unfolds Poison Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const NEMONA_SCREAMTAIL = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 1,
		"y": -2,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 2,
		"y": -3,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 3,
		"y": -4,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": 1,
		"y": -3,
		"name": "Headstrong",
		"description": "Attack cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 11,
		"x": 2,
		"y": -4,
		"name": "Ferocious Play Rough: Power 2",
		"description": "Ferocious Play Rough: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 12,
		"x": 3,
		"y": -5,
		"name": "Ferocious Play Rough: Power 2",
		"description": "Ferocious Play Rough: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 13,
		"x": 1,
		"y": -4,
		"name": "Ferocious Play Rough: Power 2",
		"description": "Ferocious Play Rough: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 14,
		"x": 2,
		"y": -5,
		"name": "Unflappable",
		"description": "Prevents the user from flinching.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 3,
		"y": -6,
		"name": "Defense 10",
		"description": "Defense 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 16,
		"x": 1,
		"y": -5,
		"name": "Ally Sets WTZ: Physical Boost ↑1 9",
		"description": "Increases the user’s Physical Moves ↑ Next effect by one rank when an ally activates a weather, terrain, or zone effect.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": 2,
		"y": -6,
		"name": "Haymaker",
		"description": "The more the user’s Attack is raised, the more it powers up the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": -1,
		"y": 2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -2,
		"y": 3,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": -3,
		"y": 4,
		"name": "Lithe",
		"description": "Prevents the user from getting paralyzed.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 21,
		"x": -1,
		"y": 3,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 22,
		"x": -2,
		"y": 4,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 23,
		"x": -3,
		"y": 5,
		"name": "Ferocious Play Rough: Power 2",
		"description": "Ferocious Play Rough: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 24,
		"x": -1,
		"y": 4,
		"name": "Ferocious Play Rough: Power 2",
		"description": "Ferocious Play Rough: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 25,
		"x": -2,
		"y": 5,
		"name": "Ferocious Play Rough: Move Gauge Refresh 2",
		"description": "Move: Ferocious Play Rough Has a chance (30%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -3,
		"y": 6,
		"name": "Healing Sun 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action while the weather is sunny.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": -1,
		"y": 5,
		"name": "Sunny Hit: Attack ↓ & Defense ↓ 9",
		"description": "Lowers the target’s Attack and Defense by one stat rank when the user’s attack move is successful while the weather is sunny.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 28,
		"x": -2,
		"y": 6,
		"name": "Paldea C (Phys): S-Moves ↑ 9",
		"description": "Powers up the user’s sync move when Paldea Circle (Physical) applies to the allied field of play.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": 2,
		"y": -1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": 3,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 31,
		"x": 2,
		"y": 0,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 32,
		"x": 1,
		"y": 1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 33,
		"x": 3,
		"y": 0,
		"name": "Booster Energy: MP Refresh 2",
		"description": "Move: Booster Energy Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": 2,
		"y": 1,
		"name": "Our Greatest Battle!: Hit and Heal 9",
		"description": "Move: Our Greatest Battle! Applies the Gradual Healing effect to the user when its move is successful.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 1,
		"y": 2,
		"name": "Circle: Status Immunity",
		"description": "Status conditions cannot be inflicted on the user when a circle applies to the allied field of play.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": 3,
		"y": 1,
		"name": "Attack 20",
		"description": "Attack 20",
		"energy": "7",
		"orb": "84",
		"level": "3",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": 2,
		"y": 2,
		"name": "Infliction Freebie 9",
		"description": "Applies the Free Move Next effect to the user when its Pokémon uses a status move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": -2,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -3,
		"y": 1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": -2,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 41,
		"x": -1,
		"y": -1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 42,
		"x": -3,
		"y": 0,
		"name": "Our Greatest Battle!: MP Refresh 2",
		"description": "Move: Our Greatest Battle! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": -2,
		"y": -1,
		"name": "One with the Sun",
		"description": "Prevents the user from flinching, becoming confused, or becoming trapped when the weather is sunny.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -1,
		"y": -2,
		"name": "Speeding Sun 2",
		"description": "Quickly charges the move gauge when the weather is sunny.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -3,
		"y": -1,
		"name": "Charging Sun 5",
		"description": "Powers up the user’s moves when the weather is sunny.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -2,
		"y": -2,
		"name": "Sync Burst 1",
		"description": "Restores one MP for the user the first time its sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "Nicely Rampagey Play Rough: Power 25",
		"description": "Nicely Rampagey Play Rough: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "Nicely Rampagey Play Rough: Power 25",
		"description": "Nicely Rampagey Play Rough: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]