export const FLORIAN_YANMEGA = [
	{
		"id": 1,
		"x": "1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "1",
		"y": "0",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "-1",
		"y": "1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "-1",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "0",
		"y": "-2",
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 8,
		"x": "0",
		"y": "-4",
		"name": "Strike: Sync Move Boost ↑1 9",
		"description": "Increases the user’s Sync Move ↑ Next effect by one rank when its attack move hits. If the move has the Multistrike effect tag, increases the user’s Sync Move ↑ Next effect by one rank for each hit.",
		"energy": "10",
		"orb": "120",
		"level": "4",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 9,
		"x": "-1",
		"y": "-3",
		"name": "1st S-Move: Bug Zone",
		"description": "Turns the field of play’s zone into a Bug Zone the first time the user’s sync move is used each battle. (A Bug Zone powers up Bug-type attacks.)",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 10,
		"x": "0",
		"y": "2",
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 11,
		"x": "0",
		"y": "4",
		"name": "EX Speed: 1st Move: Restore MP 1",
		"description": "Restores one MP of the user’s move the first time that move is successful each battle.",
		"energy": "10",
		"orb": "120",
		"level": "4",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 12,
		"x": "1",
		"y": "3",
		"name": "Festival Starts Now!: Fleet Feet 6",
		"description": "Raises the user’s Speed by six stat ranks when its move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": "1",
		"y": "-2",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 14,
		"x": "2",
		"y": "-3",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 15,
		"x": "3",
		"y": "-4",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 16,
		"x": "1",
		"y": "-3",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 17,
		"x": "2",
		"y": "-4",
		"name": "Jadeite Tera Blast: Power +2",
		"description": "Jadeite Tera Blast: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "bug"
	},
	{
		"id": 18,
		"x": "3",
		"y": "-5",
		"name": "Jadeite Tera Blast: Power +2",
		"description": "Jadeite Tera Blast: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "bug"
	},
	{
		"id": 19,
		"x": "1",
		"y": "-4",
		"name": "Jadeite Tera Blast: Power +2",
		"description": "Jadeite Tera Blast: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "bug"
	},
	{
		"id": 20,
		"x": "2",
		"y": "-5",
		"name": "Insect Healing 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action when the zone is a Bug Zone.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 21,
		"x": "3",
		"y": "-6",
		"name": "Trip Up 9",
		"description": "Lowers the target’s Speed by one stat rank when the user’s attack move against it is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 22,
		"x": "1",
		"y": "-5",
		"name": "Jadeite Tera Blast: Move Gauge Refresh 9",
		"description": "Charges the user’s move gauge by one when its move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 23,
		"x": "2",
		"y": "-6",
		"name": "Sharpened Body 3",
		"description": "Powers up the user’s moves when its Attack is raised.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": "-1",
		"y": "2",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 25,
		"x": "-2",
		"y": "3",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 26,
		"x": "-3",
		"y": "4",
		"name": "Headstrong",
		"description": "Attack cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": "-1",
		"y": "3",
		"name": "Zipping Lunge: Power +2",
		"description": "Zipping Lunge: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "bug"
	},
	{
		"id": 28,
		"x": "-2",
		"y": "4",
		"name": "Zipping Lunge: Power +2",
		"description": "Zipping Lunge: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "bug"
	},
	{
		"id": 29,
		"x": "-3",
		"y": "5",
		"name": "Zipping Lunge: Power +2",
		"description": "Zipping Lunge: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "bug"
	},
	{
		"id": 30,
		"x": "-1",
		"y": "4",
		"name": "Zipping Lunge: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": "-2",
		"y": "5",
		"name": "Speed +10",
		"description": "Speed +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 32,
		"x": "-3",
		"y": "6",
		"name": "EX Speed: Catalytic Kick 9",
		"description": "Applies the Move Gauge Acceleration effect to the allied field of play when the user’s move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": "-1",
		"y": "5",
		"name": "Unfortuitous 9",
		"description": "Lowers one of the target’s following stats by one stat rank at random when the user’s attack move against it is successful: Attack, Defense, Sp. Atk, Sp. Def, Speed, accuracy, or evasiveness.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": "-2",
		"y": "6",
		"name": "Vigilance",
		"description": "Protects the user against critical hits.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": "2",
		"y": "-1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 36,
		"x": "3",
		"y": "-1",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": "2",
		"y": "0",
		"name": "Zipping Lunge: Power +2",
		"description": "Zipping Lunge: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "bug"
	},
	{
		"id": 38,
		"x": "1",
		"y": "1",
		"name": "Zipping Lunge: Power +2",
		"description": "Zipping Lunge: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "bug"
	},
	{
		"id": 39,
		"x": "3",
		"y": "0",
		"name": "Hypnosis: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": "2",
		"y": "1",
		"name": "Hypnosis: Flabbergast 9",
		"description": "Leaves the target confused when the user’s move targeting that opponent is successful.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 41,
		"x": "1",
		"y": "2",
		"name": "Good Night-mare 3",
		"description": "Powers up the user’s moves when the target is asleep.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 42,
		"x": "3",
		"y": "1",
		"name": "Enfeeble 2",
		"description": "Lowers the Defense of all opposing sync pairs by two stat ranks when the user enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": "2",
		"y": "2",
		"name": "Hypnosis: Mighty Affliction 9",
		"description": "Increases the user’s Physical Moves ↑ Next effect by one rank when its Pokémon uses a status move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": "-2",
		"y": "1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 45,
		"x": "-3",
		"y": "1",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 46,
		"x": "-2",
		"y": "0",
		"name": "Jadeite Tera Blast: Power +2",
		"description": "Jadeite Tera Blast: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "bug"
	},
	{
		"id": 47,
		"x": "-1",
		"y": "-1",
		"name": "Jadeite Tera Blast: Power +2",
		"description": "Jadeite Tera Blast: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "bug"
	},
	{
		"id": 48,
		"x": "-3",
		"y": "0",
		"name": "Jadeite Tera Blast: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 49,
		"x": "-2",
		"y": "-1",
		"name": "Festival Starts Now!: Slippery 1",
		"description": "Raises the user’s evasiveness by one stat rank when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 50,
		"x": "-1",
		"y": "-2",
		"name": "Attack +10",
		"description": "Attack +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 51,
		"x": "-3",
		"y": "-1",
		"name": "Mighty Command 9",
		"description": "Increases the user’s Physical Moves ↑ Next effect by one rank when its Trainer uses a move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 52,
		"x": "-2",
		"y": "-2",
		"name": "Haymaker",
		"description": "The more the user’s Attack is raised, the more it powers up the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 53,
		"x": "0",
		"y": "-3",
		"name": "Festival of Curiosity Tera Blast: Power +25",
		"description": "Festival of Curiosity Tera Blast: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 54,
		"x": "0",
		"y": "3",
		"name": "Festival of Curiosity Tera Blast: Power +25",
		"description": "Festival of Curiosity Tera Blast: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const JULIANA_CHIMECHO = []

export const CARMINE_MIGHTYENA = [
	{
		"id": 1,
		"x": "1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "1",
		"y": "0",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "-1",
		"y": "1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "-1",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "0",
		"y": "-2",
		"name": "Circle: Attack Move DR 2",
		"description": "Reduces damage when the user is hit by an attack move while a circle applies to the allied field of play.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 8,
		"x": "0",
		"y": "-4",
		"name": "Team Offensive Defense 9",
		"description": "Raises the Defense of all allied sync pairs by one stat rank when the user’s attack move is successful.",
		"energy": "9",
		"orb": "108",
		"level": "4",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 9,
		"x": "-2",
		"y": "-3",
		"name": "Trainer Sync Redemption 1",
		"description": "Restores one MP for the user’s Trainer the first time its sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 10,
		"x": "0",
		"y": "2",
		"name": "Circle: HP Recovery 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action when a circle applies to the allied field of play.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 11,
		"x": "0",
		"y": "4",
		"name": "Team Mind Brace 9",
		"description": "Raises the Sp. Def of all allied sync pairs by one stat rank when the user’s attack move is successful.",
		"energy": "9",
		"orb": "108",
		"level": "4",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 12,
		"x": "-2",
		"y": "5",
		"name": "Circle: Team Condition Nullification",
		"description": "Prevents all allied sync pairs from being inflicted with status conditions, flinching, becoming confused, or becoming trapped when a circle applies to the allied field of play.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": "1",
		"y": "-2",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 14,
		"x": "2",
		"y": "-3",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 15,
		"x": "1",
		"y": "-3",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 16,
		"x": "3",
		"y": "-4",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 17,
		"x": "2",
		"y": "-4",
		"name": "Bite: Power +4",
		"description": "Bite: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 18,
		"x": "1",
		"y": "-4",
		"name": "Bite: Power +4",
		"description": "Bite: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 19,
		"x": "3",
		"y": "-5",
		"name": "Bite: Power +4",
		"description": "Bite: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 20,
		"x": "2",
		"y": "-5",
		"name": "Bite: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 21,
		"x": "1",
		"y": "-5",
		"name": "Overwhelm 9",
		"description": "Lowers the target’s Attack by one stat rank when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 22,
		"x": "3",
		"y": "-6",
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 23,
		"x": "2",
		"y": "-6",
		"name": "Bite: Aggravation 1",
		"description": "Raises the chance of inflicting the flinching, confused, or trapped condition with the additional effects of moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": "-2",
		"y": "2",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 25,
		"x": "-3",
		"y": "3",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 26,
		"x": "-1",
		"y": "2",
		"name": "Sharp Fangs Crunch: Power +3",
		"description": "Sharp Fangs Crunch: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 27,
		"x": "-2",
		"y": "3",
		"name": "Sharp Fangs Crunch: Power +3",
		"description": "Sharp Fangs Crunch: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 28,
		"x": "-3",
		"y": "4",
		"name": "Sharp Fangs Crunch: Power +3",
		"description": "Sharp Fangs Crunch: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 29,
		"x": "-1",
		"y": "3",
		"name": "Sp. Def +10",
		"description": "Sp. Def +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": "-2",
		"y": "4",
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": "-3",
		"y": "5",
		"name": "Satisfied Snicker 9",
		"description": "Lowers the target’s Sp. Atk by one stat rank when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 32,
		"x": "-1",
		"y": "4",
		"name": "T-Move: Team Physical Boost ↑1 9",
		"description": "Increases the Physical Moves ↑ Next effect of all allied sync pairs by one rank when the user’s Trainer uses a move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": "1",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": "2",
		"y": "1",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 35,
		"x": "1",
		"y": "2",
		"name": "Unflappable",
		"description": "Prevents the user from flinching.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": "3",
		"y": "1",
		"name": "Sharp Fangs Crunch: Power +3",
		"description": "Sharp Fangs Crunch: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 37,
		"x": "2",
		"y": "2",
		"name": "Sharp Fangs Crunch: Power +3",
		"description": "Sharp Fangs Crunch: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 38,
		"x": "1",
		"y": "3",
		"name": "Sharp Fangs Crunch: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 39,
		"x": "3",
		"y": "2",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": "2",
		"y": "3",
		"name": "Team Speedy Entry 1",
		"description": "Raises the Speed of all allied sync pairs by one stat rank when the user enters a battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 41,
		"x": "1",
		"y": "4",
		"name": "Paldea C (Phys) Extension 3",
		"description": "Extends the duration of Paldea Circle (Physical) when Paldea Circle (Physical) is applied to the allied field of play.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 42,
		"x": "3",
		"y": "3",
		"name": "Circle: MG → 2",
		"description": "Quickly charges the move gauge when a circle applies to the allied field of play.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": "2",
		"y": "4",
		"name": "Adrenaline 1",
		"description": "Reduces the sync move countdown by one the first time the user’s sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": "-2",
		"y": "0",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 45,
		"x": "-1",
		"y": "-1",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 46,
		"x": "-3",
		"y": "0",
		"name": "Bite: Power +4",
		"description": "Bite: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 47,
		"x": "-2",
		"y": "-1",
		"name": "Bite: Power +4",
		"description": "Bite: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 48,
		"x": "-1",
		"y": "-2",
		"name": "HP +20",
		"description": "HP +20",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 49,
		"x": "-3",
		"y": "-1",
		"name": "Gobsmack 4",
		"description": "Has a chance (50%) of leaving the target confused when the user’s attack move against it is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 50,
		"x": "-2",
		"y": "-2",
		"name": "On the Run 1",
		"description": "Raises the user’s evasiveness by one stat rank the first time it is in a pinch each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 51,
		"x": "-1",
		"y": "-3",
		"name": "Team Fist Bump 9",
		"description": "Restores the HP of all allied sync pairs when the user’s attack move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 52,
		"x": "-3",
		"y": "-2",
		"name": "Danger Damage Guard",
		"description": "Applies the Damage Guard Next effect to the user the first time its HP drops to half or below each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 53,
		"x": "0",
		"y": "-3",
		"name": "Ogre Balloon–Busting Champion Crunch: Power +25",
		"description": "Ogre Balloon–Busting Champion Crunch: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 54,
		"x": "0",
		"y": "3",
		"name": "Ogre Balloon–Busting Champion Crunch: Power +25",
		"description": "Ogre Balloon–Busting Champion Crunch: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const WHITNEY_GIRAFARIG = [
	{
		"id": 1,
		"x": "1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "1",
		"y": "0",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "-1",
		"y": "1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "-1",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "1",
		"y": "-2",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": "2",
		"y": "-3",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": "3",
		"y": "-4",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": "1",
		"y": "-3",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": "2",
		"y": "-4",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 12,
		"x": "3",
		"y": "-5",
		"name": "Hyper Beam: Power +2",
		"description": "Hyper Beam: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 13,
		"x": "1",
		"y": "-4",
		"name": "Hyper Beam: Power +2",
		"description": "Hyper Beam: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 14,
		"x": "2",
		"y": "-5",
		"name": "Hyper Beam: Power +2",
		"description": "Hyper Beam: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 15,
		"x": "3",
		"y": "-6",
		"name": "Hyper Beam: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": "1",
		"y": "-5",
		"name": "Grand Entry 2",
		"description": "Raises the user’s Sp. Atk by two stat ranks when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": "2",
		"y": "-6",
		"name": "Brainteaser",
		"description": "The more the target’s Sp. Def is lowered, the more it powers up the user’s moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": "-1",
		"y": "2",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": "-2",
		"y": "3",
		"name": "Clearheaded",
		"description": "Prevents the user from becoming confused.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 20,
		"x": "-3",
		"y": "4",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 21,
		"x": "-1",
		"y": "3",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 22,
		"x": "-2",
		"y": "4",
		"name": "Hyper Voice: Power +2",
		"description": "Hyper Voice: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 23,
		"x": "-3",
		"y": "5",
		"name": "Hyper Voice: Power +2",
		"description": "Hyper Voice: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 24,
		"x": "-1",
		"y": "4",
		"name": "Hyper Voice: Power +2",
		"description": "Hyper Voice: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 25,
		"x": "-2",
		"y": "5",
		"name": "Hyper Voice: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": "-3",
		"y": "6",
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": "-1",
		"y": "5",
		"name": "Hyper Beam: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 28,
		"x": "-2",
		"y": "6",
		"name": "Gobsmack 9",
		"description": "Leaves the target confused when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": "2",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": "3",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 31,
		"x": "2",
		"y": "0",
		"name": "Hyper Voice: Power +2",
		"description": "Hyper Voice: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 32,
		"x": "1",
		"y": "1",
		"name": "Hyper Voice: Power +2",
		"description": "Hyper Voice: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 33,
		"x": "3",
		"y": "0",
		"name": "Trip Up 4",
		"description": "Has a chance (50%) of lowering the target’s Speed by one stat rank when the user’s attack move against it is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": "2",
		"y": "1",
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": "1",
		"y": "2",
		"name": "X Sp. Atk: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": "3",
		"y": "1",
		"name": "Hyper Voice: Satisfied Snicker 9",
		"description": "Lowers the target’s Sp. Atk by one stat rank when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": "2",
		"y": "2",
		"name": "T-Move: Special Boost ↑1 9",
		"description": "Increases the user’s Special Moves ↑ Next effect by one rank when its Trainer uses a move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": "-2",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": "-3",
		"y": "1",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": "-2",
		"y": "0",
		"name": "Hyper Beam: Power +2",
		"description": "Hyper Beam: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 41,
		"x": "-1",
		"y": "-1",
		"name": "Hyper Beam: Power +2",
		"description": "Hyper Beam: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 42,
		"x": "-3",
		"y": "0",
		"name": "Hyper Beam: Accuracy +10",
		"description": "Hyper Beam: Accuracy +10",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 43,
		"x": "-2",
		"y": "-1",
		"name": "Sp. Atk +10",
		"description": "Sp. Atk +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 44,
		"x": "-1",
		"y": "-2",
		"name": "I Really Want to Battle!: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": "-3",
		"y": "-1",
		"name": "Sync Freebie",
		"description": "Applies the Free Move Next effect to the user after using its sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": "-2",
		"y": "-2",
		"name": "Brain Sync 5",
		"description": "Powers up the user’s sync move when its Sp. Atk is raised.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": "0",
		"y": "-3",
		"name": "Perfect for a Cutie Like Me Normal Beam: Power +25",
		"description": "Perfect for a Cutie Like Me Normal Beam: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": "0",
		"y": "3",
		"name": "Perfect for a Cutie Like Me Normal Beam: Power +25",
		"description": "Perfect for a Cutie Like Me Normal Beam: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const SELENE_PRIMARINA = [
	{
		"id": 1,
		"x": "1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "1",
		"y": "0",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "-1",
		"y": "1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "-1",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "2",
		"y": "-1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": "3",
		"y": "-2",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": "2",
		"y": "-2",
		"name": "Play Rough: Power +4",
		"description": "Play Rough: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 10,
		"x": "1",
		"y": "-2",
		"name": "Play Rough: Power +4",
		"description": "Play Rough: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 11,
		"x": "1",
		"y": "-3",
		"name": "Play Rough: Accuracy +10",
		"description": "Play Rough: Accuracy +10",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 12,
		"x": "2",
		"y": "-3",
		"name": "Play Rough: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": "3",
		"y": "-3",
		"name": "Play Rough: Attack Trap 4",
		"description": "Has a chance (50%) of leaving the target trapped when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 14,
		"x": "2",
		"y": "-4",
		"name": "Overwhelm 9",
		"description": "Lowers the target’s Attack by one stat rank when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": "3",
		"y": "-4",
		"name": "Overpower",
		"description": "The more the target’s Sp. Atk is lowered, the more it powers up the user’s moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": "-1",
		"y": "2",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 17,
		"x": "-2",
		"y": "3",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 18,
		"x": "-1",
		"y": "3",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": "-3",
		"y": "4",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": "-2",
		"y": "4",
		"name": "Elegant Play Rough: Power +2",
		"description": "Elegant Play Rough: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 21,
		"x": "-1",
		"y": "4",
		"name": "Elegant Play Rough: Power +2",
		"description": "Elegant Play Rough: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 22,
		"x": "-3",
		"y": "5",
		"name": "Elegant Play Rough: Power +2",
		"description": "Elegant Play Rough: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 23,
		"x": "-2",
		"y": "5",
		"name": "Fairy Wish: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": "-1",
		"y": "5",
		"name": "Whimsical Acceleration 2",
		"description": "Quickly charges the move gauge when the zone is a Fairy Zone.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": "-3",
		"y": "6",
		"name": "Fairy Zone Extension 3",
		"description": "Extends the duration of the Fairy Zone when the zone turns into a Fairy Zone while the user is on the field.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": "-2",
		"y": "6",
		"name": "Fairy Zone: Team All Stats ↓ Immunity",
		"description": "Stats cannot be lowered for all allied sync pairs when the zone is a Fairy Zone.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": "1",
		"y": "1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": "2",
		"y": "1",
		"name": "Headstrong",
		"description": "Attack cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": "1",
		"y": "2",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": "3",
		"y": "1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 31,
		"x": "2",
		"y": "2",
		"name": "Elegant Play Rough: Power +2",
		"description": "Elegant Play Rough: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 32,
		"x": "1",
		"y": "3",
		"name": "Elegant Play Rough: Power +2",
		"description": "Elegant Play Rough: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 33,
		"x": "3",
		"y": "2",
		"name": "Elegant Play Rough: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": "2",
		"y": "3",
		"name": "Attack +10",
		"description": "Attack +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 35,
		"x": "1",
		"y": "4",
		"name": "First Aid 2",
		"description": "Restores the user’s HP by approximately 20% of its maximum HP the first time it is in a pinch each battle.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": "3",
		"y": "3",
		"name": "Haymaker",
		"description": "The more the user’s Attack is raised, the more it powers up the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": "2",
		"y": "4",
		"name": "S-Move: Physical Boost ↑2 9",
		"description": "Increases the user’s Physical Moves ↑ Next effect by two ranks after using its sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": "-2",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": "-3",
		"y": "1",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": "-2",
		"y": "0",
		"name": "Play Rough: Power +4",
		"description": "Play Rough: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 41,
		"x": "-1",
		"y": "-1",
		"name": "Play Rough: Power +4",
		"description": "Play Rough: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 42,
		"x": "-3",
		"y": "0",
		"name": "In a Hurry!: Mighty Friend 9",
		"description": "When the user’s move targeting an allied sync pair (excluding field effects) is successful, increases the Physical Moves ↑ Next effect of the allied sync pair affected by the move by one rank.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": "-2",
		"y": "-1",
		"name": "In a Hurry!: Catalytic Kick 9",
		"description": "Applies the Move Gauge Acceleration effect to the allied field of play when the user’s move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": "-1",
		"y": "-2",
		"name": "In a Hurry!: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": "-3",
		"y": "-1",
		"name": "Trainer Sync Redemption 1",
		"description": "Restores one MP for the user’s Trainer the first time its sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": "-2",
		"y": "-2",
		"name": "Ally Sets WTZ: Physical Boost ↑1 9",
		"description": "Increases the user’s Physical Moves ↑ Next effect by one rank when an ally activates a weather, terrain, or zone effect.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": "0",
		"y": "3",
		"name": "Moonlit Melody Fairy Impact: Power +25",
		"description": "Moonlit Melody Fairy Impact: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": "0",
		"y": "-3",
		"name": "Moonlit Melody Fairy Impact: Power +25",
		"description": "Moonlit Melody Fairy Impact: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const HARMONY_FERALIGATR = [
	{
		"id": 1,
		"x": "-1",
		"y": "0",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "-1",
		"y": "1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "1",
		"y": "0",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "1",
		"y": "-1",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "0",
		"y": "-2",
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 8,
		"x": "0",
		"y": "-4",
		"name": "Entry: Sync Move Boost 5",
		"description": "Increases the user’s Sync Move ↑ Next effect by five ranks when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "4",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 9,
		"x": "1",
		"y": "-4",
		"name": "1st S-Move: Physical Boost 3",
		"description": "Increases the user’s Physical Moves ↑ Next effect by three ranks the first time its sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 10,
		"x": "0",
		"y": "2",
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 11,
		"x": "0",
		"y": "4",
		"name": "Piercing Gaze",
		"description": "Moves never miss.",
		"energy": "10",
		"orb": "120",
		"level": "4",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 12,
		"x": "-1",
		"y": "4",
		"name": "Kalos C (Phys) Extension 5",
		"description": "Extends the duration of Kalos Circle (Physical) when Kalos Circle (Physical) is applied to the allied field of play.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": "-4",
		"y": "0",
		"name": "Lumiose-Loving Traveler Liquidation: Power +30",
		"description": "Lumiose-Loving Traveler Liquidation: Power +30",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 14,
		"x": "-4",
		"y": "1",
		"name": "Lumiose-Loving Traveler Liquidation: Power +30",
		"description": "Lumiose-Loving Traveler Liquidation: Power +30",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 15,
		"x": "-4",
		"y": "2",
		"name": "Lumiose-Loving Traveler Liquidation: Power +30",
		"description": "Lumiose-Loving Traveler Liquidation: Power +30",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 16,
		"x": "2",
		"y": "-1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 17,
		"x": "3",
		"y": "-2",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 18,
		"x": "2",
		"y": "-2",
		"name": "Massive Jaws Liquidation: Power +2",
		"description": "Massive Jaws Liquidation: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 19,
		"x": "1",
		"y": "-2",
		"name": "Massive Jaws Liquidation: Power +2",
		"description": "Massive Jaws Liquidation: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 20,
		"x": "3",
		"y": "-3",
		"name": "Massive Jaws Liquidation: Power +2",
		"description": "Massive Jaws Liquidation: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 21,
		"x": "2",
		"y": "-3",
		"name": "Massive Jaws Liquidation: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 22,
		"x": "1",
		"y": "-3",
		"name": "Speed +10",
		"description": "Speed +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 23,
		"x": "3",
		"y": "-4",
		"name": "Sharpened Body 3",
		"description": "Powers up the user’s moves when its Attack is raised.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": "2",
		"y": "-4",
		"name": "Massive Jaws Liquidation: Move Gauge Refresh 9",
		"description": "Charges the user’s move gauge by one when its move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": "-2",
		"y": "1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 26,
		"x": "-3",
		"y": "2",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 27,
		"x": "-2",
		"y": "2",
		"name": "Rushing Rapids Aqua Jet: Power +2",
		"description": "Rushing Rapids Aqua Jet: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 28,
		"x": "-1",
		"y": "2",
		"name": "Rushing Rapids Aqua Jet: Power +2",
		"description": "Rushing Rapids Aqua Jet: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 29,
		"x": "-3",
		"y": "3",
		"name": "Speed +10",
		"description": "Speed +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": "-2",
		"y": "3",
		"name": "Circle: HP Recovery 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action when a circle applies to the allied field of play.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": "-1",
		"y": "3",
		"name": "Circle: MG → 2",
		"description": "Quickly charges the move gauge when a circle applies to the allied field of play.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 32,
		"x": "-3",
		"y": "4",
		"name": "Haymaker",
		"description": "The more the user’s Attack is raised, the more it powers up the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": "-2",
		"y": "4",
		"name": "Adrenaline 1",
		"description": "Reduces the sync move countdown by one the first time the user’s sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": "1",
		"y": "1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 35,
		"x": "2",
		"y": "1",
		"name": "Unflappable",
		"description": "Prevents the user from flinching.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": "3",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": "1",
		"y": "2",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 38,
		"x": "2",
		"y": "2",
		"name": "Rushing Rapids Aqua Jet: Power +2",
		"description": "Rushing Rapids Aqua Jet: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 39,
		"x": "3",
		"y": "2",
		"name": "Rushing Rapids Aqua Jet: Power +2",
		"description": "Rushing Rapids Aqua Jet: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 40,
		"x": "1",
		"y": "3",
		"name": "Rushing Rapids Aqua Jet: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 41,
		"x": "2",
		"y": "3",
		"name": "Healthy Healing",
		"description": "Applies the Gradual Healing effect to the user if its HP is full when it enters a battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 42,
		"x": "3",
		"y": "3",
		"name": "Attack +10",
		"description": "Attack +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 43,
		"x": "1",
		"y": "4",
		"name": "Discombobulate 4",
		"description": "Has a chance (50%) of lowering the target’s accuracy by one stat rank when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": "2",
		"y": "4",
		"name": "Defense Crush 9",
		"description": "Lowers the target’s Defense by one stat rank when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": "-1",
		"y": "-1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 46,
		"x": "-2",
		"y": "-1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 47,
		"x": "-3",
		"y": "-1",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 48,
		"x": "-1",
		"y": "-2",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 49,
		"x": "-2",
		"y": "-2",
		"name": "Massive Jaws Liquidation: Power +2",
		"description": "Massive Jaws Liquidation: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 50,
		"x": "-3",
		"y": "-2",
		"name": "Massive Jaws Liquidation: Power +2",
		"description": "Massive Jaws Liquidation: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 51,
		"x": "-1",
		"y": "-3",
		"name": "With Confidence!: Super Preparation 9",
		"description": "Applies the Supereffective ↑ Next effect to the user when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 52,
		"x": "-2",
		"y": "-3",
		"name": "Circle: Attack Move DR 2",
		"description": "Reduces damage when the user is hit by an attack move while a circle applies to the allied field of play.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 53,
		"x": "-3",
		"y": "-3",
		"name": "With Confidence!: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 54,
		"x": "-1",
		"y": "-4",
		"name": "Endurance",
		"description": "Applies the Enduring effect to the user if its HP is full when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 55,
		"x": "-2",
		"y": "-4",
		"name": "Vigilance",
		"description": "Protects the user against critical hits.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 56,
		"x": "0",
		"y": "-3",
		"name": "Lumiose-Loving Traveler Liquidation: Power +25",
		"description": "Lumiose-Loving Traveler Liquidation: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 57,
		"x": "0",
		"y": "3",
		"name": "Lumiose-Loving Traveler Liquidation: Power +25",
		"description": "Lumiose-Loving Traveler Liquidation: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const URBAIN_MEGANIUM = [
	{
		"id": 1,
		"x": "1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "1",
		"y": "0",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "-1",
		"y": "1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "-1",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "0",
		"y": "-2",
		"name": "1st S-Move: Special Boost 1",
		"description": "Increases the user’s Special Moves ↑ Next effect by one rank the first time its sync move is used each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 8,
		"x": "0",
		"y": "-4",
		"name": "Believe in Our Team!: Initial Propulsion 2",
		"description": "Reduces the user’s sync move countdown by two the first time its move is successful each battle.",
		"energy": "10",
		"orb": "120",
		"level": "4",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 9,
		"x": "-1",
		"y": "-3",
		"name": "Kalos C (Spec) Extension 5",
		"description": "Extends the duration of Kalos Circle (Special) when Kalos Circle (Special) is applied to the allied field of play.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 10,
		"x": "0",
		"y": "2",
		"name": "T-Move: Allied Field MG → 9",
		"description": "Applies the Move Gauge Acceleration effect to the allied field of play when the user’s Trainer uses a move.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 11,
		"x": "0",
		"y": "4",
		"name": "Four-Fleur Solar Beam: Staggering 9",
		"description": "Makes the target flinch when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "4",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 12,
		"x": "1",
		"y": "3",
		"name": "1st “Kalos Analysis” MP 0: Restore MP 1",
		"description": "Restores one MP of the user’s KalosAnalysis the first time the remaining MP for that move is zero each battle.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": "-4",
		"y": "2",
		"name": "Helping People and Pokémon Solar Beam: Power +30",
		"description": "Helping People and Pokémon Solar Beam: Power +30",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 14,
		"x": "-4",
		"y": "3",
		"name": "Helping People and Pokémon Solar Beam: Power +30",
		"description": "Helping People and Pokémon Solar Beam: Power +30",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 15,
		"x": "-4",
		"y": "4",
		"name": "Helping People and Pokémon Solar Beam: Power +30",
		"description": "Helping People and Pokémon Solar Beam: Power +30",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 16,
		"x": "1",
		"y": "-2",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 17,
		"x": "2",
		"y": "-3",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 18,
		"x": "3",
		"y": "-4",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": "1",
		"y": "-3",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": "2",
		"y": "-4",
		"name": "Luxuriant Leaf Storm: Power +2",
		"description": "Luxuriant Leaf Storm: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 21,
		"x": "3",
		"y": "-5",
		"name": "Luxuriant Leaf Storm: Power +2",
		"description": "Luxuriant Leaf Storm: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 22,
		"x": "1",
		"y": "-4",
		"name": "Luxuriant Leaf Storm: Power +2",
		"description": "Luxuriant Leaf Storm: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 23,
		"x": "2",
		"y": "-5",
		"name": "Luxuriant Leaf Storm: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": "3",
		"y": "-6",
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": "1",
		"y": "-5",
		"name": "Hit: Attack ↓ & Sp. Atk ↓ 9",
		"description": "Lowers the target’s Attack and Sp. Atk by one stat rank when the user’s attack move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": "2",
		"y": "-6",
		"name": "Sharpened Mind 3",
		"description": "Powers up the user’s moves when its Sp. Atk is raised.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": "-1",
		"y": "2",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": "-2",
		"y": "3",
		"name": "Dauntless",
		"description": "Sp. Atk cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": "-3",
		"y": "4",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": "-1",
		"y": "3",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 31,
		"x": "-2",
		"y": "4",
		"name": "Four-Fleur Solar Beam: Power +2",
		"description": "Four-Fleur Solar Beam: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 32,
		"x": "-3",
		"y": "5",
		"name": "Four-Fleur Solar Beam: Power +2",
		"description": "Four-Fleur Solar Beam: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 33,
		"x": "-1",
		"y": "4",
		"name": "Four-Fleur Solar Beam: Power +2",
		"description": "Four-Fleur Solar Beam: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 34,
		"x": "-2",
		"y": "5",
		"name": "Circle: HP Recovery 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action when a circle applies to the allied field of play.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": "-3",
		"y": "6",
		"name": "Circle: MG → 2",
		"description": "Quickly charges the move gauge when a circle applies to the allied field of play.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": "-1",
		"y": "5",
		"name": "Endurance",
		"description": "Applies the Enduring effect to the user if its HP is full when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": "-2",
		"y": "6",
		"name": "Team S-Move: Special Boost ↑1 9",
		"description": "Increases the user’s Special Moves ↑ Next effect by one rank after your team’s sync pair uses their sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": "2",
		"y": "-1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": "3",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": "2",
		"y": "0",
		"name": "Four-Fleur Solar Beam: Power +2",
		"description": "Four-Fleur Solar Beam: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 41,
		"x": "1",
		"y": "1",
		"name": "Four-Fleur Solar Beam: Power +2",
		"description": "Four-Fleur Solar Beam: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 42,
		"x": "3",
		"y": "0",
		"name": "Four-Fleur Solar Beam: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": "2",
		"y": "1",
		"name": "Speed +10",
		"description": "Speed +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 44,
		"x": "1",
		"y": "2",
		"name": "First Aid 2",
		"description": "Restores the user’s HP by approximately 20% of its maximum HP the first time it is in a pinch each battle.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": "3",
		"y": "1",
		"name": "Piercing Gaze",
		"description": "Moves never miss.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": "2",
		"y": "2",
		"name": "Soften Up 1",
		"description": "Critical hits land more easily when the user attacks with a sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": "-2",
		"y": "1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 48,
		"x": "-3",
		"y": "1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 49,
		"x": "-2",
		"y": "0",
		"name": "Luxuriant Leaf Storm: Power +2",
		"description": "Luxuriant Leaf Storm: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 50,
		"x": "-1",
		"y": "-1",
		"name": "Luxuriant Leaf Storm: Power +2",
		"description": "Luxuriant Leaf Storm: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 51,
		"x": "-3",
		"y": "0",
		"name": "Sp. Atk +10",
		"description": "Sp. Atk +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 52,
		"x": "-2",
		"y": "-1",
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 53,
		"x": "-1",
		"y": "-2",
		"name": "Believe in Our Team!: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 54,
		"x": "-3",
		"y": "-1",
		"name": "Physical & Special DR Extension 5",
		"description": "Extends the duration of the Physical Damage Reduction effect when the Physical Damage Reduction effect is applied to the allied field of play. Extends the duration of the Special Damage Reduction effect when the Special Damage Reduction effect is applied to the allied field of play.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 55,
		"x": "-2",
		"y": "-2",
		"name": "Brainpower",
		"description": "The more the user’s Sp. Atk is raised, the more it powers up its sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 56,
		"x": "0",
		"y": "-3",
		"name": "Helping People and Pokémon Solar Beam: Power +25",
		"description": "Helping People and Pokémon Solar Beam: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 57,
		"x": "0",
		"y": "3",
		"name": "Helping People and Pokémon Solar Beam: Power +25",
		"description": "Helping People and Pokémon Solar Beam: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]
