export const MAY_BLAZIKEN = [
	{
		id: 1,
		x: 1,
		y: -1,
		name: 'HP 10',
		description: 'HP 10',
		energy: '0',
		orb: '5',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 2,
		x: 1,
		y: 0,
		name: 'Attack 5',
		description: 'Attack 5',
		energy: '0',
		orb: '5',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 3,
		x: 0,
		y: 1,
		name: 'Defense 5',
		description: 'Defense 5',
		energy: '0',
		orb: '5',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 4,
		x: -1,
		y: 1,
		name: 'Attack 5',
		description: 'Attack 5',
		energy: '0',
		orb: '5',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 5,
		x: -1,
		y: 0,
		name: 'Sp. Def 5',
		description: 'Sp. Def 5',
		energy: '0',
		orb: '5',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 6,
		x: 0,
		y: -1,
		name: 'Speed 5',
		description: 'Speed 5',
		energy: '0',
		orb: '5',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 7,
		x: 1,
		y: -2,
		name: 'Attack 5',
		description: 'Attack 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 8,
		x: 2,
		y: -3,
		name: 'Defense 5',
		description: 'Defense 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 9,
		x: 1,
		y: -3,
		name: 'HP 10',
		description: 'HP 10',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 10,
		x: 3,
		y: -4,
		name: 'Sp. Def 5',
		description: 'Sp. Def 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 11,
		x: 2,
		y: -4,
		name: 'Blaze Kick: Power 2',
		description: 'Blaze Kick: Power ↑ 2',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'Fire'
	},
	{
		id: 12,
		x: 1,
		y: -4,
		name: 'Blaze Kick: Power 2',
		description: 'Blaze Kick: Power ↑ 2',
		energy: '3',
		orb: '36',
		level: '2',
		color: 'green',
		icon: 'Fire'
	},
	{
		id: 13,
		x: 3,
		y: -5,
		name: 'Blaze Kick: Power 2',
		description: 'Blaze Kick: Power ↑ 2',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'Fire'
	},
	{
		id: 14,
		x: 2,
		y: -5,
		name: 'Blaze Kick: Move Gauge Refresh 3',
		description: 'Move: Blaze Kick Has a chance (40%) of charging the user’s move gauge by one when a move is successful.',
		energy: '7',
		orb: '84',
		level: '2',
		color: 'red',
		icon: 'passive'
	},
	{
		id: 15,
		x: 1,
		y: -5,
		name: 'Insult to Injury',
		description: 'The more the target’s Defense is lowered, the more it powers up the user’s moves.',
		energy: '10',
		orb: '120',
		level: '3',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 16,
		x: 3,
		y: -6,
		name: 'Attack 20',
		description: 'Attack 20',
		energy: '7',
		orb: '84',
		level: '2',
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 17,
		x: 2,
		y: -6,
		name: 'Fierce Entry 2',
		description: 'Raises the user’s Attack by 2 stat ranks when it enters a battle.',
		energy: '10',
		orb: '120',
		level: '3',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 18,
		x: -2,
		y: 1,
		name: 'Speed 5',
		description: 'Speed 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 19,
		x: -3,
		y: 2,
		name: 'Attack 5',
		description: 'Attack 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 20,
		x: -2,
		y: 2,
		name: 'Low Sweep: Move Gauge Refresh 3',
		description: 'Move: Low Sweep Has a chance (40%) of charging the user’s move gauge by one when a move is successful.',
		energy: '7',
		orb: '84',
		level: 1,
		color: 'red',
		icon: 'passive'
	},
	{
		id: 21,
		x: -3,
		y: 3,
		name: 'Low Sweep: Power 3',
		description: 'Low Sweep: Power ↑ 3',
		energy: '3',
		orb: '36',
		level: '2',
		color: 'green',
		icon: 'Fighting'
	},
	{
		id: 22,
		x: -1,
		y: 2,
		name: 'Low Sweep: Power 3',
		description: 'Low Sweep: Power ↑ 3',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'Fighting'
	},
	{
		id: 23,
		x: -2,
		y: 3,
		name: 'Low Sweep: Power 3',
		description: 'Low Sweep: Power ↑ 3',
		energy: '3',
		orb: '36',
		level: '2',
		color: 'green',
		icon: 'Fighting'
	},
	{
		id: 24,
		x: -3,
		y: 4,
		name: 'Speed 20',
		description: 'Speed 20',
		energy: '7',
		orb: '84',
		level: '2',
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 25,
		x: -1,
		y: 3,
		name: 'Trip Up 9',
		description: 'Lowers the target’s Speed by 1 stat rank when the user’s attack move against the target is successful.',
		energy: '10',
		orb: '120',
		level: '3',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 26,
		x: -2,
		y: 4,
		name: 'Cakewalk',
		description: 'The more the target’s Speed is lowered, the more it powers up the user’s sync move.',
		energy: '10',
		orb: '120',
		level: '3',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 27,
		x: 2,
		y: -1,
		name: 'Speed 5',
		description: 'Speed 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 28,
		x: 3,
		y: -1,
		name: 'Flameproof',
		description: 'Prevents the user from getting burned.',
		energy: '5',
		orb: '60',
		level: 1,
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 29,
		x: 2,
		y: 0,
		name: 'HP 10',
		description: 'HP 10',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 30,
		x: 1,
		y: 1,
		name: 'Low Sweep: Power 3',
		description: 'Low Sweep: Power ↑ 3',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'Fighting'
	},
	{
		id: 31,
		x: 3,
		y: 0,
		name: 'Low Sweep: Power 3',
		description: 'Low Sweep: Power ↑ 3',
		energy: '3',
		orb: '36',
		level: '2',
		color: 'green',
		icon: 'Fighting'
	},
	{
		id: 32,
		x: 2,
		y: 1,
		name: 'Fired Up!: MP Refresh 2',
		description: 'Move: Fired Up! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.',
		energy: '7',
		orb: '84',
		level: '2',
		color: 'red',
		icon: 'passive'
	},
	{
		id: 33,
		x: 1,
		y: 2,
		name: 'Adrenaline 1',
		description: 'Reduces the sync move countdown by 1 the first time the user’s sync move is used each battle.',
		energy: '10',
		orb: '120',
		level: '3',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 34,
		x: 3,
		y: 1,
		name: 'Fired Up!: Slippery 2',
		description: 'Move: Fired Up! Raises the user’s evasiveness by 2 stat ranks when its move is successful.',
		energy: '9',
		orb: '108',
		level: '2',
		color: 'red',
		icon: 'passive'
	},
	{
		id: 35,
		x: 2,
		y: 2,
		name: 'All About Us Blaze Kick: Power 25',
		description: 'All About Us Blaze Kick: Power ↑ 25',
		energy: '5',
		orb: '60',
		level: '3',
		color: 'sync',
		icon: 'sync'
	},
	{
		id: 36,
		x: -1,
		y: -1,
		name: 'Attack 5',
		description: 'Attack 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 37,
		x: -2,
		y: -1,
		name: 'HP 10',
		description: 'HP 10',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 38,
		x: -1,
		y: -2,
		name: 'Speed 5',
		description: 'Speed 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 39,
		x: -3,
		y: -1,
		name: 'Blaze Kick: Accuracy 10',
		description: 'Blaze Kick: Accuracy ↑ 10',
		energy: '5',
		orb: '60',
		level: 1,
		color: 'green',
		icon: 'Fire'
	},
	{
		id: 40,
		x: -2,
		y: -2,
		name: 'Blaze Kick: Power 2',
		description: 'Blaze Kick: Power ↑ 2',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'Fire'
	},
	{
		id: 41,
		x: -3,
		y: -2,
		name: 'Dire Hit All +: MP Refresh 2',
		description: 'Move: Dire Hit All + Has a chance (30%) of restoring one MP of the user’s move when that move is successful.',
		energy: '7',
		orb: '84',
		level: 1,
		color: 'red',
		icon: 'passive'
	},
	{
		id: 42,
		x: -1,
		y: -3,
		name: 'Blaze Kick: Power 2',
		description: 'Blaze Kick: Power ↑ 2',
		energy: '3',
		orb: '36',
		level: '2',
		color: 'green',
		icon: 'Fire'
	},
	{
		id: 43,
		x: -2,
		y: -3,
		name: 'Fast-Track 9',
		description: 'Raises the user’s Speed by one stat rank after its Pokémon uses a move.',
		energy: '9',
		orb: '108',
		level: '2',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 44,
		x: -3,
		y: -3,
		name: 'Speeding Sun 2',
		description: 'Quickly charges the move gauge when the weather is sunny.',
		energy: '7',
		orb: '84',
		level: '2',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 45,
		x: -1,
		y: -4,
		name: 'Inertia',
		description: 'The more user’s Speed is raised, the more it powers up the user’s sync move.',
		energy: '10',
		orb: '120',
		level: '3',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 46,
		x: -2,
		y: -4,
		name: 'All About Us Blaze Kick: Power 25',
		description: 'All About Us Blaze Kick: Power ↑ 25',
		energy: '5',
		orb: '60',
		level: '3',
		color: 'sync',
		icon: 'sync'
	},
	{
		id: 47,
		x: 0,
		y: -3,
		name: 'All About Us Blaze Kick: Power 25',
		description: 'All About Us Blaze Kick: Power ↑ 25',
		energy: '5',
		orb: '60',
		level: '3',
		color: 'sync',
		icon: 'sync'
	},
	{
		id: 48,
		x: 0,
		y: 3,
		name: 'All About Us Blaze Kick: Power 25',
		description: 'All About Us Blaze Kick: Power ↑ 25',
		energy: '5',
		orb: '60',
		level: '3',
		color: 'sync',
		icon: 'sync'
	}
]

export const BRENDAN_LATIOS = [
	{
		id: 1,
		x: 1,
		y: -1,
		name: 'HP 10',
		description: 'HP 10',
		energy: '0',
		orb: '5',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 2,
		x: 1,
		y: 0,
		name: 'Sp. Atk 5',
		description: 'Sp. Atk 5',
		energy: '0',
		orb: '5',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 3,
		x: 0,
		y: 1,
		name: 'Defense 5',
		description: 'Defense 5',
		energy: '0',
		orb: '5',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 4,
		x: -1,
		y: 1,
		name: 'Sp. Atk 5',
		description: 'Sp. Atk 5',
		energy: '0',
		orb: '5',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 5,
		x: -1,
		y: 0,
		name: 'Sp. Def 5',
		description: 'Sp. Def 5',
		energy: '0',
		orb: '5',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 6,
		x: 0,
		y: -1,
		name: 'Speed 5',
		description: 'Speed 5',
		energy: '0',
		orb: '5',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 7,
		x: 1,
		y: -2,
		name: 'Speed 5',
		description: 'Speed 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 8,
		x: 2,
		y: -3,
		name: 'Defense 5',
		description: 'Defense 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 9,
		x: 1,
		y: -3,
		name: 'Sp. Def 5',
		description: 'Sp. Def 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 10,
		x: 3,
		y: -4,
		name: 'Luster Purge: Power 3',
		description: 'Luster Purge: Power ↑ 3',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'psychic'
	},
	{
		id: 11,
		x: 2,
		y: -4,
		name: 'Luster Purge: Move Gauge Refresh 3',
		description: 'Move: Luster Purge Has a chance (40%) of charging the user’s move gauge by one when a move is successful.',
		energy: '7',
		orb: '84',
		level: 1,
		color: 'red',
		icon: 'passive'
	},
	{
		id: 12,
		x: 1,
		y: -4,
		name: 'Luster Purge: Power 3',
		description: 'Luster Purge: Power ↑ 3',
		energy: '3',
		orb: '36',
		level: '2',
		color: 'green',
		icon: 'psychic'
	},
	{
		id: 13,
		x: 3,
		y: -5,
		name: 'Luster Purge: Power 3',
		description: 'Luster Purge: Power ↑ 3',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'psychic'
	},
	{
		id: 14,
		x: 2,
		y: -5,
		name: 'Quick Cure',
		description: 'Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.',
		energy: '7',
		orb: '84',
		level: '2',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 15,
		x: 1,
		y: -5,
		name: 'Head Start 1',
		description: 'Reduces the user’s sync move countdown by 1 the first time it enters a battle each battle.',
		energy: '10',
		orb: '120',
		level: '3',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 16,
		x: 3,
		y: -6,
		name: 'Flying Free!: MP Refresh 2',
		description: 'Move: Flying Free! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.',
		energy: '7',
		orb: '84',
		level: '2',
		color: 'red',
		icon: 'passive'
	},
	{
		id: 17,
		x: 2,
		y: -6,
		name: 'Team Sharp Entry 1',
		description: 'Raises the critical-hit rate of all allied sync pairs by 1 stat rank when the user enters a battle.',
		energy: '10',
		orb: '120',
		level: '3',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 18,
		x: -2,
		y: 2,
		name: 'Speed 5',
		description: 'Speed 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 19,
		x: -3,
		y: 3,
		name: 'Sp. Def 5',
		description: 'Sp. Def 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 20,
		x: -1,
		y: 2,
		name: 'HP 10',
		description: 'HP 10',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 21,
		x: -2,
		y: 3,
		name: 'Luster Purge: Power 3',
		description: 'Luster Purge: Power ↑ 3',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'psychic'
	},
	{
		id: 22,
		x: -3,
		y: 4,
		name: 'Luster Purge: Power 3',
		description: 'Luster Purge: Power ↑ 3',
		energy: '3',
		orb: '36',
		level: '2',
		color: 'green',
		icon: 'psychic'
	},
	{
		id: 23,
		x: -1,
		y: 3,
		name: 'Potion: Master Healer 1',
		description: 'Move: Potion Increases the amount of HP restored by the user’s healing moves.',
		energy: '10',
		orb: '120',
		level: '2',
		color: 'red',
		icon: 'passive'
	},
	{
		id: 24,
		x: -2,
		y: 4,
		name: 'Potion: MP Refresh 2',
		description: 'Move: Potion Has a chance (30%) of restoring one MP of the user’s move when that move is successful.',
		energy: '7',
		orb: '84',
		level: '2',
		color: 'red',
		icon: 'passive'
	},
	{
		id: 25,
		x: -3,
		y: 5,
		name: 'Potion: MP Refresh 2',
		description: 'Move: Potion Has a chance (30%) of restoring one MP of the user’s move when that move is successful.',
		energy: '7',
		orb: '84',
		level: '3',
		color: 'red',
		icon: 'passive'
	},
	{
		id: 26,
		x: -1,
		y: 4,
		name: 'Potion: Master Healer 1',
		description: 'Move: Potion Increases the amount of HP restored by the user’s healing moves.',
		energy: '10',
		orb: '120',
		level: '3',
		color: 'red',
		icon: 'passive'
	},
	{
		id: 27,
		x: 1,
		y: 1,
		name: 'Speed 5',
		description: 'Speed 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 28,
		x: 2,
		y: 1,
		name: 'HP 10',
		description: 'HP 10',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 29,
		x: 1,
		y: 2,
		name: 'Defense 5',
		description: 'Defense 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 30,
		x: 3,
		y: 1,
		name: 'Dragon Breath: Power 4',
		description: 'Dragon Breath: Power ↑ 4',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'dragon'
	},
	{
		id: 31,
		x: 2,
		y: 2,
		name: 'Dragon Breath: Move Gauge Refresh 3',
		description: 'Move: Dragon Breath Has a chance (40%) of charging the user’s move gauge by one when a move is successful.',
		energy: '7',
		orb: '84',
		level: 1,
		color: 'red',
		icon: 'passive'
	},
	{
		id: 32,
		x: 1,
		y: 3,
		name: 'Dragon Breath: Power 4',
		description: 'Dragon Breath: Power ↑ 4',
		energy: '3',
		orb: '36',
		level: '2',
		color: 'green',
		icon: 'dragon'
	},
	{
		id: 33,
		x: 3,
		y: 2,
		name: 'Dragon Breath: Power 4',
		description: 'Dragon Breath: Power ↑ 4',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'dragon'
	},
	{
		id: 34,
		x: 2,
		y: 3,
		name: 'Dragon Breath: Hostile Environment 1',
		description: 'Move: Dragon Breath Raises the chance of inflicting status conditions with the additional effects of moves.',
		energy: '10',
		orb: '120',
		level: '2',
		color: 'red',
		icon: 'passive'
	},
	{
		id: 35,
		x: 1,
		y: 4,
		name: 'Impervious',
		description: 'Stats cannot be lowered.',
		energy: '10',
		orb: '120',
		level: '3',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 36,
		x: 3,
		y: 3,
		name: 'Sp. Def 20',
		description: 'Sp. Def 20',
		energy: '7',
		orb: '84',
		level: '2',
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 37,
		x: 2,
		y: 4,
		name: 'Sync Free-for-All',
		description: 'Applies the Free Move Next effect to all allied sync pairs the first time the user’s sync move is used each battle.',
		energy: '10',
		orb: '120',
		level: '3',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 38,
		x: -2,
		y: 0,
		name: 'Defense 5',
		description: 'Defense 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 39,
		x: -1,
		y: -1,
		name: 'HP 10',
		description: 'HP 10',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 40,
		x: -3,
		y: 0,
		name: 'Dragon Breath: Power 4',
		description: 'Dragon Breath: Power ↑ 4',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'dragon'
	},
	{
		id: 41,
		x: -2,
		y: -1,
		name: 'Precognition 2',
		description: 'Quickly charges the user’s move gauge when the terrain is Psychic Terrain.',
		energy: '8',
		orb: '96',
		level: 1,
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 42,
		x: -1,
		y: -2,
		name: 'Dragon Breath: Power 4',
		description: 'Dragon Breath: Power ↑ 4',
		energy: '3',
		orb: '36',
		level: '2',
		color: 'green',
		icon: 'dragon'
	},
	{
		id: 43,
		x: -3,
		y: -1,
		name: 'Weird Recovery 1',
		description: 'Restores the user’s HP whenever its Pokémon takes an action when the terrain is Psychic Terrain.',
		energy: '8',
		orb: '96',
		level: '2',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 44,
		x: -2,
		y: -2,
		name: 'Fast-Track 9',
		description: 'Raises the user’s Speed by one stat rank after its Pokémon uses a move.',
		energy: '9',
		orb: '108',
		level: '2',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 45,
		x: -1,
		y: -3,
		name: 'Team Tough Luck 4',
		description: 'Has a chance (50%) of raising the Defense or Sp. Def—or both—of all allied sync pairs by one stat rank when the user is hit by an attack move.',
		energy: '9',
		orb: '108',
		level: '3',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 46,
		x: -3,
		y: -2,
		name: 'Adrenaline 1',
		description: 'Reduces the sync move countdown by 1 the first time the user’s sync move is used each battle.',
		energy: '10',
		orb: '120',
		level: '3',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 47,
		x: 0,
		y: -3,
		name: 'Good Times Draco Meteor: Power 25',
		description: 'Good Times Draco Meteor: Power ↑ 25',
		energy: '5',
		orb: '60',
		level: '3',
		color: 'sync',
		icon: 'sync'
	},
	{
		id: 48,
		x: 0,
		y: 3,
		name: 'Good Times Draco Meteor: Power 25',
		description: 'Good Times Draco Meteor: Power ↑ 25',
		energy: '5',
		orb: '60',
		level: '3',
		color: 'sync',
		icon: 'sync'
	}
]

export const LOOKER_CROAGUNK = [
	{
		id: 1,
		x: 1,
		y: -1,
		name: 'HP 10',
		description: 'HP 10',
		energy: '0',
		orb: '5',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 2,
		x: 1,
		y: 0,
		name: 'Attack 5',
		description: 'Attack 5',
		energy: '0',
		orb: '5',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 3,
		x: 0,
		y: 1,
		name: 'Defense 5',
		description: 'Defense 5',
		energy: '0',
		orb: '5',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 4,
		x: -1,
		y: 1,
		name: 'Attack 5',
		description: 'Attack 5',
		energy: '0',
		orb: '5',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 5,
		x: -1,
		y: 0,
		name: 'Sp. Def 5',
		description: 'Sp. Def 5',
		energy: '0',
		orb: '5',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 6,
		x: 0,
		y: -1,
		name: 'Speed 5',
		description: 'Speed 5',
		energy: '0',
		orb: '5',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 7,
		x: 1,
		y: -2,
		name: 'Attack 5',
		description: 'Attack 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 8,
		x: 2,
		y: -3,
		name: 'Defense 5',
		description: 'Defense 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 9,
		x: 3,
		y: -4,
		name: 'Antitoxin',
		description: 'Prevents the user from getting poisoned or badly poisoned.',
		energy: '5',
		orb: '60',
		level: 1,
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 10,
		x: 1,
		y: -3,
		name: 'Sp. Def 5',
		description: 'Sp. Def 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 11,
		x: 2,
		y: -4,
		name: 'Poison Jab: Power 2',
		description: 'Poison Jab: Power ↑ 2',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'poison'
	},
	{
		id: 12,
		x: 3,
		y: -5,
		name: 'Poison Jab: Power 2',
		description: 'Poison Jab: Power ↑ 2',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'poison'
	},
	{
		id: 13,
		x: 1,
		y: -4,
		name: 'Poison Jab: Power 2',
		description: 'Poison Jab: Power ↑ 2',
		energy: '3',
		orb: '36',
		level: '2',
		color: 'green',
		icon: 'poison'
	},
	{
		id: 14,
		x: 2,
		y: -5,
		name: 'Poison Jab: Move Gauge Refresh 3',
		description: 'Move: Poison Jab Has a chance (40%) of charging the user’s move gauge by one when a move is successful.',
		energy: '7',
		orb: '84',
		level: '2',
		color: 'red',
		icon: 'passive'
	},
	{
		id: 15,
		x: 3,
		y: -6,
		name: 'Water Guard',
		description: 'Reduces damage when the user is attacked by Water-type moves.',
		energy: '10',
		orb: '120',
		level: '2',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 16,
		x: 1,
		y: -5,
		name: 'Super Syncer',
		description: 'Applies the Supereffective ↑ Next effect to the user the first time its sync move is used each battle.',
		energy: '10',
		orb: '120',
		level: '3',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 17,
		x: 2,
		y: -6,
		name: 'Furious Brawn',
		description: 'The more the user’s Attack is raised, the more it powers up the user’s moves.',
		energy: '10',
		orb: '120',
		level: '3',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 18,
		x: -1,
		y: 2,
		name: 'HP 10',
		description: 'HP 10',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 19,
		x: -2,
		y: 3,
		name: 'Defense 5',
		description: 'Defense 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 20,
		x: -3,
		y: 4,
		name: 'Attack 5',
		description: 'Attack 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 21,
		x: -1,
		y: 3,
		name: 'Sp. Def 5',
		description: 'Sp. Def 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 22,
		x: -2,
		y: 4,
		name: 'Poison Sting: Power 4',
		description: 'Poison Sting: Power ↑ 4',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'poison'
	},
	{
		id: 23,
		x: -3,
		y: 5,
		name: 'Poison Sting: Power 4',
		description: 'Poison Sting: Power ↑ 4',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'poison'
	},
	{
		id: 24,
		x: -1,
		y: 4,
		name: 'Poison Sting: Power 4',
		description: 'Poison Sting: Power ↑ 4',
		energy: '3',
		orb: '36',
		level: '2',
		color: 'green',
		icon: 'poison'
	},
	{
		id: 25,
		x: -2,
		y: 5,
		name: 'Poison Sting: Move Gauge Refresh 3',
		description: 'Move: Poison Sting Has a chance (40%) of charging the user’s move gauge by one when a move is successful.',
		energy: '7',
		orb: '84',
		level: '2',
		color: 'red',
		icon: 'passive'
	},
	{
		id: 26,
		x: -3,
		y: 6,
		name: 'Attack 20',
		description: 'Attack 20',
		energy: '7',
		orb: '84',
		level: '2',
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 27,
		x: -1,
		y: 5,
		name: 'Virulent Toxin 5',
		description: 'Powers up the user’s sync move when the target is poisoned or badly poisoned.',
		energy: '10',
		orb: '120',
		level: '3',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 28,
		x: -2,
		y: 6,
		name: 'Hostile Environment 1',
		description: 'Raises the chance of inflicting status conditions with the additional effects of moves.',
		energy: '10',
		orb: '120',
		level: '3',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 29,
		x: 2,
		y: -1,
		name: 'Speed 5',
		description: 'Speed 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 30,
		x: 3,
		y: -1,
		name: 'Poison Sting: Power 4',
		description: 'Poison Sting: Power ↑ 4',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'poison'
	},
	{
		id: 31,
		x: 2,
		y: 0,
		name: 'Poison Sting: Power 4',
		description: 'Poison Sting: Power ↑ 4',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'poison'
	},
	{
		id: 32,
		x: 1,
		y: 1,
		name: 'HP 10',
		description: 'HP 10',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 33,
		x: 3,
		y: 0,
		name: 'Fast-Track 4',
		description: 'Has a chance (50%) of raising the user’s Speed by one stat rank after its Pokémon uses a move.',
		energy: '8',
		orb: '96',
		level: '2',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 34,
		x: 2,
		y: 1,
		name: 'On the Case!: MP Refresh 2',
		description: 'Move: On the Case! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.',
		energy: '7',
		orb: '84',
		level: '2',
		color: 'red',
		icon: 'passive'
	},
	{
		id: 35,
		x: 1,
		y: 2,
		name: 'Toxic Power 2',
		description: 'Powers up the user’s moves when the target is poisoned or badly poisoned.',
		energy: '8',
		orb: '96',
		level: '2',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 36,
		x: 3,
		y: 1,
		name: 'On the Case!: Berserker 2',
		description: 'Move: On the Case! Raises the user’s Attack by 2 stat ranks when its move is successful.',
		energy: '10',
		orb: '120',
		level: '3',
		color: 'red',
		icon: 'passive'
	},
	{
		id: 37,
		x: 2,
		y: 2,
		name: 'Catalyst',
		description: 'Applies the Move Gauge Acceleration effect to the allied field of play the first time the user’s sync move is used each battle.',
		energy: '9',
		orb: '108',
		level: '3',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 38,
		x: -2,
		y: 1,
		name: 'HP 10',
		description: 'HP 10',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 39,
		x: -3,
		y: 1,
		name: 'Speed 5',
		description: 'Speed 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 40,
		x: -2,
		y: 0,
		name: 'Poison Jab: Power 2',
		description: 'Poison Jab: Power ↑ 2',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'poison'
	},
	{
		id: 41,
		x: -1,
		y: -1,
		name: 'Poison Jab: Power 2',
		description: 'Poison Jab: Power ↑ 2',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'poison'
	},
	{
		id: 42,
		x: -3,
		y: 0,
		name: 'Rain Gear 1',
		description: 'Reduces damage when the user is hit by an attack move while the weather is rainy.',
		energy: '8',
		orb: '96',
		level: '2',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 43,
		x: -2,
		y: -1,
		name: 'Racing Rain 1',
		description: 'Quickly charges the move gauge when the weather is rainy.',
		energy: '7',
		orb: '84',
		level: '2',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 44,
		x: -1,
		y: -2,
		name: 'Dire Hit +: MP Refresh 2',
		description: 'Move: Dire Hit + Has a chance (30%) of restoring one MP of the user’s move when that move is successful.',
		energy: '7',
		orb: '84',
		level: '2',
		color: 'red',
		icon: 'passive'
	},
	{
		id: 45,
		x: -3,
		y: -1,
		name: 'HP 40',
		description: 'HP 40',
		energy: '7',
		orb: '84',
		level: '3',
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 46,
		x: -2,
		y: -2,
		name: 'Double Down 5',
		description: 'Powers up sync moves that are super effective.',
		energy: '10',
		orb: '120',
		level: '3',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 47,
		x: 0,
		y: -3,
		name: 'Hard-Boiled Poison Jab: Power 25',
		description: 'Hard-Boiled Poison Jab: Power ↑ 25',
		energy: '5',
		orb: '60',
		level: '3',
		color: 'sync',
		icon: 'sync'
	},
	{
		id: 48,
		x: 0,
		y: 3,
		name: 'Hard-Boiled Poison Jab: Power 25',
		description: 'Hard-Boiled Poison Jab: Power ↑ 25',
		energy: '5',
		orb: '60',
		level: '3',
		color: 'sync',
		icon: 'sync'
	}
]

export const COURTNEY_CAMERUPT = [
	{
		id: 1,
		x: 1,
		y: -1,
		name: 'HP 10',
		description: 'HP 10',
		energy: '0',
		orb: '5',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 2,
		x: 1,
		y: 0,
		name: 'Attack 5',
		description: 'Attack 5',
		energy: '0',
		orb: '5',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 3,
		x: 0,
		y: 1,
		name: 'Defense 5',
		description: 'Defense 5',
		energy: '0',
		orb: '5',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 4,
		x: -1,
		y: 1,
		name: 'Attack 5',
		description: 'Attack 5',
		energy: '0',
		orb: '5',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 5,
		x: -1,
		y: 0,
		name: 'Sp. Def 5',
		description: 'Sp. Def 5',
		energy: '0',
		orb: '5',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 6,
		x: 0,
		y: -1,
		name: 'Speed 5',
		description: 'Speed 5',
		energy: '0',
		orb: '5',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 7,
		x: 1,
		y: -2,
		name: 'Sp. Def 5',
		description: 'Sp. Def 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 8,
		x: 2,
		y: -3,
		name: 'Defense 5',
		description: 'Defense 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 9,
		x: 1,
		y: -3,
		name: 'Speed 5',
		description: 'Speed 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 10,
		x: 3,
		y: -4,
		name: 'Attack 5',
		description: 'Attack 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 11,
		x: 2,
		y: -4,
		name: 'Bulldoze: Move Gauge Refresh 1',
		description: 'Move: Bulldoze Has a chance (20%) of charging the user’s move gauge by one when a move is successful.',
		energy: '7',
		orb: '84',
		level: 1,
		color: 'red',
		icon: 'passive'
	},
	{
		id: 12,
		x: 1,
		y: -4,
		name: 'Bulldoze: Power 3',
		description: 'Bulldoze: Power ↑ 3',
		energy: '3',
		orb: '36',
		level: '2',
		color: 'green',
		icon: 'ground'
	},
	{
		id: 13,
		x: 3,
		y: -5,
		name: 'Bulldoze: Power 3',
		description: 'Bulldoze: Power ↑ 3',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'ground'
	},
	{
		id: 14,
		x: 2,
		y: -5,
		name: 'Bulldoze: Move Gauge Refresh 3',
		description: 'Move: Bulldoze Has a chance (40%) of charging the user’s move gauge by one when a move is successful.',
		energy: '7',
		orb: '84',
		level: '2',
		color: 'red',
		icon: 'passive'
	},
	{
		id: 15,
		x: 1,
		y: -5,
		name: 'Bulldoze: Trip Up 4',
		description: 'Move: Bulldoze Has a chance (50%) of lowering the target’s Speed by one stat rank when the user’s attack move against it is successful.',
		energy: '9',
		orb: '108',
		level: '3',
		color: 'red',
		icon: 'passive'
	},
	{
		id: 16,
		x: 3,
		y: -6,
		name: 'Attack 20',
		description: 'Attack 20',
		energy: '7',
		orb: '84',
		level: '2',
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 17,
		x: 2,
		y: -6,
		name: 'Hunter’s Instinct',
		description: 'The more the target’s Speed is lowered, the more it powers up the user’s moves.',
		energy: '10',
		orb: '120',
		level: '3',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 18,
		x: -2,
		y: 1,
		name: 'Speed 5',
		description: 'Speed 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 19,
		x: -3,
		y: 2,
		name: 'Unbending',
		description: 'Defense cannot be lowered.',
		energy: '5',
		orb: '60',
		level: 1,
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 20,
		x: -2,
		y: 2,
		name: 'Sp. Def 5',
		description: 'Sp. Def 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 21,
		x: -3,
		y: 3,
		name: 'Healthy Healing',
		description: 'Applies the Gradual Healing effect to the user when its HP is full when it enters a battle.',
		energy: '8',
		orb: '96',
		level: '2',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 22,
		x: -1,
		y: 2,
		name: 'Bulldoze: Power 3',
		description: 'Bulldoze: Power ↑ 3',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'ground'
	},
	{
		id: 23,
		x: -2,
		y: 3,
		name: 'X Defense: MP Refresh 2',
		description: 'Move: X Defense Has a chance (30%) of restoring one MP of the user’s move when that move is successful.',
		energy: '7',
		orb: '84',
		level: '2',
		color: 'red',
		icon: 'passive'
	},
	{
		id: 24,
		x: -3,
		y: 4,
		name: 'Defense 20',
		description: 'Defense 20',
		energy: '7',
		orb: '84',
		level: '2',
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 25,
		x: -1,
		y: 3,
		name: 'Team Sentry Entry 1',
		description: 'Raises the Defense of all allied sync pairs by 1 stat rank when the user enters a battle.',
		energy: '10',
		orb: '120',
		level: '3',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 26,
		x: -2,
		y: 4,
		name: 'Towering Force',
		description: 'The more the user’s Defense is raised, the more it powers up the user’s sync move.',
		energy: '10',
		orb: '120',
		level: '3',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 27,
		x: 2,
		y: -1,
		name: 'Defense 5',
		description: 'Defense 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 28,
		x: 3,
		y: -1,
		name: 'HP 10',
		description: 'HP 10',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 29,
		x: 2,
		y: 0,
		name: 'Speed 5',
		description: 'Speed 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 30,
		x: 1,
		y: 1,
		name: 'Bulldoze: Power 3',
		description: 'Bulldoze: Power ↑ 3',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'ground'
	},
	{
		id: 31,
		x: 3,
		y: 0,
		name: 'Flameproof',
		description: 'Prevents the user from getting burned.',
		energy: '5',
		orb: '60',
		level: '2',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 32,
		x: 2,
		y: 1,
		name: 'Ground Wish: Move Gauge Refresh 3',
		description: 'Move: Ground Wish Has a chance (40%) of charging the user’s move gauge by one when a move is successful.',
		energy: '7',
		orb: '84',
		level: '2',
		color: 'red',
		icon: 'passive'
	},
	{
		id: 33,
		x: 1,
		y: 2,
		name: 'Team Wise Entry 1',
		description: 'Raises the Sp. Def of all allied sync pairs by 1 stat rank when the user enters a battle.',
		energy: '10',
		orb: '120',
		level: '3',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 34,
		x: 3,
		y: 1,
		name: 'Fierce Entry 1',
		description: 'Raises the user’s Attack by 1 stat rank when it enters a battle.',
		energy: '9',
		orb: '108',
		level: '2',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 35,
		x: 2,
		y: 2,
		name: 'Earthen Opening Sync',
		description: 'Turns the field of play’s zone into a Ground Zone the first time the user’s sync move is used each battle. (A Ground Zone powers up Ground-type attacks.)',
		energy: '12',
		orb: '144',
		level: '3',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 36,
		x: -1,
		y: -1,
		name: 'Sp. Def 5',
		description: 'Sp. Def 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 37,
		x: -2,
		y: -1,
		name: 'Speed 5',
		description: 'Speed 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 38,
		x: -1,
		y: -2,
		name: 'HP 10',
		description: 'HP 10',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 39,
		x: -3,
		y: -1,
		name: 'Attack 5',
		description: 'Attack 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 40,
		x: -2,
		y: -2,
		name: 'Sp. Def 5',
		description: 'Sp. Def 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 41,
		x: -3,
		y: -2,
		name: 'Delete...: MP Refresh 2',
		description: 'Move: Delete... Has a chance (30%) of restoring one MP of the user’s move when that move is successful.',
		energy: '7',
		orb: '84',
		level: 1,
		color: 'red',
		icon: 'passive'
	},
	{
		id: 42,
		x: -1,
		y: -3,
		name: 'Bulldoze: Power 3',
		description: 'Bulldoze: Power ↑ 3',
		energy: '3',
		orb: '36',
		level: '2',
		color: 'green',
		icon: 'ground'
	},
	{
		id: 43,
		x: -2,
		y: -3,
		name: 'Speeding Sun 2',
		description: 'Quickly charges the move gauge when the weather is sunny.',
		energy: '7',
		orb: '84',
		level: '2',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 44,
		x: -3,
		y: -3,
		name: 'Healing Sun 1',
		description: 'Restores the user’s HP whenever its Pokémon takes an action while the weather is sunny.',
		energy: '8',
		orb: '96',
		level: '2',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 45,
		x: -1,
		y: -4,
		name: 'Sharp Entry 1',
		description: 'Raises the user’s critical-hit rate by 1 stat rank when it enters a battle.',
		energy: '10',
		orb: '120',
		level: '3',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 46,
		x: -2,
		y: -4,
		name: 'Super Syncer',
		description: 'Applies the Supereffective ↑ Next effect to the user the first time its sync move is used each battle.',
		energy: '10',
		orb: '120',
		level: '3',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 47,
		x: 0,
		y: -3,
		name: 'Analysis Complete Earthquake: Power 25',
		description: 'Analysis Complete Earthquake: Power ↑ 25',
		energy: '5',
		orb: '60',
		level: '3',
		color: 'sync',
		icon: 'sync'
	},
	{
		id: 48,
		x: 0,
		y: 3,
		name: 'Analysis Complete Earthquake: Power 25',
		description: 'Analysis Complete Earthquake: Power ↑ 25',
		energy: '5',
		orb: '60',
		level: '3',
		color: 'sync',
		icon: 'sync'
	}
]