export const DRAYTON_ARCHALUDON = [
	{
		"id": 1,
		"x": "1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "1",
		"y": "0",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "-1",
		"y": "1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "-1",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "0",
		"y": "-2",
		"name": "Circle: MG → 2",
		"description": "Quickly charges the move gauge when a circle applies to the allied field of play.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 8,
		"x": "0",
		"y": "-4",
		"name": "Dragon Zone: Team Moves ↑ 2",
		"description": "Powers up the moves of all allied sync pairs when the zone is a Dragon Zone.",
		"energy": "10",
		"orb": "120",
		"level": "4",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 9,
		"x": "0",
		"y": "-5",
		"name": "1st S-Move: Dragon Zone & Extension 3",
		"description": "Turns the field of play’s zone into a Dragon Zone the first time the user’s sync move is used each battle. (A Dragon Zone powers up Dragon-type attacks.) Extends the duration of the Dragon Zone when the zone turns into a Dragon Zone while the user is on the field.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 10,
		"x": "0",
		"y": "2",
		"name": "Circle: Attack Move DR 2",
		"description": "Reduces damage when the user is hit by an attack move while a circle applies to the allied field of play.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 11,
		"x": "-1",
		"y": "4",
		"name": "Circle: Team S-Moves ↑ 3",
		"description": "Powers up the sync moves of all allied sync pairs when a circle applies to the allied field of play.",
		"energy": "10",
		"orb": "120",
		"level": "4",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 12,
		"x": "1",
		"y": "3",
		"name": "1st “Paldea Analysis” MP 0: Restore MP 1",
		"description": "Restores one MP of the user’s PaldeaAnalysis the first time the remaining MP for that move is zero each battle.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": "1",
		"y": "-2",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 14,
		"x": "2",
		"y": "-3",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 15,
		"x": "1",
		"y": "-3",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 16,
		"x": "3",
		"y": "-4",
		"name": "Clearheaded",
		"description": "Prevents the user from becoming confused.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": "2",
		"y": "-4",
		"name": "Steel Flash Dragon Pulse: Power +3",
		"description": "Steel Flash Dragon Pulse: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "dragon"
	},
	{
		"id": 18,
		"x": "1",
		"y": "-4",
		"name": "Steel Flash Dragon Pulse: Power +3",
		"description": "Steel Flash Dragon Pulse: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "dragon"
	},
	{
		"id": 19,
		"x": "3",
		"y": "-5",
		"name": "Steel Flash Dragon Pulse: Power +3",
		"description": "Steel Flash Dragon Pulse: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "dragon"
	},
	{
		"id": 20,
		"x": "2",
		"y": "-5",
		"name": "Steel Flash Dragon Pulse: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 21,
		"x": "1",
		"y": "-5",
		"name": "Soften Up 1",
		"description": "Critical hits land more easily when the user attacks with a sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 22,
		"x": "3",
		"y": "-6",
		"name": "Dragon Zone: HP Recovery 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action when the zone is a Dragon Zone.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 23,
		"x": "2",
		"y": "-6",
		"name": "Foul Fighting 3",
		"description": "Powers up the user’s moves against targets that are flinching, confused, or trapped.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": "-2",
		"y": "1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 25,
		"x": "-3",
		"y": "2",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 26,
		"x": "-2",
		"y": "2",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 27,
		"x": "-3",
		"y": "3",
		"name": "Sapphire Tera Blast: Power +3",
		"description": "Sapphire Tera Blast: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "dragon"
	},
	{
		"id": 28,
		"x": "-1",
		"y": "2",
		"name": "Sapphire Tera Blast: Power +3",
		"description": "Sapphire Tera Blast: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "dragon"
	},
	{
		"id": 29,
		"x": "-2",
		"y": "3",
		"name": "Sapphire Tera Blast: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 30,
		"x": "-3",
		"y": "4",
		"name": "Sp. Atk +10",
		"description": "Sp. Atk +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 31,
		"x": "-1",
		"y": "3",
		"name": "Sapphire Tera Blast: Shocked Hit Freebie 9",
		"description": "Applies the Free Move Next effect to the user when its attack move is successful against a paralyzed opponent.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 32,
		"x": "-2",
		"y": "4",
		"name": "Hit Paralyzed Opp: Attack ↓2 9",
		"description": "Lowers the target’s Attack by two stat ranks when the user’s attack move is successful against a paralyzed opponent.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": "2",
		"y": "-1",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": "3",
		"y": "-1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 35,
		"x": "2",
		"y": "0",
		"name": "Thunder Wave: Accuracy +10",
		"description": "Thunder Wave: Accuracy +10",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 36,
		"x": "1",
		"y": "1",
		"name": "Steel Flash Dragon Pulse: Power +3",
		"description": "Steel Flash Dragon Pulse: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "dragon"
	},
	{
		"id": 37,
		"x": "3",
		"y": "0",
		"name": "Steel Flash Dragon Pulse: Power +3",
		"description": "Steel Flash Dragon Pulse: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "dragon"
	},
	{
		"id": 38,
		"x": "2",
		"y": "1",
		"name": "Thunder Wave: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 39,
		"x": "1",
		"y": "2",
		"name": "Afflicter’s Fervor 1",
		"description": "Reduces the sync move countdown by one the first time the user’s Pokémon uses a status move each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": "3",
		"y": "1",
		"name": "Thunder Wave: 1st Move Use: Team Special Boost 1",
		"description": "Increases the Special Moves ↑ Next effect of all allied sync pairs by one rank the first time the user’s move is used each battle.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 41,
		"x": "2",
		"y": "2",
		"name": "Circle: S-Moves ↑ 9",
		"description": "Powers up the user’s sync move when a circle applies to the allied field of play.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 42,
		"x": "-1",
		"y": "-1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 43,
		"x": "-2",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 44,
		"x": "-1",
		"y": "-2",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 45,
		"x": "-3",
		"y": "-1",
		"name": "Dauntless",
		"description": "Sp. Atk cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": "-2",
		"y": "-2",
		"name": "Sapphire Tera Blast: Power +3",
		"description": "Sapphire Tera Blast: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "dragon"
	},
	{
		"id": 47,
		"x": "-3",
		"y": "-2",
		"name": "Sapphire Tera Blast: Power +3",
		"description": "Sapphire Tera Blast: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "dragon"
	},
	{
		"id": 48,
		"x": "-1",
		"y": "-3",
		"name": "Sapphire Tera Blast: Power +3",
		"description": "Sapphire Tera Blast: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "dragon"
	},
	{
		"id": 49,
		"x": "-2",
		"y": "-3",
		"name": "Paldea Analysis: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 50,
		"x": "-3",
		"y": "-3",
		"name": "What I Like to Hear!: Move on Ally: Supereffective ↑ Next 9",
		"description": "When the user’s move targeting an allied sync pair (excluding field effects) is successful, applies the Supereffective ↑ Next effect to the allied sync pair affected by the move.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 51,
		"x": "-1",
		"y": "-4",
		"name": "Paldea C (Spec) Extension 3",
		"description": "Extends the duration of Paldea Circle (Special) when Paldea Circle (Special) is applied to the allied field of play.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 52,
		"x": "-2",
		"y": "-4",
		"name": "1st Use Status P-Move: Sp. Atk ↑ 2",
		"description": "Raises the user’s Sp. Atk by two stat ranks the first time its Pokémon uses a status move each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 53,
		"x": "0",
		"y": "-3",
		"name": "Reign of Dragon’s Blood Tera Blast: Power +25",
		"description": "Reign of Dragon’s Blood Tera Blast: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 54,
		"x": "0",
		"y": "3",
		"name": "Reign of Dragon’s Blood Tera Blast: Power +25",
		"description": "Reign of Dragon’s Blood Tera Blast: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const HAU_INCINEROAR = [
	{
		"id": 1,
		"x": "1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "1",
		"y": "0",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "-1",
		"y": "1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "-1",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "2",
		"y": "-1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": "3",
		"y": "-2",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": "2",
		"y": "-2",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": "1",
		"y": "-2",
		"name": "Brutal Swing: Power +4",
		"description": "Brutal Swing: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 11,
		"x": "1",
		"y": "-3",
		"name": "Brutal Swing: Power +4",
		"description": "Brutal Swing: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 12,
		"x": "2",
		"y": "-3",
		"name": "Brutal Swing: Numbing Blow 4",
		"description": "Has a chance (50%) of leaving the target paralyzed when the user’s attack move against it is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": "3",
		"y": "-3",
		"name": "Brutal Swing: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 14,
		"x": "2",
		"y": "-4",
		"name": "1st “Dark Wish” MP 0: Physical Boost 3",
		"description": "Increases the user’s Physical Moves ↑ Next effect by three ranks the first time the remaining MP for its Dark Wish is zero each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": "3",
		"y": "-4",
		"name": "Ally Sets WTZ: Physical Boost ↑1 9",
		"description": "Increases the user’s Physical Moves ↑ Next effect by one rank when an ally activates a weather, terrain, or zone effect.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": "-1",
		"y": "2",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 17,
		"x": "-2",
		"y": "3",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 18,
		"x": "-1",
		"y": "3",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": "-3",
		"y": "4",
		"name": "Headstrong",
		"description": "Attack cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 20,
		"x": "-2",
		"y": "4",
		"name": "Brutal Swing: Power +4",
		"description": "Brutal Swing: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 21,
		"x": "-1",
		"y": "4",
		"name": "Brutal Swing: Power +4",
		"description": "Brutal Swing: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 22,
		"x": "-3",
		"y": "5",
		"name": "Brutal Swing: Power +4",
		"description": "Brutal Swing: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 23,
		"x": "-2",
		"y": "5",
		"name": "We’ll Have a Blast!: MP Refresh 3",
		"description": "Has a chance (40%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": "-1",
		"y": "5",
		"name": "We’ll Have a Blast!: Move on Ally: Physical Boost ↑2 9",
		"description": "When the user’s move targeting an allied sync pair (excluding field effects) is successful, increases the Physical Moves ↑ Next effect of the allied sync pair affected by the move by two ranks.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": "-3",
		"y": "6",
		"name": "Hit: Sync Move Boost ↑2 9",
		"description": "Increases the user’s Sync Move ↑ Next effect by two ranks when its attack move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": "-2",
		"y": "6",
		"name": "Haymaker",
		"description": "The more the user’s Attack is raised, the more it powers up the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": "1",
		"y": "1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": "2",
		"y": "1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": "1",
		"y": "2",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": "3",
		"y": "1",
		"name": "Psychic Guard",
		"description": "Reduces damage when the user is attacked by Psychic-type moves.",
		"energy": "8",
		"orb": "96",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": "2",
		"y": "2",
		"name": "Wild Whirlwind Darkest Lariat: Power +3",
		"description": "Wild Whirlwind Darkest Lariat: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 32,
		"x": "1",
		"y": "3",
		"name": "Wild Whirlwind Darkest Lariat: Power +3",
		"description": "Wild Whirlwind Darkest Lariat: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 33,
		"x": "3",
		"y": "2",
		"name": "Wild Whirlwind Darkest Lariat: Power +3",
		"description": "Wild Whirlwind Darkest Lariat: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 34,
		"x": "2",
		"y": "3",
		"name": "Dark Wish: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": "1",
		"y": "4",
		"name": "Umbral Acceleration 2",
		"description": "Quickly charges the move gauge when the zone is a Dark Zone.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": "3",
		"y": "3",
		"name": "Satisfied Snicker 9",
		"description": "Lowers the target’s Sp. Atk by one stat rank when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": "2",
		"y": "4",
		"name": "Dark Zone Extension 3",
		"description": "Extends the duration of the Dark Zone when the zone turns into a Dark Zone while the user is on the field.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": "-2",
		"y": "1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": "-3",
		"y": "1",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": "-2",
		"y": "0",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 41,
		"x": "-1",
		"y": "-1",
		"name": "Wild Whirlwind Darkest Lariat: Power +3",
		"description": "Wild Whirlwind Darkest Lariat: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 42,
		"x": "-3",
		"y": "0",
		"name": "Wild Whirlwind Darkest Lariat: Power +3",
		"description": "Wild Whirlwind Darkest Lariat: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 43,
		"x": "-2",
		"y": "-1",
		"name": "Wild Whirlwind Darkest Lariat: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": "-1",
		"y": "-2",
		"name": "Wild Whirlwind Darkest Lariat: Move Gauge Refresh 9",
		"description": "Charges the user’s move gauge by one when its move is successful.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": "-3",
		"y": "-1",
		"name": "Trainer Sync Redemption 1",
		"description": "Restores one MP for the user’s Trainer the first time its sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": "-2",
		"y": "-2",
		"name": "Hunter’s Instinct",
		"description": "The more the target’s Speed is lowered, the more it powers up the user’s moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": "0",
		"y": "3",
		"name": "Bring Out the Best Dark Impact: Power +25",
		"description": "Bring Out the Best Dark Impact: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": "0",
		"y": "-3",
		"name": "Bring Out the Best Dark Impact: Power +25",
		"description": "Bring Out the Best Dark Impact: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const EMMET_GURDURR = [
	{
		"id": 1,
		"x": "1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "1",
		"y": "0",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "-1",
		"y": "1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "-1",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "1",
		"y": "-2",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": "2",
		"y": "-3",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": "1",
		"y": "-3",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": "3",
		"y": "-4",
		"name": "Flameproof",
		"description": "Prevents the user from getting burned.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 11,
		"x": "2",
		"y": "-4",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 12,
		"x": "1",
		"y": "-4",
		"name": "Dynamic Punch: Power +2",
		"description": "Dynamic Punch: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 13,
		"x": "3",
		"y": "-5",
		"name": "Dynamic Punch: Power +2",
		"description": "Dynamic Punch: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 14,
		"x": "2",
		"y": "-5",
		"name": "Dynamic Punch: Power +2",
		"description": "Dynamic Punch: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 15,
		"x": "1",
		"y": "-5",
		"name": "Mighty Command 9",
		"description": "Increases the user’s Physical Moves ↑ Next effect by one rank when its Trainer uses a move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": "3",
		"y": "-6",
		"name": "Superduper Effective 2",
		"description": "Powers up moves that are super effective.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": "2",
		"y": "-6",
		"name": "Insult to Injury",
		"description": "The more the target’s Defense is lowered, the more it powers up the user’s moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": "-2",
		"y": "1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": "-3",
		"y": "2",
		"name": "Headstrong",
		"description": "Attack cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 20,
		"x": "-2",
		"y": "2",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 21,
		"x": "-3",
		"y": "3",
		"name": "Dynamic Punch: Power +2",
		"description": "Dynamic Punch: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 22,
		"x": "-1",
		"y": "2",
		"name": "Dynamic Punch: Power +2",
		"description": "Dynamic Punch: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 23,
		"x": "-2",
		"y": "3",
		"name": "Dynamic Punch: Move Gauge Refresh 2",
		"description": "Has a chance (30%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": "-3",
		"y": "4",
		"name": "Attack +10",
		"description": "Attack +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 25,
		"x": "-1",
		"y": "3",
		"name": "Dynamic Punch: Easy Pickings 9",
		"description": "Lowers one of the target’s following stats by one stat rank at random when the user’s attack move is successful against a confused opponent: Attack, Defense, Sp. Atk, Sp. Def, Speed, accuracy, or evasiveness.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": "-2",
		"y": "4",
		"name": "First Aid 4",
		"description": "Restores the user’s HP by approximately 40% of its maximum HP the first time it is in a pinch each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": "2",
		"y": "-1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": "3",
		"y": "-1",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": "2",
		"y": "0",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": "1",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 31,
		"x": "3",
		"y": "0",
		"name": "We’re Both Real!: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 32,
		"x": "2",
		"y": "1",
		"name": "Healthy Healing",
		"description": "Applies the Gradual Healing effect to the user if its HP is full when it enters a battle.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": "1",
		"y": "2",
		"name": "Haymaker",
		"description": "The more the user’s Attack is raised, the more it powers up the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": "3",
		"y": "1",
		"name": "Curative Confusion 1",
		"description": "Restores the user’s HP when its attack move is successful against a confused opponent.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": "2",
		"y": "2",
		"name": "We’re Both Real!: Berserker 2",
		"description": "Raises the user’s Attack by two stat ranks when its move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": "-1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": "-2",
		"y": "-1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 38,
		"x": "-1",
		"y": "-2",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": "-3",
		"y": "-1",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": "-2",
		"y": "-2",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 41,
		"x": "-3",
		"y": "-2",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 42,
		"x": "-1",
		"y": "-3",
		"name": "X Accuracy: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": "-2",
		"y": "-3",
		"name": "Leer: Move Gauge Refresh 2",
		"description": "Has a chance (30%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": "-3",
		"y": "-3",
		"name": "Catalytic Infliction",
		"description": "Applies the Move Gauge Acceleration effect to the allied field of play the first time the user’s Pokémon uses a status move each battle.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": "-1",
		"y": "-4",
		"name": "Fast-Track 9",
		"description": "Raises the user’s Speed by one stat rank when its Pokémon uses a move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": "-2",
		"y": "-4",
		"name": "Impose 1",
		"description": "Lowers the evasiveness of all opposing sync pairs by one stat rank when the user enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": "0",
		"y": "-3",
		"name": "Great Battle Fighting Impact: Power +25",
		"description": "Great Battle Fighting Impact: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": "0",
		"y": "3",
		"name": "Great Battle Fighting Impact: Power +25",
		"description": "Great Battle Fighting Impact: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const KIERAN_FURRET = [
	{
		"id": 1,
		"x": "1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "1",
		"y": "0",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "-1",
		"y": "1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "-1",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "0",
		"y": "-2",
		"name": "1st T-Move: Restore MP 1",
		"description": "Restores one MP for the user the first time its Trainer uses a move each battle.",
		"energy": "0",
		"orb": "5",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 8,
		"x": "0",
		"y": "2",
		"name": "Ice Zone Extension & Paldea C (Spec) Extension 3",
		"description": "Extends the duration of the Ice Zone when the zone turns into an Ice Zone while the user is on the field. Extends the duration of Paldea Circle (Special) when Paldea Circle (Special) is applied to the allied field of play.",
		"energy": "0",
		"orb": "5",
		"level": "4",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 9,
		"x": "1",
		"y": "-2",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": "2",
		"y": "-3",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": "3",
		"y": "-4",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 12,
		"x": "1",
		"y": "-3",
		"name": "Dauntless",
		"description": "Sp. Atk cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": "2",
		"y": "-4",
		"name": "Cryolite Tera Blast: Power +4",
		"description": "Cryolite Tera Blast: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 14,
		"x": "3",
		"y": "-5",
		"name": "Cryolite Tera Blast: Power +4",
		"description": "Cryolite Tera Blast: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 15,
		"x": "1",
		"y": "-4",
		"name": "Cryolite Tera Blast: Power +4",
		"description": "Cryolite Tera Blast: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 16,
		"x": "2",
		"y": "-5",
		"name": "Cryolite Tera Blast: Move Gauge Refresh 2",
		"description": "Has a chance (30%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": "3",
		"y": "-6",
		"name": "First Aid 4",
		"description": "Restores the user’s HP by approximately 40% of its maximum HP the first time it is in a pinch each battle.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": "1",
		"y": "-5",
		"name": "Furious Brain",
		"description": "The more the user’s Sp. Atk is raised, the more it powers up the user’s moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 19,
		"x": "2",
		"y": "-6",
		"name": "Vigilance",
		"description": "Protects the user against critical hits.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 20,
		"x": "-1",
		"y": "2",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 21,
		"x": "-2",
		"y": "3",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 22,
		"x": "-3",
		"y": "4",
		"name": "Snow Shelter",
		"description": "Protects the user from damage from a hailstorm.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 23,
		"x": "-1",
		"y": "3",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 24,
		"x": "-2",
		"y": "4",
		"name": "Courage to Continue Ice Beam: Power +4",
		"description": "Courage to Continue Ice Beam: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 25,
		"x": "-3",
		"y": "5",
		"name": "Courage to Continue Ice Beam: Power +4",
		"description": "Courage to Continue Ice Beam: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 26,
		"x": "-1",
		"y": "4",
		"name": "Gobsmack 4",
		"description": "Has a chance (50%) of leaving the target confused when the user’s attack move against it is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": "-2",
		"y": "5",
		"name": "Courage to Continue Ice Beam: Move Gauge Refresh 2",
		"description": "Has a chance (30%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 28,
		"x": "-3",
		"y": "6",
		"name": "Courage to Continue Ice Beam: Power +4",
		"description": "Courage to Continue Ice Beam: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 29,
		"x": "-1",
		"y": "5",
		"name": "Recharging Strike 9",
		"description": "Charges the user’s move gauge by one when its attack move hits. If the move has the Multistrike effect tag, charges the user’s move gauge by one for each hit.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 30,
		"x": "-2",
		"y": "6",
		"name": "Hit: Special Boost ↑1 9",
		"description": "Increases the user’s Special Moves ↑ Next effect by one rank when its attack move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": "2",
		"y": "-1",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 32,
		"x": "3",
		"y": "-1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 33,
		"x": "2",
		"y": "0",
		"name": "Great Strides Blizzard: Power +4",
		"description": "Great Strides Blizzard: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 34,
		"x": "1",
		"y": "1",
		"name": "Great Strides Blizzard: Power +4",
		"description": "Great Strides Blizzard: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 35,
		"x": "3",
		"y": "0",
		"name": "Great Strides Blizzard: Power +4",
		"description": "Great Strides Blizzard: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 36,
		"x": "2",
		"y": "1",
		"name": "Great Strides Blizzard: Move Gauge Refresh 2",
		"description": "Has a chance (30%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": "1",
		"y": "2",
		"name": "Healthy Healing",
		"description": "Applies the Gradual Healing effect to the user if its HP is full when it enters a battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": "3",
		"y": "1",
		"name": "Ally Sets Circle: Special Boost ↑1 9",
		"description": "Increases the user’s Special Moves ↑ Next effect by one rank when an ally applies a circle to the allied field of play.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 39,
		"x": "2",
		"y": "2",
		"name": "Brainpower",
		"description": "The more the user’s Sp. Atk is raised, the more it powers up its sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": "-2",
		"y": "1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 41,
		"x": "-3",
		"y": "1",
		"name": "Antifreeze",
		"description": "Prevents the user from becoming frozen.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 42,
		"x": "-2",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 43,
		"x": "-1",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 44,
		"x": "-3",
		"y": "0",
		"name": "Ice Zone: HP Recovery 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action when the zone is an Ice Zone.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": "-2",
		"y": "-1",
		"name": "We’ll Go All Out!: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": "-1",
		"y": "-2",
		"name": "Ice Zone: MG → 2",
		"description": "Quickly charges the move gauge when the zone is an Ice Zone.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": "-3",
		"y": "-1",
		"name": "Satisfied Snicker 9",
		"description": "Lowers the target’s Sp. Atk by one stat rank when the user’s attack move against it is successful.",
		"energy": "8",
		"orb": "96",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 48,
		"x": "-2",
		"y": "-2",
		"name": "P-Moves & S-Moves Crit",
		"description": "Except in certain circumstances, successful hits with the user’s following attacks become critical hits: Pokémon’s moves or sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 49,
		"x": "0",
		"y": "-3",
		"name": "Nimble Pursuit Tera Blast: Power +25",
		"description": "Nimble Pursuit Tera Blast: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 50,
		"x": "0",
		"y": "3",
		"name": "Nimble Pursuit Tera Blast: Power +25",
		"description": "Nimble Pursuit Tera Blast: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const RIKA_GREATTUSK = [
	{
		"id": 1,
		"x": "1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "1",
		"y": "0",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "-1",
		"y": "1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "-1",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "2",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": "3",
		"y": "-2",
		"name": "Sand Shelter",
		"description": "Protects the user from damage from a sandstorm.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 9,
		"x": "2",
		"y": "-2",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": "1",
		"y": "-2",
		"name": "Headlong Rush: Power +2",
		"description": "Headlong Rush: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 11,
		"x": "1",
		"y": "-3",
		"name": "Finish This!: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 12,
		"x": "2",
		"y": "-3",
		"name": "Headlong Rush: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": "3",
		"y": "-3",
		"name": "Headlong Rush: Power +2",
		"description": "Headlong Rush: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 14,
		"x": "2",
		"y": "-4",
		"name": "Finish This!: Move on Ally: Physical Boost ↑2 9",
		"description": "When the user’s move targeting an allied sync pair (excluding field effects) is successful, increases the Physical Moves ↑ Next effect of the allied sync pair affected by the move by two ranks.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": "3",
		"y": "-4",
		"name": "Furious Brawn",
		"description": "The more the user’s Attack is raised, the more it powers up the user’s moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": "-1",
		"y": "2",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 17,
		"x": "-2",
		"y": "3",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 18,
		"x": "-1",
		"y": "3",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": "-3",
		"y": "4",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": "-2",
		"y": "4",
		"name": "Ancient Times Earth Power: Power +3",
		"description": "Ancient Times Earth Power: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 21,
		"x": "-1",
		"y": "4",
		"name": "Ancient Times Earth Power: Power +3",
		"description": "Ancient Times Earth Power: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 22,
		"x": "-3",
		"y": "5",
		"name": "Ancient Times Earth Power: Power +3",
		"description": "Ancient Times Earth Power: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 23,
		"x": "-2",
		"y": "5",
		"name": "Booster Energy: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": "-1",
		"y": "5",
		"name": "Ground Zone: MG → 2",
		"description": "Quickly charges the move gauge when the zone is a Ground Zone.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": "-3",
		"y": "6",
		"name": "Ground Zone Extension 3",
		"description": "Extends the duration of the Ground Zone when the zone turns into a Ground Zone while the user is on the field.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": "-2",
		"y": "6",
		"name": "Interference Immunity",
		"description": "Prevents the user from flinching, becoming confused, or becoming trapped.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": "1",
		"y": "1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": "2",
		"y": "1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": "1",
		"y": "2",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": "3",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 31,
		"x": "2",
		"y": "2",
		"name": "Headlong Rush: Power +2",
		"description": "Headlong Rush: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 32,
		"x": "1",
		"y": "3",
		"name": "Headlong Rush: Power +2",
		"description": "Headlong Rush: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 33,
		"x": "3",
		"y": "2",
		"name": "Headlong Rush: Power +2",
		"description": "Headlong Rush: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 34,
		"x": "2",
		"y": "3",
		"name": "Headlong Rush: Attack Trap 9",
		"description": "Leaves the target trapped when the user’s attack move against it is successful.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": "1",
		"y": "4",
		"name": "Ground Zone: HP Recovery 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action when the zone is a Ground Zone.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": "3",
		"y": "3",
		"name": "Headlong Rush: Hit: Attack ↓ & Sp. Atk ↓ 9",
		"description": "Lowers the target’s Attack and Sp. Atk by one stat rank when the user’s attack move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": "2",
		"y": "4",
		"name": "Ground Zone Hit: Free Move Next 9",
		"description": "Applies the Free Move Next effect to the user when its attack move is successful while the zone is a Ground Zone.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": "-2",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": "-3",
		"y": "1",
		"name": "Antitoxin",
		"description": "Prevents the user from getting poisoned or badly poisoned.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": "-2",
		"y": "0",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 41,
		"x": "-1",
		"y": "-1",
		"name": "Ancient Times Earth Power: Power +3",
		"description": "Ancient Times Earth Power: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 42,
		"x": "-3",
		"y": "0",
		"name": "Ancient Times Earth Power: Power +3",
		"description": "Ancient Times Earth Power: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 43,
		"x": "-2",
		"y": "-1",
		"name": "Ancient Times Earth Power: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": "-1",
		"y": "-2",
		"name": "Attack +10",
		"description": "Attack +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 45,
		"x": "-3",
		"y": "-1",
		"name": "Ferocious Entry 2",
		"description": "Raises the user’s Attack and Sp. Atk by two stat ranks when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": "-2",
		"y": "-2",
		"name": "Opp Defense ↓: S-Moves ↑ 9",
		"description": "Powers up the user’s sync move when the target’s Defense is lowered.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": "0",
		"y": "3",
		"name": "Rumbling Ground Impact: Power +25",
		"description": "Rumbling Ground Impact: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": "0",
		"y": "-3",
		"name": "Rumbling Ground Impact: Power +25",
		"description": "Rumbling Ground Impact: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const POPPY_IRONTREADS = [
	{
		"id": 1,
		"x": "1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "1",
		"y": "0",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "-1",
		"y": "1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "-1",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "2",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": "3",
		"y": "-2",
		"name": "Headstrong",
		"description": "Attack cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 9,
		"x": "2",
		"y": "-2",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": "1",
		"y": "-2",
		"name": "Whirly Twirly Iron Head: Power +3",
		"description": "Whirly Twirly Iron Head: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "steel"
	},
	{
		"id": 11,
		"x": "1",
		"y": "-3",
		"name": "Sp. Atk +10",
		"description": "Sp. Atk +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 12,
		"x": "2",
		"y": "-3",
		"name": "Whirly Twirly Iron Head: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": "3",
		"y": "-3",
		"name": "Whirly Twirly Iron Head: Power +3",
		"description": "Whirly Twirly Iron Head: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "steel"
	},
	{
		"id": 14,
		"x": "2",
		"y": "-4",
		"name": "Opp Sp. Def ↓: S-Moves ↑ 9",
		"description": "Powers up the user’s sync move when the target’s Sp. Def is lowered.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": "3",
		"y": "-4",
		"name": "Ferocious Entry 2",
		"description": "Raises the user’s Attack and Sp. Atk by two stat ranks when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": "-1",
		"y": "2",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 17,
		"x": "-2",
		"y": "3",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 18,
		"x": "-1",
		"y": "3",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": "-3",
		"y": "4",
		"name": "Steel Beam: Accuracy +5",
		"description": "Steel Beam: Accuracy +5",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "steel"
	},
	{
		"id": 20,
		"x": "-2",
		"y": "4",
		"name": "Steel Beam: Power +2",
		"description": "Steel Beam: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "steel"
	},
	{
		"id": 21,
		"x": "-1",
		"y": "4",
		"name": "Steel Beam: Power +2",
		"description": "Steel Beam: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "steel"
	},
	{
		"id": 22,
		"x": "-3",
		"y": "5",
		"name": "Steel Beam: Power +2",
		"description": "Steel Beam: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "steel"
	},
	{
		"id": 23,
		"x": "-2",
		"y": "5",
		"name": "Steel Beam: Gobsmack 9",
		"description": "Leaves the target confused when the user’s attack move against it is successful.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": "-1",
		"y": "5",
		"name": "Metallic Healing 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action when the zone is a Steel Zone.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": "-3",
		"y": "6",
		"name": "Steel Beam: Hit: Attack ↓ & Sp. Atk ↓ 9",
		"description": "Lowers the target’s Attack and Sp. Atk by one stat rank when the user’s attack move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": "-2",
		"y": "6",
		"name": "Steel Zone Hit: Free Move Next 9",
		"description": "Applies the Free Move Next effect to the user when its attack move is successful while the zone is a Steel Zone.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": "1",
		"y": "1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": "2",
		"y": "1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": "1",
		"y": "2",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": "3",
		"y": "1",
		"name": "Sand Shelter",
		"description": "Protects the user from damage from a sandstorm.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": "2",
		"y": "2",
		"name": "Whirly Twirly Iron Head: Power +3",
		"description": "Whirly Twirly Iron Head: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "steel"
	},
	{
		"id": 32,
		"x": "1",
		"y": "3",
		"name": "Whirly Twirly Iron Head: Power +3",
		"description": "Whirly Twirly Iron Head: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "steel"
	},
	{
		"id": 33,
		"x": "3",
		"y": "2",
		"name": "Whirly Twirly Iron Head: Power +3",
		"description": "Whirly Twirly Iron Head: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "steel"
	},
	{
		"id": 34,
		"x": "2",
		"y": "3",
		"name": "Booster Energy: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": "1",
		"y": "4",
		"name": "Metallic Acceleration 2",
		"description": "Quickly charges the move gauge when the zone is a Steel Zone.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": "3",
		"y": "3",
		"name": "Steel Zone Extension 3",
		"description": "Extends the duration of the Steel Zone when the zone turns into a Steel Zone while the user is on the field.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": "2",
		"y": "4",
		"name": "Vigilance",
		"description": "Protects the user against critical hits.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": "-2",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": "-3",
		"y": "1",
		"name": "Dauntless",
		"description": "Sp. Atk cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": "-2",
		"y": "0",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 41,
		"x": "-1",
		"y": "-1",
		"name": "Steel Beam: Power +2",
		"description": "Steel Beam: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "steel"
	},
	{
		"id": 42,
		"x": "-3",
		"y": "0",
		"name": "Steel Beam: Power +2",
		"description": "Steel Beam: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "steel"
	},
	{
		"id": 43,
		"x": "-2",
		"y": "-1",
		"name": "Steel Beam: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": "-1",
		"y": "-2",
		"name": "Oh Wow!: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": "-3",
		"y": "-1",
		"name": "Furious Brain",
		"description": "The more the user’s Sp. Atk is raised, the more it powers up the user’s moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": "-2",
		"y": "-2",
		"name": "Oh Wow!: Move on Ally: Special Boost ↑2 9",
		"description": "When the user’s move targeting an allied sync pair (excluding field effects) is successful, increases the Special Moves ↑ Next effect of the allied sync pair affected by the move by two ranks.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": "0",
		"y": "3",
		"name": "Super Tough Steel Beam from the Future: Power +25",
		"description": "Super Tough Steel Beam from the Future: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": "0",
		"y": "-3",
		"name": "Super Tough Steel Beam from the Future: Power +25",
		"description": "Super Tough Steel Beam from the Future: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const LARRY_KOMALA = [
	{
		"id": 1,
		"x": "1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "1",
		"y": "0",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "-1",
		"y": "1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "-1",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "2",
		"y": "-1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": "3",
		"y": "-2",
		"name": "Ghost Guard",
		"description": "Reduces damage when the user is attacked by Ghost-type moves.",
		"energy": "8",
		"orb": "96",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 9,
		"x": "2",
		"y": "-2",
		"name": "Zeolite Tera Blast: Power +3",
		"description": "Zeolite Tera Blast: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 10,
		"x": "1",
		"y": "-2",
		"name": "Zeolite Tera Blast: Power +3",
		"description": "Zeolite Tera Blast: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 11,
		"x": "1",
		"y": "-3",
		"name": "Asleep & Hit: Stat ↑ 9",
		"description": "Raises one of the user’s following stats by one stat rank at random when its attack move is successful while it is asleep: Attack, Defense, Sp. Atk, Sp. Def, Speed, accuracy, or evasiveness.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 12,
		"x": "2",
		"y": "-3",
		"name": "Zeolite Tera Blast: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": "3",
		"y": "-3",
		"name": "Zeolite Tera Blast: Dashing Team 9",
		"description": "Raises the Speed of all allied sync pairs by one stat rank when the user’s attack move is successful.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 14,
		"x": "2",
		"y": "-4",
		"name": "Dirty Fighting 3",
		"description": "Powers up the user’s moves against targets that are affected by a status condition.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": "3",
		"y": "-4",
		"name": "Relaxed Charm: Team Brain Gain 9",
		"description": "Increases the Special Moves ↑ Next effect of all allied sync pairs by one rank when the user’s move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": "-1",
		"y": "2",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 17,
		"x": "-2",
		"y": "3",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 18,
		"x": "-1",
		"y": "3",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": "-3",
		"y": "4",
		"name": "Dauntless",
		"description": "Sp. Atk cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 20,
		"x": "-2",
		"y": "4",
		"name": "Zeolite Tera Blast: Power +3",
		"description": "Zeolite Tera Blast: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 21,
		"x": "-1",
		"y": "4",
		"name": "Zeolite Tera Blast: Power +3",
		"description": "Zeolite Tera Blast: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 22,
		"x": "-3",
		"y": "5",
		"name": "Zeolite Tera Blast: Power +3",
		"description": "Zeolite Tera Blast: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 23,
		"x": "-2",
		"y": "5",
		"name": "Relaxed Charm: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": "-1",
		"y": "5",
		"name": "Circle: MG → 2",
		"description": "Quickly charges the move gauge when a circle applies to the allied field of play.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": "-3",
		"y": "6",
		"name": "Circle Hit: Free Move Next 9",
		"description": "Applies the Free Move Next effect to the user when its attack move is successful while a circle applies to the allied field of play.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": "-2",
		"y": "6",
		"name": "Paldea C (Spec) Extension 3",
		"description": "Extends the duration of Paldea Circle (Special) when Paldea Circle (Special) is applied to the allied field of play.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": "1",
		"y": "1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": "2",
		"y": "1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": "1",
		"y": "2",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": "3",
		"y": "1",
		"name": "Rock Tomb: Power +4",
		"description": "Rock Tomb: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 31,
		"x": "2",
		"y": "2",
		"name": "Rock Tomb: Power +4",
		"description": "Rock Tomb: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 32,
		"x": "1",
		"y": "3",
		"name": "Rock Tomb: Power +4",
		"description": "Rock Tomb: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 33,
		"x": "3",
		"y": "2",
		"name": "They Suit Me...: MP Refresh 3",
		"description": "Has a chance (40%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": "2",
		"y": "3",
		"name": "Potion: Master Healer 1",
		"description": "Increases the amount of HP restored by the user’s healing moves.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": "1",
		"y": "4",
		"name": "Asleep: Attack Move DR 2",
		"description": "Reduces damage when the user is hit by an attack move while asleep.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": "3",
		"y": "3",
		"name": "Potion: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": "2",
		"y": "4",
		"name": "Brainpower",
		"description": "The more the user’s Sp. Atk is raised, the more it powers up its sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": "-2",
		"y": "1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": "-3",
		"y": "1",
		"name": "Rock Tomb: Accuracy +5",
		"description": "Rock Tomb: Accuracy +5",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 40,
		"x": "-2",
		"y": "0",
		"name": "Rock Tomb: Power +4",
		"description": "Rock Tomb: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 41,
		"x": "-1",
		"y": "-1",
		"name": "Rock Tomb: Power +4",
		"description": "Rock Tomb: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 42,
		"x": "-3",
		"y": "0",
		"name": "Normal Zone: HP Recovery 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action when the zone is a Normal Zone.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": "-2",
		"y": "-1",
		"name": "Rock Tomb: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": "-1",
		"y": "-2",
		"name": "Rock Tomb: Trip Up 9",
		"description": "Lowers the target’s Speed by one stat rank when the user’s attack move against it is successful.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": "-3",
		"y": "-1",
		"name": "Normal Zone: Team S-Moves ↑ 3",
		"description": "Powers up the sync moves of all allied sync pairs when the zone is a Normal Zone.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": "-2",
		"y": "-2",
		"name": "Normal Zone Extension 3",
		"description": "Extends the duration of the Normal Zone when the zone turns into a Normal Zone while the user is on the field.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": "0",
		"y": "3",
		"name": "Just Let Me Sleep Tera Blast: Power +25",
		"description": "Just Let Me Sleep Tera Blast: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": "0",
		"y": "-3",
		"name": "Just Let Me Sleep Tera Blast: Power +25",
		"description": "Just Let Me Sleep Tera Blast: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const FLANNERY_MAGCARGO = [
	{
		"id": 1,
		"x": "-1",
		"y": "0",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "-1",
		"y": "1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "1",
		"y": "0",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "1",
		"y": "-1",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "2",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": "3",
		"y": "-2",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": "2",
		"y": "-2",
		"name": "Fire Spin: Power +4",
		"description": "Fire Spin: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 10,
		"x": "1",
		"y": "-2",
		"name": "Fire Spin: Power +4",
		"description": "Fire Spin: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 11,
		"x": "3",
		"y": "-3",
		"name": "Fire Spin: Power +4",
		"description": "Fire Spin: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 12,
		"x": "2",
		"y": "-3",
		"name": "Fire Spin: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": "1",
		"y": "-3",
		"name": "Fire Spin: Dashing Team 9",
		"description": "Raises the Speed of all allied sync pairs by one stat rank when the user’s attack move is successful.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 14,
		"x": "3",
		"y": "-4",
		"name": "Fire Spin: Hit: Team Apply Status Change 9",
		"description": "When the user inflicts a status change on an opponent with the additional effects of a move, inflicts the same status change on all opposing sync pairs.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": "2",
		"y": "-4",
		"name": "Ruthless 9",
		"description": "Lowers one of the target’s following stats by two stat ranks at random when the user’s attack move is successful against a flinching, confused, or trapped opponent: Attack, Defense, Sp. Atk, Sp. Def, Speed, accuracy, or evasiveness.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": "-2",
		"y": "1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 17,
		"x": "-3",
		"y": "2",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 18,
		"x": "-2",
		"y": "2",
		"name": "Thermal Inferno: Power +2",
		"description": "Thermal Inferno: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 19,
		"x": "-1",
		"y": "2",
		"name": "Thermal Inferno: Power +2",
		"description": "Thermal Inferno: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 20,
		"x": "-3",
		"y": "3",
		"name": "Thermal Inferno: Power +2",
		"description": "Thermal Inferno: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 21,
		"x": "-2",
		"y": "3",
		"name": "Thermal Inferno: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 22,
		"x": "-1",
		"y": "3",
		"name": "Superduper Effective 3",
		"description": "Powers up moves that are super effective.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 23,
		"x": "-3",
		"y": "4",
		"name": "Sp. Atk +20",
		"description": "Sp. Atk +20",
		"energy": "7",
		"orb": "84",
		"level": "3",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 24,
		"x": "-2",
		"y": "4",
		"name": "Grand Entry 2",
		"description": "Raises the user’s Sp. Atk by two stat ranks when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": "1",
		"y": "1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 26,
		"x": "2",
		"y": "1",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 27,
		"x": "3",
		"y": "1",
		"name": "Antifreeze",
		"description": "Prevents the user from becoming frozen.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 28,
		"x": "1",
		"y": "2",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": "2",
		"y": "2",
		"name": "Thermal Inferno: Power +2",
		"description": "Thermal Inferno: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 30,
		"x": "3",
		"y": "2",
		"name": "Thermal Inferno: Power +2",
		"description": "Thermal Inferno: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 31,
		"x": "1",
		"y": "3",
		"name": "Sp. Atk +10",
		"description": "Sp. Atk +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 32,
		"x": "2",
		"y": "3",
		"name": "Cuprite Tera Blast: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": "3",
		"y": "3",
		"name": "Speeding Sun 2",
		"description": "Quickly charges the move gauge when the weather is sunny.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": "1",
		"y": "4",
		"name": "Debut: Special Boost 2",
		"description": "Increases the user’s Special Moves ↑ Next effect by two ranks the first time it enters a battle each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": "2",
		"y": "4",
		"name": "Sync Buff 0 & Move: Special Boost ↑2 9",
		"description": "Increases the user’s Special Moves ↑ Next effect by two ranks when its move is successful while its team does not have a sync buff.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": "-1",
		"y": "-1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": "-2",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 38,
		"x": "-3",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": "-1",
		"y": "-2",
		"name": "Fire Spin: Power +4",
		"description": "Fire Spin: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 40,
		"x": "-2",
		"y": "-2",
		"name": "Fire Spin: Power +4",
		"description": "Fire Spin: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 41,
		"x": "-3",
		"y": "-2",
		"name": "Fire Spin: Accuracy +15",
		"description": "Fire Spin: Accuracy +15",
		"energy": "7",
		"orb": "84",
		"level": "1",
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 42,
		"x": "-1",
		"y": "-3",
		"name": "X Defense All: MP Refresh 3",
		"description": "Has a chance (40%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": "-2",
		"y": "-3",
		"name": "Hot Enough for You?: MP Refresh 3",
		"description": "Has a chance (40%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": "-3",
		"y": "-3",
		"name": "Healing Sun 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action while the weather is sunny.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": "-1",
		"y": "-4",
		"name": "1st S-Move: Special Boost 3",
		"description": "Increases the user’s Special Moves ↑ Next effect by three ranks the first time its sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": "-2",
		"y": "-4",
		"name": "Solar Flare 9",
		"description": "Powers up the user’s sync move when the weather is sunny.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": "0",
		"y": "-3",
		"name": "Steamed Up Tera Blast: Power +25",
		"description": "Steamed Up Tera Blast: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": "0",
		"y": "3",
		"name": "Steamed Up Tera Blast: Power +25",
		"description": "Steamed Up Tera Blast: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]