export const HILBERT_KYUREM = [
	{
		"id": 1,
		"x": "1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "1",
		"y": "0",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "-1",
		"y": "1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "-1",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "0",
		"y": "-2",
		"name": "Freezing Energy Leak",
		"description": "Powers up the user’s sync move when the zone is an Ice Zone. Extends the duration of the Ice Zone when the zone turns into an Ice Zone while the user is on the field.",
		"energy": "0",
		"orb": "5",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 8,
		"x": "0",
		"y": "2",
		"name": "Head Start 2",
		"description": "Reduces the user’s sync move countdown by two the first time it enters a battle each battle.",
		"energy": "0",
		"orb": "5",
		"level": "4",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 9,
		"x": "2",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": "3",
		"y": "-2",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": "2",
		"y": "-2",
		"name": "Ice Beam: Power +4",
		"description": "Ice Beam: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 12,
		"x": "1",
		"y": "-2",
		"name": "Ice Beam: Power +4",
		"description": "Ice Beam: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 13,
		"x": "1",
		"y": "-3",
		"name": "Ice Beam: Power +4",
		"description": "Ice Beam: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 14,
		"x": "2",
		"y": "-3",
		"name": "Ice Beam: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": "3",
		"y": "-3",
		"name": "Trip Up 9",
		"description": "Lowers the target’s Speed by one stat rank when the user’s attack move against it is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": "2",
		"y": "-4",
		"name": "Burn Synergy 3",
		"description": "Powers up the user’s moves when the target is burned.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": "3",
		"y": "-4",
		"name": "Endurance",
		"description": "Applies the Enduring effect to the user if its HP is full when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": "-1",
		"y": "2",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": "-2",
		"y": "3",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": "-1",
		"y": "3",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 21,
		"x": "-3",
		"y": "4",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 22,
		"x": "-2",
		"y": "4",
		"name": "Absolute Zero Ice Burn: Power +2",
		"description": "Absolute Zero Ice Burn: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 23,
		"x": "-1",
		"y": "4",
		"name": "Absolute Zero Ice Burn: Power +2",
		"description": "Absolute Zero Ice Burn: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 24,
		"x": "-3",
		"y": "5",
		"name": "Absolute Zero Ice Burn: Power +2",
		"description": "Absolute Zero Ice Burn: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 25,
		"x": "-2",
		"y": "5",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 26,
		"x": "-1",
		"y": "5",
		"name": "Sp. Atk +10",
		"description": "Sp. Atk +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 27,
		"x": "-3",
		"y": "6",
		"name": "Brainpower",
		"description": "The more the user’s Sp. Atk is raised, the more it powers up its sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 28,
		"x": "-2",
		"y": "6",
		"name": "1st Use Status P-Move: Team Special Boost 2",
		"description": "Increases the Special Moves ↑ Next effect of all allied sync pairs by two ranks the first time the user’s Pokémon uses a status move each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": "1",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": "2",
		"y": "1",
		"name": "Unflappable",
		"description": "Prevents the user from flinching.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": "1",
		"y": "2",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 32,
		"x": "3",
		"y": "1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 33,
		"x": "2",
		"y": "2",
		"name": "Absolute Zero Ice Burn: Power +2",
		"description": "Absolute Zero Ice Burn: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 34,
		"x": "1",
		"y": "3",
		"name": "Absolute Zero Ice Burn: Power +2",
		"description": "Absolute Zero Ice Burn: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 35,
		"x": "3",
		"y": "2",
		"name": "Absolute Zero Ice Burn: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": "2",
		"y": "3",
		"name": "Speed +10",
		"description": "Speed +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": "1",
		"y": "4",
		"name": "Noble Roar: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": "3",
		"y": "3",
		"name": "Noble Roar: Move on Opp: Sp. Atk ↓2 9",
		"description": "Lowers the target’s Sp. Atk by two stat ranks when the user’s move targeting that opponent is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 39,
		"x": "2",
		"y": "4",
		"name": "Noble Roar: Move on Opp: Attack ↓2 9",
		"description": "Lowers the target’s Attack by two stat ranks when the user’s move targeting that opponent is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": "-2",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 41,
		"x": "-3",
		"y": "1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 42,
		"x": "-2",
		"y": "0",
		"name": "Ice Beam: Power +4",
		"description": "Ice Beam: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 43,
		"x": "-1",
		"y": "-1",
		"name": "Ice Beam: Power +4",
		"description": "Ice Beam: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 44,
		"x": "-3",
		"y": "0",
		"name": "Ice Zone: MG → 2",
		"description": "Quickly charges the move gauge when the zone is an Ice Zone.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": "-2",
		"y": "-1",
		"name": "Ice Zone: HP Recovery 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action when the zone is an Ice Zone.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": "-1",
		"y": "-2",
		"name": "Sp. Atk +10",
		"description": "Sp. Atk +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 47,
		"x": "-3",
		"y": "-1",
		"name": "Hit Status Cond Opp: Sync Move Boost ↑3 9",
		"description": "Increases the user’s Sync Move ↑ Next effect by three ranks when its attack move is successful against an opponent that is affected by a status condition.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 48,
		"x": "-2",
		"y": "-2",
		"name": "Trainer Sync Redemption 1",
		"description": "Restores one MP for the user’s Trainer the first time its sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 49,
		"x": "0",
		"y": "3",
		"name": "Foreseeing the Truth Ice Burn: Power +25",
		"description": "Foreseeing the Truth Ice Burn: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 50,
		"x": "0",
		"y": "-3",
		"name": "Foreseeing the Truth Ice Burn: Power +25",
		"description": "Foreseeing the Truth Ice Burn: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const HILDA_IRONLEAVES = [
	{
		"id": 1,
		"x": "1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "1",
		"y": "0",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "-1",
		"y": "1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "-1",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "0",
		"y": "-2",
		"name": "Shining Sword Psyblade: 1st Move: Restore MP 1",
		"description": "Restores one MP of the user’s move the first time that move is successful each battle.",
		"energy": "0",
		"orb": "5",
		"level": "5",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 8,
		"x": "0",
		"y": "2",
		"name": "T-Move: Physical Boost ↑2 9",
		"description": "Increases the user’s Physical Moves ↑ Next effect by two ranks when its Trainer uses a move.",
		"energy": "0",
		"orb": "5",
		"level": "4",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 9,
		"x": "1",
		"y": "-2",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": "2",
		"y": "-3",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": "3",
		"y": "-4",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 12,
		"x": "1",
		"y": "-3",
		"name": "Giga Impact: Power +2",
		"description": "Giga Impact: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 13,
		"x": "2",
		"y": "-4",
		"name": "Giga Impact: Power +2",
		"description": "Giga Impact: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 14,
		"x": "3",
		"y": "-5",
		"name": "Giga Impact: Power +2",
		"description": "Giga Impact: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 15,
		"x": "1",
		"y": "-4",
		"name": "Giga Impact: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": "2",
		"y": "-5",
		"name": "Catalyst",
		"description": "Applies the Move Gauge Acceleration effect to the allied field of play the first time the user’s sync move is used each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": "3",
		"y": "-6",
		"name": "Healthy Healing",
		"description": "Applies the Gradual Healing effect to the user when its HP is full when it enters a battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": "1",
		"y": "-5",
		"name": "Terrain: P-Moves ↑ & S-Moves ↑ 3",
		"description": "Powers up the user’s moves and sync move when a terrain applies to the field of play.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 19,
		"x": "2",
		"y": "-6",
		"name": "Hit: Physical Boost ↑1 9",
		"description": "Increases the user’s Physical Moves ↑ Next effect by one rank when its attack move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 20,
		"x": "-1",
		"y": "2",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 21,
		"x": "-2",
		"y": "3",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 22,
		"x": "-3",
		"y": "4",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 23,
		"x": "-1",
		"y": "3",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 24,
		"x": "-2",
		"y": "4",
		"name": "Shining Sword Psyblade: Power +2",
		"description": "Shining Sword Psyblade: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "psychic"
	},
	{
		"id": 25,
		"x": "-3",
		"y": "5",
		"name": "Shining Sword Psyblade: Power +2",
		"description": "Shining Sword Psyblade: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "psychic"
	},
	{
		"id": 26,
		"x": "-1",
		"y": "4",
		"name": "Shining Sword Psyblade: Power +2",
		"description": "Shining Sword Psyblade: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "psychic"
	},
	{
		"id": 27,
		"x": "-2",
		"y": "5",
		"name": "Booster Energy: Super Preparation 9",
		"description": "Applies the Supereffective ↑ Next effect to the user when its move is successful.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 28,
		"x": "-3",
		"y": "6",
		"name": "Booster Energy: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": "-1",
		"y": "5",
		"name": "Head Start 1",
		"description": "Reduces the user’s sync move countdown by one the first time it enters a battle each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 30,
		"x": "-2",
		"y": "6",
		"name": "Haymaker",
		"description": "The more the user’s Attack is raised, the more it powers up the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": "2",
		"y": "-1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 32,
		"x": "3",
		"y": "-1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 33,
		"x": "2",
		"y": "0",
		"name": "Shining Sword Psyblade: Power +2",
		"description": "Shining Sword Psyblade: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "psychic"
	},
	{
		"id": 34,
		"x": "1",
		"y": "1",
		"name": "Shining Sword Psyblade: Power +2",
		"description": "Shining Sword Psyblade: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "psychic"
	},
	{
		"id": 35,
		"x": "3",
		"y": "0",
		"name": "Shining Sword Psyblade: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": "2",
		"y": "1",
		"name": "Turbo Charge 2",
		"description": "Quickly charges the move gauge when the field is Electric Terrain.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": "1",
		"y": "2",
		"name": "Attack +10",
		"description": "Attack +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 38,
		"x": "3",
		"y": "1",
		"name": "Glory of the Burning Fight!: 1st Move: Restore MP 1",
		"description": "Restores one MP of the user’s move the first time that move is successful each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 39,
		"x": "2",
		"y": "2",
		"name": "Electric Terrain Extension 5",
		"description": "Extends the duration of Electric Terrain when the terrain turns into Electric Terrain while the user is on the field.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": "-2",
		"y": "1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 41,
		"x": "-3",
		"y": "1",
		"name": "Unflappable",
		"description": "Prevents the user from flinching.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 42,
		"x": "-2",
		"y": "0",
		"name": "Giga Impact: Power +2",
		"description": "Giga Impact: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 43,
		"x": "-1",
		"y": "-1",
		"name": "Giga Impact: Power +2",
		"description": "Giga Impact: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 44,
		"x": "-3",
		"y": "0",
		"name": "Giga Impact: Accuracy +10",
		"description": "Giga Impact: Accuracy +10",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 45,
		"x": "-2",
		"y": "-1",
		"name": "Precognition 2",
		"description": "Quickly charges the user’s move gauge when the terrain is Psychic Terrain.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": "-1",
		"y": "-2",
		"name": "Speed +10",
		"description": "Speed +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 47,
		"x": "-3",
		"y": "-1",
		"name": "1st S-Move: Psychic Terrain",
		"description": "Turns the field of play’s terrain into Psychic Terrain the first time the user’s sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 48,
		"x": "-2",
		"y": "-2",
		"name": "Psychic Terrain Extension 5",
		"description": "Extends the duration of Psychic Terrain when the terrain turns into Psychic Terrain while the user is on the field.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 49,
		"x": "0",
		"y": "-3",
		"name": "A Future of Helping One Another Psyblade: Power +25",
		"description": "A Future of Helping One Another Psyblade: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 50,
		"x": "0",
		"y": "3",
		"name": "A Future of Helping One Another Psyblade: Power +25",
		"description": "A Future of Helping One Another Psyblade: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const HILDA_MIENFOO = [
	{
		"id": 1,
		"x": "1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "1",
		"y": "0",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "-1",
		"y": "1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "-1",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "1",
		"y": "-2",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": "2",
		"y": "-3",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": "1",
		"y": "-3",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": "3",
		"y": "-4",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": "2",
		"y": "-4",
		"name": "Low Sweep: Power +4",
		"description": "Low Sweep: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 12,
		"x": "1",
		"y": "-4",
		"name": "Low Sweep: Power +4",
		"description": "Low Sweep: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 13,
		"x": "3",
		"y": "-5",
		"name": "Low Sweep: Power +4",
		"description": "Low Sweep: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 14,
		"x": "2",
		"y": "-5",
		"name": "Low Sweep: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": "1",
		"y": "-5",
		"name": "Hit: Team Attack ↑ 9",
		"description": "Raises the Attack of all allied sync pairs by one stat rank when the user’s attack move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": "3",
		"y": "-6",
		"name": "HP +20",
		"description": "HP +20",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 17,
		"x": "2",
		"y": "-6",
		"name": "Rock Smash: On a Roll 1",
		"description": "Raises the chance of lowering stat values with the additional effects of the user’s moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": "-2",
		"y": "2",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": "-3",
		"y": "3",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": "-1",
		"y": "2",
		"name": "Rock Smash: Power +4",
		"description": "Rock Smash: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 21,
		"x": "-2",
		"y": "3",
		"name": "Rock Smash: Power +4",
		"description": "Rock Smash: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 22,
		"x": "-3",
		"y": "4",
		"name": "Rock Smash: Power +4",
		"description": "Rock Smash: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 23,
		"x": "-1",
		"y": "3",
		"name": "Sync Move: Team Speed ↑ 1",
		"description": "Raises the Speed of all allied sync pairs by one stat rank after using the user’s sync move.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": "-2",
		"y": "4",
		"name": "Speed +10",
		"description": "Speed +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 25,
		"x": "-3",
		"y": "5",
		"name": "S-Move: HP Recovery (M) 1",
		"description": "Restores the user’s HP by approximately 20% of its maximum HP after using its sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": "-1",
		"y": "4",
		"name": "Team Sync Regen",
		"description": "Applies the Gradual Healing effect to all allied sync pairs after the user uses a sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": "1",
		"y": "1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": "2",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": "1",
		"y": "2",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": "3",
		"y": "1",
		"name": "Rock Smash: Power +4",
		"description": "Rock Smash: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 31,
		"x": "2",
		"y": "2",
		"name": "Rock Smash: Power +4",
		"description": "Rock Smash: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 32,
		"x": "1",
		"y": "3",
		"name": "Rock Smash: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": "3",
		"y": "2",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": "2",
		"y": "3",
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": "1",
		"y": "4",
		"name": "Ready to Go!: Critical Squad 1",
		"description": "Raises the critical-hit rate of all allied sync pairs by one stat rank when the user’s move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": "3",
		"y": "3",
		"name": "Ready to Go!: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": "2",
		"y": "4",
		"name": "Quick Tempo",
		"description": "Applies the Move Gauge Acceleration effect to the allied field of play the first time the user enters a battle each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": "-2",
		"y": "0",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": "-1",
		"y": "-1",
		"name": "Unbending",
		"description": "Defense cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": "-3",
		"y": "0",
		"name": "Low Sweep: Power +4",
		"description": "Low Sweep: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 41,
		"x": "-2",
		"y": "-1",
		"name": "Low Sweep: Power +4",
		"description": "Low Sweep: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 42,
		"x": "-1",
		"y": "-2",
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": "-3",
		"y": "-1",
		"name": "HP +20",
		"description": "HP +20",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 44,
		"x": "-2",
		"y": "-2",
		"name": "Protect: Slippery 1",
		"description": "Raises the user’s evasiveness by one stat rank when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": "-1",
		"y": "-3",
		"name": "Triage Tank 9",
		"description": "Restores the user’s HP when it is hit by an attack move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": "-3",
		"y": "-2",
		"name": "Vigilance",
		"description": "Protects the user against critical hits.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": "0",
		"y": "-3",
		"name": "Strengthened Spirit Fighting Impact: Power +25",
		"description": "Strengthened Spirit Fighting Impact: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": "0",
		"y": "3",
		"name": "Strengthened Spirit Fighting Impact: Power +25",
		"description": "Strengthened Spirit Fighting Impact: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const LANCE_CHARIZARD = [
	{
		"id": 1,
		"x": "1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "1",
		"y": "0",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "-1",
		"y": "1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "-1",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "1",
		"y": "-2",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": "2",
		"y": "-3",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": "3",
		"y": "-4",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": "1",
		"y": "-3",
		"name": "Giga Impact: Power +2",
		"description": "Giga Impact: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 11,
		"x": "2",
		"y": "-4",
		"name": "Giga Impact: Power +2",
		"description": "Giga Impact: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 12,
		"x": "3",
		"y": "-5",
		"name": "Giga Impact: Power +2",
		"description": "Giga Impact: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 13,
		"x": "1",
		"y": "-4",
		"name": "Giga Impact: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 14,
		"x": "2",
		"y": "-5",
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": "3",
		"y": "-6",
		"name": "Attack +10",
		"description": "Attack +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 16,
		"x": "1",
		"y": "-5",
		"name": "Entry: Physical Boost 3",
		"description": "Increases the user’s Physical Moves ↑ Next effect by three ranks when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": "2",
		"y": "-6",
		"name": "Defense Crush 9",
		"description": "Lowers the target’s Defense by one stat rank when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": "-1",
		"y": "2",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": "-2",
		"y": "3",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": "-3",
		"y": "4",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 21,
		"x": "-1",
		"y": "3",
		"name": "Dragon King’s Slash: Power +2",
		"description": "Dragon King’s Slash: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 22,
		"x": "-2",
		"y": "4",
		"name": "Dragon King’s Slash: Power +2",
		"description": "Dragon King’s Slash: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 23,
		"x": "-3",
		"y": "5",
		"name": "Dragon King’s Slash: Power +2",
		"description": "Dragon King’s Slash: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 24,
		"x": "-1",
		"y": "4",
		"name": "Dragon King’s Slash: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": "-2",
		"y": "5",
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": "-3",
		"y": "6",
		"name": "Protect: Fleet Feet 2",
		"description": "Raises the user’s Speed by two stat ranks when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": "-1",
		"y": "5",
		"name": "Leg Up 1",
		"description": "Reduces the user’s sync move countdown by one when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 28,
		"x": "-2",
		"y": "6",
		"name": "Entry: Sync Move Boost 5",
		"description": "Increases the user’s Sync Move ↑ Next effect by five ranks when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": "2",
		"y": "-1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": "3",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 31,
		"x": "2",
		"y": "0",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 32,
		"x": "1",
		"y": "1",
		"name": "Dragon King’s Slash: Power +2",
		"description": "Dragon King’s Slash: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 33,
		"x": "3",
		"y": "0",
		"name": "Dragon King’s Slash: Power +2",
		"description": "Dragon King’s Slash: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 34,
		"x": "2",
		"y": "1",
		"name": "Aerial Acceleration 2",
		"description": "Quickly charges the move gauge when the zone is a Flying Zone.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": "1",
		"y": "2",
		"name": "Considerable Skill!: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": "3",
		"y": "1",
		"name": "Commanded Freebie 9",
		"description": "Applies the Free Move Next effect to the user when its Trainer uses a move.",
		"energy": "8",
		"orb": "96",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": "2",
		"y": "2",
		"name": "1st T-Move: Flying Zone",
		"description": "Turns the field of play’s zone into a Flying Zone the first time the user’s Trainer uses a move each battle. (A Flying Zone powers up Flying-type attacks.)",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": "-2",
		"y": "1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": "-3",
		"y": "1",
		"name": "Headstrong",
		"description": "Attack cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": "-2",
		"y": "0",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 41,
		"x": "-1",
		"y": "-1",
		"name": "Giga Impact: Power +2",
		"description": "Giga Impact: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 42,
		"x": "-3",
		"y": "0",
		"name": "Giga Impact: Power +2",
		"description": "Giga Impact: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 43,
		"x": "-2",
		"y": "-1",
		"name": "Sync Regen",
		"description": "Applies the Gradual Healing effect to the user after using its sync move.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": "-1",
		"y": "-2",
		"name": "HP +20",
		"description": "HP +20",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 45,
		"x": "-3",
		"y": "-1",
		"name": "Haymaker",
		"description": "The more the user’s Attack is raised, the more it powers up the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": "-2",
		"y": "-2",
		"name": "Soften Up 1",
		"description": "Critical hits land more easily when the user attacks with a sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": "0",
		"y": "-3",
		"name": "Long and Difficult Journey Flying Impact: Power +25",
		"description": "Long and Difficult Journey Flying Impact: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": "0",
		"y": "3",
		"name": "Long and Difficult Journey Flying Impact: Power +25",
		"description": "Long and Difficult Journey Flying Impact: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 49,
		"x": "-4",
		"y": "2",
		"name": "Long and Difficult Journey Flying Impact: Power +30",
		"description": "Long and Difficult Journey Flying Impact: Power +30",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 50,
		"x": "-4",
		"y": "3",
		"name": "Long and Difficult Journey Flying Impact: Power +30",
		"description": "Long and Difficult Journey Flying Impact: Power +30",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 51,
		"x": "-4",
		"y": "4",
		"name": "Long and Difficult Journey Flying Impact: Power +30",
		"description": "Long and Difficult Journey Flying Impact: Power +30",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "sync",
		"icon": "sync"
	}
]

export const ARVEN_SCOVILLAIN = [
	{
		"id": 1,
		"x": "1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "1",
		"y": "0",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "-1",
		"y": "1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "-1",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "1",
		"y": "-2",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": "2",
		"y": "-3",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": "1",
		"y": "-3",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": "3",
		"y": "-4",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": "2",
		"y": "-4",
		"name": "Fire Blast: Power +4",
		"description": "Fire Blast: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 12,
		"x": "1",
		"y": "-4",
		"name": "Fire Blast: Power +4",
		"description": "Fire Blast: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 13,
		"x": "3",
		"y": "-5",
		"name": "Fire Blast: Power +4",
		"description": "Fire Blast: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 14,
		"x": "2",
		"y": "-5",
		"name": "Sync Regen",
		"description": "Applies the Gradual Healing effect to the user after using its sync move.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": "1",
		"y": "-5",
		"name": "Scorching Sync 9",
		"description": "Powers up the user’s sync move when the target is burned.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": "3",
		"y": "-6",
		"name": "Fire Blast: Accuracy +10",
		"description": "Fire Blast: Accuracy +10",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 17,
		"x": "2",
		"y": "-6",
		"name": "Fire Blast: Hostile Environment 9",
		"description": "Raises the chance of inflicting status conditions with the additional effects of moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": "-2",
		"y": "1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": "-3",
		"y": "2",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": "-2",
		"y": "2",
		"name": "Super-Spicy Overheat: Power +4",
		"description": "Super-Spicy Overheat: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 21,
		"x": "-3",
		"y": "3",
		"name": "Super-Spicy Overheat: Power +4",
		"description": "Super-Spicy Overheat: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 22,
		"x": "-1",
		"y": "2",
		"name": "Super-Spicy Overheat: Power +4",
		"description": "Super-Spicy Overheat: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 23,
		"x": "-2",
		"y": "3",
		"name": "Grand Entry 2",
		"description": "Raises the user’s Sp. Atk by two stat ranks when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": "-3",
		"y": "4",
		"name": "Debut: Special Boost 1",
		"description": "Increases the user’s Special Moves ↑ Next effect by one rank the first time it enters a battle each battle.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": "-1",
		"y": "3",
		"name": "Sharpened Mind 3",
		"description": "Powers up the user’s moves when its Sp. Atk is raised.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": "-2",
		"y": "4",
		"name": "Staggering 4",
		"description": "Has a chance (50%) of making the target flinch when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": "2",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": "3",
		"y": "-1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": "2",
		"y": "0",
		"name": "Super-Spicy Overheat: Power +4",
		"description": "Super-Spicy Overheat: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 30,
		"x": "1",
		"y": "1",
		"name": "Super-Spicy Overheat: Power +4",
		"description": "Super-Spicy Overheat: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 31,
		"x": "3",
		"y": "0",
		"name": "Super-Spicy Overheat: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 32,
		"x": "2",
		"y": "1",
		"name": "Sp. Atk +10",
		"description": "Sp. Atk +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 33,
		"x": "1",
		"y": "2",
		"name": "Soften Up 1",
		"description": "Critical hits land more easily when the user attacks with a sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": "3",
		"y": "1",
		"name": "Catalytic Acceleration",
		"description": "Applies the Move Gauge Acceleration effect to the allied field of play after using the user’s sync move.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": "2",
		"y": "2",
		"name": "Brainpower",
		"description": "The more the user’s Sp. Atk is raised, the more it powers up its sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": "-1",
		"y": "-1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": "-2",
		"y": "-1",
		"name": "Wide Awake",
		"description": "Prevents the user from falling asleep.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": "-1",
		"y": "-2",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": "-3",
		"y": "-1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": "-2",
		"y": "-2",
		"name": "Fire Blast: Power +4",
		"description": "Fire Blast: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 41,
		"x": "-3",
		"y": "-2",
		"name": "Fire Blast: Power +4",
		"description": "Fire Blast: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 42,
		"x": "-1",
		"y": "-3",
		"name": "Fire Blast: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": "-2",
		"y": "-3",
		"name": "Lemme Show Off!: Move: Team Sync Move Boost ↑1 9",
		"description": "Increases the Sync Move ↑ Next effect of all allied sync pairs by one rank when the user’s move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": "-3",
		"y": "-3",
		"name": "Lemme Show Off!: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": "-1",
		"y": "-4",
		"name": "Solar Sync",
		"description": "Makes the weather sunny the first time the user’s sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": "-2",
		"y": "-4",
		"name": "S-Move: Team-Synced Special Boost 1–4 9",
		"description": "Increases the Special Moves ↑ Next effect of all allied sync pairs by one to four ranks at random after using the user’s sync move. (The increase is the same for all allied sync pairs.)",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": "0",
		"y": "-3",
		"name": "Real Spicy Flavor Fire Beam: Power +25",
		"description": "Real Spicy Flavor Fire Beam: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": "0",
		"y": "3",
		"name": "Real Spicy Flavor Fire Beam: Power +25",
		"description": "Real Spicy Flavor Fire Beam: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const CARMINE_PECHARUNT = [
	{
		"id": 1,
		"x": "1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "1",
		"y": "0",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "-1",
		"y": "1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "-1",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "0",
		"y": "-2",
		"name": "1st S-Move: Poison Zone & Extension 3",
		"description": "Turns the field of play’s zone into a Poison Zone the first time the user’s sync move is used each battle. (A Poison Zone powers up Poison-type attacks.) Extends the duration of the Poison Zone when the zone turns into a Poison Zone while the user is on the field.",
		"energy": "0",
		"orb": "5",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 8,
		"x": "0",
		"y": "2",
		"name": "Corrosive Malignant Chain: Staggering 9",
		"description": "Makes the target flinch when the user’s attack move against it is successful.",
		"energy": "0",
		"orb": "5",
		"level": "4",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 9,
		"x": "1",
		"y": "-2",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": "2",
		"y": "-3",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": "3",
		"y": "-4",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 12,
		"x": "1",
		"y": "-3",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 13,
		"x": "2",
		"y": "-4",
		"name": "Malignant Chain: Power +2",
		"description": "Malignant Chain: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 14,
		"x": "3",
		"y": "-5",
		"name": "Malignant Chain: Power +2",
		"description": "Malignant Chain: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 15,
		"x": "1",
		"y": "-4",
		"name": "Malignant Chain: Power +2",
		"description": "Malignant Chain: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 16,
		"x": "2",
		"y": "-5",
		"name": "Hit Poisoned Opp: HP Recovery 9",
		"description": "Restores the user’s HP when its attack move is successful against a poisoned or badly poisoned opponent.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": "3",
		"y": "-6",
		"name": "Sp. Atk +10",
		"description": "Sp. Atk +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 18,
		"x": "1",
		"y": "-5",
		"name": "Hit Confused Opp: MG ↑ 9",
		"description": "Charges the user’s move gauge by one when its attack move is successful against a confused opponent.",
		"energy": "7",
		"orb": "84",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 19,
		"x": "2",
		"y": "-6",
		"name": "Hit Poisoned Opp: MG ↑ 9",
		"description": "Charges the user’s move gauge by one when its attack move is successful against a poisoned or badly poisoned opponent.",
		"energy": "7",
		"orb": "84",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 20,
		"x": "-1",
		"y": "2",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 21,
		"x": "-2",
		"y": "3",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 22,
		"x": "-3",
		"y": "4",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 23,
		"x": "-1",
		"y": "3",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 24,
		"x": "-2",
		"y": "4",
		"name": "Corrosive Malignant Chain: Power +2",
		"description": "Corrosive Malignant Chain: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 25,
		"x": "-3",
		"y": "5",
		"name": "Corrosive Malignant Chain: Power +2",
		"description": "Corrosive Malignant Chain: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 26,
		"x": "-1",
		"y": "4",
		"name": "Super Syncer",
		"description": "Applies the Supereffective ↑ Next effect to the user the first time its sync move is used each battle.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": "-2",
		"y": "5",
		"name": "I’m Gonna Crush You!: Hit and Heal 9",
		"description": "Applies the Gradual Healing effect to the user when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 28,
		"x": "-3",
		"y": "6",
		"name": "I’m Gonna Crush You!: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": "-1",
		"y": "5",
		"name": "Fuzzy Strike 9",
		"description": "Powers up the user’s sync move when the target is confused.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 30,
		"x": "-2",
		"y": "6",
		"name": "Head Start 1",
		"description": "Reduces the user’s sync move countdown by one the first time it enters a battle each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": "2",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 32,
		"x": "3",
		"y": "-1",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 33,
		"x": "2",
		"y": "0",
		"name": "Corrosive Malignant Chain: Power +2",
		"description": "Corrosive Malignant Chain: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 34,
		"x": "1",
		"y": "1",
		"name": "Corrosive Malignant Chain: Power +2",
		"description": "Corrosive Malignant Chain: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 35,
		"x": "3",
		"y": "0",
		"name": "Corrosive Malignant Chain: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": "2",
		"y": "1",
		"name": "Corrosive Malignant Chain: Power +2",
		"description": "Corrosive Malignant Chain: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 37,
		"x": "1",
		"y": "2",
		"name": "Easy Pickings 9",
		"description": "Lowers one of the target’s following stats by one stat rank at random when the user’s attack move is successful against a confused opponent: Attack, Defense, Sp. Atk, Sp. Def, Speed, accuracy, or evasiveness.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": "3",
		"y": "1",
		"name": "Debut: Paldea C (Spec) on Field",
		"description": "Applies Paldea Circle (Special) to the allied field of play the first time the user enters a battle each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 39,
		"x": "2",
		"y": "2",
		"name": "Sync Damage Guard",
		"description": "Applies the Damage Guard Next effect to the user the first time its sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": "-2",
		"y": "1",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 41,
		"x": "-3",
		"y": "1",
		"name": "Antitoxin",
		"description": "Prevents the user from getting poisoned or badly poisoned.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 42,
		"x": "-2",
		"y": "0",
		"name": "Malignant Chain: Power +2",
		"description": "Malignant Chain: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 43,
		"x": "-1",
		"y": "-1",
		"name": "Malignant Chain: Power +2",
		"description": "Malignant Chain: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 44,
		"x": "-3",
		"y": "0",
		"name": "Malignant Chain: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": "-2",
		"y": "-1",
		"name": "Speed +10",
		"description": "Speed +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 46,
		"x": "-1",
		"y": "-2",
		"name": "Move Gauge Boost: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": "-3",
		"y": "-1",
		"name": "Hit Poisoned Opp: Special Boost ↑1 9",
		"description": "Increases the user’s Special Moves ↑ Next effect by one rank when its attack move is successful against a poisoned or badly poisoned opponent.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 48,
		"x": "-2",
		"y": "-2",
		"name": "Trainer Sync Redemption 1",
		"description": "Restores one MP for the user’s Trainer the first time its sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 49,
		"x": "0",
		"y": "-3",
		"name": "Teach ’Em Who’s Better Malignant Chain: Power +25",
		"description": "Teach ’Em Who’s Better Malignant Chain: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 50,
		"x": "0",
		"y": "3",
		"name": "Teach ’Em Who’s Better Malignant Chain: Power +25",
		"description": "Teach ’Em Who’s Better Malignant Chain: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]