export const ROSA_DEERLING = []

export const REI_BRAVIARY = [
	{
		"id": 1,
		"x": -1,
		"y": 0,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": -1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": 1,
		"y": 0,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": 1,
		"y": -1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 2,
		"y": -1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 3,
		"y": -2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 2,
		"y": -2,
		"name": "Psybeam: Power 4",
		"description": "Psybeam: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "psychic"
	},
	{
		"id": 10,
		"x": 1,
		"y": -2,
		"name": "Psybeam: Power 4",
		"description": "Psybeam: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "psychic"
	},
	{
		"id": 11,
		"x": 3,
		"y": -3,
		"name": "Psybeam: Power 4",
		"description": "Psybeam: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "psychic"
	},
	{
		"id": 12,
		"x": 2,
		"y": -3,
		"name": "Psybeam: Move Gauge Refresh 3",
		"description": "Move: Psybeam",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": 1,
		"y": -3,
		"name": "Entry: Sync Move Boost 2",
		"description": "Increases the user’s Sync Move ↑ Next effect by two ranks when it enters a battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 14,
		"x": 3,
		"y": -4,
		"name": "Grand Entry 2",
		"description": "Raises the user’s Sp. Atk by two stat ranks when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 2,
		"y": -4,
		"name": "T-Move MP 0 & Hit: Stat ↓2 9",
		"description": "Lowers one of the target’s following stats by two stat ranks at random when the user’s attack move is successful while the remaining MP for its Trainer’s moves is zero: Attack, Defense, Sp. Atk, Sp. Def, Speed, accuracy, or evasiveness.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": -2,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 17,
		"x": -3,
		"y": 2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 18,
		"x": -2,
		"y": 2,
		"name": "Gusty Mountains Esper Wing: Power 3",
		"description": "Gusty Mountains Esper Wing: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "psychic"
	},
	{
		"id": 19,
		"x": -1,
		"y": 2,
		"name": "Gusty Mountains Esper Wing: Power 3",
		"description": "Gusty Mountains Esper Wing: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "psychic"
	},
	{
		"id": 20,
		"x": -3,
		"y": 3,
		"name": "Gusty Mountains Esper Wing: Power 3",
		"description": "Gusty Mountains Esper Wing: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "psychic"
	},
	{
		"id": 21,
		"x": -2,
		"y": 3,
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 22,
		"x": -1,
		"y": 3,
		"name": "Trip Up 9",
		"description": "Lowers the target’s Speed by one stat rank when the user’s attack move against it is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 23,
		"x": -3,
		"y": 4,
		"name": "T-Move MP 1 or More & Hit: Sp. Def ↓ 9",
		"description": "Lowers the target’s Sp. Def by one stat rank when the user’s attack move against it is successful while the remaining MP for its Trainer’s moves is one or more.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -2,
		"y": 4,
		"name": "Team Speedy Entry 2",
		"description": "Raises the Speed of all allied sync pairs by two stat ranks when the user enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": 1,
		"y": 1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 26,
		"x": 2,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 27,
		"x": 3,
		"y": 1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 1,
		"y": 2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": 2,
		"y": 2,
		"name": "Gusty Mountains Esper Wing: Power 3",
		"description": "Gusty Mountains Esper Wing: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "psychic"
	},
	{
		"id": 30,
		"x": 3,
		"y": 2,
		"name": "Gusty Mountains Esper Wing: Power 3",
		"description": "Gusty Mountains Esper Wing: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "psychic"
	},
	{
		"id": 31,
		"x": 1,
		"y": 3,
		"name": "Gusty Mountains Esper Wing: Move Gauge Refresh 3",
		"description": "Move: Gusty Mountains Esper Wing",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 32,
		"x": 2,
		"y": 3,
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": 3,
		"y": 3,
		"name": "Protect: Hit and Heal 9",
		"description": "Move: Protect",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": 1,
		"y": 4,
		"name": "Inertia",
		"description": "The more the user’s Speed is raised, the more it powers up the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 2,
		"y": 4,
		"name": "Protect: Move: Team Free Move Next 9",
		"description": "Move: Protect",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": -1,
		"y": -1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": -2,
		"y": -1,
		"name": "Acuity",
		"description": "Accuracy cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": -3,
		"y": -1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -1,
		"y": -2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": -2,
		"y": -2,
		"name": "Psybeam: Power 4",
		"description": "Psybeam: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "psychic"
	},
	{
		"id": 41,
		"x": -3,
		"y": -2,
		"name": "Psybeam: Power 4",
		"description": "Psybeam: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "psychic"
	},
	{
		"id": 42,
		"x": -1,
		"y": -3,
		"name": "Psybeam: Aggravation 9",
		"description": "Move: Psybeam",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": -2,
		"y": -3,
		"name": "Sp. Atk 10",
		"description": "Sp. Atk 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 44,
		"x": -3,
		"y": -3,
		"name": "Go Faster!: T-Move: Allied Field MG → 9",
		"description": "Move: Go Faster!",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -1,
		"y": -4,
		"name": "Baffle Buff 3",
		"description": "Powers up the user’s moves when the target is confused. Powers up the user’s sync move when the target is confused.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -2,
		"y": -4,
		"name": "Hit Confused Opp: Accuracy ↓ 9",
		"description": "Lowers the target’s accuracy by one stat rank when the user’s attack move is successful against a confused opponent.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "Flying to School Psychic Beam: Power 25",
		"description": "Flying to School Psychic Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "Flying to School Psychic Beam: Power 25",
		"description": "Flying to School Psychic Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const LACEY_GRANBULL = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 0,
		"y": 2,
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 8,
		"x": 0,
		"y": 4,
		"name": "MG → On Field: Team Condition Nullification",
		"description": "Prevents all allied sync pairs from being inflicted with status conditions, flinching, becoming confused, or becoming trapped when the Move Gauge Acceleration effect applies to the allied field of play.",
		"energy": "10",
		"orb": "120",
		"level": "4",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 9,
		"x": 0,
		"y": 5,
		"name": "MG → On Field: Team S-Moves ↑ 3",
		"description": "Powers up the sync moves of all allied sync pairs when the Move Gauge Acceleration effect applies to the allied field of play.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 10,
		"x": 0,
		"y": -2,
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 11,
		"x": -1,
		"y": -3,
		"name": "1st S-Move on Opp: Stat Ranks ↓ ×2",
		"description": "If the target’s stats are lowered, the amount of decrease is doubled the first time the user’s sync move targeting the opponent is successful each battle. This effect can activate only once per battle.",
		"energy": "10",
		"orb": "120",
		"level": "4",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 12,
		"x": 1,
		"y": -4,
		"name": "S-Move: Team Special Boost ↑2 9",
		"description": "Increases the Special Moves ↑ Next effect of all allied sync pairs by two ranks after using the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": 2,
		"y": -1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 14,
		"x": 3,
		"y": -2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 15,
		"x": 2,
		"y": -2,
		"name": "Dazzling Gleam: Power 3",
		"description": "Dazzling Gleam: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 16,
		"x": 1,
		"y": -2,
		"name": "Dazzling Gleam: Power 3",
		"description": "Dazzling Gleam: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 17,
		"x": 1,
		"y": -3,
		"name": "Dazzling Gleam: Power 3",
		"description": "Dazzling Gleam: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 18,
		"x": 2,
		"y": -3,
		"name": "Dazzling Gleam: Move Gauge Refresh 3",
		"description": "Move: Dazzling Gleam",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 19,
		"x": 3,
		"y": -3,
		"name": "Sp. Atk 10",
		"description": "Sp. Atk 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": 2,
		"y": -4,
		"name": "Power Play",
		"description": "The more the target’s stats are lowered, the more it powers up the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 21,
		"x": 3,
		"y": -4,
		"name": "Catalyst",
		"description": "Applies the Move Gauge Acceleration effect to the allied field of play the first time the user’s sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 22,
		"x": -1,
		"y": 2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 23,
		"x": -2,
		"y": 3,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 24,
		"x": -1,
		"y": 3,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 25,
		"x": -3,
		"y": 4,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 26,
		"x": -2,
		"y": 4,
		"name": "Love Dazzling Gleam: Power 3",
		"description": "Love Dazzling Gleam: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 27,
		"x": -1,
		"y": 4,
		"name": "Love Dazzling Gleam: Power 3",
		"description": "Love Dazzling Gleam: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 28,
		"x": -3,
		"y": 5,
		"name": "Love Dazzling Gleam: Power 3",
		"description": "Love Dazzling Gleam: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 29,
		"x": -2,
		"y": 5,
		"name": "Speedy Entry 2",
		"description": "Raises the user’s Speed by two stat ranks when it enters a battle.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 30,
		"x": -1,
		"y": 5,
		"name": "Quick Tempo",
		"description": "Applies the Move Gauge Acceleration effect to the allied field of play the first time the user enters a battle each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": -3,
		"y": 6,
		"name": "MG → On Field: Attack Move DR 2",
		"description": "Reduces damage when the user is hit by an attack move while the Move Gauge Acceleration effect applies to the allied field of play.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 32,
		"x": -2,
		"y": 6,
		"name": "Head Start 1",
		"description": "Reduces the user’s sync move countdown by one the first time it enters a battle each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": 1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": 2,
		"y": 1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 35,
		"x": 1,
		"y": 2,
		"name": "Unflappable",
		"description": "Prevents the user from flinching.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": 3,
		"y": 1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": 2,
		"y": 2,
		"name": "Love Dazzling Gleam: Power 3",
		"description": "Love Dazzling Gleam: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 38,
		"x": 1,
		"y": 3,
		"name": "Love Dazzling Gleam: Power 3",
		"description": "Love Dazzling Gleam: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 39,
		"x": 3,
		"y": 2,
		"name": "Love Dazzling Gleam: Move Gauge Refresh 3",
		"description": "Move: Love Dazzling Gleam",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": 2,
		"y": 3,
		"name": "Potion: MP Refresh 2",
		"description": "Move: Potion",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 41,
		"x": 1,
		"y": 4,
		"name": "Potion: Master Healer 1",
		"description": "Move: Potion",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 42,
		"x": 3,
		"y": 3,
		"name": "Potion: MP Refresh 2",
		"description": "Move: Potion",
		"energy": "7",
		"orb": "84",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": 2,
		"y": 4,
		"name": "Potion: Master Healer 1",
		"description": "Move: Potion",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -2,
		"y": 1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 45,
		"x": -3,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 46,
		"x": -2,
		"y": 0,
		"name": "Dazzling Gleam: Power 3",
		"description": "Dazzling Gleam: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 47,
		"x": -1,
		"y": -1,
		"name": "Dazzling Gleam: Power 3",
		"description": "Dazzling Gleam: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 48,
		"x": -3,
		"y": 0,
		"name": "HP 20",
		"description": "HP 20",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 49,
		"x": -2,
		"y": -1,
		"name": "Share the Cuteness!: Hit and Heal 9",
		"description": "Move: Share the Cuteness!",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 50,
		"x": -1,
		"y": -2,
		"name": "Share the Cuteness!: MP Refresh 2",
		"description": "Move: Share the Cuteness!",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 51,
		"x": -3,
		"y": -1,
		"name": "Unfortuitous 9",
		"description": "Lowers one of the target’s following stats by one stat rank at random when the user’s attack move against it is successful: Attack, Defense, Sp. Atk, Sp. Def, Speed, accuracy, or evasiveness.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 52,
		"x": -2,
		"y": -2,
		"name": "Sharpened Mind 5",
		"description": "Powers up the user’s moves when its Sp. Atk is raised.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 53,
		"x": 0,
		"y": 3,
		"name": "Cuteness Is Real Strength Dazzling Gleam: Power 25",
		"description": "Cuteness Is Real Strength Dazzling Gleam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 54,
		"x": 0,
		"y": -3,
		"name": "Cuteness Is Real Strength Dazzling Gleam: Power 25",
		"description": "Cuteness Is Real Strength Dazzling Gleam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const BIANCA_CHANDELURE = [
	{
		"id": 1,
		"x": -1,
		"y": 0,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": -1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": 1,
		"y": 0,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": 1,
		"y": -1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 2,
		"y": -1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 3,
		"y": -2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 2,
		"y": -2,
		"name": "Heat Wave: Power 3",
		"description": "Heat Wave: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 10,
		"x": 1,
		"y": -2,
		"name": "Heat Wave: Power 3",
		"description": "Heat Wave: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 11,
		"x": 3,
		"y": -3,
		"name": "Heat Wave: Power 3",
		"description": "Heat Wave: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 12,
		"x": 2,
		"y": -3,
		"name": "Heat Wave: Move Gauge Refresh 3",
		"description": "Move: Heat Wave",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": 1,
		"y": -3,
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 14,
		"x": 3,
		"y": -4,
		"name": "Hit Burned Opp: Sp. Atk ↓ 9",
		"description": "Lowers the target’s Sp. Atk by one stat rank when the user’s attack move is successful against a burned opponent.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 2,
		"y": -4,
		"name": "Heat Wave: Scorching Touch 9",
		"description": "Move: Heat Wave",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": -2,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 17,
		"x": -3,
		"y": 2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 18,
		"x": -2,
		"y": 2,
		"name": "Fire Spin: Power 4",
		"description": "Fire Spin: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 19,
		"x": -1,
		"y": 2,
		"name": "Fire Spin: Power 4",
		"description": "Fire Spin: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 20,
		"x": -3,
		"y": 3,
		"name": "Fire Spin: Power 4",
		"description": "Fire Spin: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 21,
		"x": -2,
		"y": 3,
		"name": "Fire Spin: Move Gauge Refresh 3",
		"description": "Move: Fire Spin",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 22,
		"x": -1,
		"y": 3,
		"name": "HP 20",
		"description": "HP 20",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 23,
		"x": -3,
		"y": 4,
		"name": "Sharp Entry 1",
		"description": "Raises the user’s critical-hit rate by one stat rank when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -2,
		"y": 4,
		"name": "Scorching Sync 5",
		"description": "Powers up the user’s sync move when the target is burned.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": 1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 26,
		"x": 2,
		"y": 1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 27,
		"x": 3,
		"y": 1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 1,
		"y": 2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": 2,
		"y": 2,
		"name": "Fire Spin: Power 4",
		"description": "Fire Spin: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 30,
		"x": 3,
		"y": 2,
		"name": "Fire Spin: Power 4",
		"description": "Fire Spin: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 31,
		"x": 1,
		"y": 3,
		"name": "Fire Spin: Accuracy 5",
		"description": "Fire Spin: Accuracy ↑ 5",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 32,
		"x": 2,
		"y": 3,
		"name": "Dire Hit +: MP Refresh 2",
		"description": "Move: Dire Hit +",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": 3,
		"y": 3,
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": 1,
		"y": 4,
		"name": "Hit Trapped Opp: Attack ↓ 9",
		"description": "Lowers the target’s Attack by one stat rank when the user’s attack move is successful against targets that are trapped.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 2,
		"y": 4,
		"name": "Sync Freebie",
		"description": "Applies the Free Move Next effect to the user after using its sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": -1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": -2,
		"y": -1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 38,
		"x": -3,
		"y": -1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -1,
		"y": -2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": -2,
		"y": -2,
		"name": "Heat Wave: Power 3",
		"description": "Heat Wave: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 41,
		"x": -3,
		"y": -2,
		"name": "Heat Wave: Power 3",
		"description": "Heat Wave: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 42,
		"x": -1,
		"y": -3,
		"name": "Trip Up 4",
		"description": "Has a chance (50%) of lowering the target’s Speed by one stat rank when the user’s attack move against it is successful.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": -2,
		"y": -3,
		"name": "Heat Wave: Accuracy 5",
		"description": "Heat Wave: Accuracy ↑ 5",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 44,
		"x": -3,
		"y": -3,
		"name": "Hey There!: MP Refresh 2",
		"description": "Move: Hey There!",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -1,
		"y": -4,
		"name": "Hey There!: Brain Gain 9",
		"description": "Move: Hey There!",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -2,
		"y": -4,
		"name": "Burn Synergy 3",
		"description": "Powers up the user’s moves when the target is burned.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "I’ll Show You How Fire Beam: Power 25",
		"description": "I’ll Show You How Fire Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "I’ll Show You How Fire Beam: Power 25",
		"description": "I’ll Show You How Fire Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const LACEY_ALCREMIE = [
	{
		"id": 1,
		"x": -1,
		"y": 0,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": -1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": 1,
		"y": 0,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": 1,
		"y": -1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 2,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 3,
		"y": -2,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 2,
		"y": -2,
		"name": "Disarming Voice: Power 3",
		"description": "Disarming Voice: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 10,
		"x": 1,
		"y": -2,
		"name": "Disarming Voice: Power 3",
		"description": "Disarming Voice: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 11,
		"x": 3,
		"y": -3,
		"name": "Disarming Voice: Power 3",
		"description": "Disarming Voice: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 12,
		"x": 2,
		"y": -3,
		"name": "Disarming Voice: Move Gauge Refresh 3",
		"description": "Move: Disarming Voice",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": 1,
		"y": -3,
		"name": "Trip Up 4",
		"description": "Has a chance (50%) of lowering the target’s Speed by one stat rank when the user’s attack move against it is successful.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 14,
		"x": 3,
		"y": -4,
		"name": "Sharp Entry 1",
		"description": "Raises the user’s critical-hit rate by one stat rank when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 2,
		"y": -4,
		"name": "Adrenaline 1",
		"description": "Reduces the sync move countdown by one the first time the user’s sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": -2,
		"y": 1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 17,
		"x": -3,
		"y": 2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 18,
		"x": -2,
		"y": 2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -1,
		"y": 2,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": -3,
		"y": 3,
		"name": "X Sp. Atk: MP Refresh 2",
		"description": "Move: X Sp. Atk",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 21,
		"x": -2,
		"y": 3,
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 22,
		"x": -1,
		"y": 3,
		"name": "Dragon Guard",
		"description": "Reduces damage when the user is attacked by Dragon-type moves.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 23,
		"x": -3,
		"y": 4,
		"name": "Satisfied Snicker 9",
		"description": "Lowers the target’s Sp. Atk by one stat rank when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -2,
		"y": 4,
		"name": "1st T-Move: Defense ↑ & Sp. Def ↑ 2",
		"description": "Raises the user’s Defense and Sp. Def by two stat ranks the first time its Trainer uses a move each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": 1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 26,
		"x": 2,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 27,
		"x": 3,
		"y": 1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 1,
		"y": 2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": 2,
		"y": 2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": 3,
		"y": 2,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 31,
		"x": 1,
		"y": 3,
		"name": "Light Screen: MP Refresh 2",
		"description": "Move: Light Screen",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 32,
		"x": 2,
		"y": 3,
		"name": "First Aid 1",
		"description": "Restores the user’s HP by approximately 10% of its maximum HP the first time it is in a pinch each battle.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": 3,
		"y": 3,
		"name": "HP 20",
		"description": "HP 20",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": 1,
		"y": 4,
		"name": "Use Status P-Move: Special Boost ↑1 9",
		"description": "Increases the user’s Special Moves ↑ Next effect by one rank when its Pokémon uses a status move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 2,
		"y": 4,
		"name": "Light Screen: Physical Damage Reducer 9",
		"description": "Move: Light Screen",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": -1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": -2,
		"y": -1,
		"name": "Wide Awake",
		"description": "Prevents the user from falling asleep.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": -3,
		"y": -1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -1,
		"y": -2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": -2,
		"y": -2,
		"name": "Disarming Voice: Power 3",
		"description": "Disarming Voice: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 41,
		"x": -3,
		"y": -2,
		"name": "Disarming Voice: Power 3",
		"description": "Disarming Voice: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 42,
		"x": -1,
		"y": -3,
		"name": "A Fine Idea!: MP Refresh 2",
		"description": "Move: A Fine Idea!",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": -2,
		"y": -3,
		"name": "Sp. Atk 10",
		"description": "Sp. Atk 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 44,
		"x": -3,
		"y": -3,
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -1,
		"y": -4,
		"name": "Brain Sync 5",
		"description": "Powers up the user’s sync move when its Sp. Atk is raised.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -2,
		"y": -4,
		"name": "Speed ↑: Moves ↑ 5",
		"description": "Powers up the user’s moves when its Speed is raised.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "So Many Cute Things Fairy Beam: Power 25",
		"description": "So Many Cute Things Fairy Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "So Many Cute Things Fairy Beam: Power 25",
		"description": "So Many Cute Things Fairy Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const ILIMA_GUMSHOOS = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 2,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 3,
		"y": -2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 2,
		"y": -2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": 1,
		"y": -2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": 1,
		"y": -3,
		"name": "Headstrong",
		"description": "Attack cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 12,
		"x": 2,
		"y": -3,
		"name": "On the Run 2",
		"description": "Raises the user’s evasiveness by two stat ranks the first time it is in a pinch each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": 3,
		"y": -3,
		"name": "Entry: Sync Move Boost 2",
		"description": "Increases the user’s Sync Move ↑ Next effect by two ranks when it enters a battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 14,
		"x": 2,
		"y": -4,
		"name": "Enthusiast’s Breakneck Blitz: Power 25",
		"description": "Enthusiast’s Breakneck Blitz: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 15,
		"x": 3,
		"y": -4,
		"name": "Debut: Normal Zone",
		"description": "Turns the field of play’s zone into a Normal Zone the first time the user enters a battle each battle. (A Normal Zone powers up Normal-type attacks.)",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": -1,
		"y": 2,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 17,
		"x": -2,
		"y": 3,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 18,
		"x": -1,
		"y": 3,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -3,
		"y": 4,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": -2,
		"y": 4,
		"name": "Body Slam: Power 4",
		"description": "Body Slam: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 21,
		"x": -1,
		"y": 4,
		"name": "Body Slam: Power 4",
		"description": "Body Slam: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 22,
		"x": -3,
		"y": 5,
		"name": "Body Slam: Power 4",
		"description": "Body Slam: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 23,
		"x": -2,
		"y": 5,
		"name": "Body Slam: Move Gauge Refresh 3",
		"description": "Move: Body Slam",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -1,
		"y": 5,
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": -3,
		"y": 6,
		"name": "1st S-Move: Physical Boost 1",
		"description": "Increases the user’s Physical Moves ↑ Next effect by one rank the first time its sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -2,
		"y": 6,
		"name": "Enthusiast’s Breakneck Blitz: Power 25",
		"description": "Enthusiast’s Breakneck Blitz: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 27,
		"x": 1,
		"y": 1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 2,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": 1,
		"y": 2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": 3,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 31,
		"x": 2,
		"y": 2,
		"name": "Body Slam: Power 4",
		"description": "Body Slam: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 32,
		"x": 1,
		"y": 3,
		"name": "Body Slam: Power 4",
		"description": "Body Slam: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 33,
		"x": 3,
		"y": 2,
		"name": "Body Slam: Hostile Environment 3",
		"description": "Move: Body Slam",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": 2,
		"y": 3,
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 1,
		"y": 4,
		"name": "Leer: Move Gauge Refresh 3",
		"description": "Move: Leer",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": 3,
		"y": 3,
		"name": "Static Shock 5",
		"description": "Powers up the user’s sync move when the target is paralyzed.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": 2,
		"y": 4,
		"name": "Might Afflicter 4",
		"description": "Has a chance (50%) of lowering the Attack of all opposing sync pairs by one stat rank when a status move used by the user’s Pokémon is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": -2,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -3,
		"y": 1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": -2,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 41,
		"x": -1,
		"y": -1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 42,
		"x": -3,
		"y": 0,
		"name": "Catalyst",
		"description": "Applies the Move Gauge Acceleration effect to the allied field of play the first time the user’s sync move is used each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": -2,
		"y": -1,
		"name": "Welcome!: MP Refresh 2",
		"description": "Move: Welcome!",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -1,
		"y": -2,
		"name": "Attack 10",
		"description": "Attack 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 45,
		"x": -3,
		"y": -1,
		"name": "Paralysis Synergy 9",
		"description": "Powers up the user’s moves when the target is paralyzed.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -2,
		"y": -2,
		"name": "Vigilance",
		"description": "Protects the user against critical hits.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": 3,
		"name": "Enthusiast’s Breakneck Blitz: Power 25",
		"description": "Enthusiast’s Breakneck Blitz: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": -3,
		"name": "Enthusiast’s Breakneck Blitz: Power 25",
		"description": "Enthusiast’s Breakneck Blitz: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const CYNTHIA_SPIRITOMB = [
	{
		"id": 1,
		"x": -1,
		"y": 0,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": -1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": 1,
		"y": 0,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": 1,
		"y": -1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 2,
		"y": -1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 3,
		"y": -2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 2,
		"y": -2,
		"name": "Evil Spirit Shadow Ball: Power 2",
		"description": "Evil Spirit Shadow Ball: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 10,
		"x": 1,
		"y": -2,
		"name": "Evil Spirit Shadow Ball: Power 2",
		"description": "Evil Spirit Shadow Ball: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 11,
		"x": 3,
		"y": -3,
		"name": "Evil Spirit Shadow Ball: Power 2",
		"description": "Evil Spirit Shadow Ball: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 12,
		"x": 2,
		"y": -3,
		"name": "Evil Spirit Shadow Ball: Move Gauge Refresh 3",
		"description": "Move: Evil Spirit Shadow Ball",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": 1,
		"y": -3,
		"name": "Hit Inter Opp: HP Recovery 1",
		"description": "Has a chance (20%) of restoring the user’s HP when its attack move is successful against a flinching, confused, or trapped opponent.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 14,
		"x": 3,
		"y": -4,
		"name": "Interference Sync 9",
		"description": "Powers up the user’s sync move against targets that are flinching, confused, or trapped.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 2,
		"y": -4,
		"name": "Opp Interference: Team Moves ↑ 2",
		"description": "Powers up the moves of all allied sync pairs when attacking a target that is flinching, confused, or trapped.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": -2,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 17,
		"x": -3,
		"y": 2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 18,
		"x": -2,
		"y": 2,
		"name": "Hex: Power 2",
		"description": "Hex: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 19,
		"x": -1,
		"y": 2,
		"name": "Hex: Power 2",
		"description": "Hex: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 20,
		"x": -3,
		"y": 3,
		"name": "Hex: Power 2",
		"description": "Hex: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 21,
		"x": -2,
		"y": 3,
		"name": "Hex: Move Gauge Refresh 3",
		"description": "Move: Hex",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 22,
		"x": -1,
		"y": 3,
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 23,
		"x": -3,
		"y": 4,
		"name": "Hex: Hit: B-Move MP Recovery (32) 5",
		"description": "Move: Hex",
		"energy": "12",
		"orb": "144",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -2,
		"y": 4,
		"name": "Grand Entry 2",
		"description": "Raises the user’s Sp. Atk by two stat ranks when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": 1,
		"y": 1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 26,
		"x": 2,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 27,
		"x": 3,
		"y": 1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 1,
		"y": 2,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": 2,
		"y": 2,
		"name": "Hex: Power 2",
		"description": "Hex: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 30,
		"x": 3,
		"y": 2,
		"name": "Hex: Power 2",
		"description": "Hex: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 31,
		"x": 1,
		"y": 3,
		"name": "Will-O-Wisp: Move Gauge Refresh 3",
		"description": "Move: Will-O-Wisp",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 32,
		"x": 2,
		"y": 3,
		"name": "Will-O-Wisp: Accuracy 10",
		"description": "Will-O-Wisp: Accuracy ↑ 10",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 33,
		"x": 3,
		"y": 3,
		"name": "Team Viral Hustle 9",
		"description": "Raises the Speed of all allied sync pairs by one stat rank when the user’s Pokémon uses a status move.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": 1,
		"y": 4,
		"name": "Will-O-Wisp: 1st Move Use: Team Special Boost 1",
		"description": "Move: Will-O-Wisp",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 2,
		"y": 4,
		"name": "Hit Burned Opp: Sp. Atk ↓ & Sp. Def ↓ 9",
		"description": "Lowers the target’s Sp. Atk and Sp. Def by one stat rank when the user’s attack move is successful against a burned opponent.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": -1,
		"y": -1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": -2,
		"y": -1,
		"name": "Unflappable",
		"description": "Prevents the user from flinching.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": -3,
		"y": -1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -1,
		"y": -2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": -2,
		"y": -2,
		"name": "Evil Spirit Shadow Ball: Power 2",
		"description": "Evil Spirit Shadow Ball: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 41,
		"x": -3,
		"y": -2,
		"name": "Evil Spirit Shadow Ball: Power 2",
		"description": "Evil Spirit Shadow Ball: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 42,
		"x": -1,
		"y": -3,
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": -2,
		"y": -3,
		"name": "HP 20",
		"description": "HP 20",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 44,
		"x": -3,
		"y": -3,
		"name": "Too Fun to End!: Hit and Heal 9",
		"description": "Move: Too Fun to End!",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -1,
		"y": -4,
		"name": "Sharpened Mind 3",
		"description": "Powers up the user’s moves when its Sp. Atk is raised.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -2,
		"y": -4,
		"name": "Head Start 1",
		"description": "Reduces the user’s sync move countdown by one the first time it enters a battle each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "Five Score and Eight Spirits Ghost Beam: Power 25",
		"description": "Five Score and Eight Spirits Ghost Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "Five Score and Eight Spirits Ghost Beam: Power 25",
		"description": "Five Score and Eight Spirits Ghost Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const MORTY_TYPHLOSION = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 1,
		"y": -2,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 2,
		"y": -3,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 1,
		"y": -3,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": 3,
		"y": -4,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": 2,
		"y": -4,
		"name": "Infernal Parade: Power 2",
		"description": "Infernal Parade: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 12,
		"x": 1,
		"y": -4,
		"name": "Infernal Parade: Power 2",
		"description": "Infernal Parade: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 13,
		"x": 3,
		"y": -5,
		"name": "Infernal Parade: Power 2",
		"description": "Infernal Parade: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 14,
		"x": 2,
		"y": -5,
		"name": "Infernal Parade: Move Gauge Refresh 3",
		"description": "Move: Infernal Parade",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 1,
		"y": -5,
		"name": "Debut: Johto C (Spec) on Field",
		"description": "Applies Johto Circle (Special) to the allied field of play the first time the user enters a battle each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": 3,
		"y": -6,
		"name": "Circle: HP Recovery 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action when a circle applies to the allied field of play.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": 2,
		"y": -6,
		"name": "Johto Analysis: 1st T-Move: Sync CD ↓ 1",
		"description": "Move: Johto Analysis",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": -2,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -3,
		"y": 2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": -2,
		"y": 2,
		"name": "Perilous Twilight Infernal Parade: Power 2",
		"description": "Perilous Twilight Infernal Parade: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 21,
		"x": -3,
		"y": 3,
		"name": "Perilous Twilight Infernal Parade: Power 2",
		"description": "Perilous Twilight Infernal Parade: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 22,
		"x": -1,
		"y": 2,
		"name": "Perilous Twilight Infernal Parade: Power 2",
		"description": "Perilous Twilight Infernal Parade: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 23,
		"x": -2,
		"y": 3,
		"name": "Perilous Twilight Infernal Parade: Move Gauge Refresh 3",
		"description": "Move: Perilous Twilight Infernal Parade",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -3,
		"y": 4,
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": -1,
		"y": 3,
		"name": "Johto C (Spec) Extension 3",
		"description": "Extends the duration of Johto Circle (Special) when Johto Circle (Special) is applied to the allied field of play.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -2,
		"y": 4,
		"name": "Hit Burned Opp: Attack ↓ & Sp. Atk ↓ 9",
		"description": "Lowers the target’s Attack and Sp. Atk by one stat rank when the user’s attack move is successful against a burned opponent.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": 2,
		"y": -1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 3,
		"y": -1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": 2,
		"y": 0,
		"name": "Perilous Twilight Infernal Parade: Power 2",
		"description": "Perilous Twilight Infernal Parade: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 30,
		"x": 1,
		"y": 1,
		"name": "Perilous Twilight Infernal Parade: Power 2",
		"description": "Perilous Twilight Infernal Parade: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 31,
		"x": 3,
		"y": 0,
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 32,
		"x": 2,
		"y": 1,
		"name": "Sp. Atk 10",
		"description": "Sp. Atk 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 33,
		"x": 1,
		"y": 2,
		"name": "Brain Sync 9",
		"description": "Powers up the user’s sync move when its Sp. Atk is raised.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": 3,
		"y": 1,
		"name": "Initial Pinch Special Boost 1",
		"description": "Increases the user’s Special Moves ↑ Next effect by one rank the first time it is in a pinch each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 2,
		"y": 2,
		"name": "Sync Thinker 9",
		"description": "Increases the user’s Special Moves ↑ Next effect by one rank after using its sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": -1,
		"y": -1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": -2,
		"y": -1,
		"name": "Flameproof",
		"description": "Prevents the user from getting burned.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": -1,
		"y": -2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -3,
		"y": -1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": -2,
		"y": -2,
		"name": "Infernal Parade: Power 2",
		"description": "Infernal Parade: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 41,
		"x": -3,
		"y": -2,
		"name": "Infernal Parade: Power 2",
		"description": "Infernal Parade: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 42,
		"x": -1,
		"y": -3,
		"name": "HP 20",
		"description": "HP 20",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 43,
		"x": -2,
		"y": -3,
		"name": "Lesson from the Soul!: MP Refresh 2",
		"description": "Move: Lesson from the Soul!",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -3,
		"y": -3,
		"name": "Lesson from the Soul!: Super Preparation 9",
		"description": "Move: Lesson from the Soul!",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -1,
		"y": -4,
		"name": "Staggering 3",
		"description": "Has a chance (40%) of making the target flinch when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -2,
		"y": -4,
		"name": "Head Start 1",
		"description": "Reduces the user’s sync move countdown by one the first time it enters a battle each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "Teaching Johto Myths Ghost Beam: Power 25",
		"description": "Teaching Johto Myths Ghost Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "Teaching Johto Myths Ghost Beam: Power 25",
		"description": "Teaching Johto Myths Ghost Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const MARNIE_CYCLIZAR = [
	{
		"id": 1,
		"x": -1,
		"y": 0,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": -1,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": 1,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": 1,
		"y": -1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 2,
		"y": -1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 3,
		"y": -2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 2,
		"y": -2,
		"name": "Spring Breeze Scale Shot: Power 1",
		"description": "Spring Breeze Scale Shot: Power ↑ 1",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dragon"
	},
	{
		"id": 10,
		"x": 1,
		"y": -2,
		"name": "Spring Breeze Scale Shot: Power 1",
		"description": "Spring Breeze Scale Shot: Power ↑ 1",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dragon"
	},
	{
		"id": 11,
		"x": 3,
		"y": -3,
		"name": "Spring Breeze Scale Shot: Power 1",
		"description": "Spring Breeze Scale Shot: Power ↑ 1",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "dragon"
	},
	{
		"id": 12,
		"x": 2,
		"y": -3,
		"name": "First Aid 2",
		"description": "Restores the user’s HP by approximately 20% of its maximum HP the first time it is in a pinch each battle.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": 1,
		"y": -3,
		"name": "Spring Breeze Scale Shot: Move Gauge Refresh 3",
		"description": "Move: Spring Breeze Scale Shot",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 14,
		"x": 3,
		"y": -4,
		"name": "Guaranteed Triple",
		"description": "Increases the number of times the user hits with a move that has the multistrike effect tag to three or more when that move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 2,
		"y": -4,
		"name": "Recharging Strike 2",
		"description": "Has a chance (30%) of charging the user’s move gauge by one when its attack move hits. If the move has the Multistrike effect tag, has a chance (30%) of charging the user’s move gauge by one for each hit.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": -2,
		"y": 1,
		"name": "HP 5",
		"description": "HP 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 17,
		"x": -3,
		"y": 2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 18,
		"x": -2,
		"y": 2,
		"name": "Breaking Swipe: Power 3",
		"description": "Breaking Swipe: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dragon"
	},
	{
		"id": 19,
		"x": -1,
		"y": 2,
		"name": "Breaking Swipe: Power 3",
		"description": "Breaking Swipe: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dragon"
	},
	{
		"id": 20,
		"x": -3,
		"y": 3,
		"name": "Breaking Swipe: Power 3",
		"description": "Breaking Swipe: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "dragon"
	},
	{
		"id": 21,
		"x": -2,
		"y": 3,
		"name": "Breaking Swipe: Move Gauge Refresh 3",
		"description": "Move: Breaking Swipe",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 22,
		"x": -1,
		"y": 3,
		"name": "Attack 10",
		"description": "Attack 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 23,
		"x": -3,
		"y": 4,
		"name": "S-Move: Restore “Berry” MP 1",
		"description": "Restores one MP of the user’s moves that have the Berry effect tag after using its sync move.",
		"energy": "12",
		"orb": "144",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -2,
		"y": 4,
		"name": "Breaking Swipe: Hit: Stat ↓2 9",
		"description": "Move: Breaking Swipe",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": 1,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 26,
		"x": 2,
		"y": 1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 27,
		"x": 3,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 1,
		"y": 2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": 2,
		"y": 2,
		"name": "Breaking Swipe: Power 3",
		"description": "Breaking Swipe: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dragon"
	},
	{
		"id": 30,
		"x": 3,
		"y": 2,
		"name": "Breaking Swipe: Power 3",
		"description": "Breaking Swipe: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dragon"
	},
	{
		"id": 31,
		"x": 1,
		"y": 3,
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 32,
		"x": 2,
		"y": 3,
		"name": "Healthy Healing",
		"description": "Applies the Gradual Healing effect to the user when its HP is full when it enters a battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": 3,
		"y": 3,
		"name": "HP 20",
		"description": "HP 20",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": 1,
		"y": 4,
		"name": "Speedster’s Sync 9",
		"description": "Powers up the user’s sync move when its Speed is raised.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 2,
		"y": 4,
		"name": "Unfortunate Strike 3",
		"description": "Has a chance (40%) of lowering one of the target’s following stats by one stat rank at random when the user’s attack move against it hits: Attack, Defense, Sp. Atk, Sp. Def, Speed, accuracy, or evasiveness. If the move has the multistrike effect tag, has a chance (40%) of lowering one of the target’s following stats by one stat rank at random for each hit: Attack, Defense, Sp. Atk, Sp. Def, Speed, accuracy, or evasiveness.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": -1,
		"y": -1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": -2,
		"y": -1,
		"name": "Headstrong",
		"description": "Attack cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": -3,
		"y": -1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -1,
		"y": -2,
		"name": "Spring Breeze Scale Shot: Power 1",
		"description": "Spring Breeze Scale Shot: Power ↑ 1",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dragon"
	},
	{
		"id": 40,
		"x": -2,
		"y": -2,
		"name": "Spring Breeze Scale Shot: Power 1",
		"description": "Spring Breeze Scale Shot: Power ↑ 1",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dragon"
	},
	{
		"id": 41,
		"x": -3,
		"y": -2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 42,
		"x": -1,
		"y": -3,
		"name": "Full Throttle!: Super Preparation 9",
		"description": "Move: Full Throttle!",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": -2,
		"y": -3,
		"name": "Full Throttle!: MP Refresh 2",
		"description": "Move: Full Throttle!",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -3,
		"y": -3,
		"name": "Fierce Entry 2",
		"description": "Raises the user’s Attack by two stat ranks when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -1,
		"y": -4,
		"name": "1st “Berry” MP 0: Team Physical Boost 1",
		"description": "Increases the Physical Moves ↑ Next effect of all allied sync pairs by one rank the first time the remaining MP for the user’s moves that have the Berry effect tag is zero each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -2,
		"y": -4,
		"name": "Furious Brawn",
		"description": "The more the user’s Attack is raised, the more it powers up the user’s moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "Zoom Around School Dragon Impact: Power 25",
		"description": "Zoom Around School Dragon Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "Requirements: Move level must be 3 or higher",
		"description": "Zoom Around School Dragon Impact: Power 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const FLORIAN_LECHONK = []