export const CLAIR_DRAMPA = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 1,
		"y": -2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 2,
		"y": -3,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 1,
		"y": -3,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": 3,
		"y": -4,
		"name": "Unbending",
		"description": "Defense cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 11,
		"x": 2,
		"y": -4,
		"name": "Twister: Power 4",
		"description": "Twister: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dragon"
	},
	{
		"id": 12,
		"x": 1,
		"y": -4,
		"name": "Twister: Power 4",
		"description": "Twister: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "dragon"
	},
	{
		"id": 13,
		"x": 3,
		"y": -5,
		"name": "Twister: Power 4",
		"description": "Twister: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dragon"
	},
	{
		"id": 14,
		"x": 2,
		"y": -5,
		"name": "Twister: Move Gauge Refresh 3",
		"description": "Move: Twister Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 1,
		"y": -5,
		"name": "Twister: Aggravation 1",
		"description": "Move: Twister Raises the chance of inflicting the flinching, confused, or trapped condition with the additional effects of moves.",
		"energy": "9",
		"orb": "108",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": 3,
		"y": -6,
		"name": "Defense 10",
		"description": "Defense 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 17,
		"x": 2,
		"y": -6,
		"name": "Team Fist Bump 3",
		"description": "Has a chance (40%) of restoring the HP of all allied sync pairs when the user’s attack move is successful.",
		"energy": "9",
		"orb": "108",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": -2,
		"y": 2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -3,
		"y": 3,
		"name": "Dragon Breath: Power 4",
		"description": "Dragon Breath: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dragon"
	},
	{
		"id": 20,
		"x": -1,
		"y": 2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 21,
		"x": -2,
		"y": 3,
		"name": "Dragon Breath: Power 4",
		"description": "Dragon Breath: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dragon"
	},
	{
		"id": 22,
		"x": -3,
		"y": 4,
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 23,
		"x": -1,
		"y": 3,
		"name": "Revenge Boost 4",
		"description": "Has a chance (50%) of charging the user’s move gauge by one when the user is hit by an attack move.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -2,
		"y": 4,
		"name": "You’re Good!: Team Hit and Heal",
		"description": "Move: You’re Good! Applies the Gradual Healing effect to all allied sync pairs when the user’s move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": -3,
		"y": 5,
		"name": "All Ramped Up 1",
		"description": "Raises the Sp. Atk of all allied sync pairs by 1 stat rank when the user’s move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -1,
		"y": 4,
		"name": "WTZ Change: Team Moves ↑ 2",
		"description": "Powers up the moves of all allied sync pairs when weather conditions, a terrain, or a zone are in effect.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": 1,
		"y": 1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 2,
		"y": 1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": 1,
		"y": 2,
		"name": "Dragon Breath: Power 4",
		"description": "Dragon Breath: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dragon"
	},
	{
		"id": 30,
		"x": 3,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 31,
		"x": 2,
		"y": 2,
		"name": "Dragon Breath: Power 4",
		"description": "Dragon Breath: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dragon"
	},
	{
		"id": 32,
		"x": 1,
		"y": 3,
		"name": "Dragon Breath: Hostile Environment 1",
		"description": "Move: Dragon Breath Raises the chance of inflicting status conditions with the additional effects of moves.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": 3,
		"y": 2,
		"name": "Dragon Breath: Power 4",
		"description": "Dragon Breath: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dragon"
	},
	{
		"id": 34,
		"x": 2,
		"y": 3,
		"name": "Dragon Breath: Move Gauge Refresh 3",
		"description": "Move: Dragon Breath Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 1,
		"y": 4,
		"name": "Hit Paralyzed Opp: HP Recovery 9",
		"description": "Restores the user’s HP when its attack move is successful against a paralyzed opponent.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": 3,
		"y": 3,
		"name": "Sp. Def 10",
		"description": "Sp. Def 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": 2,
		"y": 4,
		"name": "Half HP: Restore MP Once 9",
		"description": "Restores 1 MP for the user’s moves when its HP drops to half or below. This effect can activate only once per battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": -2,
		"y": 0,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": -3,
		"y": 0,
		"name": "Twister: Power 4",
		"description": "Twister: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dragon"
	},
	{
		"id": 41,
		"x": -2,
		"y": -1,
		"name": "Twister: Power 4",
		"description": "Twister: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dragon"
	},
	{
		"id": 42,
		"x": -1,
		"y": -2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 43,
		"x": -3,
		"y": -1,
		"name": "Grass Guard",
		"description": "Reduces damage when the user is attacked by Grass-type moves.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -2,
		"y": -2,
		"name": "Panic Button",
		"description": "Applies the Move Gauge Acceleration effect to the allied field of play the first time the user is in a pinch each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -1,
		"y": -3,
		"name": "First Aid 4",
		"description": "Restores the user’s HP by approximately 40% of its maximum HP the first time it is in a pinch each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -3,
		"y": -2,
		"name": "Berserk Bunch 1",
		"description": "Raises the Attack of all allied sync pairs by 1 stat rank when the user’s move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "New Year’s Dance Dragon Beam: Power 25",
		"description": "New Year’s Dance Dragon Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "New Year’s Dance Dragon Beam: Power 25",
		"description": "New Year’s Dance Dragon Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const WALLACE_BLACEPHALON = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 2,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 3,
		"y": -2,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 2,
		"y": -2,
		"name": "Strange Flames Mind Blown: Move Gauge Refresh 2",
		"description": "Move: Strange Flames Mind Blown Has a chance (30%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "6",
		"orb": "72",
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 10,
		"x": 1,
		"y": -2,
		"name": "Strange Flames Mind Blown: Power 2",
		"description": "Strange Flames Mind Blown: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 11,
		"x": 1,
		"y": -3,
		"name": "Gobsmack 4",
		"description": "Has a chance (50%) of leaving the target confused when the user’s attack move against it is successful.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 12,
		"x": 2,
		"y": -3,
		"name": "Strange Flames Mind Blown: Move Gauge Refresh 5",
		"description": "Move: Strange Flames Mind Blown Has a chance (60%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": 3,
		"y": -3,
		"name": "Strange Flames Mind Blown: Power 2",
		"description": "Strange Flames Mind Blown: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 14,
		"x": 2,
		"y": -4,
		"name": "Brainpower",
		"description": "The more the user’s Sp. Atk is raised, the more it powers up the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 3,
		"y": -4,
		"name": "Soften Up 1",
		"description": "Critical hits land more easily when the user attacks with a sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": -1,
		"y": 2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 17,
		"x": -2,
		"y": 3,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 18,
		"x": -1,
		"y": 3,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -3,
		"y": 4,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": -2,
		"y": 4,
		"name": "Shadow Ball: Power 3",
		"description": "Shadow Ball: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 21,
		"x": -1,
		"y": 4,
		"name": "Shadow Ball: Power 3",
		"description": "Shadow Ball: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 22,
		"x": -3,
		"y": 5,
		"name": "Shadow Ball: Power 3",
		"description": "Shadow Ball: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 23,
		"x": -2,
		"y": 5,
		"name": "Sp. Atk 10",
		"description": "Sp. Atk 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 24,
		"x": -1,
		"y": 5,
		"name": "It’s Showtime!: MP Refresh 2",
		"description": "Move: It’s Showtime! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": -3,
		"y": 6,
		"name": "Hoenn Analysis: MP Refresh 2",
		"description": "Move: Hoenn Analysis Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -2,
		"y": 6,
		"name": "It’s Showtime!: Ramp Up 2",
		"description": "Move: It’s Showtime! Raises the user’s Sp. Atk by 2 stat ranks when its move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": 1,
		"y": 1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 2,
		"y": 1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": 1,
		"y": 2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": 3,
		"y": 1,
		"name": "Dauntless",
		"description": "Sp. Atk cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": 2,
		"y": 2,
		"name": "Shadow Ball: Power 3",
		"description": "Shadow Ball: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 32,
		"x": 1,
		"y": 3,
		"name": "Shadow Ball: Power 3",
		"description": "Shadow Ball: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 33,
		"x": 3,
		"y": 2,
		"name": "Shadow Ball: On a Roll 2",
		"description": "Move: Shadow Ball Raises the chance of lowering stat values with the additional effects of the user’s moves.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": 2,
		"y": 3,
		"name": "Shadow Ball: Move Gauge Refresh 3",
		"description": "Move: Shadow Ball Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 1,
		"y": 4,
		"name": "Shadow Ball: Superduper Effective 5",
		"description": "Move: Shadow Ball Powers up moves that are super effective.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": 3,
		"y": 3,
		"name": "Shadow Ball: Brain Gain 9",
		"description": "Move: Shadow Ball Increases the user’s Special Moves ↑ Next effect by 1 rank when its move is successful.",
		"energy": "9",
		"orb": "108",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": 2,
		"y": 4,
		"name": "Max Phantasm: Power 100",
		"description": "Max Phantasm: Power ↑ 100",
		"energy": "8",
		"orb": "96",
		"level": "3",
		"color": "dynamax",
		"icon": "dynamax"
	},
	{
		"id": 38,
		"x": -2,
		"y": 1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -3,
		"y": 1,
		"name": "Strange Flames Mind Blown: Power 2",
		"description": "Strange Flames Mind Blown: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 40,
		"x": -2,
		"y": 0,
		"name": "Strange Flames Mind Blown: Power 2",
		"description": "Strange Flames Mind Blown: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 41,
		"x": -1,
		"y": -1,
		"name": "Strange Flames Mind Blown: Power 2",
		"description": "Strange Flames Mind Blown: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 42,
		"x": -3,
		"y": 0,
		"name": "Healing Sun 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action while the weather is sunny.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": -2,
		"y": -1,
		"name": "Speeding Sun 2",
		"description": "Quickly charges the move gauge when the weather is sunny.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -1,
		"y": -2,
		"name": "One with the Sun",
		"description": "Prevents the user from flinching, becoming confused, or becoming trapped when the weather is sunny.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -3,
		"y": -1,
		"name": "Charging Sun 3",
		"description": "Powers up the user’s moves when the weather is sunny.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -2,
		"y": -2,
		"name": "Max Flare: Power 100",
		"description": "Max Flare: Power ↑ 100",
		"energy": "8",
		"orb": "96",
		"level": "3",
		"color": "dynamax",
		"icon": "dynamax"
	},
	{
		"id": 47,
		"x": 0,
		"y": 3,
		"name": "Burning Elegant Fire Beam: Power 25",
		"description": "Burning Elegant Fire Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": -3,
		"name": "Burning Elegant Fire Beam: Power 25",
		"description": "Burning Elegant Fire Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const VOLKNER_RAICHU = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 1,
		"y": -2,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 2,
		"y": -3,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 1,
		"y": -3,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": 3,
		"y": -4,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": 2,
		"y": -4,
		"name": "Discharge: Power 3",
		"description": "Discharge: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 12,
		"x": 1,
		"y": -4,
		"name": "Discharge: Power 3",
		"description": "Discharge: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 13,
		"x": 3,
		"y": -5,
		"name": "Discharge: Power 3",
		"description": "Discharge: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 14,
		"x": 2,
		"y": -5,
		"name": "Discharge: Move Gauge Refresh 3",
		"description": "Move: Discharge Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 1,
		"y": -5,
		"name": "Superduper Effective 3",
		"description": "Powers up moves that are super effective.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": 3,
		"y": -6,
		"name": "Double Down 3",
		"description": "Powers up the user’s sync moves that are super effective.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": 2,
		"y": -6,
		"name": "Thrilling Battles Electric Beam: Power 25",
		"description": "Thrilling Battles Electric Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 18,
		"x": -2,
		"y": 1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -3,
		"y": 2,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": -2,
		"y": 2,
		"name": "Discharge: Power 3",
		"description": "Discharge: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 21,
		"x": -3,
		"y": 3,
		"name": "Static Cling 2",
		"description": "Has a chance (30%) of leaving an opponent that attacked the user paralyzed when the user is hit by an attack move.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 22,
		"x": -1,
		"y": 2,
		"name": "Discharge: Power 3",
		"description": "Discharge: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 23,
		"x": -2,
		"y": 3,
		"name": "Fully Charged!: MP Refresh 2",
		"description": "Move: Fully Charged! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -3,
		"y": 4,
		"name": "Fully Charged!: Slippery 1",
		"description": "Move: Fully Charged! Raises the user’s evasiveness by 1 stat rank when its move is successful.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": -1,
		"y": 3,
		"name": "Hostile Environment 1",
		"description": "Raises the chance of inflicting status conditions with the additional effects of moves.",
		"energy": "8",
		"orb": "96",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -2,
		"y": 4,
		"name": "Thrilling Battles Electric Beam: Power 25",
		"description": "Thrilling Battles Electric Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 27,
		"x": 2,
		"y": -1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 3,
		"y": -1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": 2,
		"y": 0,
		"name": "Surf: Power 3",
		"description": "Surf: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "water"
	},
	{
		"id": 30,
		"x": 1,
		"y": 1,
		"name": "Surf: Power 3",
		"description": "Surf: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "water"
	},
	{
		"id": 31,
		"x": 3,
		"y": 0,
		"name": "Surf: Power 3",
		"description": "Surf: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 32,
		"x": 2,
		"y": 1,
		"name": "Surf: Move Gauge Refresh 3",
		"description": "Move: Surf Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": 1,
		"y": 2,
		"name": "Super Freebie 2",
		"description": "Has a chance (30%) of applying the Free Move Next effect to the user when its move is super effective.",
		"energy": "9",
		"orb": "108",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": 3,
		"y": 1,
		"name": "Sp. Atk 10",
		"description": "Sp. Atk 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 35,
		"x": 2,
		"y": 2,
		"name": "Double Down 5",
		"description": "Powers up the user’s sync moves that are super effective.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": -1,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": -2,
		"y": -1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 38,
		"x": -1,
		"y": -2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -3,
		"y": -1,
		"name": "Fast Runner",
		"description": "Evasiveness cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": -2,
		"y": -2,
		"name": "Surf: Power 3",
		"description": "Surf: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "water"
	},
	{
		"id": 41,
		"x": -3,
		"y": -2,
		"name": "Speed 10",
		"description": "Speed 10",
		"energy": "4",
		"orb": "48",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 42,
		"x": -1,
		"y": -3,
		"name": "Surf: Power 3",
		"description": "Surf: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 43,
		"x": -2,
		"y": -3,
		"name": "Dire Hit +: Move Gauge Refresh 3",
		"description": "Move: Dire Hit + Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -3,
		"y": -3,
		"name": "Dire Hit +: MP Refresh 2",
		"description": "Move: Dire Hit + Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -1,
		"y": -4,
		"name": "Unfortuitous 9",
		"description": "Lowers one of the target’s following stats by one stat rank at random when the user’s attack move against it is successful: Attack, Defense, Sp. Atk, Sp. Def, Speed, accuracy, or evasiveness.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -2,
		"y": -4,
		"name": "Catalyst",
		"description": "Applies the Move Gauge Acceleration effect to the allied field of play the first time the user’s sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "Thrilling Battles Electric Beam: Power 25",
		"description": "Thrilling Battles Electric Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "Thrilling Battles Electric Beam: Power 25",
		"description": "Thrilling Battles Electric Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const KATHERINE_SLURPUFF = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 1,
		"y": -2,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 2,
		"y": -3,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 1,
		"y": -3,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": 3,
		"y": -4,
		"name": "Dauntless",
		"description": "Sp. Atk cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 11,
		"x": 2,
		"y": -4,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 12,
		"x": 1,
		"y": -4,
		"name": "Dazzling Gleam: Power 4",
		"description": "Dazzling Gleam: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 13,
		"x": 3,
		"y": -5,
		"name": "Dazzling Gleam: Power 4",
		"description": "Dazzling Gleam: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 14,
		"x": 2,
		"y": -5,
		"name": "Dazzling Gleam: Move Gauge Refresh 3",
		"description": "Move: Dazzling Gleam Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 1,
		"y": -5,
		"name": "Dazzling Gleam: Superduper Effective 9",
		"description": "Move: Dazzling Gleam Powers up moves that are super effective.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": 3,
		"y": -6,
		"name": "Sp. Atk 10",
		"description": "Sp. Atk 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 17,
		"x": 2,
		"y": -6,
		"name": "Dazzling Gleam: Gobsmack 4",
		"description": "Move: Dazzling Gleam Has a chance (50%) of leaving the target confused when the user’s attack move against it is successful.",
		"energy": "8",
		"orb": "96",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": -2,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -3,
		"y": 2,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": -2,
		"y": 2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 21,
		"x": -3,
		"y": 3,
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 22,
		"x": -1,
		"y": 2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 23,
		"x": -2,
		"y": 3,
		"name": "Sweet Scent: Move Gauge Refresh 3",
		"description": "Move: Sweet Scent Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -3,
		"y": 4,
		"name": "Double Down 3",
		"description": "Powers up the user’s sync moves that are super effective.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": -1,
		"y": 3,
		"name": "Fast-Track 9",
		"description": "Raises the user’s Speed by one stat rank when its Pokémon uses a move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -2,
		"y": 4,
		"name": "Sweet Scent: Move Gauge Refresh 9",
		"description": "Move: Sweet Scent Charges the user’s move gauge by one when its move is successful.",
		"energy": "9",
		"orb": "108",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": 2,
		"y": -1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 3,
		"y": -1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": 2,
		"y": 0,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": 1,
		"y": 1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 31,
		"x": 3,
		"y": 0,
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 32,
		"x": 2,
		"y": 1,
		"name": "Charm: Move Gauge Refresh 3",
		"description": "Move: Charm Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": 1,
		"y": 2,
		"name": "Beautiful Determination Fairy Beam: Power 25",
		"description": "Beautiful Determination Fairy Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 34,
		"x": 3,
		"y": 1,
		"name": "Dragon Guard",
		"description": "Reduces damage when the user is attacked by Dragon-type moves.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 2,
		"y": 2,
		"name": "Charm: Move Gauge Refresh 9",
		"description": "Move: Charm Charges the user’s move gauge by one when its move is successful.",
		"energy": "9",
		"orb": "108",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": -1,
		"y": -1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": -2,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 38,
		"x": -1,
		"y": -2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -3,
		"y": -1,
		"name": "Dazzling Gleam: Power 4",
		"description": "Dazzling Gleam: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 40,
		"x": -2,
		"y": -2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 41,
		"x": -3,
		"y": -2,
		"name": "Dazzling Gleam: Power 4",
		"description": "Dazzling Gleam: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 42,
		"x": -1,
		"y": -3,
		"name": "Dazzling Gleam: Power 4",
		"description": "Dazzling Gleam: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 43,
		"x": -2,
		"y": -3,
		"name": "Time to Attack!: Move Gauge Refresh 3",
		"description": "Move: Time to Attack! Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -3,
		"y": -3,
		"name": "Time to Attack!: MP Refresh 2",
		"description": "Move: Time to Attack! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -1,
		"y": -4,
		"name": "Beautiful Determination Fairy Beam: Power 25",
		"description": "Beautiful Determination Fairy Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 46,
		"x": -2,
		"y": -4,
		"name": "Sharp Entry 1",
		"description": "Raises the user’s critical-hit rate by 1 stat rank when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "Beautiful Determination Fairy Beam: Power 25",
		"description": "Beautiful Determination Fairy Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "Beautiful Determination Fairy Beam: Power 25",
		"description": "Beautiful Determination Fairy Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const IONO_BELLIBOLT = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 0,
		"y": -2,
		"name": "Unbending",
		"description": "Defense cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 8,
		"x": 0,
		"y": -4,
		"name": "Sync Damage Guard",
		"description": "Applies the Damage Guard Next effect to the user the first time its sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "4",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 9,
		"x": -2,
		"y": -3,
		"name": "Endure Again",
		"description": "Except in certain circumstances, when the user’s Enduring effect activates for the first time and the user has 1 HP remaining, applies the Enduring effect to the user again each battle.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 10,
		"x": 0,
		"y": 2,
		"name": "Stalwart",
		"description": "Sp. Def cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 11,
		"x": 0,
		"y": 4,
		"name": "Eerie Impulse: Full-Bracing P-Move 9",
		"description": "Move: Eerie Impulse Raises the user’s Defense and Sp. Def by 1 stat rank when its Pokémon uses a move.",
		"energy": "10",
		"orb": "120",
		"level": "4",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 12,
		"x": -2,
		"y": 5,
		"name": "Stupefying Strike 9",
		"description": "Lowers the target’s Sp. Def by 1 stat rank when the user’s Pokémon uses a move targeting that opponent. Lowers the target’s Sp. Def by 1 stat rank after using the user’s sync move targeting that opponent.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": 1,
		"y": -2,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 14,
		"x": 2,
		"y": -3,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 15,
		"x": 1,
		"y": -3,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 16,
		"x": 3,
		"y": -4,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 17,
		"x": 2,
		"y": -4,
		"name": "Ultra-Bright Zap Cannon: Power 2",
		"description": "Ultra-Bright Zap Cannon: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 18,
		"x": 1,
		"y": -4,
		"name": "Ultra-Bright Zap Cannon: Power 2",
		"description": "Ultra-Bright Zap Cannon: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 19,
		"x": 3,
		"y": -5,
		"name": "Ultra-Bright Zap Cannon: Power 2",
		"description": "Ultra-Bright Zap Cannon: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 20,
		"x": 2,
		"y": -5,
		"name": "Sp. Atk 10",
		"description": "Sp. Atk 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 21,
		"x": 1,
		"y": -5,
		"name": "Triage Tank 9",
		"description": "Restores the user’s HP when it is hit by an attack move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 22,
		"x": 3,
		"y": -6,
		"name": "Brainpower",
		"description": "The more the user’s Sp. Atk is raised, the more it powers up the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 23,
		"x": 2,
		"y": -6,
		"name": "Team Smart Start 1",
		"description": "Increases the Special Moves ↑ Next effect of all allied sync pairs by 1 rank when the user enters a battle.",
		"energy": "9",
		"orb": "108",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -2,
		"y": 2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 25,
		"x": -3,
		"y": 3,
		"name": "Lithe",
		"description": "Prevents the user from getting paralyzed.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -1,
		"y": 2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 27,
		"x": -2,
		"y": 3,
		"name": "Eerie Impulse: Move Gauge Refresh 3",
		"description": "Move: Eerie Impulse Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 28,
		"x": -3,
		"y": 4,
		"name": "Sp. Def 10",
		"description": "Sp. Def 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": -1,
		"y": 3,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": -2,
		"y": 4,
		"name": "Brain Brawn 2",
		"description": "Reduces damage when the user is hit by a special attack move.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": -3,
		"y": 5,
		"name": "Eerie Impulse: Charging Infliction 2",
		"description": "Move: Eerie Impulse Charges the user’s move gauge by 2 when its Pokémon uses a status move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 32,
		"x": -1,
		"y": 4,
		"name": "Eerie Impulse: Brain Gain 9",
		"description": "Move: Eerie Impulse Increases the user’s Special Moves ↑ Next effect by 1 rank when its move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": 1,
		"y": 1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": 2,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 35,
		"x": 1,
		"y": 2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 36,
		"x": 3,
		"y": 1,
		"name": "Unflappable",
		"description": "Prevents the user from flinching.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": 2,
		"y": 2,
		"name": "Ultra-Bright Zap Cannon: Move Gauge Refresh 3",
		"description": "Move: Ultra-Bright Zap Cannon Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": 1,
		"y": 3,
		"name": "Ultra-Bright Zap Cannon: Power 2",
		"description": "Ultra-Bright Zap Cannon: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 39,
		"x": 3,
		"y": 2,
		"name": "Ultra-Bright Zap Cannon: Power 2",
		"description": "Ultra-Bright Zap Cannon: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 40,
		"x": 2,
		"y": 3,
		"name": "Potion: MP Refresh 2",
		"description": "Move: Potion Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 41,
		"x": 1,
		"y": 4,
		"name": "Potion: Master Healer 1",
		"description": "Move: Potion Increases the amount of HP restored by the user’s healing moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 42,
		"x": 3,
		"y": 3,
		"name": "Potion: Master Healer 1",
		"description": "Move: Potion Increases the amount of HP restored by the user’s healing moves.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": 2,
		"y": 4,
		"name": "Potion: MP Refresh 2",
		"description": "Move: Potion Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -2,
		"y": 0,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 45,
		"x": -1,
		"y": -1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 46,
		"x": -3,
		"y": 0,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 47,
		"x": -2,
		"y": -1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 48,
		"x": -1,
		"y": -2,
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 49,
		"x": -3,
		"y": -1,
		"name": "On the Rise!: MP Refresh 2",
		"description": "Move: On the Rise! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 50,
		"x": -2,
		"y": -2,
		"name": "Sterner Stuff 2",
		"description": "Reduces damage when the user is hit by a physical attack move.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 51,
		"x": -1,
		"y": -3,
		"name": "S-Move: Team Special Boost ↑2 Once 9",
		"description": "Increases the Special Moves ↑ Next effect of all allied sync pairs by 2 ranks after using the user’s sync move. This effect can activate only once per battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 52,
		"x": -3,
		"y": -2,
		"name": "1st T-Move: Team Sp. Atk ↑ 2",
		"description": "Raises the Sp. Atk of all allied sync pairs by 2 stat ranks the first time the user’s Trainer uses a move each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 53,
		"x": 0,
		"y": -3,
		"name": "Supercharged Streamer Zap Cannon: Power 25",
		"description": "Supercharged Streamer Zap Cannon: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 54,
		"x": 0,
		"y": 3,
		"name": "Supercharged Streamer Zap Cannon: Power 25",
		"description": "Supercharged Streamer Zap Cannon: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const GRUSHA_CETITAN = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 0,
		"y": -2,
		"name": "Ice Guard",
		"description": "Reduces damage when the user is attacked by Ice-type moves.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 8,
		"x": 0,
		"y": -4,
		"name": "Let’s Cool Down!: Propulsion 9",
		"description": "Move: Let’s Cool Down! Reduces the user’s sync move countdown by one when its move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "4",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 9,
		"x": -2,
		"y": -3,
		"name": "Super Interference 2",
		"description": "Raises the chance of inflicting status conditions—as well as inflicting the flinching, confused, or trapped condition—with the additional effects of the user’s moves.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 10,
		"x": 0,
		"y": 2,
		"name": "Fire Guard",
		"description": "Reduces damage when the user is attacked by Fire-type moves.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 11,
		"x": 0,
		"y": 4,
		"name": "Ice Zone: Team Status Immunity",
		"description": "Status conditions cannot be inflicted on any allied sync pairs when the zone is an Ice Zone.",
		"energy": "10",
		"orb": "120",
		"level": "4",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 12,
		"x": -2,
		"y": 5,
		"name": "Defense Crush 9",
		"description": "Lowers the target’s Defense by one stat rank when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": 1,
		"y": -2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 14,
		"x": 2,
		"y": -3,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 15,
		"x": 1,
		"y": -3,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 16,
		"x": 3,
		"y": -4,
		"name": "Ice Fang: Power 4",
		"description": "Ice Fang: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 17,
		"x": 2,
		"y": -4,
		"name": "Ice Fang: Power 4",
		"description": "Ice Fang: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 18,
		"x": 1,
		"y": -4,
		"name": "Ice Fang: Power 4",
		"description": "Ice Fang: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 19,
		"x": 3,
		"y": -5,
		"name": "Ice Fang: Move Gauge Refresh 3",
		"description": "Move: Ice Fang Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 20,
		"x": 2,
		"y": -5,
		"name": "Ice Fang: Accuracy 5",
		"description": "Ice Fang: Accuracy ↑ 5",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 21,
		"x": 1,
		"y": -5,
		"name": "Trainer Sync Redemption 1",
		"description": "Restores 1 MP for the user’s Trainer the first time its sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 22,
		"x": 3,
		"y": -6,
		"name": "Team Mighty Sync 9",
		"description": "Increases the Physical Moves ↑ Next effect of all allied sync pairs by 1 rank after using the user’s sync move. This effect can activate only once per battle.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 23,
		"x": 2,
		"y": -6,
		"name": "Team Fierce Entry 2",
		"description": "Raises the Attack of all allied sync pairs by 2 stat ranks when the user enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -2,
		"y": 2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 25,
		"x": -3,
		"y": 3,
		"name": "Snow Shelter",
		"description": "Protects the user from damage from a hailstorm.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -1,
		"y": 2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 27,
		"x": -2,
		"y": 3,
		"name": "Absolute Zero Ice Avalanche: Power 4",
		"description": "Absolute Zero Ice Avalanche: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 28,
		"x": -3,
		"y": 4,
		"name": "Let’s Cool Down!: Pep Rally 1",
		"description": "Move: Let’s Cool Down! Raises the Speed of all allied sync pairs by 1 stat rank when the user’s move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": -1,
		"y": 3,
		"name": "Absolute Zero Ice Avalanche: Power 4",
		"description": "Absolute Zero Ice Avalanche: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 30,
		"x": -2,
		"y": 4,
		"name": "Let’s Cool Down!: Hit and Heal 9",
		"description": "Move: Let’s Cool Down! Applies the Gradual Healing effect to the user when its move is successful.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": -3,
		"y": 5,
		"name": "Vigilance",
		"description": "Protects the user against critical hits.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 32,
		"x": -1,
		"y": 4,
		"name": "Let’s Cool Down!: Move: Team Def ↑ & Sp. Def ↑ 9",
		"description": "Move: Let’s Cool Down! Raises the Defense and Sp. Def of all allied sync pairs by 1 stat rank when the user’s move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": 1,
		"y": 1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": 2,
		"y": 1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 35,
		"x": 1,
		"y": 2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 36,
		"x": 3,
		"y": 1,
		"name": "Absolute Zero Ice Avalanche: Power 4",
		"description": "Absolute Zero Ice Avalanche: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 37,
		"x": 2,
		"y": 2,
		"name": "Absolute Zero Ice Avalanche: Power 4",
		"description": "Absolute Zero Ice Avalanche: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 38,
		"x": 1,
		"y": 3,
		"name": "Absolute Zero Ice Avalanche: Power 4",
		"description": "Absolute Zero Ice Avalanche: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 39,
		"x": 3,
		"y": 2,
		"name": "HP 20",
		"description": "HP 20",
		"energy": "4",
		"orb": "48",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": 2,
		"y": 3,
		"name": "Absolute Zero Ice Avalanche: Inspire Ire",
		"description": "Move: Absolute Zero Ice Avalanche Makes opponents target the user for a short time when a move is successful.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 41,
		"x": 1,
		"y": 4,
		"name": "Use Move When Ice Zone: Team HP Recovery 9",
		"description": "Restores the HP of all allied sync pairs when the user uses a move while the zone is an Ice Zone.",
		"energy": "8",
		"orb": "96",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 42,
		"x": 3,
		"y": 3,
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": 2,
		"y": 4,
		"name": "Revenge Boost 9",
		"description": "Charges the user’s move gauge by one when it is hit by an attack move.",
		"energy": "9",
		"orb": "108",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -2,
		"y": 0,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 45,
		"x": -1,
		"y": -1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 46,
		"x": -3,
		"y": 0,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 47,
		"x": -2,
		"y": -1,
		"name": "Ice Fang: Power 4",
		"description": "Ice Fang: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 48,
		"x": -1,
		"y": -2,
		"name": "Ice Fang: Power 4",
		"description": "Ice Fang: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 49,
		"x": -3,
		"y": -1,
		"name": "Dire Hit All +: MP Refresh 2",
		"description": "Move: Dire Hit All + Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 50,
		"x": -2,
		"y": -2,
		"name": "Defense 10",
		"description": "Defense 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 51,
		"x": -1,
		"y": -3,
		"name": "1st S-Move: HP Recovery 2",
		"description": "Restores the user’s HP by approximately 40% of its maximum HP the first time its sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 52,
		"x": -3,
		"y": -2,
		"name": "Team Sharp Entry 1",
		"description": "Raises the critical-hit rate of all allied sync pairs by 1 stat rank when the user enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 53,
		"x": 0,
		"y": -3,
		"name": "Sub-zero Shredder Avalanche: Power 25",
		"description": "Sub-zero Shredder Avalanche: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 54,
		"x": 0,
		"y": 3,
		"name": "Sub-zero Shredder Avalanche: Power 25",
		"description": "Sub-zero Shredder Avalanche: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]