export const AKARI_SAMUROTT = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 0,
		"y": 2,
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 8,
		"x": 0,
		"y": 4,
		"name": "Entry Freebie",
		"description": "Applies the Free Move Next effect to the user when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "4",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 9,
		"x": 0,
		"y": 5,
		"name": "Mighty Rush 9",
		"description": "Increases the user’s Physical Moves ↑ Next effect by one rank after using its sync move.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 10,
		"x": 0,
		"y": -2,
		"name": "Dark DF on Opp & Hit: Speed ↑ 9",
		"description": "Raises the user’s Speed by 1 stat rank when its attack move is successful while Dark Damage Field is applied to the opponents’ field of play.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 11,
		"x": -1,
		"y": -3,
		"name": "Soften Up 1",
		"description": "Critical hits land more easily when the user attacks with a sync move.",
		"energy": "10",
		"orb": "120",
		"level": "4",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 12,
		"x": 1,
		"y": -4,
		"name": "Dark DF on Opp & Hit: Defense ↓ & Sp. Def ↓ 9",
		"description": "Lowers the target’s Defense and Sp. Def by 1 stat rank when the user’s attack move is successful while Dark Damage Field is applied to the opponents’ field of play.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": 2,
		"y": -1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 14,
		"x": 3,
		"y": -2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 15,
		"x": 2,
		"y": -2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 16,
		"x": 1,
		"y": -2,
		"name": "Ceaseless Edge: Power 3",
		"description": "Ceaseless Edge: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 17,
		"x": 1,
		"y": -3,
		"name": "Ceaseless Edge: Power 3",
		"description": "Ceaseless Edge: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 18,
		"x": 2,
		"y": -3,
		"name": "Ceaseless Edge: Accuracy 10",
		"description": "Ceaseless Edge: Accuracy ↑ 10",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 19,
		"x": 3,
		"y": -3,
		"name": "Umbral Acceleration 2",
		"description": "Quickly charges the move gauge when the zone is a Dark Zone.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 20,
		"x": 2,
		"y": -4,
		"name": "Dark DF Extension 3",
		"description": "Extends the duration of Dark Damage Field when Dark Damage Field applies to the opponents’ field of play.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 21,
		"x": 3,
		"y": -4,
		"name": "Dark Zone: S-Moves ↑ 5",
		"description": "Powers up the user’s sync move when the zone is a Dark Zone.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 22,
		"x": -1,
		"y": 2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 23,
		"x": -2,
		"y": 3,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 24,
		"x": -1,
		"y": 3,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 25,
		"x": -3,
		"y": 4,
		"name": "Ceaseless Edge: Power 3",
		"description": "Ceaseless Edge: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 26,
		"x": -2,
		"y": 4,
		"name": "Ceaseless Edge: Power 3",
		"description": "Ceaseless Edge: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 27,
		"x": -1,
		"y": 4,
		"name": "Ceaseless Edge: Power 3",
		"description": "Ceaseless Edge: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 28,
		"x": -3,
		"y": 5,
		"name": "Ceaseless Edge: Move Gauge Refresh 3",
		"description": "Move: Ceaseless Edge Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": -2,
		"y": 5,
		"name": "Potion: MP Refresh 2",
		"description": "Move: Potion Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 30,
		"x": -1,
		"y": 5,
		"name": "Potion: Master Healer 1",
		"description": "Move: Potion Increases the amount of HP restored by the user’s healing moves.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": -3,
		"y": 6,
		"name": "Sync Burst 1",
		"description": "Restores 1 MP for the user the first time its sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 32,
		"x": -2,
		"y": 6,
		"name": "Fierce Entry 2",
		"description": "Raises the user’s Attack by 2 stat ranks when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": 1,
		"y": 1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": 2,
		"y": 1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 35,
		"x": 1,
		"y": 2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 36,
		"x": 3,
		"y": 1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": 2,
		"y": 2,
		"name": "Top Performer Ceaseless Edge: Power 3",
		"description": "Top Performer Ceaseless Edge: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 38,
		"x": 1,
		"y": 3,
		"name": "Top Performer Ceaseless Edge: Power 3",
		"description": "Top Performer Ceaseless Edge: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 39,
		"x": 3,
		"y": 2,
		"name": "Top Performer Ceaseless Edge: Power 3",
		"description": "Top Performer Ceaseless Edge: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 40,
		"x": 2,
		"y": 3,
		"name": "Attack 10",
		"description": "Attack 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 41,
		"x": 1,
		"y": 4,
		"name": "Unflappable",
		"description": "Prevents the user from flinching.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 42,
		"x": 3,
		"y": 3,
		"name": "Dark DF on Opp & Hit: Free Move Next 4",
		"description": "Has a chance (50%) of applying the Free Move Next effect to the user when its attack move is successful while Dark Damage Field is applied to the opponent’s field of play.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": 2,
		"y": 4,
		"name": "Mutual Understanding!: MP Refresh 2",
		"description": "Move: Mutual Understanding! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -2,
		"y": 1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 45,
		"x": -3,
		"y": 1,
		"name": "Headstrong",
		"description": "Attack cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -2,
		"y": 0,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 47,
		"x": -1,
		"y": -1,
		"name": "Top Performer Ceaseless Edge: Power 3",
		"description": "Top Performer Ceaseless Edge: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 48,
		"x": -3,
		"y": 0,
		"name": "Top Performer Ceaseless Edge: Power 3",
		"description": "Top Performer Ceaseless Edge: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 49,
		"x": -2,
		"y": -1,
		"name": "Gobsmack 4",
		"description": "Has a chance (50%) of leaving the target confused when the user’s attack move against it is successful.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 50,
		"x": -1,
		"y": -2,
		"name": "Dark Zone: Attack Move DR 2",
		"description": "Reduces damage when the user is hit by an attack move while the zone is a Dark Zone.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 51,
		"x": -3,
		"y": -1,
		"name": "Dark DF on Opp: Moves ↑ 3",
		"description": "Powers up the user’s moves when Dark Damage Field is applied to the opponent’s field of play.",
		"energy": "8",
		"orb": "96",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 52,
		"x": -2,
		"y": -2,
		"name": "Haymaker",
		"description": "The more the user’s Attack is raised, the more it powers up the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 53,
		"x": 0,
		"y": 3,
		"name": "Master Crafter Ceaseless Edge: Power 25",
		"description": "Master Crafter Ceaseless Edge: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "dark"
	},
	{
		"id": 54,
		"x": 0,
		"y": -3,
		"name": "Master Crafter Ceaseless Edge: Power 25",
		"description": "Master Crafter Ceaseless Edge: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "dark"
	}
]

export const REI_DECIDUEYE = [
	{
		"id": 1,
		"x": -1,
		"y": 0,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": -1,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": 1,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": 1,
		"y": -1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 0,
		"y": -2,
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 8,
		"x": 0,
		"y": -4,
		"name": "Triple Arrows: Aggravation 1",
		"description": "Move: Triple Arrows Raises the chance of inflicting the flinching, confused, or trapped condition with the additional effects of moves.",
		"energy": "10",
		"orb": "120",
		"level": "4",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 9,
		"x": 1,
		"y": -4,
		"name": "Trip Twice 9",
		"description": "Lowers the target’s Speed by 2 stat ranks when the user’s attack move against the target is successful.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 10,
		"x": 0,
		"y": 2,
		"name": "Catalyst",
		"description": "Applies the Move Gauge Acceleration effect to the allied field of play the first time the user’s sync move is used each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 11,
		"x": 0,
		"y": 4,
		"name": "Our Hearts Are One!: Slippery Sidekicks 2",
		"description": "Move: Our Hearts Are One! Raises the evasiveness of all allied sync pairs by 2 stat ranks when the user’s move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "4",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 12,
		"x": -1,
		"y": 4,
		"name": "Mighty Command 9",
		"description": "Increases the user’s Physical Moves ↑ Next effect by one rank when its Trainer uses a move.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": 2,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 14,
		"x": 3,
		"y": -2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 15,
		"x": 2,
		"y": -2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 16,
		"x": 1,
		"y": -2,
		"name": "Triple Arrows: Power 3",
		"description": "Triple Arrows: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 17,
		"x": 3,
		"y": -3,
		"name": "Triple Arrows: Power 3",
		"description": "Triple Arrows: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 18,
		"x": 2,
		"y": -3,
		"name": "Triple Arrows: Power 3",
		"description": "Triple Arrows: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 19,
		"x": 1,
		"y": -3,
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 20,
		"x": 3,
		"y": -4,
		"name": "Triple Arrows: Move Gauge Refresh 9",
		"description": "Move: Triple Arrows Charges the user’s move gauge by one when its move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 21,
		"x": 2,
		"y": -4,
		"name": "Head Start 1",
		"description": "Reduces the user’s sync move countdown by 1 the first time it enters a battle each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 22,
		"x": -2,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 23,
		"x": -3,
		"y": 2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 24,
		"x": -2,
		"y": 2,
		"name": "Triple Arrows: Power 3",
		"description": "Triple Arrows: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 25,
		"x": -1,
		"y": 2,
		"name": "Triple Arrows: Power 3",
		"description": "Triple Arrows: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 26,
		"x": -3,
		"y": 3,
		"name": "Speed 10",
		"description": "Speed 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 27,
		"x": -2,
		"y": 3,
		"name": "Brawling Healing 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action when the zone is a Fighting Zone.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 28,
		"x": -1,
		"y": 3,
		"name": "Brawling Acceleration 2",
		"description": "Quickly charges the move gauge when the zone is a Fighting Zone.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": -3,
		"y": 4,
		"name": "Move Gauge Boost: Catalytic Cure 9",
		"description": "Move: Move Gauge Boost Restores the user’s HP by approximately 20% of its maximum HP when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 30,
		"x": -2,
		"y": 4,
		"name": "Our Hearts Are One!: Berserker 2",
		"description": "Move: Our Hearts Are One! Raises the user’s Attack by 2 stat ranks when its move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": 1,
		"y": 1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 32,
		"x": 2,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 33,
		"x": 3,
		"y": 1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": 1,
		"y": 2,
		"name": "Triple Arrows Barrage: Power 3",
		"description": "Triple Arrows Barrage: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 35,
		"x": 2,
		"y": 2,
		"name": "Triple Arrows Barrage: Power 3",
		"description": "Triple Arrows Barrage: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 36,
		"x": 3,
		"y": 2,
		"name": "Triple Arrows Barrage: Power 3",
		"description": "Triple Arrows Barrage: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 37,
		"x": 1,
		"y": 3,
		"name": "Move Gauge Boost: MP Refresh 2",
		"description": "Move: Move Gauge Boost Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": 2,
		"y": 3,
		"name": "Super Desperate",
		"description": "Applies the Supereffective ↑ Next effect to the user the first time it is in a pinch each battle.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 39,
		"x": 3,
		"y": 3,
		"name": "On a Roll 1",
		"description": "Raises the chance of lowering stat values with the additional effects of moves.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": 1,
		"y": 4,
		"name": "Space-Time Traveler Triple Arrows: Power 25",
		"description": "Space-Time Traveler Triple Arrows: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "fighting"
	},
	{
		"id": 41,
		"x": 2,
		"y": 4,
		"name": "Insult to Injury",
		"description": "The more the target’s Defense is lowered, the more it powers up the user’s moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 42,
		"x": -1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 43,
		"x": -2,
		"y": -1,
		"name": "Lithe",
		"description": "Prevents the user from getting paralyzed.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -3,
		"y": -1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 45,
		"x": -1,
		"y": -2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 46,
		"x": -2,
		"y": -2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 47,
		"x": -3,
		"y": -2,
		"name": "Triple Arrows Barrage: Power 3",
		"description": "Triple Arrows Barrage: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 48,
		"x": -1,
		"y": -3,
		"name": "Triple Arrows Barrage: Power 3",
		"description": "Triple Arrows Barrage: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 49,
		"x": -2,
		"y": -3,
		"name": "Haste",
		"description": "Speed cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 50,
		"x": -3,
		"y": -3,
		"name": "Our Hearts Are One!: MP Refresh 2",
		"description": "Move: Our Hearts Are One! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 51,
		"x": -1,
		"y": -4,
		"name": "Space-Time Traveler Triple Arrows: Power 25",
		"description": "Space-Time Traveler Triple Arrows: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "fighting"
	},
	{
		"id": 52,
		"x": -2,
		"y": -4,
		"name": "Brawn Sync 5",
		"description": "Powers up the user’s sync move when its Attack is raised.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 53,
		"x": 0,
		"y": -3,
		"name": "Space-Time Traveler Triple Arrows: Power 25",
		"description": "Space-Time Traveler Triple Arrows: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "fighting"
	},
	{
		"id": 54,
		"x": 0,
		"y": 3,
		"name": "Space-Time Traveler Triple Arrows: Power 25",
		"description": "Space-Time Traveler Triple Arrows: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "fighting"
	}
]

export const GIOVANNI_NIDORINO = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 1,
		"y": -2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 2,
		"y": -3,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 1,
		"y": -3,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": 3,
		"y": -4,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": 2,
		"y": -4,
		"name": "Poison Tail: Power 3",
		"description": "Poison Tail: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 12,
		"x": 1,
		"y": -4,
		"name": "Poison Tail: Power 3",
		"description": "Poison Tail: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 13,
		"x": 3,
		"y": -5,
		"name": "Poison Tail: Power 3",
		"description": "Poison Tail: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 14,
		"x": 2,
		"y": -5,
		"name": "Poison Tail: Move Gauge Refresh 3",
		"description": "Move: Poison Tail Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 1,
		"y": -5,
		"name": "Poison Tail: Hostile Environment 4",
		"description": "Move: Poison Tail Raises the chance of inflicting status conditions with the additional effects of moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": 3,
		"y": -6,
		"name": "Antitoxin",
		"description": "Prevents the user from getting poisoned or badly poisoned.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": 2,
		"y": -6,
		"name": "Team Sharp Entry 1",
		"description": "Raises the critical-hit rate of all allied sync pairs by 1 stat rank when the user enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": -2,
		"y": 2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -3,
		"y": 3,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": -1,
		"y": 2,
		"name": "Poison Tail: Power 3",
		"description": "Poison Tail: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 21,
		"x": -2,
		"y": 3,
		"name": "Poison Tail: Power 3",
		"description": "Poison Tail: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 22,
		"x": -3,
		"y": 4,
		"name": "HP 20",
		"description": "HP 20",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 23,
		"x": -1,
		"y": 3,
		"name": "Tighten Up 4",
		"description": "Has a chance (50%) of raising the user’s Sp. Def by one stat rank when it is hit by an attack move.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -2,
		"y": 4,
		"name": "Well, Well...: MP Refresh 2",
		"description": "Move: Well, Well... Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": -3,
		"y": 5,
		"name": "Well, Well...: Berserk Bunch 1",
		"description": "Move: Well, Well... Raises the Attack of all allied sync pairs by 1 stat rank when the user’s move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -1,
		"y": 4,
		"name": "Toxic Hit (Speed ↑) 9",
		"description": "Raises the user’s Speed by 1 stat rank when its attack move is successful against a poisoned or badly poisoned opponent.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": 1,
		"y": 1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 2,
		"y": 1,
		"name": "Unbending",
		"description": "Defense cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": 1,
		"y": 2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": 3,
		"y": 1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 31,
		"x": 2,
		"y": 2,
		"name": "Stomping Tantrum: Power 3",
		"description": "Stomping Tantrum: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 32,
		"x": 1,
		"y": 3,
		"name": "Stomping Tantrum: Power 3",
		"description": "Stomping Tantrum: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 33,
		"x": 3,
		"y": 2,
		"name": "Stomping Tantrum: Power 3",
		"description": "Stomping Tantrum: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 34,
		"x": 2,
		"y": 3,
		"name": "Stomping Tantrum: Move Gauge Refresh 3",
		"description": "Move: Stomping Tantrum Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 1,
		"y": 4,
		"name": "Potion: Master Healer 1",
		"description": "Move: Potion Increases the amount of HP restored by the user’s healing moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": 3,
		"y": 3,
		"name": "Healthy Healing",
		"description": "Applies the Gradual Healing effect to the user when its HP is full when it enters a battle.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": 2,
		"y": 4,
		"name": "Potion: MP Refresh 2",
		"description": "Move: Potion Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": -2,
		"y": 0,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -1,
		"y": -1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": -3,
		"y": 0,
		"name": "Stomping Tantrum: Power 3",
		"description": "Stomping Tantrum: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 41,
		"x": -2,
		"y": -1,
		"name": "Stomping Tantrum: Power 3",
		"description": "Stomping Tantrum: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 42,
		"x": -1,
		"y": -2,
		"name": "Defense 10",
		"description": "Defense 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 43,
		"x": -3,
		"y": -1,
		"name": "Team Sync Cure 9",
		"description": "Removes all status conditions from all allied sync pairs after using the user’s sync move.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -2,
		"y": -2,
		"name": "Unflappable",
		"description": "Prevents the user from flinching.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -1,
		"y": -3,
		"name": "Catalyst",
		"description": "Applies the Move Gauge Acceleration effect to the allied field of play the first time the user’s sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -3,
		"y": -2,
		"name": "First Aid 4",
		"description": "Restores the user’s HP by approximately 40% of its maximum HP the first time it is in a pinch each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "World-Eroding Poison Impact: Power 25",
		"description": "World-Eroding Poison Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "World-Eroding Poison Impact: Power 25",
		"description": "World-Eroding Poison Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const THORTON_MAGNEZONE = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 2,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 3,
		"y": -2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 2,
		"y": -2,
		"name": "Flash Cannon: Power 3",
		"description": "Flash Cannon: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "steel"
	},
	{
		"id": 10,
		"x": 1,
		"y": -2,
		"name": "Flash Cannon: Power 3",
		"description": "Flash Cannon: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "steel"
	},
	{
		"id": 11,
		"x": 1,
		"y": -3,
		"name": "Flash Cannon: Power 3",
		"description": "Flash Cannon: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "steel"
	},
	{
		"id": 12,
		"x": 2,
		"y": -3,
		"name": "Flash Cannon: Move Gauge Refresh 3",
		"description": "Move: Flash Cannon Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": 3,
		"y": -3,
		"name": "Metallic Acceleration 2",
		"description": "Quickly charges the move gauge when the zone is a Steel Zone.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 14,
		"x": 2,
		"y": -4,
		"name": "Power Hold 5",
		"description": "Powers up the user’s moves when the target is restrained. Powers up the user’s sync move when the target is restrained.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 3,
		"y": -4,
		"name": "Flash Cannon: Staggering 4",
		"description": "Move: Flash Cannon Has a chance (50%) of making the target flinch when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": -1,
		"y": 2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 17,
		"x": -2,
		"y": 3,
		"name": "Sand Shelter",
		"description": "Protects the user from damage from a sandstorm.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": -1,
		"y": 3,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -3,
		"y": 4,
		"name": "Discharge: Power 3",
		"description": "Discharge: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 20,
		"x": -2,
		"y": 4,
		"name": "Discharge: Power 3",
		"description": "Discharge: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 21,
		"x": -1,
		"y": 4,
		"name": "Discharge: Power 3",
		"description": "Discharge: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 22,
		"x": -3,
		"y": 5,
		"name": "Discharge: Paralysis Synergy 3",
		"description": "Move: Discharge Powers up the user’s moves when the target is paralyzed.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 23,
		"x": -2,
		"y": 5,
		"name": "Metallic Healing 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action when the zone is a Steel Zone.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -1,
		"y": 5,
		"name": "Discharge: Move Gauge Refresh 3",
		"description": "Move: Discharge Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": -3,
		"y": 6,
		"name": "Static Shock 5",
		"description": "Powers up the user’s sync move when the target is paralyzed.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -2,
		"y": 6,
		"name": "Hostile Environment 2",
		"description": "Raises the chance of inflicting status conditions with the additional effects of moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": 1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 2,
		"y": 1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": 1,
		"y": 2,
		"name": "Flash Cannon: Power 3",
		"description": "Flash Cannon: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "steel"
	},
	{
		"id": 30,
		"x": 3,
		"y": 1,
		"name": "Flash Cannon: Power 3",
		"description": "Flash Cannon: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "steel"
	},
	{
		"id": 31,
		"x": 2,
		"y": 2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 32,
		"x": 1,
		"y": 3,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 33,
		"x": 3,
		"y": 2,
		"name": "Metal Sound: Fast-Track 9",
		"description": "Move: Metal Sound Raises the user’s Speed by one stat rank when its Pokémon uses a move.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": 2,
		"y": 3,
		"name": "Metal Sound: Move Gauge Refresh 3",
		"description": "Move: Metal Sound Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 1,
		"y": 4,
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": 3,
		"y": 3,
		"name": "Metal Sound: Stupefy 9",
		"description": "Move: Metal Sound Lowers the target’s Sp. Def by one stat rank when a move targeting that opponent is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": 2,
		"y": 4,
		"name": "Satisfied Snarl 9",
		"description": "Lowers the target’s Sp. Atk by one stat rank when a move targeting that opponent is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": -2,
		"y": 1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -3,
		"y": 1,
		"name": "Antitoxin",
		"description": "Prevents the user from getting poisoned or badly poisoned.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": -2,
		"y": 0,
		"name": "Discharge: Power 3",
		"description": "Discharge: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 41,
		"x": -1,
		"y": -1,
		"name": "Discharge: Power 3",
		"description": "Discharge: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 42,
		"x": -3,
		"y": 0,
		"name": "Let’s Get Going!: MP Refresh 2",
		"description": "Move: Let’s Get Going! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": -2,
		"y": -1,
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -1,
		"y": -2,
		"name": "Superduper Effective 2",
		"description": "Powers up moves that are super effective.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -3,
		"y": -1,
		"name": "Hit Paralyzed Opp: Special Boost ↑1 4",
		"description": "Has a chance (50%) of increasing the user’s Special Moves ↑ Next effect by 1 rank when its attack move is successful against a paralyzed opponent.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -2,
		"y": -2,
		"name": "Grand Entry 2",
		"description": "Raises the user’s Sp. Atk by 2 stat ranks when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": 3,
		"name": "One Hundred Percent Steel Beam: Power 25",
		"description": "One Hundred Percent Steel Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": -3,
		"name": "One Hundred Percent Steel Beam: Power 25",
		"description": "One Hundred Percent Steel Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const NOLAND_NINJASK = [
	{
		"id": 1,
		"x": -1,
		"y": 0,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": -1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": 1,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": 1,
		"y": -1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 2,
		"y": -1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 3,
		"y": -2,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 2,
		"y": -2,
		"name": "Struggle Bug: Power 3",
		"description": "Struggle Bug: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "bug"
	},
	{
		"id": 10,
		"x": 1,
		"y": -2,
		"name": "Struggle Bug: Power 3",
		"description": "Struggle Bug: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "bug"
	},
	{
		"id": 11,
		"x": 3,
		"y": -3,
		"name": "Struggle Bug: Power 3",
		"description": "Struggle Bug: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "bug"
	},
	{
		"id": 12,
		"x": 2,
		"y": -3,
		"name": "Struggle Bug: Move Gauge Refresh 3",
		"description": "Move: Struggle Bug Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": 1,
		"y": -3,
		"name": "Superduper Effective 3",
		"description": "Powers up moves that are super effective.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 14,
		"x": 3,
		"y": -4,
		"name": "Slo-pponent Sync 5",
		"description": "Powers up the user’s sync move when the target’s Speed is lowered.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 2,
		"y": -4,
		"name": "Trip Up 9",
		"description": "Lowers the target’s Speed by 1 stat rank when the user’s attack move against the target is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": -2,
		"y": 1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 17,
		"x": -3,
		"y": 2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 18,
		"x": -2,
		"y": 2,
		"name": "Struggle Bug: Power 3",
		"description": "Struggle Bug: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "bug"
	},
	{
		"id": 19,
		"x": -1,
		"y": 2,
		"name": "Struggle Bug: Power 3",
		"description": "Struggle Bug: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "bug"
	},
	{
		"id": 20,
		"x": -3,
		"y": 3,
		"name": "Fail Forward 1",
		"description": "Charges the user’s move gauge by 1 when an opponent’s attack move targeting the user misses.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 21,
		"x": -2,
		"y": 3,
		"name": "Stop Hitting Yourself 5",
		"description": "Raises the chance that an opponent will attack themselves due to being confused.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 22,
		"x": -1,
		"y": 3,
		"name": "Curative Confusion 1",
		"description": "Restores the user’s HP when its attack move is successful against a confused opponent.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 23,
		"x": -3,
		"y": 4,
		"name": "Critical Eye 1",
		"description": "Raises the user’s critical-hit rate by 1 stat rank when its move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -2,
		"y": 4,
		"name": "Ramming Speed",
		"description": "The more the user’s Speed is raised, the more it powers up the user’s moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": 1,
		"y": 1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 26,
		"x": 2,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 27,
		"x": 3,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 1,
		"y": 2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": 2,
		"y": 2,
		"name": "Accelerating X-Scissor: Power 3",
		"description": "Accelerating X-Scissor: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "bug"
	},
	{
		"id": 30,
		"x": 3,
		"y": 2,
		"name": "Accelerating X-Scissor: Power 3",
		"description": "Accelerating X-Scissor: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "bug"
	},
	{
		"id": 31,
		"x": 1,
		"y": 3,
		"name": "Accelerating X-Scissor: Power 3",
		"description": "Accelerating X-Scissor: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "bug"
	},
	{
		"id": 32,
		"x": 2,
		"y": 3,
		"name": "Sync Regen",
		"description": "Applies the Gradual Healing effect to the user after using its sync move.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": 3,
		"y": 3,
		"name": "Attack 10",
		"description": "Attack 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": 1,
		"y": 4,
		"name": "Hit: Evasiveness ↑ 9",
		"description": "Raises the user’s evasiveness by 1 stat rank when its attack move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 2,
		"y": 4,
		"name": "Good Job!: Fleet Feet 2",
		"description": "Move: Good Job! Raises the user’s Speed by 2 stat ranks when its move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": -1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": -2,
		"y": -1,
		"name": "Headstrong",
		"description": "Attack cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": -3,
		"y": -1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -1,
		"y": -2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": -2,
		"y": -2,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 41,
		"x": -3,
		"y": -2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 42,
		"x": -1,
		"y": -3,
		"name": "Catalyst",
		"description": "Applies the Move Gauge Acceleration effect to the allied field of play the first time the user’s sync move is used each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": -2,
		"y": -3,
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -3,
		"y": -3,
		"name": "Dire Hit +: MP Refresh 2",
		"description": "Move: Dire Hit + Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -1,
		"y": -4,
		"name": "Pecking Order",
		"description": "The more the target’s Attack is lowered, the more it powers up the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -2,
		"y": -4,
		"name": "Good Job!: Berserker 2",
		"description": "Move: Good Job! Raises the user’s Attack by 2 stat ranks when its move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "Knowledge from Experience Bug Impact: Power 25",
		"description": "Knowledge from Experience Bug Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "Knowledge from Experience Bug Impact: Power 25",
		"description": "Knowledge from Experience Bug Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const ROXANNE_RUNERIGUS = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 1,
		"y": -2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 2,
		"y": -3,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 1,
		"y": -3,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": 3,
		"y": -4,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": 2,
		"y": -4,
		"name": "Sand Tomb: Power 3",
		"description": "Sand Tomb: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 12,
		"x": 1,
		"y": -4,
		"name": "Sand Tomb: Power 3",
		"description": "Sand Tomb: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 13,
		"x": 3,
		"y": -5,
		"name": "Sand Tomb: Power 3",
		"description": "Sand Tomb: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 14,
		"x": 2,
		"y": -5,
		"name": "Sand Tomb: Accuracy 10",
		"description": "Sand Tomb: Accuracy ↑ 10",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 15,
		"x": 1,
		"y": -5,
		"name": "Better Prepared 5",
		"description": "Powers up the user’s moves when none of the target’s stats are raised.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": 3,
		"y": -6,
		"name": "Sand Tomb: Move Gauge Refresh 3",
		"description": "Move: Sand Tomb Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": 2,
		"y": -6,
		"name": "Hit Trapped Opp: Attack ↓ 9",
		"description": "Lowers the target’s Attack by 1 stat rank when the user’s attack move is successful against targets that are trapped.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": -2,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -3,
		"y": 2,
		"name": "Sand Tomb: Power 3",
		"description": "Sand Tomb: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 20,
		"x": -2,
		"y": 2,
		"name": "Sand Tomb: Power 3",
		"description": "Sand Tomb: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 21,
		"x": -3,
		"y": 3,
		"name": "Sand Tomb: Accuracy 5",
		"description": "Sand Tomb: Accuracy ↑ 5",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 22,
		"x": -1,
		"y": 2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 23,
		"x": -2,
		"y": 3,
		"name": "Pokey Trap 2",
		"description": "Increases the amount of damage an opponent takes from being trapped.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -3,
		"y": 4,
		"name": "Unbending",
		"description": "Defense cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": -1,
		"y": 3,
		"name": "Sync Power Flux",
		"description": "The fuller the move gauge when the user’s sync move is selected, the more this powers up the sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -2,
		"y": 4,
		"name": "1st S-Move: No Stat ↑ on Field",
		"description": "Applies the No Stat Increases effect to the opponents’ field of play the first time the user’s sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": 2,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 3,
		"y": -1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": 2,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": 1,
		"y": 1,
		"name": "Grudgeful Bulldoze: Power 3",
		"description": "Grudgeful Bulldoze: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 31,
		"x": 3,
		"y": 0,
		"name": "Grudgeful Bulldoze: Power 3",
		"description": "Grudgeful Bulldoze: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 32,
		"x": 2,
		"y": 1,
		"name": "Grudgeful Bulldoze: Power 3",
		"description": "Grudgeful Bulldoze: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 33,
		"x": 1,
		"y": 2,
		"name": "Fierce Entry 2",
		"description": "Raises the user’s Attack by 2 stat ranks when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": 3,
		"y": 1,
		"name": "I See It All!: MP Refresh 2",
		"description": "Move: I See It All! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 2,
		"y": 2,
		"name": "Mighty Command 9",
		"description": "Increases the user’s Physical Moves ↑ Next effect by one rank when its Trainer uses a move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": -1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": -2,
		"y": -1,
		"name": "Sand Shelter",
		"description": "Protects the user from damage from a sandstorm.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": -1,
		"y": -2,
		"name": "Grudgeful Bulldoze: Power 3",
		"description": "Grudgeful Bulldoze: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 39,
		"x": -3,
		"y": -1,
		"name": "Grudgeful Bulldoze: Power 3",
		"description": "Grudgeful Bulldoze: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 40,
		"x": -2,
		"y": -2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 41,
		"x": -3,
		"y": -2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 42,
		"x": -1,
		"y": -3,
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": -2,
		"y": -3,
		"name": "X Attack All: MP Refresh 2",
		"description": "Move: X Attack All Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -3,
		"y": -3,
		"name": "Sands of Time 2",
		"description": "Quickly charges the move gauge during a sandstorm.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -1,
		"y": -4,
		"name": "Slo-pponent Sync 5",
		"description": "Powers up the user’s sync move when the target’s Speed is lowered.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -2,
		"y": -4,
		"name": "Vigilance",
		"description": "Protects the user against critical hits.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "Menacing Memories Ground Impact: Power 25",
		"description": "Menacing Memories Ground Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "Menacing Memories Ground Impact: Power 25",
		"description": "Menacing Memories Ground Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const PHOEBE_COFAGRIGUS = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 1,
		"y": -2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 2,
		"y": -3,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 1,
		"y": -3,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": 3,
		"y": -4,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": 2,
		"y": -4,
		"name": "Shadow Claw: Power 3",
		"description": "Shadow Claw: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 12,
		"x": 1,
		"y": -4,
		"name": "Shadow Claw: Power 3",
		"description": "Shadow Claw: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 13,
		"x": 3,
		"y": -5,
		"name": "Shadow Claw: Power 3",
		"description": "Shadow Claw: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 14,
		"x": 2,
		"y": -5,
		"name": "Shadow Claw: Move Gauge Refresh 3",
		"description": "Move: Shadow Claw Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 1,
		"y": -5,
		"name": "Staggering 3",
		"description": "Has a chance (40%) of making the target flinch when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": 3,
		"y": -6,
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": 2,
		"y": -6,
		"name": "Group Gloat 9",
		"description": "Raises the Attack, Sp. Atk—or both—of all allied sync pairs by one stat rank when an opponent’s attack move targeting the user misses.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": -2,
		"y": 2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -3,
		"y": 3,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": -1,
		"y": 2,
		"name": "Shadow Claw: Power 3",
		"description": "Shadow Claw: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 21,
		"x": -2,
		"y": 3,
		"name": "Shadow Claw: Power 3",
		"description": "Shadow Claw: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 22,
		"x": -3,
		"y": 4,
		"name": "Fail Forward 1",
		"description": "Charges the user’s move gauge by 1 when an opponent’s attack move targeting the user misses.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 23,
		"x": -1,
		"y": 3,
		"name": "Phantom Force: MP Refresh 2",
		"description": "Move: Phantom Force Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -2,
		"y": 4,
		"name": "Ridicure 4",
		"description": "Has a chance (50%) of restoring the user’s HP by approximately 20% of its maximum HP when an opponent’s attack move targeting the user misses.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": -3,
		"y": 5,
		"name": "Team Sharp Entry 1",
		"description": "Raises the critical-hit rate of all allied sync pairs by 1 stat rank when the user enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -1,
		"y": 4,
		"name": "Endurance",
		"description": "When the user enters battle with full HP, applies the Enduring effect to it.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": 1,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 2,
		"y": 1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": 1,
		"y": 2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": 3,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 31,
		"x": 2,
		"y": 2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 32,
		"x": 1,
		"y": 3,
		"name": "Pinch: Restore “Quick Move” MP Once 9",
		"description": "Restores 1 MP for the user’s moves that have the quick move effect tag when it is in a pinch. This effect can activate only once per battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": 3,
		"y": 2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": 2,
		"y": 3,
		"name": "Potion: Master Healer 1",
		"description": "Move: Potion Increases the amount of HP restored by the user’s healing moves.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 1,
		"y": 4,
		"name": "Potion: Master Healer 1",
		"description": "Move: Potion Increases the amount of HP restored by the user’s healing moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": 3,
		"y": 3,
		"name": "Potion: MP Refresh 2",
		"description": "Move: Potion Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": 2,
		"y": 4,
		"name": "Potion: MP Refresh 2",
		"description": "Move: Potion Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": -2,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -1,
		"y": -1,
		"name": "Antitoxin",
		"description": "Prevents the user from getting poisoned or badly poisoned.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": -3,
		"y": 0,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 41,
		"x": -2,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 42,
		"x": -1,
		"y": -2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 43,
		"x": -3,
		"y": -1,
		"name": "It’s Lively Now!: MP Refresh 2",
		"description": "Move: It’s Lively Now! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -2,
		"y": -2,
		"name": "Unflappable",
		"description": "Prevents the user from flinching.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -1,
		"y": -3,
		"name": "Status Immunity",
		"description": "Status conditions cannot be inflicted on the user.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -3,
		"y": -2,
		"name": "Adrenaline 1",
		"description": "Reduces the sync move countdown by 1 the first time the user’s sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "Glimmering Gold Ghost Impact: Power 25",
		"description": "Glimmering Gold Ghost Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "Glimmering Gold Ghost Impact: Power 25",
		"description": "Glimmering Gold Ghost Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const LENORA_WATCHOG = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 1,
		"y": -2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 2,
		"y": -3,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 1,
		"y": -3,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": 3,
		"y": -4,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": 2,
		"y": -4,
		"name": "Facade: Power 3",
		"description": "Facade: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 12,
		"x": 1,
		"y": -4,
		"name": "Facade: Power 3",
		"description": "Facade: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 13,
		"x": 3,
		"y": -5,
		"name": "Facade: Power 3",
		"description": "Facade: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 14,
		"x": 2,
		"y": -5,
		"name": "Facade: Fleet Feet 1",
		"description": "Move: Facade Raises the user’s Speed by 1 stat rank when its move is successful.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 1,
		"y": -5,
		"name": "Hit: Team Attack ↑ 9",
		"description": "Raises the Attack of all allied sync pairs by 1 stat rank when the user’s attack move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": 3,
		"y": -6,
		"name": "Facade: Move Gauge Refresh 3",
		"description": "Move: Facade Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": 2,
		"y": -6,
		"name": "Facade: Staggering 2",
		"description": "Move: Facade Has a chance (30%) of making the target flinch when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": -2,
		"y": 2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -3,
		"y": 3,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": -1,
		"y": 2,
		"name": "Facade: Power 3",
		"description": "Facade: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 21,
		"x": -2,
		"y": 3,
		"name": "Facade: Power 3",
		"description": "Facade: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 22,
		"x": -3,
		"y": 4,
		"name": "Unflappable",
		"description": "Prevents the user from flinching.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 23,
		"x": -1,
		"y": 3,
		"name": "HP 20",
		"description": "HP 20",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 24,
		"x": -2,
		"y": 4,
		"name": "Research Time!: MP Refresh 2",
		"description": "Move: Research Time! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": -3,
		"y": 5,
		"name": "Research Time!: Group Therapy",
		"description": "Move: Research Time! Removes all status conditions from all allied sync pairs when a move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -1,
		"y": 4,
		"name": "Research Time!: Master Healer 1",
		"description": "Move: Research Time! Increases the amount of HP restored by the user’s healing moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": 1,
		"y": 1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 2,
		"y": 1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": 1,
		"y": 2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": 3,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 31,
		"x": 2,
		"y": 2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 32,
		"x": 1,
		"y": 3,
		"name": "X Sp. Def All: MP Refresh 2",
		"description": "Move: X Sp. Def All Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": 3,
		"y": 2,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": 2,
		"y": 3,
		"name": "Leer: Move Gauge Refresh 3",
		"description": "Move: Leer Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 1,
		"y": 4,
		"name": "Team Sharp Entry 1",
		"description": "Raises the critical-hit rate of all allied sync pairs by 1 stat rank when the user enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": 3,
		"y": 3,
		"name": "Survivor Mentality 2",
		"description": "Reduces damage when the user is hit by a special attack move while it is in a pinch.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": 2,
		"y": 4,
		"name": "Hit: Team Sp. Atk ↑ 9",
		"description": "Raises the Sp. Atk of all allied sync pairs by 1 stat rank when the user’s attack move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": -2,
		"y": 0,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -1,
		"y": -1,
		"name": "Stalwart",
		"description": "Sp. Def cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": -3,
		"y": 0,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 41,
		"x": -2,
		"y": -1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 42,
		"x": -1,
		"y": -2,
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": -3,
		"y": -1,
		"name": "HP 20",
		"description": "HP 20",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 44,
		"x": -2,
		"y": -2,
		"name": "Sync Regen",
		"description": "Applies the Gradual Healing effect to the user after using its sync move.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -1,
		"y": -3,
		"name": "Safety Tether",
		"description": "Applies the Enduring effect to the user the first time its sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -3,
		"y": -2,
		"name": "Rejuvenate 6",
		"description": "Charges the user’s move gauge by 6 after using a sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "Museum Director Normal Impact: Power 25",
		"description": "Museum Director Normal Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "Museum Director Normal Impact: Power 25",
		"description": "Museum Director Normal Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]