export const CHEREN_TORNADUS = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 1,
		"y": -2,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 2,
		"y": -3,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 1,
		"y": -3,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": 3,
		"y": -4,
		"name": "Dauntless",
		"description": "Sp. Atk cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 11,
		"x": 2,
		"y": -4,
		"name": "Bleakwind Storm: Move Gauge Refresh 2",
		"description": "Move: Bleakwind Storm Has a chance (30%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "6",
		"orb": "72",
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 12,
		"x": 1,
		"y": -4,
		"name": "Bleakwind Storm: Power 2",
		"description": "Bleakwind Storm: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 13,
		"x": 3,
		"y": -5,
		"name": "Bleakwind Storm: Power 2",
		"description": "Bleakwind Storm: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 14,
		"x": 2,
		"y": -5,
		"name": "Bleakwind Storm: Move Gauge Refresh 4",
		"description": "Move: Bleakwind Storm Has a chance (50%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 1,
		"y": -5,
		"name": "Grand Entry 2",
		"description": "Raises the user’s Sp. Atk by two stat ranks when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": 3,
		"y": -6,
		"name": "Bleakwind Storm: On a Roll 3",
		"description": "Move: Bleakwind Storm Raises the chance of lowering stat values with the additional effects of the user’s moves.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": 2,
		"y": -6,
		"name": "Head Start 1",
		"description": "Reduces the user’s sync move countdown by one the first time it enters a battle each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": -2,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -3,
		"y": 2,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": -2,
		"y": 2,
		"name": "Fly: Power 3",
		"description": "Fly: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 21,
		"x": -3,
		"y": 3,
		"name": "Fly: Power 3",
		"description": "Fly: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 22,
		"x": -1,
		"y": 2,
		"name": "Fly: Power 3",
		"description": "Fly: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 23,
		"x": -2,
		"y": 3,
		"name": "Fly: MP Refresh 3",
		"description": "Move: Fly Has a chance (40%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -3,
		"y": 4,
		"name": "Slippery Slope 9",
		"description": "Raises the user’s evasiveness by one stat rank when an opponent’s attack move targeting the user misses.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": -1,
		"y": 3,
		"name": "Strong Start 1",
		"description": "Increases the user’s Physical Moves ↑ Next effect and Special Moves ↑ Next effect by one rank the first time the user enters a battle each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -2,
		"y": 4,
		"name": "Discombobulate 4",
		"description": "Has a chance (50%) of lowering the target’s accuracy by one stat rank when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": 2,
		"y": -1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 3,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": 2,
		"y": 0,
		"name": "Black Gale Bleakwind Storm: Power 2",
		"description": "Black Gale Bleakwind Storm: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 30,
		"x": 1,
		"y": 1,
		"name": "Black Gale Bleakwind Storm: Power 2",
		"description": "Black Gale Bleakwind Storm: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 31,
		"x": 3,
		"y": 0,
		"name": "Black Gale Bleakwind Storm: Power 2",
		"description": "Black Gale Bleakwind Storm: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 32,
		"x": 2,
		"y": 1,
		"name": "Thoughts of Glory: MP Refresh 2",
		"description": "Move: Thoughts of Glory Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": 1,
		"y": 2,
		"name": "Thoughts of Glory: Durable 9",
		"description": "Move: Thoughts of Glory Applies the Enduring effect to the user when its move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": 3,
		"y": 1,
		"name": "Wall for Challengers Bleakwind Storm: Power 25",
		"description": "Wall for Challengers Bleakwind Storm: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 35,
		"x": 2,
		"y": 2,
		"name": "Thoughts of Glory: Move: Special Boost ↑2 9",
		"description": "Move: Thoughts of Glory Increases the user’s Special Moves ↑ Next effect by two ranks when its move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": -1,
		"y": -1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": -2,
		"y": -1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 38,
		"x": -1,
		"y": -2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -3,
		"y": -1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": -2,
		"y": -2,
		"name": "Bleakwind Storm: Power 2",
		"description": "Bleakwind Storm: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 41,
		"x": -3,
		"y": -2,
		"name": "Bleakwind Storm: Power 2",
		"description": "Bleakwind Storm: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 42,
		"x": -1,
		"y": -3,
		"name": "Bleakwind Storm: Power 2",
		"description": "Bleakwind Storm: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 43,
		"x": -2,
		"y": -3,
		"name": "Gobsmack 4",
		"description": "Has a chance (50%) of leaving the target confused when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -3,
		"y": -3,
		"name": "Wall for Challengers Bleakwind Storm: Power 25",
		"description": "Wall for Challengers Bleakwind Storm: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 45,
		"x": -1,
		"y": -4,
		"name": "S-Move: Physical Boost ↑1 & Special Boost ↑1 9",
		"description": "Increases the user’s Physical Moves ↑ Next effect and Special Moves ↑ Next effect by one rank after using its sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -2,
		"y": -4,
		"name": "Cakewalk",
		"description": "The more the target’s Speed is lowered, the more it powers up the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "Wall for Challengers Bleakwind Storm: Power 25",
		"description": "Wall for Challengers Bleakwind Storm: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "Wall for Challengers Bleakwind Storm: Power 25",
		"description": "Wall for Challengers Bleakwind Storm: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const CHEREN_PURRLOIN = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 1,
		"y": -2,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 2,
		"y": -3,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 1,
		"y": -3,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": 3,
		"y": -4,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": 2,
		"y": -4,
		"name": "Dark Pulse: Power 3",
		"description": "Dark Pulse: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 12,
		"x": 1,
		"y": -4,
		"name": "Dark Pulse: Power 3",
		"description": "Dark Pulse: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 13,
		"x": 3,
		"y": -5,
		"name": "Dark Pulse: Power 3",
		"description": "Dark Pulse: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 14,
		"x": 2,
		"y": -5,
		"name": "Dark Pulse: Move Gauge Refresh 3",
		"description": "Move: Dark Pulse Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 1,
		"y": -5,
		"name": "Brainteaser",
		"description": "The more the target’s Sp. Def is lowered, the more it powers up the user’s moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": 3,
		"y": -6,
		"name": "Sp. Atk 10",
		"description": "Sp. Atk 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 17,
		"x": 2,
		"y": -6,
		"name": "Dark Pulse: Aggravation 1",
		"description": "Move: Dark Pulse Raises the chance of inflicting the flinching, confused, or trapped condition with the additional effects of moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": -2,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -3,
		"y": 2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": -2,
		"y": 2,
		"name": "Dark Pulse: Power 3",
		"description": "Dark Pulse: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 21,
		"x": -3,
		"y": 3,
		"name": "Dark Pulse: Power 3",
		"description": "Dark Pulse: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 22,
		"x": -1,
		"y": 2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 23,
		"x": -2,
		"y": 3,
		"name": "What to Do...: MP Refresh 2",
		"description": "Move: What to Do... Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -3,
		"y": 4,
		"name": "What to Do...: Fleet Feet 1",
		"description": "Move: What to Do... Raises the user’s Speed by one stat rank when its move is successful.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": -1,
		"y": 3,
		"name": "Speedster’s Sync 5",
		"description": "Powers up the user’s sync move when its Speed is raised.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -2,
		"y": 4,
		"name": "What to Do...: Hit and Heal 9",
		"description": "Move: What to Do... Applies the Gradual Healing effect to the user when its move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": 2,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 3,
		"y": -1,
		"name": "Haste",
		"description": "Speed cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": 2,
		"y": 0,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": 1,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 31,
		"x": 3,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 32,
		"x": 2,
		"y": 1,
		"name": "Fake Tears: Move Gauge Refresh 3",
		"description": "Move: Fake Tears Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": 1,
		"y": 2,
		"name": "Toward My Ideals Dark Beam: Power 25",
		"description": "Toward My Ideals Dark Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 34,
		"x": 3,
		"y": 1,
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 2,
		"y": 2,
		"name": "Fake Tears: Twofer 2",
		"description": "Move: Fake Tears Has a chance (30%) of applying the Free Move Next effect to the user when its Pokémon uses a move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": -1,
		"y": -1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": -2,
		"y": -1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 38,
		"x": -1,
		"y": -2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -3,
		"y": -1,
		"name": "Dauntless",
		"description": "Sp. Atk cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": -2,
		"y": -2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 41,
		"x": -3,
		"y": -2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 42,
		"x": -1,
		"y": -3,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 43,
		"x": -2,
		"y": -3,
		"name": "Dire Hit +: MP Refresh 2",
		"description": "Move: Dire Hit + Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -3,
		"y": -3,
		"name": "Superduper Effective 2",
		"description": "Powers up moves that are super effective.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -1,
		"y": -4,
		"name": "Toward My Ideals Dark Beam: Power 25",
		"description": "Toward My Ideals Dark Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 46,
		"x": -2,
		"y": -4,
		"name": "Catalyst",
		"description": "Applies the Move Gauge Acceleration effect to the allied field of play the first time the user’s sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "Toward My Ideals Dark Beam: Power 25",
		"description": "Toward My Ideals Dark Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "Toward My Ideals Dark Beam: Power 25",
		"description": "Toward My Ideals Dark Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const BIANCA_VIRIZION = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 1,
		"y": -2,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 2,
		"y": -3,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 3,
		"y": -4,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": 1,
		"y": -3,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": 2,
		"y": -4,
		"name": "Sacred Sword: Power 3",
		"description": "Sacred Sword: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 12,
		"x": 3,
		"y": -5,
		"name": "Sacred Sword: Power 3",
		"description": "Sacred Sword: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 13,
		"x": 1,
		"y": -4,
		"name": "Sacred Sword: Power 3",
		"description": "Sacred Sword: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 14,
		"x": 2,
		"y": -5,
		"name": "Furious Brawn",
		"description": "The more the user’s Attack is raised, the more it powers up the user’s moves.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 3,
		"y": -6,
		"name": "Ridicure 3",
		"description": "Has a chance (40%) of restoring the user’s HP by approximately 20% of its maximum HP when an opponent’s attack move targeting the user misses.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": 1,
		"y": -5,
		"name": "Defense Destroyer 9",
		"description": "Lowers the target’s Defense by two stat ranks when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": 2,
		"y": -6,
		"name": "Staggering 4",
		"description": "Has a chance (50%) of making the target flinch when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": -1,
		"y": 2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -2,
		"y": 3,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": -3,
		"y": 4,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 21,
		"x": -1,
		"y": 3,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 22,
		"x": -2,
		"y": 4,
		"name": "White Light Sacred Sword: Power 3",
		"description": "White Light Sacred Sword: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 23,
		"x": -3,
		"y": 5,
		"name": "White Light Sacred Sword: Power 3",
		"description": "White Light Sacred Sword: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 24,
		"x": -1,
		"y": 4,
		"name": "White Light Sacred Sword: Power 3",
		"description": "White Light Sacred Sword: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 25,
		"x": -2,
		"y": 5,
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -3,
		"y": 6,
		"name": "First Step to Glory: MP Refresh 2",
		"description": "Move: First Step to Glory Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": -1,
		"y": 5,
		"name": "First Step to Glory: Berserker 2",
		"description": "Move: First Step to Glory Raises the user’s Attack by two stat ranks when its move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 28,
		"x": -2,
		"y": 6,
		"name": "Trainer Sync Redemption 1",
		"description": "Restores one MP for the user’s Trainer the first time its sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": 2,
		"y": -1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": 3,
		"y": -1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 31,
		"x": 2,
		"y": 0,
		"name": "White Light Sacred Sword: Power 3",
		"description": "White Light Sacred Sword: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 32,
		"x": 1,
		"y": 1,
		"name": "White Light Sacred Sword: Power 3",
		"description": "White Light Sacred Sword: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 33,
		"x": 3,
		"y": 0,
		"name": "Circle: HP Recovery 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action when a circle applies to the allied field of play.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": 2,
		"y": 1,
		"name": "Evasive Sync-Up 3",
		"description": "Powers up the user’s sync move when its evasiveness is raised.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 1,
		"y": 2,
		"name": "Circle: MG → 2",
		"description": "Quickly charges the move gauge when a circle applies to the allied field of play.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": 3,
		"y": 1,
		"name": "Unova C (Defensive) Extension 5",
		"description": "Extends the duration of Unova Circle (Defensive) when Unova Circle (Defensive) applies to the allied field of play.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": 2,
		"y": 2,
		"name": "Circle Hit: Attack ↓ & Sp. Atk ↓ 9",
		"description": "Lowers the target’s Attack and Sp. Atk by one stat rank when the user’s attack move is successful while a circle applies to the allied field of play.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": -2,
		"y": 1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -3,
		"y": 1,
		"name": "Headstrong",
		"description": "Attack cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": -2,
		"y": 0,
		"name": "Sacred Sword: Move Gauge Refresh 3",
		"description": "Move: Sacred Sword Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 41,
		"x": -1,
		"y": -1,
		"name": "Sacred Sword: Power 3",
		"description": "Sacred Sword: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 42,
		"x": -3,
		"y": 0,
		"name": "Sacred Sword: Power 3",
		"description": "Sacred Sword: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 43,
		"x": -2,
		"y": -1,
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -1,
		"y": -2,
		"name": "Attack 10",
		"description": "Attack 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 45,
		"x": -3,
		"y": -1,
		"name": "Circle Hit: Physical Boost ↑1 9",
		"description": "Increases the user’s Physical Moves ↑ Next effect by one rank when its attack move is successful while a circle applies to the allied field of play.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -2,
		"y": -2,
		"name": "Unova C (Defensive): S-Moves ↑ 9",
		"description": "Powers up the user’s sync move when Unova Circle (Defensive) is applied to the allied field of play.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "Steps to a New Path Sacred Sword: Power 25",
		"description": "Steps to a New Path Sacred Sword: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "Steps to a New Path Sacred Sword: Power 25",
		"description": "Steps to a New Path Sacred Sword: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const LARRY_DUDUNSPARCE = [
	{
		"id": 1,
		"x": -1,
		"y": 0,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": -1,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": 1,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": 1,
		"y": -1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 0,
		"y": -2,
		"name": "Unflappable",
		"description": "Prevents the user from flinching.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 8,
		"x": 0,
		"y": -4,
		"name": "Enfeeble 2",
		"description": "Lowers the Defense of all opposing sync pairs by two stat ranks when the user enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "4",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 9,
		"x": 1,
		"y": -4,
		"name": "Recuperation 2",
		"description": "Restores the user’s HP by approximately 40% of its maximum HP after using its sync move.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 10,
		"x": 0,
		"y": 2,
		"name": "Escape Artist",
		"description": "Prevents the user from becoming trapped.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 11,
		"x": 0,
		"y": 4,
		"name": "Team Speedy Entry 2",
		"description": "Raises the Speed of all allied sync pairs by two stat ranks when the user enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "4",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 12,
		"x": -1,
		"y": 4,
		"name": "Dire Hit All +: Team Brawn Gain 9",
		"description": "Move: Dire Hit All + Increases the Physical Moves ↑ Next effect of all allied sync pairs by one rank when the user’s move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": 2,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 14,
		"x": 3,
		"y": -2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 15,
		"x": 2,
		"y": -2,
		"name": "Hyper Drill: Power 2",
		"description": "Hyper Drill: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 16,
		"x": 1,
		"y": -2,
		"name": "Hyper Drill: Power 2",
		"description": "Hyper Drill: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 17,
		"x": 3,
		"y": -3,
		"name": "Hyper Drill: Power 2",
		"description": "Hyper Drill: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 18,
		"x": 2,
		"y": -3,
		"name": "Hyper Drill: Move Gauge Refresh 3",
		"description": "Move: Hyper Drill Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 19,
		"x": 1,
		"y": -3,
		"name": "Numbing Blow 4",
		"description": "Has a chance (50%) of leaving the target paralyzed when the user’s attack move against it is successful.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 20,
		"x": 3,
		"y": -4,
		"name": "Hyper Drill: Move Gauge Refresh 9",
		"description": "Move: Hyper Drill Charges the user’s move gauge by one when its move is successful.",
		"energy": "9",
		"orb": "108",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 21,
		"x": 2,
		"y": -4,
		"name": "Ramming Speed",
		"description": "The more the user’s Speed is raised, the more it powers up the user’s moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 22,
		"x": -2,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 23,
		"x": -3,
		"y": 2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 24,
		"x": -2,
		"y": 2,
		"name": "Bullet Speed Hyper Drill: Power 2",
		"description": "Bullet Speed Hyper Drill: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 25,
		"x": -1,
		"y": 2,
		"name": "Bullet Speed Hyper Drill: Power 2",
		"description": "Bullet Speed Hyper Drill: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 26,
		"x": -3,
		"y": 3,
		"name": "Bullet Speed Hyper Drill: Power 2",
		"description": "Bullet Speed Hyper Drill: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 27,
		"x": -2,
		"y": 3,
		"name": "Dire Hit All +: MP Refresh 2",
		"description": "Move: Dire Hit All + Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 28,
		"x": -1,
		"y": 3,
		"name": "Attack Trap 4",
		"description": "Has a chance (50%) of leaving the target trapped when the user’s attack move against it is successful.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": -3,
		"y": 4,
		"name": "Head Start 1",
		"description": "Reduces the user’s sync move countdown by one the first time it enters a battle each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 30,
		"x": -2,
		"y": 4,
		"name": "Endurance",
		"description": "When the user enters battle with full HP, applies the Enduring effect to it.",
		"energy": "9",
		"orb": "108",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": 1,
		"y": 1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 32,
		"x": 2,
		"y": 1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 33,
		"x": 3,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": 1,
		"y": 2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 35,
		"x": 2,
		"y": 2,
		"name": "Bullet Speed Hyper Drill: Power 2",
		"description": "Bullet Speed Hyper Drill: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 36,
		"x": 3,
		"y": 2,
		"name": "Bullet Speed Hyper Drill: Power 2",
		"description": "Bullet Speed Hyper Drill: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 37,
		"x": 1,
		"y": 3,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 38,
		"x": 2,
		"y": 3,
		"name": "Plain and Simple: MP Refresh 2",
		"description": "Move: Plain and Simple Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 39,
		"x": 3,
		"y": 3,
		"name": "HP 40",
		"description": "HP 40",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": 1,
		"y": 4,
		"name": "Inertia",
		"description": "The more user’s Speed is raised, the more it powers up the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 41,
		"x": 2,
		"y": 4,
		"name": "Mighty Command 9",
		"description": "Increases the user’s Physical Moves ↑ Next effect by one rank when its Trainer uses a move.",
		"energy": "9",
		"orb": "108",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 42,
		"x": -1,
		"y": -1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 43,
		"x": -2,
		"y": -1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 44,
		"x": -3,
		"y": -1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 45,
		"x": -1,
		"y": -2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 46,
		"x": -2,
		"y": -2,
		"name": "Hyper Drill: Power 2",
		"description": "Hyper Drill: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 47,
		"x": -3,
		"y": -2,
		"name": "Hyper Drill: Power 2",
		"description": "Hyper Drill: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 48,
		"x": -1,
		"y": -3,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 49,
		"x": -2,
		"y": -3,
		"name": "Mad Strength 9",
		"description": "Raises the user’s Attack by one stat rank when its attack move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 50,
		"x": -3,
		"y": -3,
		"name": "Ghost Guard",
		"description": "Reduces damage when the user is attacked by Ghost-type moves.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 51,
		"x": -1,
		"y": -4,
		"name": "S-Move on Opp: Attack ↓ & Sp. Atk ↓ 2",
		"description": "Lowers the target’s Attack and Sp. Atk by two stat ranks when the user’s sync move targeting that opponent is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 52,
		"x": -2,
		"y": -4,
		"name": "Hit Rebuff ↓ Opp: Free Move Next 4",
		"description": "Has a chance (50%) of applying the Free Move Next effect to the user when its attack move is successful while the target’s Type Rebuff is lowered.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 53,
		"x": 0,
		"y": -3,
		"name": "Exceptional Everyman Hyper Drill: Power 25",
		"description": "Exceptional Everyman Hyper Drill: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 54,
		"x": 0,
		"y": 3,
		"name": "Exceptional Everyman Hyper Drill: Power 25",
		"description": "Exceptional Everyman Hyper Drill: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const KABU_CENTISKORCH = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 0,
		"y": -2,
		"name": "Antitoxin",
		"description": "Prevents the user from getting poisoned or badly poisoned.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 8,
		"x": 0,
		"y": -4,
		"name": "Overwhelm 9",
		"description": "Lowers the target’s Attack by one stat rank when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "4",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 9,
		"x": -2,
		"y": -3,
		"name": "First Aid 4",
		"description": "Restores the user’s HP by approximately 40% of its maximum HP the first time it is in a pinch each battle.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 10,
		"x": 0,
		"y": 2,
		"name": "Antifreeze",
		"description": "Prevents the user from becoming frozen.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 11,
		"x": 0,
		"y": 4,
		"name": "Team MAX/Sync Boost (Physical) 9",
		"description": "Increases the Physical Moves ↑ Next effect of all allied sync pairs by one rank after using the user’s sync move or max move.",
		"energy": "10",
		"orb": "120",
		"level": "4",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 12,
		"x": -2,
		"y": 5,
		"name": "MAX Countdown 2",
		"description": "Reduces the user’s sync move countdown by two after using its max move.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": 1,
		"y": -2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 14,
		"x": 2,
		"y": -3,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 15,
		"x": 1,
		"y": -3,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 16,
		"x": 3,
		"y": -4,
		"name": "Flameproof",
		"description": "Prevents the user from getting burned.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": 2,
		"y": -4,
		"name": "Ember: Power 4",
		"description": "Ember: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 18,
		"x": 1,
		"y": -4,
		"name": "Ember: Move Gauge Refresh 3",
		"description": "Move: Ember Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 19,
		"x": 3,
		"y": -5,
		"name": "Ember: Power 4",
		"description": "Ember: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 20,
		"x": 2,
		"y": -5,
		"name": "Scorcher 2",
		"description": "Increases the amount of damage an opponent takes from being burned.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 21,
		"x": 1,
		"y": -5,
		"name": "Impervious",
		"description": "The user’s stats cannot be lowered.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 22,
		"x": 3,
		"y": -6,
		"name": "Sp. Def 10",
		"description": "Sp. Def 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 23,
		"x": 2,
		"y": -6,
		"name": "Flag Bearer 9",
		"description": "Raises the Attack of all allied sync pairs by one stat rank when the user’s Pokémon uses a move.",
		"energy": "9",
		"orb": "108",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -2,
		"y": 2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 25,
		"x": -3,
		"y": 3,
		"name": "Blazing Flame Wheel: Power 3",
		"description": "Blazing Flame Wheel: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 26,
		"x": -1,
		"y": 2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 27,
		"x": -2,
		"y": 3,
		"name": "Blazing Flame Wheel: Power 3",
		"description": "Blazing Flame Wheel: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 28,
		"x": -3,
		"y": 4,
		"name": "Sunscreen 2",
		"description": "Reduces damage when the user is hit by an attack move while the weather is sunny.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": -1,
		"y": 3,
		"name": "Blazing Flame Wheel: Power 3",
		"description": "Blazing Flame Wheel: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 30,
		"x": -2,
		"y": 4,
		"name": "Get Your Mind Moving!: MP Refresh 2",
		"description": "Move: Get Your Mind Moving! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": -3,
		"y": 5,
		"name": "Get Your Mind Moving!: Team Hit and Heal",
		"description": "Move: Get Your Mind Moving! Applies the Gradual Healing effect to all allied sync pairs when the user’s move is successful.",
		"energy": "9",
		"orb": "108",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 32,
		"x": -1,
		"y": 4,
		"name": "Debut: Team Physical Boost 1",
		"description": "Increases the Physical Moves ↑ Next effect of all allied sync pairs by one rank the first time the user enters a battle each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": 1,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": 2,
		"y": 1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 35,
		"x": 1,
		"y": 2,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 36,
		"x": 3,
		"y": 1,
		"name": "Escape Artist",
		"description": "Prevents the user from becoming trapped.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": 2,
		"y": 2,
		"name": "Blazing Flame Wheel: Power 3",
		"description": "Blazing Flame Wheel: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 38,
		"x": 1,
		"y": 3,
		"name": "Blazing Flame Wheel: Move Gauge Refresh 3",
		"description": "Move: Blazing Flame Wheel Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 39,
		"x": 3,
		"y": 2,
		"name": "Blazing Flame Wheel: Power 3",
		"description": "Blazing Flame Wheel: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 40,
		"x": 2,
		"y": 3,
		"name": "Pokey Trap 2",
		"description": "Increases the amount of damage an opponent takes from being trapped.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 41,
		"x": 1,
		"y": 4,
		"name": "Team First Super Sync",
		"description": "Applies the Supereffective ↑ Next effect to all allied sync pairs the first time the user’s sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 42,
		"x": 3,
		"y": 3,
		"name": "MAX Double Down 3",
		"description": "Powers up the user’s max moves that are super effective.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": 2,
		"y": 4,
		"name": "Haymaker",
		"description": "The more the user’s Attack is raised, the more it powers up the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -2,
		"y": 0,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 45,
		"x": -1,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 46,
		"x": -3,
		"y": 0,
		"name": "Ember: Power 4",
		"description": "Ember: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 47,
		"x": -2,
		"y": -1,
		"name": "Ember: Power 4",
		"description": "Ember: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 48,
		"x": -1,
		"y": -2,
		"name": "Ember: Power 4",
		"description": "Ember: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 49,
		"x": -3,
		"y": -1,
		"name": "Healing Sun 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action while the weather is sunny.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 50,
		"x": -2,
		"y": -2,
		"name": "Protect: Move Gauge Refresh 9",
		"description": "Move: Protect Charges the user’s move gauge by one when its move is successful.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 51,
		"x": -1,
		"y": -3,
		"name": "Sync Damage Guard",
		"description": "Applies the Damage Guard Next effect to the user the first time its sync move is used each battle.",
		"energy": "9",
		"orb": "108",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 52,
		"x": -3,
		"y": -2,
		"name": "Vigilance",
		"description": "Protects the user against critical hits.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 53,
		"x": 0,
		"y": -3,
		"name": "Ever-Burning Man Fire Impact: Power 25",
		"description": "Ever-Burning Man Fire Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 54,
		"x": 0,
		"y": 3,
		"name": "Ever-Burning Man Fire Impact: Power 25",
		"description": "Ever-Burning Man Fire Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]