export const ZINNIA_RAYQUAZA = [
	{
		id: 1,
		x: 1,
		y: -1,
		name: 'HP +10',
		description: 'HP +10',
		energy: 0,
		orb: 5,
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 2,
		x: 1,
		y: 0,
		name: 'Attack +5',
		description: 'Attack +5',
		energy: 0,
		orb: 5,
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 3,
		x: 0,
		y: 1,
		name: 'Defense +5',
		description: 'Defense +5',
		energy: 0,
		orb: 5,
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 4,
		x: -1,
		y: 1,
		name: 'Sp. Atk +5',
		description: 'Sp. Atk +5',
		energy: 0,
		orb: 5,
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 5,
		x: -1,
		y: 0,
		name: 'Sp. Def +5',
		description: 'Sp. Def +5',
		energy: 0,
		orb: 5,
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 6,
		x: 0,
		y: -1,
		name: 'Speed +5',
		description: 'Speed +5',
		energy: 0,
		orb: 5,
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 7,
		x: 1,
		y: -2,
		name: 'Attack +5',
		description: 'Attack +5',
		energy: 2,
		orb: 24,
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 8,
		x: 2,
		y: -3,
		name: 'Sp. Atk +5',
		description: 'Sp. Atk +5',
		energy: 2,
		orb: 24,
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 9,
		x: 3,
		y: -4,
		name: 'Defense +5',
		description: 'Defense +5',
		energy: 2,
		orb: 24,
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 10,
		x: 1,
		y: -3,
		name: 'Speed +5',
		description: 'Speed +5',
		energy: 2,
		orb: 24,
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 11,
		x: 2,
		y: -4,
		name: 'Outrage Move Gauge Refresh 2',
		description: 'Has a chance (30%) of charging the user’s move gauge by one when a move is successful.',
		energy: 7,
		orb: 84,
		level: 1,
		color: 'red',
		icon: 'passive'
	},
	{
		id: 12,
		x: 3,
		y: -5,
		name: 'Outrage: Power ↑ +3',
		description: 'Outrage: Power ↑ +3',
		energy: 4,
		orb: 48,
		level: 1,
		color: 'green',
		icon: 'dragon'
	},
	{
		id: 13,
		x: 1,
		y: -4,
		name: 'Outrage: Power ↑ +3',
		description: 'Outrage: Power ↑ +3',
		energy: 4,
		orb: 48,
		level: 2,
		color: 'green',
		icon: 'dragon'
	},
	{
		id: 14,
		x: 2,
		y: -5,
		name: 'Outrage: Power ↑ +3',
		description: 'Outrage: Power ↑ +3',
		energy: 4,
		orb: 48,
		level: 2,
		color: 'green',
		icon: 'dragon'
	},
	{
		id: 15,
		x: 3,
		y: -6,
		name: 'HP +20',
		description: 'HP +20',
		energy: 4,
		orb: 48,
		level: 2,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 16,
		x: 1,
		y: -5,
		name: 'Clearheaded',
		description: 'Prevents the user from becoming confused.',
		energy: 10,
		orb: 120,
		level: 3,
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 17,
		x: 2,
		y: -6,
		name: 'Weather Surge 3',
		description: 'Powers up moves when weather conditions are in effect.',
		energy: 10,
		orb: 120,
		level: 3,
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 18,
		x: -1,
		y: 2,
		name: 'Sp. Def +5',
		description: 'Sp. Def +5',
		energy: 2,
		orb: 24,
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 19,
		x: -2,
		y: 3,
		name: 'Speed +5',
		description: 'Speed +5',
		energy: 2,
		orb: 24,
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 20,
		x: -3,
		y: 4,
		name: 'Defense +5',
		description: 'Defense +5',
		energy: 2,
		orb: 24,
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 21,
		x: -1,
		y: 3,
		name: 'Sp. Atk +5',
		description: 'Sp. Atk +5',
		energy: 2,
		orb: 24,
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 22,
		x: -2,
		y: 4,
		name: 'Draco Meteor: Power ↑ +3',
		description: 'Draco Meteor: Power ↑ +3',
		energy: 4,
		orb: 48,
		level: 1,
		color: 'green',
		icon: 'dragon'
	},
	{
		id: 23,
		x: -3,
		y: 5,
		name: 'Draco Meteor: Accuracy ↑ +5',
		description: 'Draco Meteor: Accuracy ↑ +5',
		energy: 4,
		orb: 48,
		level: 1,
		color: 'green',
		icon: 'dragon'
	},
	{
		id: 24,
		x: -1,
		y: 4,
		name: 'Draco Meteor: Power ↑ +3',
		description: 'Draco Meteor: Power ↑ +3',
		energy: 4,
		orb: 48,
		level: 2,
		color: 'green',
		icon: 'dragon'
	},
	{
		id: 25,
		x: -2,
		y: 5,
		name: 'Draco Meteor Move Gauge Refresh 2',
		description: 'Has a chance (30%) of charging the user’s move gauge by one when a move is successful.',
		energy: 7,
		orb: 84,
		level: 2,
		color: 'red',
		icon: 'passive'
	},
	{
		id: 26,
		x: -3,
		y: 6,
		name: 'Draco Meteor: Power ↑ +3',
		description: 'Draco Meteor: Power ↑ +3',
		energy: 4,
		orb: 48,
		level: 2,
		color: 'green',
		icon: 'dragon'
	},
	{
		id: 27,
		x: -1,
		y: 5,
		name: 'Special Reserves 4',
		description: 'Raises the user’s Sp. Atk by 4 stat rank the first time it is in a pinch each battle.',
		energy: 10,
		orb: 120,
		level: 3,
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 28,
		x: -2,
		y: 6,
		name: 'Weather Sync-Up 5',
		description: 'Powers up sync moves when weather conditions are in effect.',
		energy: 10,
		orb: 120,
		level: 3,
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 29,
		x: 2,
		y: -1,
		name: 'HP +10',
		description: 'HP +10',
		energy: 2,
		orb: 24,
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 30,
		x: 3,
		y: -1,
		name: 'Aerial Ace: Power ↑ +4',
		description: 'Aerial Ace: Power ↑ +4',
		energy: 3,
		orb: 36,
		level: 1,
		color: 'green',
		icon: 'flying'
	},
	{
		id: 31,
		x: 2,
		y: 0,
		name: 'Aerial Ace Move Gauge Refresh 2',
		description: 'Has a chance (30%) of charging the user’s move gauge by one when a move is successful.',
		energy: 7,
		orb: 84,
		level: 1,
		color: 'red',
		icon: 'passive'
	},
	{
		id: 32,
		x: 1,
		y: 1,
		name: 'Aerial Ace: Power ↑ +4',
		description: 'Aerial Ace: Power ↑ +4',
		energy: 3,
		orb: 36,
		level: 1,
		color: 'green',
		icon: 'flying'
	},
	{
		id: 33,
		x: 3,
		y: 0,
		name: 'Aerial Ace: Power ↑ +4',
		description: 'Aerial Ace: Power ↑ +4',
		energy: 3,
		orb: 36,
		level: 2,
		color: 'green',
		icon: 'flying'
	},
	{
		id: 34,
		x: 2,
		y: 1,
		name: 'Aerial Ace: Power ↑ +4',
		description: 'Aerial Ace: Power ↑ +4',
		energy: 3,
		orb: 36,
		level: 2,
		color: 'green',
		icon: 'flying'
	},
	{
		id: 35,
		x: 1,
		y: 2,
		name: 'Draco Meteor: Accuracy ↑ +5',
		description: 'Draco Meteor: Accuracy ↑ +5',
		energy: 4,
		orb: 48,
		level: 2,
		color: 'green',
		icon: 'dragon'
	},
	{
		id: 36,
		x: 3,
		y: 1,
		name: 'Aerial Ace Mind Swell 3',
		description: 'Has a chance (40%) of raising the user’s Sp. Atk by one stat rank when its Pokémon uses a move.',
		energy: 10,
		orb: 120,
		level: 3,
		color: 'red',
		icon: 'passive'
	},
	{
		id: 37,
		x: 2,
		y: 2,
		name: 'Grand Entry 2',
		description: 'Raises the user’s Sp. Atk by 2 stat rank when it enters a battle.',
		energy: 10,
		orb: 120,
		level: 3,
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 38,
		x: -2,
		y: 1,
		name: 'Sp. Atk +5',
		description: 'Sp. Atk +5',
		energy: 2,
		orb: 24,
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 39,
		x: -3,
		y: 1,
		name: 'Draco Meteor: Power ↑ +3',
		description: 'Draco Meteor: Power ↑ +3',
		energy: 4,
		orb: 48,
		level: 1,
		color: 'green',
		icon: 'dragon'
	},
	{
		id: 40,
		x: -2,
		y: 0,
		name: 'Speed +5',
		description: 'Speed +5',
		energy: 2,
		orb: 24,
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 41,
		x: -1,
		y: -1,
		name: 'Defense +5',
		description: 'Defense +5',
		energy: 2,
		orb: 24,
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 42,
		x: -3,
		y: 0,
		name: 'Aerial Ace: Power ↑ +4',
		description: 'Aerial Ace: Power ↑ +4',
		energy: 3,
		orb: 36,
		level: 2,
		color: 'green',
		icon: 'flying'
	},
	{
		id: 43,
		x: -2,
		y: -1,
		name: 'Stellar\nImagination! MP Refresh 2',
		description: 'Has a chance (30%) of restoring one MP of the user’s move when that move is successful.',
		energy: 7,
		orb: 84,
		level: 2,
		color: 'red',
		icon: 'passive'
	},
	{
		id: 44,
		x: -1,
		y: -2,
		name: 'Outrage: Power ↑ +3',
		description: 'Outrage: Power ↑ +3',
		energy: 4,
		orb: 48,
		level: 2,
		color: 'green',
		icon: 'dragon'
	},
	{
		id: 45,
		x: -3,
		y: -1,
		name: 'Aerial Ace Eagle Eye 3',
		description: 'Has a chance (40%) of raising the user’s critical-hit rate by one stat rank when its Pokémon uses a move.',
		energy: 9,
		orb: 108,
		level: 3,
		color: 'red',
		icon: 'passive'
	},
	{
		id: 46,
		x: -2,
		y: -2,
		name: 'Attack +20',
		description: 'Attack +20',
		energy: 7,
		orb: 84,
		level: 3,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 47,
		x: 0,
		y: -3,
		name: 'Dimensional Defender\nDraco Meteor: Power ↑ +25',
		description: 'Dimensional Defender\nDraco Meteor: Power ↑ +25',
		energy: 5,
		orb: 60,
		level: 3,
		color: 'sync',
		icon: 'sync'
	},
	{
		id: 48,
		x: 0,
		y: 3,
		name: 'Dimensional Defender\nDraco Meteor: Power ↑ +25',
		description: 'Dimensional Defender\nDraco Meteor: Power ↑ +25',
		energy: 5,
		orb: 60,
		level: 3,
		color: 'sync',
		icon: 'sync'
	}
]

export const STEVEN_DEOXYS = [
	{
		id: 1,
		x: 1,
		y: -1,
		name: 'HP 10',
		description: 'HP 10',
		energy: '0',
		orb: '5',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 2,
		x: 1,
		y: 0,
		name: 'Attack 5',
		description: 'Attack 5',
		energy: '0',
		orb: '5',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 3,
		x: 0,
		y: 1,
		name: 'Defense 5',
		description: 'Defense 5',
		energy: '0',
		orb: '5',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 4,
		x: -1,
		y: 1,
		name: 'Sp. Atk 5',
		description: 'Sp. Atk 5',
		energy: '0',
		orb: '5',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 5,
		x: -1,
		y: 0,
		name: 'Sp. Def 5',
		description: 'Sp. Def 5',
		energy: '0',
		orb: '5',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 6,
		x: 0,
		y: -1,
		name: 'Speed 5',
		description: 'Speed 5',
		energy: '0',
		orb: '5',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 7,
		x: 0,
		y: -2,
		name: 'Sp. Atk 5',
		description: 'Sp. Atk 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 8,
		x: -1,
		y: -2,
		name: 'Psycho Boost: Power 2',
		description: 'Psycho Boost: Power + 2',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'psychic'
	},
	{
		id: 9,
		x: -1,
		y: -3,
		name: 'Space Rocks Psycho Boost: Power 25',
		description: 'Space Rocks Psycho Boost: Power + 25',
		energy: '5',
		orb: '60',
		level: 1,
		color: 'sync',
		icon: 'sync'
	},
	{
		id: 10,
		x: 0,
		y: -4,
		name: 'Space Rocks Psycho Boost: Power 25',
		description: 'Space Rocks Psycho Boost: Power + 25',
		energy: '5',
		orb: '60',
		level: '2',
		color: 'sync',
		icon: 'sync'
	},
	{
		id: 11,
		x: 1,
		y: -4,
		name: 'Space Rocks Psycho Boost: Power 25',
		description: 'Space Rocks Psycho Boost: Power + 25',
		energy: '5',
		orb: '60',
		level: '2',
		color: 'sync',
		icon: 'sync'
	},
	{
		id: 12,
		x: 1,
		y: -3,
		name: 'Psycho Boost: Power 2',
		description: 'Psycho Boost: Power + 2',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'psychic'
	},
	{
		id: 13,
		x: 0,
		y: -3,
		name: 'Psycho Boost: Accuracy 10',
		description: 'Psycho Boost: Accuracy + 10',
		energy: '5',
		orb: '60',
		level: 1,
		color: 'green',
		icon: 'psychic'
	},
	{
		id: 14,
		x: 2,
		y: -2,
		name: 'Sp. Atk 5',
		description: 'Sp. Atk 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 15,
		x: 2,
		y: -3,
		name: 'Psycho Boost: Power 2',
		description: 'Psycho Boost: Power + 2',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'psychic'
	},
	{
		id: 16,
		x: 3,
		y: -4,
		name: 'Furious Brain',
		description: "The more the user's Sp. Atk is raised, the more it powers up the user's moves.",
		energy: '10',
		orb: '120',
		level: '3',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 17,
		x: 4,
		y: -4,
		name: 'Soften Up 1',
		description: 'Critical hits land more easily when the user attacks with a sync move.',
		energy: '10',
		orb: '120',
		level: '3',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 18,
		x: 4,
		y: -3,
		name: 'Psycho Boost: BOGO 4',
		description: 'Move: Psycho Boost Has a chance (50%) of applying the Free Move Next effect to the user when its move is successful.',
		energy: '10',
		orb: '120',
		level: '3',
		color: 'red',
		icon: 'passive'
	},
	{
		id: 19,
		x: 3,
		y: -2,
		name: 'Psycho Boost: Power 2',
		description: 'Psycho Boost: Power + 2',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'psychic'
	},
	{
		id: 20,
		x: 3,
		y: -3,
		name: 'Psycho Boost: Move Gauge Refresh 3',
		description: "Move: Psycho Boost Has a chance (40%) of charging the user's move gauge by one when a move is successful.",
		energy: '7',
		orb: '84',
		level: 1,
		color: 'red',
		icon: 'passive'
	},
	{
		id: 21,
		x: 2,
		y: 0,
		name: 'HP 10',
		description: 'HP 10',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 22,
		x: 3,
		y: -1,
		name: 'Psycho Boost: Power 2',
		description: 'Psycho Boost: Power + 2',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'psychic'
	},
	{
		id: 23,
		x: 4,
		y: -1,
		name: 'Sp. Def 20',
		description: 'Sp. Def 20',
		energy: '7',
		orb: '84',
		level: '2',
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 24,
		x: 4,
		y: 0,
		name: 'Move Gauge Refresh 2',
		description: "Has a chance (30%) of charging the user's move gauge by one when a move is successful.",
		energy: '7',
		orb: '84',
		level: '2',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 25,
		x: 3,
		y: 1,
		name: 'Defense 20',
		description: 'Defense 20',
		energy: '7',
		orb: '84',
		level: '2',
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 26,
		x: 2,
		y: 1,
		name: 'Zen Headbutt: Power 2',
		description: 'Zen Headbutt: Power + 2',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'psychic'
	},
	{
		id: 27,
		x: 3,
		y: 0,
		name: 'Cosmic Power: Move Gauge Refresh 3',
		description: "Move: Cosmic Power Has a chance (40%) of charging the user's move gauge by one when a move is successful.",
		energy: '7',
		orb: '84',
		level: 1,
		color: 'red',
		icon: 'passive'
	},
	{
		id: 28,
		x: 0,
		y: 2,
		name: 'HP 10',
		description: 'HP 10',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 29,
		x: 1,
		y: 2,
		name: 'HP 10',
		description: 'HP 10',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 30,
		x: 1,
		y: 3,
		name: 'Recover: MP Refresh 2',
		description: "Move: Recover Has a chance (30%) of restoring one MP of the user's move when that move is successful.",
		energy: '7',
		orb: '84',
		level: '3',
		color: 'red',
		icon: 'passive'
	},
	{
		id: 31,
		x: 0,
		y: 4,
		name: 'Iron Defense: Move Gauge Refresh 9',
		description: "Move: Iron Defense Charges the user's move gauge by one when its move is successful.",
		energy: '10',
		orb: '120',
		level: '3',
		color: 'red',
		icon: 'passive'
	},
	{
		id: 32,
		x: -1,
		y: 4,
		name: 'Recover: Master Healer 1',
		description: "Move: Recover Increases the amount of HP restored by the user's healing moves.",
		energy: '10',
		orb: '120',
		level: '3',
		color: 'red',
		icon: 'passive'
	},
	{
		id: 33,
		x: -1,
		y: 3,
		name: 'HP 10',
		description: 'HP 10',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 34,
		x: 0,
		y: 3,
		name: 'Recover: Move Gauge Refresh 3',
		description: "Move: Recover Has a chance (40%) of charging the user's move gauge by one when a move is successful.",
		energy: '7',
		orb: '84',
		level: 1,
		color: 'red',
		icon: 'passive'
	},
	{
		id: 35,
		x: -2,
		y: 2,
		name: 'Speed 5',
		description: 'Speed 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 36,
		x: -2,
		y: 3,
		name: 'Zen Headbutt: Power 3',
		description: 'Zen Headbutt: Power + 3',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'psychic'
	},
	{
		id: 37,
		x: -3,
		y: 4,
		name: 'Double Team: Move Gauge Refresh 9',
		description: "Move: Double Team Charges the user's move gauge by one when its move is successful.",
		energy: '10',
		orb: '120',
		level: '2',
		color: 'red',
		icon: 'passive'
	},
	{
		id: 38,
		x: -4,
		y: 4,
		name: 'Morale Boost+ 9',
		description: "Raises the user's Sp.Â Atk by 2 stat ranks when its Trainer uses a move.",
		energy: '10',
		orb: '120',
		level: '2',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 39,
		x: -4,
		y: 3,
		name: 'Double Team: Pep Rally 1',
		description: "Move: Double Team Raises the Speed of all allied sync pairs by 1 stat rank when the user's move is successful.",
		energy: '10',
		orb: '120',
		level: '2',
		color: 'red',
		icon: 'passive'
	},
	{
		id: 40,
		x: -3,
		y: 2,
		name: 'Zen Headbutt: Power 3',
		description: 'Zen Headbutt: Power + 3',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'psychic'
	},
	{
		id: 41,
		x: -3,
		y: 3,
		name: 'Zen Headbutt: Accuracy 10',
		description: 'Zen Headbutt: Accuracy + 10',
		energy: '5',
		orb: '60',
		level: 1,
		color: 'green',
		icon: 'psychic'
	},
	{
		id: 42,
		x: -2,
		y: 0,
		name: 'Attack 5',
		description: 'Attack 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 43,
		x: -3,
		y: 1,
		name: 'Zen Headbutt: Power 3',
		description: 'Zen Headbutt: Power + 3',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'psychic'
	},
	{
		id: 44,
		x: -4,
		y: 1,
		name: 'Critical Odds+ 9',
		description: "Raises the user's critical-hit rate by 2 stat ranks when its Trainer uses a move.",
		energy: '10',
		orb: '120',
		level: '3',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 45,
		x: -4,
		y: 0,
		name: 'Space Rocks Psycho Boost: Power 25',
		description: 'Space Rocks Psycho Boost: Power + 25',
		energy: '5',
		orb: '60',
		level: '3',
		color: 'sync',
		icon: 'sync'
	},
	{
		id: 46,
		x: -3,
		y: -1,
		name: 'Disarm 9',
		description: "Lowers the target's Attack and Sp.Â Atk by one stat rank when the user's attack move is successful against a flinching, confused, or trapped opponent.",
		energy: '10',
		orb: '120',
		level: '3',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 47,
		x: -2,
		y: -1,
		name: 'Zen Headbutt: Power 3',
		description: 'Zen Headbutt: Power + 3',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'psychic'
	},
	{
		id: 48,
		x: -3,
		y: 0,
		name: 'Move Gauge Refresh 3',
		description: 'Has a chance (40%) of charging the user’s move gauge by one when a move is successful.',
		energy: '7',
		orb: '84',
		level: 1,
		color: 'green',
		icon: 'psychic'
	},
	{
		"id": 49,
		"x": -2,
		"y": -2,
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": 7,
		"orb": 84,
		"level": 2,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 50,
		"x": 2,
		"y": 2,
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": 7,
		"orb": 84,
		"level": 2,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 51,
		"x": -2,
		"y": 4,
		"name": "Vigilance",
		"description": "Protects the user against critical hits.",
		"energy": 10,
		"orb": 120,
		"level": 4,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 52,
		"x": 2,
		"y": -4,
		"name": "Piercing Gaze",
		"description": "Moves never miss.",
		"energy": 10,
		"orb": 120,
		"level": 4,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 53,
		"x": 4,
		"y": -2,
		"name": "Mind Games 9",
		"description": "Has a chance (100%) of lowering the target’s Sp. Def by one stat rank when the user’s attack move against it is successful.",
		"energy": 10,
		"orb": 120,
		"level": 5,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 54,
		"x": -4,
		"y": 2,
		"name": "Head Start 1",
		"description": "Reduces the user’s sync move countdown by 1 the first time it enters a battle each battle.",
		"energy": 10,
		"orb": 120,
		"level": 5,
		"color": "yellow",
		"icon": "passive"
	}
]

export const GIOVANNI_PERSIAN = [
	{
		id: 1,
		x: 1,
		y: -1,
		name: 'HP 10',
		description: 'HP 10',
		energy: '0',
		orb: '5',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 2,
		x: 1,
		y: 0,
		name: 'Attack 5',
		description: 'Attack 5',
		energy: '0',
		orb: '5',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 3,
		x: 0,
		y: 1,
		name: 'Defense 5',
		description: 'Defense 5',
		energy: '0',
		orb: '5',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 4,
		x: -1,
		y: 1,
		name: 'Attack 5',
		description: 'Attack 5',
		energy: '0',
		orb: '5',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 5,
		x: -1,
		y: 0,
		name: 'Sp. Def 5',
		description: 'Sp. Def 5',
		energy: '0',
		orb: '5',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 6,
		x: 0,
		y: -1,
		name: 'Speed 5',
		description: 'Speed 5',
		energy: '0',
		orb: '5',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 7,
		x: 1,
		y: -2,
		name: 'Speed 5',
		description: 'Speed 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 8,
		x: 2,
		y: -3,
		name: 'Defense 5',
		description: 'Defense 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 9,
		x: 1,
		y: -3,
		name: 'Sp. Def 5',
		description: 'Sp. Def 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 10,
		x: 3,
		y: -4,
		name: 'HP 10',
		description: 'HP 10',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 11,
		x: 2,
		y: -4,
		name: 'Slash: Power 3',
		description: 'Slash: Power + 3',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'normal'
	},
	{
		id: 12,
		x: 1,
		y: -4,
		name: 'Slash: Power 3',
		description: 'Slash: Power + 3',
		energy: '3',
		orb: '36',
		level: '2',
		color: 'green',
		icon: 'normal'
	},
	{
		id: 13,
		x: 3,
		y: -5,
		name: 'Slash: Power 3',
		description: 'Slash: Power + 3',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'normal'
	},
	{
		id: 14,
		x: 2,
		y: -5,
		name: 'Slash: Move Gauge Refresh 3',
		description: "Move: Slash Has a chance (40%) of charging the user's move gauge by one when a move is successful.",
		energy: '7',
		orb: '84',
		level: '2',
		color: 'red',
		icon: 'passive'
	},
	{
		id: 15,
		x: 1,
		y: -5,
		name: 'Enough!: Berserk Bunch 1',
		description: "Move: Enough! Raises the Attack of all allied sync pairs by 1 stat rank when the user's move is successful.",
		energy: '10',
		orb: '120',
		level: '3',
		color: 'red',
		icon: 'passive'
	},
	{
		id: 16,
		x: 3,
		y: -6,
		name: 'Ramming Speed',
		description: "The more the user's Speed is raised, the more it powers up the user's moves.",
		energy: '10',
		orb: '120',
		level: '2',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 17,
		x: 2,
		y: -6,
		name: 'On the Run 2',
		description: "Raises the user's evasiveness by 2 stat ranks the first time it is in a pinch each battle.",
		energy: '10',
		orb: '120',
		level: '3',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 18,
		x: -2,
		y: 2,
		name: 'Speed 5',
		description: 'Speed 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 19,
		x: -3,
		y: 3,
		name: 'Bite: Power 3',
		description: 'Bite: Power + 3',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'dark'
	},
	{
		id: 20,
		x: -1,
		y: 2,
		name: 'Sp. Def 5',
		description: 'Sp. Def 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 21,
		x: -2,
		y: 3,
		name: 'Bite: Power 3',
		description: 'Bite: Power + 3',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'dark'
	},
	{
		id: 22,
		x: -3,
		y: 4,
		name: 'Stamina Reserves 2',
		description: "Charges the user's move gauge by 2 the first time it is in a pinch each battle.",
		energy: '8',
		orb: '96',
		level: '2',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 23,
		x: -1,
		y: 3,
		name: 'Defense 5',
		description: 'Defense 5',
		energy: '2',
		orb: '24',
		level: '2',
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 24,
		x: -2,
		y: 4,
		name: 'Enough!: Slippery 1',
		description: "Move: Enough! Raises the user's evasiveness by 1 stat rank when its move is successful.",
		energy: '7',
		orb: '84',
		level: '2',
		color: 'red',
		icon: 'passive'
	},
	{
		id: 25,
		x: -3,
		y: 5,
		name: 'Enough!: MP Refresh 2',
		description: "Move: Enough! Has a chance (30%) of restoring one MP of the user's move when that move is successful.",
		energy: '7',
		orb: '84',
		level: '3',
		color: 'red',
		icon: 'passive'
	},
	{
		id: 26,
		x: -1,
		y: 4,
		name: 'Team Sync Regen',
		description: 'Applies the Gradual Healing effect to all allied sync pairs after the user uses a sync move.',
		energy: '7',
		orb: '84',
		level: '3',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 27,
		x: 1,
		y: 1,
		name: 'Speed 5',
		description: 'Speed 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 28,
		x: 2,
		y: 1,
		name: 'Sp. Def 5',
		description: 'Sp. Def 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 29,
		x: 1,
		y: 2,
		name: 'Defense 5',
		description: 'Defense 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 30,
		x: 3,
		y: 1,
		name: 'HP 10',
		description: 'HP 10',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 31,
		x: 2,
		y: 2,
		name: 'Bite: Power 3',
		description: 'Bite: Power + 3',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'dark'
	},
	{
		id: 32,
		x: 1,
		y: 3,
		name: 'Bite: Power 3',
		description: 'Bite: Power + 3',
		energy: '3',
		orb: '36',
		level: '2',
		color: 'green',
		icon: 'dark'
	},
	{
		id: 33,
		x: 3,
		y: 2,
		name: 'Bite: Power 3',
		description: 'Bite: Power + 3',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'dark'
	},
	{
		id: 34,
		x: 2,
		y: 3,
		name: 'Bite: Move Gauge Refresh 3',
		description: "Move: Bite Has a chance (40%) of charging the user's move gauge by one when a move is successful.",
		energy: '7',
		orb: '84',
		level: '2',
		color: 'red',
		icon: 'passive'
	},
	{
		id: 35,
		x: 1,
		y: 4,
		name: 'Enough!: All Ramped Up 1',
		description: "Move: Enough! Raises the Sp. Atk of all allied sync pairs by 1 stat rank when the user's move is successful.",
		energy: '10',
		orb: '120',
		level: '3',
		color: 'red',
		icon: 'passive'
	},
	{
		id: 36,
		x: 3,
		y: 3,
		name: 'HP 30',
		description: 'HP 30',
		energy: '5',
		orb: '60',
		level: '2',
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 37,
		x: 2,
		y: 4,
		name: 'Catalyst',
		description: "Applies the Move Gauge Acceleration effect to the allied field of play the first time the user's sync move is used each battle.",
		energy: '10',
		orb: '120',
		level: '3',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 38,
		x: -2,
		y: 0,
		name: 'HP 10',
		description: 'HP 10',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 39,
		x: -1,
		y: -1,
		name: 'Speed 5',
		description: 'Speed 5',
		energy: '2',
		orb: '24',
		level: 1,
		color: 'blue',
		icon: 'stat'
	},
	{
		id: 40,
		x: -3,
		y: 0,
		name: 'Slash: Power 3',
		description: 'Slash: Power + 3',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'normal'
	},
	{
		id: 41,
		x: -2,
		y: -1,
		name: 'Slash: Power 3',
		description: 'Slash: Power + 3',
		energy: '3',
		orb: '36',
		level: 1,
		color: 'green',
		icon: 'normal'
	},
	{
		id: 42,
		x: -1,
		y: -2,
		name: 'Amped Up 1',
		description: "Raises the user's Speed by 1 stat rank when it lands a critical hit.",
		energy: '10',
		orb: '120',
		level: '2',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 43,
		x: -3,
		y: -1,
		name: 'Dire Hit All +: MP Refresh 2',
		description: "Move: Dire Hit All + Has a chance (30%) of restoring one MP of the user's move when that move is successful.",
		energy: '7',
		orb: '84',
		level: '2',
		color: 'red',
		icon: 'passive'
	},
	{
		id: 44,
		x: -2,
		y: -2,
		name: 'Quick Cure',
		description: 'Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.',
		energy: '7',
		orb: '84',
		level: '2',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 45,
		x: -1,
		y: -3,
		name: 'Safety Tether',
		description: 'Applies the Enduring effect to the user the first time its sync move is used each battle.',
		energy: '10',
		orb: '120',
		level: '3',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 46,
		x: -3,
		y: -2,
		name: 'First Aid 4',
		description: "Restores the user's HP by approximately 40% of its maximum HP the first time it is in a pinch each battle.",
		energy: '10',
		orb: '120',
		level: '3',
		color: 'yellow',
		icon: 'passive'
	},
	{
		id: 47,
		x: 0,
		y: -3,
		name: 'Perfectly Evil Normal Impact: Power 25',
		description: 'Perfectly Evil Normal Impact: Power + 25',
		energy: '5',
		orb: '60',
		level: '3',
		color: 'sync',
		icon: 'sync'
	},
	{
		id: 48,
		x: 0,
		y: 3,
		name: 'Perfectly Evil Normal Impact: Power 25',
		description: 'Perfectly Evil Normal Impact: Power + 25',
		energy: '5',
		orb: '60',
		level: '3',
		color: 'sync',
		icon: 'sync'
	}
]