export const SERENA_GRENINJA = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 1,
		"y": -2,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 2,
		"y": -3,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 1,
		"y": -3,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": 3,
		"y": -4,
		"name": "Unflappable",
		"description": "Prevents the user from flinching.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 11,
		"x": 2,
		"y": -4,
		"name": "Water Shuriken: Power 1",
		"description": "Water Shuriken: Power ↑ 1",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "water"
	},
	{
		"id": 12,
		"x": 1,
		"y": -4,
		"name": "Water Shuriken: Power 1",
		"description": "Water Shuriken: Power ↑ 1",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 13,
		"x": 3,
		"y": -5,
		"name": "Water Shuriken: Power 1",
		"description": "Water Shuriken: Power ↑ 1",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "water"
	},
	{
		"id": 14,
		"x": 2,
		"y": -5,
		"name": "Water Shuriken: Move Gauge Refresh 3",
		"description": "Move: Water Shuriken Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 1,
		"y": -5,
		"name": "Soften Up 1",
		"description": "Critical hits land more easily when the user attacks with a sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": 3,
		"y": -6,
		"name": "Vivid Water Shuriken: Power 25",
		"description": "Vivid Water Shuriken: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 17,
		"x": 2,
		"y": -6,
		"name": "Furious Brain",
		"description": "The more the user’s Sp. Atk is raised, the more it powers up the user’s moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": -2,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -3,
		"y": 2,
		"name": "Brutal Swing: Power 4",
		"description": "Brutal Swing: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 20,
		"x": -2,
		"y": 2,
		"name": "Brutal Swing: Power 4",
		"description": "Brutal Swing: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 21,
		"x": -3,
		"y": 3,
		"name": "Brutal Swing: Foul Fighting 5",
		"description": "Move: Brutal Swing Powers up the user’s moves against targets that are flinching, confused, or trapped.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 22,
		"x": -1,
		"y": 2,
		"name": "Brutal Swing: Power 4",
		"description": "Brutal Swing: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 23,
		"x": -2,
		"y": 3,
		"name": "Brutal Swing: Flabbergast 4",
		"description": "Move: Brutal Swing Has a chance (50%) of leaving the target confused when a move targeting that opponent is successful.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -3,
		"y": 4,
		"name": "Serious Night Slash: Power 25",
		"description": "Serious Night Slash: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 25,
		"x": -1,
		"y": 3,
		"name": "Brutal Swing: Superduper Effective 9",
		"description": "Move: Brutal Swing Powers up moves that are super effective.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -2,
		"y": 4,
		"name": "Brutal Swing: Move Gauge Refresh 9",
		"description": "Move: Brutal Swing Charges the user’s move gauge by one when its move is successful.",
		"energy": "9",
		"orb": "108",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": 2,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 3,
		"y": -1,
		"name": "B Quick Attack: Power 3",
		"description": "B Quick Attack: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 29,
		"x": 2,
		"y": 0,
		"name": "B Quick Attack: Power 3",
		"description": "B Quick Attack: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 30,
		"x": 1,
		"y": 1,
		"name": "Brutal Swing: Power 4",
		"description": "Brutal Swing: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 31,
		"x": 3,
		"y": 0,
		"name": "Umbral Acceleration 2",
		"description": "Quickly charges the move gauge when the zone is a Dark Zone.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 32,
		"x": 2,
		"y": 1,
		"name": "Umbral Healing 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action when the zone is a Dark Zone.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": 1,
		"y": 2,
		"name": "Brutal Swing: Defense Crush 9",
		"description": "Move: Brutal Swing Lowers the target’s Defense by one stat rank when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": 3,
		"y": 1,
		"name": "Glory of Tomorrow!: MP Refresh 2",
		"description": "Move: Glory of Tomorrow! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 2,
		"y": 2,
		"name": "Glory of Tomorrow!: Power Combo 9",
		"description": "Move: Glory of Tomorrow! Increases the user’s Physical Moves ↑ Next effect and Special Moves ↑ Next effect by 1 rank when its move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": -1,
		"y": -1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": -2,
		"y": -1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 38,
		"x": -1,
		"y": -2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -3,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": -2,
		"y": -2,
		"name": "B Quick Attack: Power 3",
		"description": "B Quick Attack: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 41,
		"x": -3,
		"y": -2,
		"name": "B Quick Attack: Power 3",
		"description": "B Quick Attack: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 42,
		"x": -1,
		"y": -3,
		"name": "Water Shuriken: Power 1",
		"description": "Water Shuriken: Power ↑ 1",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 43,
		"x": -2,
		"y": -3,
		"name": "Refreshing Rain 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action while the weather is rainy.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -3,
		"y": -3,
		"name": "Rainy Immunity",
		"description": "Status conditions cannot be inflicted on the user when the weather is rainy.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -1,
		"y": -4,
		"name": "Power Play",
		"description": "The more the target’s stats are lowered, the more it powers up the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -2,
		"y": -4,
		"name": "Water Shuriken: Rainy Mind-Blowing Strike 2",
		"description": "Move: Water Shuriken Has a chance (30%) of lowering the target’s Sp. Def by 1 stat rank when the user’s attack move against it hits while the weather is rainy. If the move has the multistrike effect tag and the weather is rainy, has a chance (30%) of lowering the target’s Sp. Def by 1 stat rank for each hit.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "Vivid Water Shuriken: Power 50",
		"description": "Vivid Water Shuriken: Power ↑ 50",
		"energy": "7",
		"orb": "84",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "Serious Night Slash: Power 50",
		"description": "Serious Night Slash: Power ↑ 50",
		"energy": "7",
		"orb": "84",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const CALEM_GRENINJA = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 1,
		"y": -2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 2,
		"y": -3,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 1,
		"y": -3,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": 3,
		"y": -4,
		"name": "Brutal Swing: Power 4",
		"description": "Brutal Swing: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 11,
		"x": 2,
		"y": -4,
		"name": "Brutal Swing: Move Gauge Refresh 3",
		"description": "Move: Brutal Swing Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 12,
		"x": 1,
		"y": -4,
		"name": "Brutal Swing: Power 4",
		"description": "Brutal Swing: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 13,
		"x": 3,
		"y": -5,
		"name": "Brutal Swing: Power 4",
		"description": "Brutal Swing: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 14,
		"x": 2,
		"y": -5,
		"name": "Brutal Swing: Flabbergast 4",
		"description": "Move: Brutal Swing Has a chance (50%) of leaving the target confused when a move targeting that opponent is successful.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 1,
		"y": -5,
		"name": "Team Mighty Sync 9",
		"description": "Once per battle, increases the Physical Moves ↑ Next effect of all allied sync pairs by 1 rank after using the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": 3,
		"y": -6,
		"name": "Umbral Tenacity",
		"description": "Prevents the user from flinching, becoming confused, or becoming trapped when the zone is a Dark Zone.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": 2,
		"y": -6,
		"name": "Team Umbral Restoration 9",
		"description": "Restores the HP of all allied sync pairs when the user uses a move while the zone is a Dark Zone.",
		"energy": "8",
		"orb": "96",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": -2,
		"y": 2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -3,
		"y": 3,
		"name": "Unflappable",
		"description": "Prevents the user from flinching.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 20,
		"x": -1,
		"y": 2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 21,
		"x": -2,
		"y": 3,
		"name": "Water Shuriken: Power 1",
		"description": "Water Shuriken: Power ↑ 1",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "water"
	},
	{
		"id": 22,
		"x": -3,
		"y": 4,
		"name": "HP 20",
		"description": "HP 20",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 23,
		"x": -1,
		"y": 3,
		"name": "Water Shuriken: Power 1",
		"description": "Water Shuriken: Power ↑ 1",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 24,
		"x": -2,
		"y": 4,
		"name": "First Aid 4",
		"description": "Restores the user’s HP by approximately 40% of its maximum HP the first time it is in a pinch each battle.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": -3,
		"y": 5,
		"name": "Team Safe Start",
		"description": "Applies the Enduring effect to all allied sync pairs the first time the user enters a battle each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -1,
		"y": 4,
		"name": "Queue Cutter 2",
		"description": "Has a chance (30%) of reducing the user’s sync move countdown by one when an opponent’s attack move targeting the user misses.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": 1,
		"y": 1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 2,
		"y": 1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": 1,
		"y": 2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": 3,
		"y": 1,
		"name": "Water Shuriken: Power 1",
		"description": "Water Shuriken: Power ↑ 1",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "water"
	},
	{
		"id": 31,
		"x": 2,
		"y": 2,
		"name": "Water Shuriken: Move Gauge Refresh 3",
		"description": "Move: Water Shuriken Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 32,
		"x": 1,
		"y": 3,
		"name": "Water Shuriken: Power 1",
		"description": "Water Shuriken: Power ↑ 1",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 33,
		"x": 3,
		"y": 2,
		"name": "Water Shuriken: Power 1",
		"description": "Water Shuriken: Power ↑ 1",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "water"
	},
	{
		"id": 34,
		"x": 2,
		"y": 3,
		"name": "Racing Rain 2",
		"description": "Quickly charges the move gauge when the weather is rainy.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 1,
		"y": 4,
		"name": "Team Sync Think 9",
		"description": "Once per battle, increases the Special Moves ↑ Next effect of all allied sync pairs by one rank after using the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": 3,
		"y": 3,
		"name": "Water Shuriken: Guaranteed Triple",
		"description": "Move: Water Shuriken Increases the number of times the user hits with a move that has the multistrike effect tag to three or more when that move is successful.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": 2,
		"y": 4,
		"name": "Rain Gear 2",
		"description": "Reduces damage when the user is hit by an attack move while the weather is rainy.",
		"energy": "8",
		"orb": "96",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": -2,
		"y": 0,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -1,
		"y": -1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": -3,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 41,
		"x": -2,
		"y": -1,
		"name": "Brutal Swing: Power 4",
		"description": "Brutal Swing: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 42,
		"x": -1,
		"y": -2,
		"name": "Brutal Swing: Power 4",
		"description": "Brutal Swing: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 43,
		"x": -3,
		"y": -1,
		"name": "Glory of Understanding!: MP Refresh 2",
		"description": "Move: Glory of Understanding! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -2,
		"y": -2,
		"name": "Group Fortification 9",
		"description": "Raises the Defense, Sp. Def—or both—of all allied sync pairs by 1 stat rank when an opponent’s attack move targeting the user misses.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -1,
		"y": -3,
		"name": "Glory of Understanding!: Propulsion 9",
		"description": "Move: Glory of Understanding! Reduces the user’s sync move countdown by one when its move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -3,
		"y": -2,
		"name": "Glory of Understanding!: Critical Squad 1",
		"description": "Move: Glory of Understanding! Raises the critical-hit rate of all allied sync pairs by 1 stat rank when the user’s move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "Shrouded Night Slash: Power 50",
		"description": "Shrouded Night Slash: Power ↑ 50",
		"energy": "7",
		"orb": "84",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "Unseen Water Shuriken: Power 50",
		"description": "Unseen Water Shuriken: Power ↑ 50",
		"energy": "7",
		"orb": "84",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const SERENA_FLETCHLING = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 1,
		"y": -2,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 2,
		"y": -3,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 1,
		"y": -3,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": 3,
		"y": -4,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": 2,
		"y": -4,
		"name": "Peck: Power 3",
		"description": "Peck: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 12,
		"x": 1,
		"y": -4,
		"name": "Peck: Power 3",
		"description": "Peck: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 13,
		"x": 3,
		"y": -5,
		"name": "Peck: Power 3",
		"description": "Peck: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 14,
		"x": 2,
		"y": -5,
		"name": "Peck: Move Gauge Refresh 3",
		"description": "Move: Peck Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 1,
		"y": -5,
		"name": "Cakewalk",
		"description": "The more the target’s Speed is lowered, the more it powers up the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": 3,
		"y": -6,
		"name": "Superduper Effective 2",
		"description": "Powers up moves that are super effective.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": 2,
		"y": -6,
		"name": "Unfortuitous 4",
		"description": "Has a chance (50%) of lowering one of the target’s following stats by one stat rank at random when the user’s attack move against it is successful: Attack, Defense, Sp. Atk, Sp. Def, Speed, accuracy, or evasiveness.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": -2,
		"y": 1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -3,
		"y": 2,
		"name": "Unbending",
		"description": "Defense cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 20,
		"x": -2,
		"y": 2,
		"name": "Peck: Power 3",
		"description": "Peck: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 21,
		"x": -3,
		"y": 3,
		"name": "HP 20",
		"description": "HP 20",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 22,
		"x": -1,
		"y": 2,
		"name": "Peck: Power 3",
		"description": "Peck: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 23,
		"x": -2,
		"y": 3,
		"name": "Let’s Begin!: Move Gauge Refresh 3",
		"description": "Move: Let’s Begin! Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -3,
		"y": 4,
		"name": "Dominating Sync 2",
		"description": "Powers up the user’s sync move when the target’s Attack is lowered.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": -1,
		"y": 3,
		"name": "Let’s Begin!: Hit and Heal 9",
		"description": "Move: Let’s Begin! Applies the Gradual Healing effect to the user when its move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -2,
		"y": 4,
		"name": "Let’s Begin!: MP Refresh 2",
		"description": "Move: Let’s Begin! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": 2,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 3,
		"y": -1,
		"name": "Flameproof",
		"description": "Prevents the user from getting burned.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": 2,
		"y": 0,
		"name": "Flame Charge: Power 3",
		"description": "Flame Charge: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 30,
		"x": 1,
		"y": 1,
		"name": "Flame Charge: Power 3",
		"description": "Flame Charge: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 31,
		"x": 3,
		"y": 0,
		"name": "Flame Charge: Power 3",
		"description": "Flame Charge: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 32,
		"x": 2,
		"y": 1,
		"name": "Flame Charge: Move Gauge Refresh 3",
		"description": "Move: Flame Charge Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": 1,
		"y": 2,
		"name": "Let’s Begin!: Slippery 1",
		"description": "Move: Let’s Begin! Raises the user’s evasiveness by 1 stat rank when its move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": 3,
		"y": 1,
		"name": "Speed 10",
		"description": "Speed 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 35,
		"x": 2,
		"y": 2,
		"name": "Scorching Touch 4",
		"description": "Has a chance (50%) of leaving the target burned when the user’s attack move against it is successful.",
		"energy": "7",
		"orb": "84",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": -1,
		"y": -1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": -2,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 38,
		"x": -1,
		"y": -2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -3,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": -2,
		"y": -2,
		"name": "Flame Charge: Power 3",
		"description": "Flame Charge: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 41,
		"x": -3,
		"y": -2,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 42,
		"x": -1,
		"y": -3,
		"name": "Flame Charge: Power 3",
		"description": "Flame Charge: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 43,
		"x": -2,
		"y": -3,
		"name": "Dire Hit +: Move Gauge Refresh 3",
		"description": "Move: Dire Hit + Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -3,
		"y": -3,
		"name": "Dire Hit +: MP Refresh 2",
		"description": "Move: Dire Hit + Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -1,
		"y": -4,
		"name": "Flame Charge: Fast-Track 9",
		"description": "Move: Flame Charge Raises the user’s Speed by one stat rank after its Pokémon uses a move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -2,
		"y": -4,
		"name": "Quick Tempo",
		"description": "Applies the Move Gauge Acceleration effect to the allied field of play the first time the user enters a battle each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "First Flight Flying Impact: Power 25",
		"description": "First Flight Flying Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "First Flight Flying Impact: Power 25",
		"description": "First Flight Flying Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const JASMINE_AMHPAROS = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 1,
		"y": -2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 2,
		"y": -3,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 1,
		"y": -3,
		"name": "Thunder Shock: Power 4",
		"description": "Thunder Shock: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 10,
		"x": 3,
		"y": -4,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": 2,
		"y": -4,
		"name": "Thunder Shock: Move Gauge Refresh 3",
		"description": "Move: Thunder Shock Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 12,
		"x": 1,
		"y": -4,
		"name": "Turbo Charge 2",
		"description": "Quickly charges the move gauge when the field is Electric Terrain.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": 3,
		"y": -5,
		"name": "Thunder Shock: Power 4",
		"description": "Thunder Shock: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 14,
		"x": 2,
		"y": -5,
		"name": "Thunder Shock: Hostile Environment 2",
		"description": "Move: Thunder Shock Raises the chance of inflicting status conditions with the additional effects of moves.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 1,
		"y": -5,
		"name": "Static Cling 9",
		"description": "Leaves an opponent that attacked the user paralyzed when the user is hit by an attack move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": 3,
		"y": -6,
		"name": "Shock Recovery 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action when the terrain is Electric Terrain.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": 2,
		"y": -6,
		"name": "Team Shout 4",
		"description": "Has a chance (50%) of raising the Attack or Sp. Atk—or both—of all allied sync pairs by one stat rank when the user is hit by an attack move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": -2,
		"y": 2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -3,
		"y": 3,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": -1,
		"y": 2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 21,
		"x": -2,
		"y": 3,
		"name": "Thunder Shock: Power 4",
		"description": "Thunder Shock: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 22,
		"x": -3,
		"y": 4,
		"name": "Unbending",
		"description": "Defense cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 23,
		"x": -1,
		"y": 3,
		"name": "Stalwart",
		"description": "Sp. Def cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -2,
		"y": 4,
		"name": "Super Effective ↑: MP Refresh 2",
		"description": "Move: Super Effective ↑ Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": -3,
		"y": 5,
		"name": "Adrenaline 1",
		"description": "Reduces the sync move countdown by 1 the first time the user’s sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -1,
		"y": 4,
		"name": "Catalyst",
		"description": "Applies the Move Gauge Acceleration effect to the allied field of play the first time the user’s sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": 1,
		"y": 1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 2,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": 1,
		"y": 2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": 3,
		"y": 1,
		"name": "Lithe",
		"description": "Prevents the user from getting paralyzed.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": 2,
		"y": 2,
		"name": "Thunder Shock: Power 4",
		"description": "Thunder Shock: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 32,
		"x": 1,
		"y": 3,
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": 3,
		"y": 2,
		"name": "HP 40",
		"description": "HP 40",
		"energy": "7",
		"orb": "84",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": 2,
		"y": 3,
		"name": "Potion: Master Healer 1",
		"description": "Move: Potion Increases the amount of HP restored by the user’s healing moves.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 1,
		"y": 4,
		"name": "Potion: MP Refresh 2",
		"description": "Move: Potion Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": 3,
		"y": 3,
		"name": "Potion: MP Refresh 2",
		"description": "Move: Potion Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": 2,
		"y": 4,
		"name": "Potion: Master Healer 1",
		"description": "Move: Potion Increases the amount of HP restored by the user’s healing moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": -2,
		"y": 0,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -1,
		"y": -1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": -3,
		"y": 0,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 41,
		"x": -2,
		"y": -1,
		"name": "Thunder Shock: Power 4",
		"description": "Thunder Shock: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 42,
		"x": -1,
		"y": -2,
		"name": "Team Fierce Entry 1",
		"description": "Raises the Attack of all allied sync pairs by 1 stat rank when the user enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": -3,
		"y": -1,
		"name": "Team Grand Entry 1",
		"description": "Raises the Sp. Atk of all allied sync pairs by 1 stat rank when the user enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -2,
		"y": -2,
		"name": "Comforting Light!: MP Refresh 2",
		"description": "Move: Comforting Light! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -1,
		"y": -3,
		"name": "Comforting Light!: Mighty Friend 9",
		"description": "Move: Comforting Light! When the user’s move targeting an allied sync pair (excluding field effects) is successful, increases the Physical Moves ↑ Next effect of the allied sync pair affected by the move by one rank.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -3,
		"y": -2,
		"name": "Comforting Light!: Clever Friend 9",
		"description": "Move: Comforting Light! When the user’s move targeting an allied sync pair (excluding field effects) is successful, increases the Special Moves ↑ Next effect of the allied sync pair affected by the move by 1 rank.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "Snowy Night’s Guide Electric Beam: Power 25",
		"description": "Snowy Night’s Guide Electric Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "Snowy Night’s Guide Electric Beam: Power 25",
		"description": "Snowy Night’s Guide Electric Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const WHITNEY_SAWSBUCK = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 1,
		"y": -2,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 2,
		"y": -3,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 1,
		"y": -3,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": 3,
		"y": -4,
		"name": "Headbutt: Power 3",
		"description": "Headbutt: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 11,
		"x": 2,
		"y": -4,
		"name": "Headbutt: Move Gauge Refresh 3",
		"description": "Move: Headbutt Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 12,
		"x": 1,
		"y": -4,
		"name": "Headbutt: Power 3",
		"description": "Headbutt: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 13,
		"x": 3,
		"y": -5,
		"name": "Headbutt: Power 3",
		"description": "Headbutt: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 14,
		"x": 2,
		"y": -5,
		"name": "Mad Strength 9",
		"description": "Raises the user’s Attack by one stat rank when its attack move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 1,
		"y": -5,
		"name": "Terrain Sync-Up 9",
		"description": "Powers up the user’s sync move when a terrain is in effect.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": 3,
		"y": -6,
		"name": "Speed 20",
		"description": "Speed 20",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 17,
		"x": 2,
		"y": -6,
		"name": "Headbutt: Aggravation 1",
		"description": "Move: Headbutt Raises the chance of inflicting the flinching, confused, or trapped condition with the additional effects of moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": -2,
		"y": 1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -3,
		"y": 2,
		"name": "Horn Leech: Power 3",
		"description": "Horn Leech: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 20,
		"x": -2,
		"y": 2,
		"name": "Horn Leech: Move Gauge Refresh 3",
		"description": "Move: Horn Leech Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 21,
		"x": -3,
		"y": 3,
		"name": "Horn Leech: Power 3",
		"description": "Horn Leech: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 22,
		"x": -1,
		"y": 2,
		"name": "Horn Leech: Power 3",
		"description": "Horn Leech: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 23,
		"x": -2,
		"y": 3,
		"name": "Turbo Turf 2",
		"description": "Quickly charges the move gauge when the terrain is Grassy Terrain.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -3,
		"y": 4,
		"name": "Verdant Recovery 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action when the terrain is Grassy Terrain.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": -1,
		"y": 3,
		"name": "Sharp Entry 1",
		"description": "Raises the user’s critical-hit rate by 1 stat rank when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -2,
		"y": 4,
		"name": "Empowering Overgrowth 3",
		"description": "Powers up the user’s moves when the terrain is Grassy Terrain.",
		"energy": "7",
		"orb": "84",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": 2,
		"y": -1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 3,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": 2,
		"y": 0,
		"name": "Horn Leech: Power 3",
		"description": "Horn Leech: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 30,
		"x": 1,
		"y": 1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 31,
		"x": 3,
		"y": 0,
		"name": "Weird Recovery 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action when the terrain is Psychic Terrain.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 32,
		"x": 2,
		"y": 1,
		"name": "Precognition 2",
		"description": "Quickly charges the user’s move gauge when the terrain is Psychic Terrain.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": 1,
		"y": 2,
		"name": "Interference Sync 9",
		"description": "Powers up the user’s sync move against targets that are flinching, confused, or trapped.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": 3,
		"y": 1,
		"name": "Flabbergast 4",
		"description": "Has a chance (50%) of leaving the target confused when a move targeting that opponent is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 2,
		"y": 2,
		"name": "Mind Boggler 9",
		"description": "Lowers the target’s Sp. Def by one stat rank when the user’s attack move is successful against a flinching, confused, or trapped opponent.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": -1,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": -2,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 38,
		"x": -1,
		"y": -2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -3,
		"y": -1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": -2,
		"y": -2,
		"name": "Headbutt: Power 3",
		"description": "Headbutt: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 41,
		"x": -3,
		"y": -2,
		"name": "Move Gauge Boost: MP Refresh 2",
		"description": "Move: Move Gauge Boost Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 42,
		"x": -1,
		"y": -3,
		"name": "Shock Recovery 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action when the terrain is Electric Terrain.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": -2,
		"y": -3,
		"name": "Turbo Charge 2",
		"description": "Quickly charges the move gauge when the field is Electric Terrain.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -3,
		"y": -3,
		"name": "Move Gauge Boost: Pep Rally 1",
		"description": "Move: Move Gauge Boost Raises the Speed of all allied sync pairs by 1 stat rank when the user’s move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -1,
		"y": -4,
		"name": "Team Charged Slo-mo 9",
		"description": "Lowers the Speed of all opposing sync pairs by 1 stat rank when the user’s attack move is successful while the terrain is Electric Terrain.",
		"energy": "7",
		"orb": "84",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -2,
		"y": -4,
		"name": "Sync Burst 1",
		"description": "Restores 1 MP for the user the first time its sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "Indomitable Happiness Normal Impact: Power 25",
		"description": "Indomitable Happiness Normal Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "Indomitable Happiness Normal Impact: Power 25",
		"description": "Indomitable Happiness Normal Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]