export const AS_KORRINA_LUCARIO = [
	{
		"id": 1,
		"x": "1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "1",
		"y": "0",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "-1",
		"y": "1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "-1",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "0",
		"y": "-2",
		"name": "HP +40",
		"description": "HP +40",
		"energy": "0",
		"orb": "5",
		"level": "2",
		"color": "divine",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": "0",
		"y": "-3",
		"name": "Fervent Fighter Divine Power-Up Punch: Power +50",
		"description": "Fervent Fighter Divine Power-Up Punch: Power +50",
		"energy": "0",
		"orb": "5",
		"level": "3",
		"color": "divine",
		"icon": "sync"
	},
	{
		"id": 9,
		"x": "0",
		"y": "-4",
		"name": "Team Sharp Entry 3",
		"description": "Raises the critical-hit rate of all allied sync pairs by three stat ranks when the user enters a battle.",
		"energy": "0",
		"orb": "5",
		"level": "4",
		"color": "divine",
		"icon": "passive"
	},
	{
		"id": 10,
		"x": "0",
		"y": "-5",
		"name": "1st S-Move: Fighting Z ｜ Fighting Z: Team Crit Immun.",
		"description": "Turns the field of play’s zone into a Fighting Zone the first time the user’s sync move is used each battle. (A Fighting Zone powers up Fighting-type attacks.) Protects all allied sync pairs against critical hits when the zone is a Fighting Zone.",
		"energy": "0",
		"orb": "5",
		"level": "5",
		"color": "divine",
		"icon": "passive"
	},
	{
		"id": 11,
		"x": "1",
		"y": "-2",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 12,
		"x": "2",
		"y": "-2",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 13,
		"x": "3",
		"y": "-2",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 14,
		"x": "2",
		"y": "-3",
		"name": "Sand Shelter",
		"description": "Protects the user from damage from a sandstorm.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": "3",
		"y": "-3",
		"name": "Antitoxin",
		"description": "Prevents the user from getting poisoned or badly poisoned.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": "2",
		"y": "-4",
		"name": "Waiting to Skate On Through!: Slippery 1",
		"description": "Raises the user’s evasiveness by one stat rank when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": "3",
		"y": "-4",
		"name": "Brawling Healing 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action when the zone is a Fighting Zone.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": "3",
		"y": "-5",
		"name": "Circle: Attack Move DR 2",
		"description": "Reduces damage when the user is hit by an attack move while a circle applies to the allied field of play.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 19,
		"x": "1",
		"y": "-4",
		"name": "Almighty Aura Sphere: 1st “Almighty Aura Sphere” MP 0: Kalos C (Spec) on Field",
		"description": "Applies Kalos Circle (Special) to the allied field of play the first time the remaining MP for the user’s AlmightyAura Sphere is zero each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 20,
		"x": "2",
		"y": "-5",
		"name": "Kalos C (Spec) Extension 3",
		"description": "Extends the duration of Kalos Circle (Special) when Kalos Circle (Special) is applied to the allied field of play.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 21,
		"x": "-2",
		"y": "2",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 22,
		"x": "-1",
		"y": "2",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 23,
		"x": "-2",
		"y": "3",
		"name": "Almighty Rock Smash: Power +2",
		"description": "Almighty Rock Smash: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 24,
		"x": "-1",
		"y": "3",
		"name": "Almighty Rock Smash: Power +2",
		"description": "Almighty Rock Smash: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 25,
		"x": "-1",
		"y": "4",
		"name": "Almighty Rock Smash: Power +2",
		"description": "Almighty Rock Smash: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 26,
		"x": "-3",
		"y": "3",
		"name": "Almighty Rock Smash: Power +2",
		"description": "Almighty Rock Smash: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 27,
		"x": "-3",
		"y": "4",
		"name": "Almighty Rock Smash: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 28,
		"x": "-2",
		"y": "4",
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": "-3",
		"y": "5",
		"name": "Hit: Team Attack ↑2 9",
		"description": "Raises the Attack of all allied sync pairs by two stat ranks when the user’s attack move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 30,
		"x": "-2",
		"y": "5",
		"name": "Overwhelm 9",
		"description": "Lowers the target’s Attack by one stat rank when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": "2",
		"y": "0",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 32,
		"x": "1",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 33,
		"x": "2",
		"y": "1",
		"name": "Almighty Aura Sphere: Power +2",
		"description": "Almighty Aura Sphere: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 34,
		"x": "1",
		"y": "2",
		"name": "Almighty Aura Sphere: Power +2",
		"description": "Almighty Aura Sphere: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 35,
		"x": "1",
		"y": "3",
		"name": "Almighty Aura Sphere: Power +2",
		"description": "Almighty Aura Sphere: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 36,
		"x": "3",
		"y": "0",
		"name": "Almighty Aura Sphere: Power +2",
		"description": "Almighty Aura Sphere: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 37,
		"x": "3",
		"y": "1",
		"name": "Almighty Aura Sphere: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": "2",
		"y": "2",
		"name": "Brawling Acceleration 2",
		"description": "Quickly charges the move gauge when the zone is a Fighting Zone.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 39,
		"x": "3",
		"y": "2",
		"name": "Hit: Team Sp. Atk ↑2 9",
		"description": "Raises the Sp. Atk of all allied sync pairs by two stat ranks when the user’s attack move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": "2",
		"y": "3",
		"name": "Satisfied Snicker 9",
		"description": "Lowers the target’s Sp. Atk by one stat rank when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 41,
		"x": "-2",
		"y": "0",
		"name": "Drain Punch: Power +4",
		"description": "Drain Punch: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 42,
		"x": "-1",
		"y": "-1",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 43,
		"x": "-3",
		"y": "1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 44,
		"x": "-3",
		"y": "0",
		"name": "Drain Punch: Power +4",
		"description": "Drain Punch: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 45,
		"x": "-2",
		"y": "-1",
		"name": "Drain Punch: Power +4",
		"description": "Drain Punch: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 46,
		"x": "-3",
		"y": "-1",
		"name": "Drain Punch: Power +4",
		"description": "Drain Punch: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 47,
		"x": "-2",
		"y": "-2",
		"name": "Drain Punch: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 48,
		"x": "-3",
		"y": "-2",
		"name": "Team Speedy Entry 2",
		"description": "Raises the Speed of all allied sync pairs by two stat ranks when the user enters a battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 49,
		"x": "-1",
		"y": "-3",
		"name": "Almighty Rock Smash: 1st “Almighty Rock Smash” MP 0: Kalos C (Phys) on Field",
		"description": "Applies Kalos Circle (Physical) to the allied field of play the first time the remaining MP for the user’s AlmightyRock Smash is zero each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 50,
		"x": "-2",
		"y": "-3",
		"name": "Kalos C (Phys) Extension 3",
		"description": "Extends the duration of Kalos Circle (Physical) when Kalos Circle (Physical) is applied to the allied field of play.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 51,
		"x": "3",
		"y": "-1",
		"name": "Fervent Fighter Divine Power-Up Punch: Power +25",
		"description": "Fervent Fighter Divine Power-Up Punch: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 52,
		"x": "-3",
		"y": "2",
		"name": "Fervent Fighter Divine Power-Up Punch: Power +25",
		"description": "Fervent Fighter Divine Power-Up Punch: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const INGO_BOLDORE = [
	{
		"id": 1,
		"x": "1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "1",
		"y": "0",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "-1",
		"y": "1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "-1",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "1",
		"y": "-2",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": "2",
		"y": "-3",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": "1",
		"y": "-3",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": "3",
		"y": "-4",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": "2",
		"y": "-4",
		"name": "Rock Tomb: Power +4",
		"description": "Rock Tomb: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 12,
		"x": "1",
		"y": "-4",
		"name": "Rock Tomb: Power +4",
		"description": "Rock Tomb: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 13,
		"x": "3",
		"y": "-5",
		"name": "Rock Tomb: Power +4",
		"description": "Rock Tomb: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 14,
		"x": "2",
		"y": "-5",
		"name": "Rock Tomb: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": "1",
		"y": "-5",
		"name": "Sp. Def +20",
		"description": "Sp. Def +20",
		"energy": "7",
		"orb": "84",
		"level": "3",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 16,
		"x": "3",
		"y": "-6",
		"name": "Defense +10",
		"description": "Defense +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 17,
		"x": "2",
		"y": "-6",
		"name": "Overwhelm 9",
		"description": "Lowers the target’s Attack by one stat rank when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": "-2",
		"y": "2",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": "-3",
		"y": "3",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": "-1",
		"y": "2",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 21,
		"x": "-2",
		"y": "3",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 22,
		"x": "-3",
		"y": "4",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 23,
		"x": "-1",
		"y": "3",
		"name": "X Regen All: Fleet Feet 1",
		"description": "Raises the user’s Speed by one stat rank when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": "-2",
		"y": "4",
		"name": "X Regen All: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": "-3",
		"y": "5",
		"name": "Triage Tank 9",
		"description": "Restores the user’s HP when it is hit by an attack move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": "-1",
		"y": "4",
		"name": "Toughen Up 9",
		"description": "Raises the user’s Defense by one stat rank when it is hit by an attack move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": "1",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": "2",
		"y": "1",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": "1",
		"y": "2",
		"name": "Sand Shelter",
		"description": "Protects the user from damage from a sandstorm.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 30,
		"x": "3",
		"y": "1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 31,
		"x": "2",
		"y": "2",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 32,
		"x": "1",
		"y": "3",
		"name": "On the Run 1",
		"description": "Raises the user’s evasiveness by one stat rank the first time it is in a pinch each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": "3",
		"y": "2",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": "2",
		"y": "3",
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": "1",
		"y": "4",
		"name": "Block and Heal 9",
		"description": "Restores the user’s HP by approximately 20% of its maximum HP when the user nullifies an opponent’s move while in a defensive posture.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": "3",
		"y": "3",
		"name": "Block and Charge 1",
		"description": "Charges the user’s move gauge by one when it nullifies an opponent’s move while in a defensive posture.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": "2",
		"y": "4",
		"name": "Wide Guard: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": "-2",
		"y": "0",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": "-1",
		"y": "-1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": "-3",
		"y": "0",
		"name": "Rock Tomb: Power +4",
		"description": "Rock Tomb: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 41,
		"x": "-2",
		"y": "-1",
		"name": "Rock Tomb: Power +4",
		"description": "Rock Tomb: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 42,
		"x": "-1",
		"y": "-2",
		"name": "HP +20",
		"description": "HP +20",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 43,
		"x": "-3",
		"y": "-1",
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": "-2",
		"y": "-2",
		"name": "Please Stand Back!: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": "-1",
		"y": "-3",
		"name": "Quick Tempo",
		"description": "Applies the Move Gauge Acceleration effect to the allied field of play the first time the user enters a battle each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": "-3",
		"y": "-2",
		"name": "Interference Immunity",
		"description": "Prevents the user from flinching, becoming confused, or becoming trapped.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": "0",
		"y": "-3",
		"name": "Train to the Top Rock Impact: Power +25",
		"description": "Train to the Top Rock Impact: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": "0",
		"y": "3",
		"name": "Train to the Top Rock Impact: Power +25",
		"description": "Train to the Top Rock Impact: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const AS_SABRINA_ALAKAZAM = [
	{
		"id": 1,
		"x": "1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "1",
		"y": "0",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "-1",
		"y": "1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "-1",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "0",
		"y": "-2",
		"name": "Sp. Atk +20",
		"description": "Sp. Atk +20",
		"energy": "0",
		"orb": "5",
		"level": "2",
		"color": "divine",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": "0",
		"y": "-3",
		"name": "Prescient Divine Psywave: Power +50",
		"description": "Prescient Divine Psywave: Power +50",
		"energy": "0",
		"orb": "5",
		"level": "3",
		"color": "divine",
		"icon": "sync"
	},
	{
		"id": 9,
		"x": "0",
		"y": "-4",
		"name": "Kanto C (Spec) Extension 5",
		"description": "Extends the duration of Kanto Circle (Special) when Kanto Circle (Special) is applied to the allied field of play.",
		"energy": "0",
		"orb": "5",
		"level": "4",
		"color": "divine",
		"icon": "passive"
	},
	{
		"id": 10,
		"x": "0",
		"y": "-5",
		"name": "Almighty Psychic: 1st Move: Restore MP 1",
		"description": "Restores one MP of the user’s move the first time that move is successful each battle.",
		"energy": "0",
		"orb": "5",
		"level": "5",
		"color": "divine",
		"icon": "passive"
	},
	{
		"id": 11,
		"x": "1",
		"y": "-2",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 12,
		"x": "2",
		"y": "-2",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 13,
		"x": "3",
		"y": "-2",
		"name": "Almighty Psybeam: Power +2",
		"description": "Almighty Psybeam: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "psychic"
	},
	{
		"id": 14,
		"x": "2",
		"y": "-3",
		"name": "Almighty Psybeam: Power +2",
		"description": "Almighty Psybeam: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "psychic"
	},
	{
		"id": 15,
		"x": "3",
		"y": "-3",
		"name": "Almighty Psybeam: Power +2",
		"description": "Almighty Psybeam: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "psychic"
	},
	{
		"id": 16,
		"x": "2",
		"y": "-4",
		"name": "Sp. Atk +10",
		"description": "Sp. Atk +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 17,
		"x": "3",
		"y": "-4",
		"name": "Weird Recovery 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action when the terrain is Psychic Terrain.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": "3",
		"y": "-5",
		"name": "Precognition 2",
		"description": "Quickly charges the user’s move gauge when the terrain is Psychic Terrain.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 19,
		"x": "1",
		"y": "-4",
		"name": "Almighty Psychic: Move: Physical & Special DR on Field 9",
		"description": "Applies the Physical Damage Reduction effect and the Special Damage Reduction effect to the allied field of play when the user’s move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 20,
		"x": "2",
		"y": "-5",
		"name": "Confusion Synergy 3",
		"description": "Powers up the user’s moves when the target is confused.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 21,
		"x": "-2",
		"y": "2",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 22,
		"x": "-1",
		"y": "2",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 23,
		"x": "-2",
		"y": "3",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 24,
		"x": "-1",
		"y": "3",
		"name": "Almighty Psychic: Power +2",
		"description": "Almighty Psychic: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "psychic"
	},
	{
		"id": 25,
		"x": "-1",
		"y": "4",
		"name": "Almighty Psychic: Power +2",
		"description": "Almighty Psychic: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "psychic"
	},
	{
		"id": 26,
		"x": "-3",
		"y": "3",
		"name": "Almighty Psychic: Power +2",
		"description": "Almighty Psychic: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "psychic"
	},
	{
		"id": 27,
		"x": "-3",
		"y": "4",
		"name": "Speed +10",
		"description": "Speed +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": "-2",
		"y": "4",
		"name": "Quick Tempo",
		"description": "Applies the Move Gauge Acceleration effect to the allied field of play the first time the user enters a battle each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": "-3",
		"y": "5",
		"name": "Entry: Special Boost 2",
		"description": "Increases the user’s Special Moves ↑ Next effect by two ranks when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 30,
		"x": "-2",
		"y": "5",
		"name": "Staggering 9",
		"description": "Makes the target flinch when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": "2",
		"y": "0",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 32,
		"x": "1",
		"y": "1",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 33,
		"x": "2",
		"y": "1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": "1",
		"y": "2",
		"name": "Almighty Psychic: Power +2",
		"description": "Almighty Psychic: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "psychic"
	},
	{
		"id": 35,
		"x": "1",
		"y": "3",
		"name": "Almighty Psychic: Power +2",
		"description": "Almighty Psychic: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "psychic"
	},
	{
		"id": 36,
		"x": "3",
		"y": "0",
		"name": "Almighty Psychic: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": "3",
		"y": "1",
		"name": "Circle: MG → 2",
		"description": "Quickly charges the move gauge when a circle applies to the allied field of play.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": "2",
		"y": "2",
		"name": "Potion: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 39,
		"x": "3",
		"y": "2",
		"name": "Potion: Master Healer 1",
		"description": "Increases the amount of HP restored by the user’s healing moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": "2",
		"y": "3",
		"name": "Physical & Special DR Extension 5",
		"description": "Extends the duration of the Physical Damage Reduction effect when the Physical Damage Reduction effect is applied to the allied field of play. Extends the duration of the Special Damage Reduction effect when the Special Damage Reduction effect is applied to the allied field of play.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 41,
		"x": "-2",
		"y": "0",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 42,
		"x": "-1",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 43,
		"x": "-3",
		"y": "1",
		"name": "Unflappable",
		"description": "Prevents the user from flinching.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": "-3",
		"y": "0",
		"name": "Almighty Psybeam: Power +2",
		"description": "Almighty Psybeam: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "psychic"
	},
	{
		"id": 45,
		"x": "-2",
		"y": "-1",
		"name": "Almighty Psybeam: Power +2",
		"description": "Almighty Psybeam: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "psychic"
	},
	{
		"id": 46,
		"x": "-3",
		"y": "-1",
		"name": "Almighty Psybeam: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": "-2",
		"y": "-2",
		"name": "Speed +10",
		"description": "Speed +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 48,
		"x": "-3",
		"y": "-2",
		"name": "Our Sixth Sense!: Move: Sync Move Boost ↑3 9",
		"description": "Increases the user’s Sync Move ↑ Next effect by three ranks when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 49,
		"x": "-1",
		"y": "-3",
		"name": "1st S-Move: Team Stat ↓ (10 Times)",
		"description": "Grants the following effect 10 times the first time the user’s sync move is used each battle: Lowers one of the following stats of all opposing sync pairs by one stat rank at random: Attack, Defense, Sp. Atk, Sp. Def, Speed, accuracy, or evasiveness.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 50,
		"x": "-2",
		"y": "-3",
		"name": "Power Play",
		"description": "The more the target’s stats are lowered, the more it powers up the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 51,
		"x": "3",
		"y": "-1",
		"name": "Prescient Divine Psywave: Power +25",
		"description": "Prescient Divine Psywave: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 52,
		"x": "-3",
		"y": "2",
		"name": "Prescient Divine Psywave: Power +25",
		"description": "Prescient Divine Psywave: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const SONIA_CORVIKNIGHT = [
	{
		"id": 1,
		"x": "1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "1",
		"y": "0",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "-1",
		"y": "1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "-1",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "1",
		"y": "-2",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": "2",
		"y": "-3",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": "1",
		"y": "-3",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": "3",
		"y": "-4",
		"name": "Metal Claw: Power +4",
		"description": "Metal Claw: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "steel"
	},
	{
		"id": 11,
		"x": "2",
		"y": "-4",
		"name": "Metal Claw: Power +4",
		"description": "Metal Claw: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "steel"
	},
	{
		"id": 12,
		"x": "1",
		"y": "-4",
		"name": "Metal Claw: Power +4",
		"description": "Metal Claw: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "steel"
	},
	{
		"id": 13,
		"x": "3",
		"y": "-5",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 14,
		"x": "2",
		"y": "-5",
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": "1",
		"y": "-5",
		"name": "Attack Trap 9",
		"description": "Leaves the target trapped when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": "3",
		"y": "-6",
		"name": "Super Potion: MP Refresh 1",
		"description": "Has a chance (20%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": "2",
		"y": "-6",
		"name": "Defense Crush 9",
		"description": "Lowers the target’s Defense by one stat rank when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": "-2",
		"y": "2",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": "-3",
		"y": "3",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": "-1",
		"y": "2",
		"name": "Black Steel Wing: Power +2",
		"description": "Black Steel Wing: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "steel"
	},
	{
		"id": 21,
		"x": "-2",
		"y": "3",
		"name": "Black Steel Wing: Power +2",
		"description": "Black Steel Wing: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "steel"
	},
	{
		"id": 22,
		"x": "-3",
		"y": "4",
		"name": "Black Steel Wing: Power +2",
		"description": "Black Steel Wing: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "steel"
	},
	{
		"id": 23,
		"x": "-1",
		"y": "3",
		"name": "Black Steel Wing: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": "-2",
		"y": "4",
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": "-3",
		"y": "5",
		"name": "Endurance",
		"description": "Applies the Enduring effect to the user if its HP is full when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": "-1",
		"y": "4",
		"name": "Vigilance",
		"description": "Protects the user against critical hits.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": "1",
		"y": "1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": "2",
		"y": "1",
		"name": "Antitoxin",
		"description": "Prevents the user from getting poisoned or badly poisoned.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": "1",
		"y": "2",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": "3",
		"y": "1",
		"name": "Black Steel Wing: Power +2",
		"description": "Black Steel Wing: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "steel"
	},
	{
		"id": 31,
		"x": "2",
		"y": "2",
		"name": "Black Steel Wing: Power +2",
		"description": "Black Steel Wing: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "steel"
	},
	{
		"id": 32,
		"x": "1",
		"y": "3",
		"name": "So Young and Cute!: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": "3",
		"y": "2",
		"name": "Sp. Def +10",
		"description": "Sp. Def +10",
		"energy": "4",
		"orb": "48",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": "2",
		"y": "3",
		"name": "Metallic Acceleration 2",
		"description": "Quickly charges the move gauge when the zone is a Steel Zone.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": "1",
		"y": "4",
		"name": "Black Steel Wing: 1st Move: Restore MP 1",
		"description": "Restores one MP of the user’s move the first time that move is successful each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": "3",
		"y": "3",
		"name": "Metallic Healing 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action when the zone is a Steel Zone.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": "2",
		"y": "4",
		"name": "Steel Zone: Team Condition Nullification",
		"description": "Prevents all allied sync pairs from being inflicted with status conditions, flinching, becoming confused, or becoming trapped when the zone is a Steel Zone.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": "-2",
		"y": "0",
		"name": "Sand Shelter",
		"description": "Protects the user from damage from a sandstorm.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 39,
		"x": "-1",
		"y": "-1",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": "-3",
		"y": "0",
		"name": "Metal Claw: Power +4",
		"description": "Metal Claw: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "steel"
	},
	{
		"id": 41,
		"x": "-2",
		"y": "-1",
		"name": "Metal Claw: Power +4",
		"description": "Metal Claw: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "steel"
	},
	{
		"id": 42,
		"x": "-1",
		"y": "-2",
		"name": "Metal Claw: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": "-3",
		"y": "-1",
		"name": "Metal Claw: Accuracy +5",
		"description": "Metal Claw: Accuracy +5",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "steel"
	},
	{
		"id": 44,
		"x": "-2",
		"y": "-2",
		"name": "Team Sync Regen",
		"description": "Applies the Gradual Healing effect to all allied sync pairs after the user uses a sync move.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": "-1",
		"y": "-3",
		"name": "S-Move: Team Phys & Spec Boost ↑1 9",
		"description": "Increases the Physical Moves ↑ Next effect and Special Moves ↑ Next effect of all allied sync pairs by one rank after using the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": "-3",
		"y": "-2",
		"name": "Head Start 1",
		"description": "Reduces the user’s sync move countdown by one the first time it enters a battle each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": "0",
		"y": "-3",
		"name": "Young Studying Professor Steel Impact: Power +25",
		"description": "Young Studying Professor Steel Impact: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": "0",
		"y": "3",
		"name": "Young Studying Professor Steel Impact: Power +25",
		"description": "Young Studying Professor Steel Impact: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const ARVEN_SKWOVET = [
	{
		"id": 1,
		"x": -1,
		"y": 0,
		"name": "Dauntless",
		"description": "Sp. Atk cannot be lowered.",
		"energy": "0",
		"orb": "5",
		"orbs": {
			"tm": 0,
			"fiery": 40,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 2,
		"x": 0,
		"y": -1,
		"name": "Ghost Guard",
		"description": "Reduces damage when the user is attacked by Ghost-type moves.",
		"energy": "0",
		"orb": "5",
		"orbs": {
			"tm": 0,
			"fiery": 40,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 3,
		"x": 1,
		"y": -1,
		"name": "Headstrong",
		"description": "Attack cannot be lowered.",
		"energy": "0",
		"orb": "5",
		"orbs": {
			"tm": 0,
			"fiery": 40,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 4,
		"x": 1,
		"y": 0,
		"name": "Attack +10",
		"description": "Attack +10",
		"energy": "0",
		"orb": "5",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": 0,
		"y": 1,
		"name": "HP +20",
		"description": "HP +20",
		"energy": "0",
		"orb": "5",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": -1,
		"y": 1,
		"name": "Sp. Atk +10",
		"description": "Sp. Atk +10",
		"energy": "0",
		"orb": "5",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 2,
		"y": -1,
		"name": "Attack +10",
		"description": "Attack +10",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 2,
		"y": -2,
		"name": "Dire Hit +",
		"description": "Raises the user’s critical-hit rate by two stat ranks.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 1,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "learnmove",
		"icon": "learnmove"
	},
	{
		"id": 9,
		"x": 2,
		"y": -3,
		"name": "Dire Hit +: MP Refresh +2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 40,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 10,
		"x": 2,
		"y": -4,
		"name": "Dire Hit +: Power Combo +9",
		"description": "Increases the user’s Physical Moves ↑ Next effect and Special Moves ↑ Next effect by one rank when its move is successful.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 80,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 11,
		"x": 3,
		"y": -5,
		"name": "Dire Hit +: Critical Eye +1",
		"description": "Raises the user’s critical-hit rate by one stat rank when its move is successful.",
		"energy": "0",
		"orb": "5",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 60,
			"bubbly": 0,
			"sparky": 60
		},
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 12,
		"x": 4,
		"y": -6,
		"name": "Dire Hit +: Power Combo +9",
		"description": "Increases the user’s Physical Moves ↑ Next effect and Special Moves ↑ Next effect by one rank when its move is successful.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 80,
			"bubbly": 0,
			"sparky": 80
		},
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": 5,
		"y": -7,
		"name": "Dire Hit +: +1st T-Move: Sync CD ↓ +1",
		"description": "Reduces the user’s sync move countdown by one the first time its Trainer uses a move each battle.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 100,
			"bubbly": 0,
			"sparky": 100
		},
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 14,
		"x": 3,
		"y": -2,
		"name": "Double-Edge",
		"description": "The user also takes 25% of the damage it dealt to the target.",
		"energy": "0",
		"orb": "5",
		"orbs": {
			"tm": 1,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "learnmove",
		"icon": "learnmove"
	},
	{
		"id": 15,
		"x": 4,
		"y": -3,
		"name": "Double-Edge: Move Gauge Refresh +3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 40,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": 5,
		"y": -4,
		"name": "Recoil Removal 9",
		"description": "Negates recoil damage when using moves that have the recoil effect tag.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 80,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": 6,
		"y": -5,
		"name": "Double-Edge: Power +100",
		"description": "Double-Edge: Power +100",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 60,
			"bubbly": 0,
			"sparky": 60
		},
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 18,
		"x": 7,
		"y": -6,
		"name": "Double-Edge: Hit: Physical Boost ↑+1 +9",
		"description": "Increases the user’s Physical Moves ↑ Next effect by one rank when its attack move is successful.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 80,
			"bubbly": 0,
			"sparky": 80
		},
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 19,
		"x": 8,
		"y": -7,
		"name": "Double-Edge: Combo Freebie +9",
		"description": "Applies the Free Move Next effect to the user when its attack move is successful.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 100,
			"bubbly": 0,
			"sparky": 100
		},
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 20,
		"x": 4,
		"y": -4,
		"name": "Attack +20",
		"description": "Attack +20",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 21,
		"x": 5,
		"y": -5,
		"name": "Attack +20",
		"description": "Attack +20",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 22,
		"x": 6,
		"y": -6,
		"name": "Attack +40",
		"description": "Attack +40",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 23,
		"x": 7,
		"y": -7,
		"name": "Attack +40",
		"description": "Attack +40",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 24,
		"x": 8,
		"y": -8,
		"name": "Attack +60",
		"description": "Attack +60",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 25,
		"x": 3,
		"y": -1,
		"name": "Brutal Swing",
		"description": "No additional effect.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 1,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "learnmove",
		"icon": "learnmove"
	},
	{
		"id": 26,
		"x": 4,
		"y": -1,
		"name": "Brutal Swing: Move Gauge Refresh +3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 40,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": 5,
		"y": -1,
		"name": "Brutal Swing: Trip Up +9",
		"description": "Lowers the target’s Speed by one stat rank when the user’s attack move against it is successful.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 80,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 28,
		"x": 6,
		"y": -1,
		"name": "Brutal Swing: Power +50",
		"description": "Brutal Swing: Power +50",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 60,
			"bubbly": 0,
			"sparky": 60
		},
		"level": 1,
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 29,
		"x": 7,
		"y": -1,
		"name": "Brutal Swing: Overwhelm +9",
		"description": "Lowers the target’s Attack by one stat rank when the user’s attack move against it is successful.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 80,
			"bubbly": 0,
			"sparky": 80
		},
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 30,
		"x": 8,
		"y": -1,
		"name": "Brutal Swing: Defense Crush +9",
		"description": "Lowers the target’s Defense by one stat rank when the user’s attack move against it is successful.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 100,
			"bubbly": 0,
			"sparky": 100
		},
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": 5,
		"y": -2,
		"name": "Attack +20",
		"description": "Attack +20",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 32,
		"x": 6,
		"y": -2,
		"name": "Attack +20",
		"description": "Attack +20",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 33,
		"x": 7,
		"y": -2,
		"name": "Attack +40",
		"description": "Attack +40",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": 8,
		"y": -2,
		"name": "Attack +40",
		"description": "Attack +40",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 35,
		"x": 9,
		"y": -2,
		"name": "Attack +60",
		"description": "Attack +60",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 36,
		"x": 2,
		"y": 0,
		"name": "Offense Studies",
		"description": "Raises the user’s Attack and Sp. Atk by two stat ranks.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 1,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "learnmove",
		"icon": "learnmove"
	},
	{
		"id": 37,
		"x": 2,
		"y": 1,
		"name": "Offense Studies: MP Refresh +2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 40,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": 3,
		"y": 1,
		"name": "Offense Studies: Ramp Up +1",
		"description": "Raises the user’s Sp. Atk by one stat rank when its move is successful.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 80,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 39,
		"x": 4,
		"y": 1,
		"name": "Offense Studies: Berserker +1",
		"description": "Raises the user’s Attack by one stat rank when its move is successful.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 60,
			"bubbly": 0,
			"sparky": 60
		},
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": 5,
		"y": 1,
		"name": "Offense Studies: Critical Eye +2",
		"description": "Raises the user’s critical-hit rate by two stat ranks when its move is successful.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 80,
			"bubbly": 0,
			"sparky": 80
		},
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 41,
		"x": 6,
		"y": 1,
		"name": "Offense Studies: Move: Physical Boost ↑+2 & Special Boost ↑+2 +9",
		"description": "Increases the user’s Physical Moves ↑ Next effect and Special Moves ↑ Next effect by two ranks when its move is successful.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 100,
			"bubbly": 0,
			"sparky": 100
		},
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 42,
		"x": -2,
		"y": 1,
		"name": "Sp. Atk +10",
		"description": "Sp. Atk +10",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 43,
		"x": -2,
		"y": 0,
		"name": "X Evasion",
		"description": "Raises the user’s evasiveness by two stat ranks.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 1,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "learnmove",
		"icon": "learnmove"
	},
	{
		"id": 44,
		"x": -2,
		"y": -1,
		"name": "X Evasion: MP Refresh +2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 40,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -2,
		"y": -2,
		"name": "X Evasion: Pep Rally +1",
		"description": "Raises the Speed of all allied sync pairs by one stat rank when the user’s move is successful.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 80,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -3,
		"y": -2,
		"name": "X Evasion: Slippery Sidekicks +1",
		"description": "Raises the evasiveness of all allied sync pairs by one stat rank when the user’s move is successful.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 60,
			"bubbly": 0,
			"sparky": 60
		},
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": -4,
		"y": -2,
		"name": "X Evasion: Move: Team Free Move Next +9",
		"description": "Applies the Free Move Next effect to all allied sync pairs when the user’s move is successful.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 80,
			"bubbly": 0,
			"sparky": 80
		},
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 48,
		"x": -5,
		"y": -2,
		"name": "Ridicure 4",
		"description": "Has a chance (50%) of restoring the user’s HP by approximately 20% of its maximum HP when an opponent’s attack move targeting the user misses.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 100,
			"bubbly": 0,
			"sparky": 100
		},
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 49,
		"x": -3,
		"y": 1,
		"name": "Mud-Slap",
		"description": "Lowers the target’s accuracy by one stat rank.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 1,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "learnmove",
		"icon": "learnmove"
	},
	{
		"id": 50,
		"x": -4,
		"y": 1,
		"name": "Mud-Slap: Move Gauge Refresh +3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 40,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 51,
		"x": -5,
		"y": 1,
		"name": "Mud-Slap: Accuracy +10",
		"description": "Mud-Slap: Accuracy +10",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 80,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 52,
		"x": -6,
		"y": 1,
		"name": "Mud-Slap: Power +50",
		"description": "Mud-Slap: Power +50",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 60,
			"bubbly": 0,
			"sparky": 60
		},
		"level": 1,
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 53,
		"x": -7,
		"y": 1,
		"name": "Mud-Slap: Staggering +4",
		"description": "Has a chance (50%) of making the target flinch when the user’s attack move against it is successful.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 80,
			"bubbly": 0,
			"sparky": 80
		},
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 54,
		"x": -8,
		"y": 1,
		"name": "Mud-Slap: Hit: Sp. Def ↓+2 +9",
		"description": "Lowers the target’s Sp. Def by two stat ranks when the user’s attack move against it is successful.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 100,
			"bubbly": 0,
			"sparky": 100
		},
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 55,
		"x": -4,
		"y": 0,
		"name": "Sp. Atk +20",
		"description": "Sp. Atk +20",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 56,
		"x": -5,
		"y": 0,
		"name": "Sp. Atk +20",
		"description": "Sp. Atk +20",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 57,
		"x": -6,
		"y": 0,
		"name": "Sp. Atk +40",
		"description": "Sp. Atk +40",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 58,
		"x": -7,
		"y": 0,
		"name": "Sp. Atk +40",
		"description": "Sp. Atk +40",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 59,
		"x": -8,
		"y": 0,
		"name": "Sp. Atk +60",
		"description": "Sp. Atk +60",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 60,
		"x": -3,
		"y": 2,
		"name": "Hyper Voice",
		"description": "No additional effect.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 1,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "learnmove",
		"icon": "learnmove"
	},
	{
		"id": 61,
		"x": -4,
		"y": 3,
		"name": "Hyper Voice: Move Gauge Refresh +3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 40,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 62,
		"x": -5,
		"y": 4,
		"name": "Hyper Voice: Attack Trap +9",
		"description": "Leaves the target trapped when the user’s attack move against it is successful.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 80,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 63,
		"x": -6,
		"y": 5,
		"name": "Hyper Voice: Power +50",
		"description": "Hyper Voice: Power +50",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 60,
			"bubbly": 0,
			"sparky": 60
		},
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 64,
		"x": -7,
		"y": 6,
		"name": "Hyper Voice: Satisfied Snicker +9",
		"description": "Lowers the target’s Sp. Atk by one stat rank when the user’s attack move against it is successful.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 80,
			"bubbly": 0,
			"sparky": 80
		},
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 65,
		"x": -8,
		"y": 7,
		"name": "Hyper Voice: Discombobulate +9",
		"description": "Lowers the target’s accuracy by one stat rank when the user’s attack move against it is successful.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 100,
			"bubbly": 0,
			"sparky": 100
		},
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 66,
		"x": -5,
		"y": 3,
		"name": "Sp. Atk +20",
		"description": "Sp. Atk +20",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 67,
		"x": -6,
		"y": 4,
		"name": "Sp. Atk +20",
		"description": "Sp. Atk +20",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 68,
		"x": -7,
		"y": 5,
		"name": "Sp. Atk +40",
		"description": "Sp. Atk +40",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 69,
		"x": -8,
		"y": 6,
		"name": "Sp. Atk +40",
		"description": "Sp. Atk +40",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 70,
		"x": -9,
		"y": 7,
		"name": "Sp. Atk +60",
		"description": "Sp. Atk +60",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 71,
		"x": -2,
		"y": 2,
		"name": "Defensive Studies",
		"description": "Raises the user’s Defense and Sp. Def by two stat ranks.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 1,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "learnmove",
		"icon": "learnmove"
	},
	{
		"id": 72,
		"x": -2,
		"y": 3,
		"name": "Defensive Studies: MP Refresh +2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 40,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 73,
		"x": -3,
		"y": 4,
		"name": "Defensive Studies: Pep Rally +1",
		"description": "Raises the Speed of all allied sync pairs by one stat rank when the user’s move is successful.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 80,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 74,
		"x": -4,
		"y": 5,
		"name": "Defensive Studies: Move: Team Def ↑ & Sp. Def ↑ +9",
		"description": "Raises the Defense and Sp. Def of all allied sync pairs by one stat rank when the user’s move is successful.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 60,
			"bubbly": 0,
			"sparky": 60
		},
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 75,
		"x": -5,
		"y": 6,
		"name": "Defensive Studies: Durable +9",
		"description": "Applies the Enduring effect to the user when its move is successful.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 80,
			"bubbly": 0,
			"sparky": 80
		},
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 76,
		"x": -6,
		"y": 7,
		"name": "Defensive Studies: Propulsion +9",
		"description": "Reduces the user’s sync move countdown by one when its move is successful.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 100,
			"bubbly": 0,
			"sparky": 100
		},
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 77,
		"x": 0,
		"y": -2,
		"name": "Body Slam: Move Gauge Refresh +3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 40,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 78,
		"x": 0,
		"y": -3,
		"name": "Entry: Sync Move Boost 4",
		"description": "Increases the user’s Sync Move ↑ Next effect by four ranks when it enters a battle.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 80,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 79,
		"x": 0,
		"y": -4,
		"name": "Body Slam: Gobsmack +4",
		"description": "Has a chance (50%) of leaving the target confused when the user’s attack move against it is successful.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 80,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 80,
		"x": 0,
		"y": -5,
		"name": "Normal Zone: MG → 2",
		"description": "Quickly charges the move gauge when the zone is a Normal Zone.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 80,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 81,
		"x": 0,
		"y": -6,
		"name": "First Aid 4",
		"description": "Restores the user’s HP by approximately 40% of its maximum HP the first time it is in a pinch each battle.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 80,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 82,
		"x": 0,
		"y": -7,
		"name": "Static Boost 3",
		"description": "Powers up the user’s moves and sync move when the target is paralyzed.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 60,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 60
		},
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 83,
		"x": 0,
		"y": -8,
		"name": "Body Slam: Hostile Environment +3",
		"description": "Raises the chance of inflicting status conditions with the additional effects of moves.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 60,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 60
		},
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 84,
		"x": 0,
		"y": -9,
		"name": "Debut: Normal Zone",
		"description": "Turns the field of play’s zone into a Normal Zone the first time the user enters a battle each battle. (A Normal Zone powers up Normal-type attacks.)",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 60,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 60
		},
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 85,
		"x": 0,
		"y": -10,
		"name": "1st S-Move: Normal Zone & Extension 5",
		"description": "Turns the field of play’s zone into a Normal Zone the first time the user’s sync move is used each battle. (A Normal Zone powers up Normal-type attacks.) Extends the duration of the Normal Zone when the zone turns into a Normal Zone while the user is on the field.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 160,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 160
		},
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 86,
		"x": 1,
		"y": -5,
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 80,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 87,
		"x": 2,
		"y": -6,
		"name": "Entry: Physical Boost 1",
		"description": "Increases the user’s Physical Moves ↑ Next effect by one rank when it enters a battle.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 60,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 60
		},
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 88,
		"x": 3,
		"y": -7,
		"name": "No Leftovers Normal Impact: Power +25",
		"description": "No Leftovers Normal Impact: Power +25",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 60,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 60
		},
		"level": 1,
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 89,
		"x": 3,
		"y": -8,
		"name": "Circle: MG → 2",
		"description": "Quickly charges the move gauge when a circle applies to the allied field of play.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 60,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 60
		},
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 90,
		"x": 4,
		"y": -8,
		"name": "1st S-Move: Physical & Special Boost 2",
		"description": "Increases the user’s Physical Moves ↑ Next effect and Special Moves ↑ Next effect by two ranks the first time its sync move is used each battle.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 60,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 60
		},
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 91,
		"x": 3,
		"y": -9,
		"name": "Paldea C (Defensive) Extension 5",
		"description": "Extends the duration of Paldea Circle (Defensive) when Paldea Circle (Defensive) is applied to the allied field of play.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 80,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 80
		},
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 92,
		"x": 5,
		"y": -9,
		"name": "1st S-Move: Paldea C (Def) on Field",
		"description": "Applies Paldea Circle (Defensive) to the allied field of play the first time the user’s sync move is used each battle.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 60,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 60
		},
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 93,
		"x": -1,
		"y": -4,
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 80,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 94,
		"x": -2,
		"y": -4,
		"name": "Entry: Special Boost 1",
		"description": "Increases the user’s Special Moves ↑ Next effect by one rank when it enters a battle.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 60,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 60
		},
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 95,
		"x": -3,
		"y": -4,
		"name": "No Leftovers Normal Impact: Power +25",
		"description": "No Leftovers Normal Impact: Power +25",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 60,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 60
		},
		"level": 1,
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 96,
		"x": -3,
		"y": -5,
		"name": "Circle: HP Recovery 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action when a circle applies to the allied field of play.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 60,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 60
		},
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 97,
		"x": -4,
		"y": -4,
		"name": "Brawn Sync 5",
		"description": "Powers up the user’s sync move when its Attack is raised.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 60,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 60
		},
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 98,
		"x": -3,
		"y": -6,
		"name": "Debut: Paldea C (Def) on Field",
		"description": "Applies Paldea Circle (Defensive) to the allied field of play the first time the user enters a battle each battle.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 80,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 80
		},
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 99,
		"x": -5,
		"y": -4,
		"name": "Head Start 1",
		"description": "Reduces the user’s sync move countdown by one the first time it enters a battle each battle.",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 60,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 60
		},
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 100,
		"x": 0,
		"y": 2,
		"name": "HP +20",
		"description": "HP +20",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 101,
		"x": 0,
		"y": 3,
		"name": "HP +20",
		"description": "HP +20",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 102,
		"x": 0,
		"y": 4,
		"name": "HP +20",
		"description": "HP +20",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 103,
		"x": 0,
		"y": 5,
		"name": "HP +20",
		"description": "HP +20",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 104,
		"x": 0,
		"y": 6,
		"name": "HP +40",
		"description": "HP +40",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 105,
		"x": -1,
		"y": 7,
		"name": "HP +40",
		"description": "HP +40",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 106,
		"x": 1,
		"y": 6,
		"name": "HP +40",
		"description": "HP +40",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 107,
		"x": 0,
		"y": 7,
		"name": "HP +60",
		"description": "HP +60",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 108,
		"x": -1,
		"y": 8,
		"name": "HP +60",
		"description": "HP +60",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 109,
		"x": 1,
		"y": 7,
		"name": "HP +60",
		"description": "HP +60",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 110,
		"x": 0,
		"y": 8,
		"name": "HP +80",
		"description": "HP +80",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 111,
		"x": 1,
		"y": 3,
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 112,
		"x": 2,
		"y": 3,
		"name": "Defense +10",
		"description": "Defense +10",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 113,
		"x": 3,
		"y": 3,
		"name": "Defense +10",
		"description": "Defense +10",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 114,
		"x": 3,
		"y": 4,
		"name": "Defense +15",
		"description": "Defense +15",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 115,
		"x": 4,
		"y": 3,
		"name": "Defense +15",
		"description": "Defense +15",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 116,
		"x": 3,
		"y": 5,
		"name": "Defense +20",
		"description": "Defense +20",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 117,
		"x": 4,
		"y": 4,
		"name": "Defense +25",
		"description": "Defense +25",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 118,
		"x": 5,
		"y": 3,
		"name": "Defense +20",
		"description": "Defense +20",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 119,
		"x": -1,
		"y": 4,
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 120,
		"x": -2,
		"y": 5,
		"name": "Sp. Def +10",
		"description": "Sp. Def +10",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 121,
		"x": -3,
		"y": 6,
		"name": "Sp. Def +10",
		"description": "Sp. Def +10",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 122,
		"x": -3,
		"y": 7,
		"name": "Sp. Def +15",
		"description": "Sp. Def +15",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 123,
		"x": -4,
		"y": 7,
		"name": "Sp. Def +15",
		"description": "Sp. Def +15",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 124,
		"x": -3,
		"y": 8,
		"name": "Sp. Def +20",
		"description": "Sp. Def +20",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 125,
		"x": -4,
		"y": 8,
		"name": "Sp. Def +25",
		"description": "Sp. Def +25",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 126,
		"x": -5,
		"y": 8,
		"name": "Sp. Def +20",
		"description": "Sp. Def +20",
		"energy": "0",
		"orb": "0",
		"orbs": {
			"tm": 0,
			"fiery": 0,
			"leafy": 0,
			"bubbly": 0,
			"sparky": 0
		},
		"level": 1,
		"color": "blue",
		"icon": "stat"
	}
]

export const PERRIN_NOCTOWL = [
	{
		"id": 1,
		"x": "-1",
		"y": "0",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "-1",
		"y": "1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "1",
		"y": "0",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "1",
		"y": "-1",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "2",
		"y": "-1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": "3",
		"y": "-2",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": "2",
		"y": "-2",
		"name": "Aerial Ace: Power +4",
		"description": "Aerial Ace: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 10,
		"x": "1",
		"y": "-2",
		"name": "Aerial Ace: Power +4",
		"description": "Aerial Ace: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 11,
		"x": "3",
		"y": "-3",
		"name": "Aerial Ace: Power +4",
		"description": "Aerial Ace: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 12,
		"x": "2",
		"y": "-3",
		"name": "Aerial Ace: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": "1",
		"y": "-3",
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 14,
		"x": "3",
		"y": "-4",
		"name": "Real Good Shot Flying Impact: Power +50",
		"description": "Real Good Shot Flying Impact: Power +50",
		"energy": "8",
		"orb": "96",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 15,
		"x": "2",
		"y": "-4",
		"name": "1st Hit: Flying Zone",
		"description": "Turns the field of play’s zone into a Flying Zone the first time the user’s attack move is successful each battle. (A Flying Zone powers up Flying-type attacks.)",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": "-2",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 17,
		"x": "-3",
		"y": "2",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 18,
		"x": "-2",
		"y": "2",
		"name": "Eagle Eye Zen Headbutt: Power +2",
		"description": "Eagle Eye Zen Headbutt: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "psychic"
	},
	{
		"id": 19,
		"x": "-1",
		"y": "2",
		"name": "Eagle Eye Zen Headbutt: Power +2",
		"description": "Eagle Eye Zen Headbutt: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "psychic"
	},
	{
		"id": 20,
		"x": "-3",
		"y": "3",
		"name": "Eagle Eye Zen Headbutt: Power +2",
		"description": "Eagle Eye Zen Headbutt: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "psychic"
	},
	{
		"id": 21,
		"x": "-2",
		"y": "3",
		"name": "Eagle Eye Zen Headbutt: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 22,
		"x": "-1",
		"y": "3",
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 23,
		"x": "-3",
		"y": "4",
		"name": "Real Good Shot Flying Impact: Power +50",
		"description": "Real Good Shot Flying Impact: Power +50",
		"energy": "8",
		"orb": "96",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 24,
		"x": "-2",
		"y": "4",
		"name": "1st S-Move: Team Physical Boost 2",
		"description": "Increases the Physical Moves ↑ Next effect of all allied sync pairs by two ranks the first time the user’s sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": "1",
		"y": "1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 26,
		"x": "2",
		"y": "1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 27,
		"x": "3",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": "1",
		"y": "2",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": "2",
		"y": "2",
		"name": "Eagle Eye Zen Headbutt: Power +2",
		"description": "Eagle Eye Zen Headbutt: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "psychic"
	},
	{
		"id": 30,
		"x": "3",
		"y": "2",
		"name": "Eagle Eye Zen Headbutt: Power +2",
		"description": "Eagle Eye Zen Headbutt: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "psychic"
	},
	{
		"id": 31,
		"x": "1",
		"y": "3",
		"name": "Attack +10",
		"description": "Attack +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 32,
		"x": "2",
		"y": "3",
		"name": "Circle: MG → 2",
		"description": "Quickly charges the move gauge when a circle applies to the allied field of play.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": "3",
		"y": "3",
		"name": "Pretty Amazing!: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": "1",
		"y": "4",
		"name": "Pretty Amazing!: Initial Propulsion 2",
		"description": "Reduces the sync move countdown by two the first time the user’s move is successful each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": "2",
		"y": "4",
		"name": "Paldea C (Phys): Team Moves ↑ 2",
		"description": "Powers up the moves of all allied sync pairs when Paldea Circle (Physical) applies to the allied field of play.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": "-1",
		"y": "-1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": "-2",
		"y": "-1",
		"name": "Wide Awake",
		"description": "Prevents the user from falling asleep.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": "-3",
		"y": "-1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": "-1",
		"y": "-2",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": "-2",
		"y": "-2",
		"name": "Aerial Ace: Power +4",
		"description": "Aerial Ace: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 41,
		"x": "-3",
		"y": "-2",
		"name": "Aerial Ace: Power +4",
		"description": "Aerial Ace: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 42,
		"x": "-1",
		"y": "-3",
		"name": "Aerial Ace: Trip Up 9",
		"description": "Lowers the target’s Speed by one stat rank when the user’s attack move against it is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": "-2",
		"y": "-3",
		"name": "Speedy Entry 2",
		"description": "Raises the user’s Speed by two stat ranks when it enters a battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": "-3",
		"y": "-3",
		"name": "Catalyst",
		"description": "Applies the Move Gauge Acceleration effect to the allied field of play the first time the user’s sync move is used each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": "-1",
		"y": "-4",
		"name": "Slo-pponent Sync 9",
		"description": "Powers up the user’s sync move when the target’s Speed is lowered.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": "-2",
		"y": "-4",
		"name": "Soften Up 1",
		"description": "Critical hits land more easily when the user attacks with a sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": "0",
		"y": "-3",
		"name": "Real Good Shot Flying Impact: Power +25",
		"description": "Real Good Shot Flying Impact: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": "0",
		"y": "3",
		"name": "Real Good Shot Flying Impact: Power +25",
		"description": "Real Good Shot Flying Impact: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]