export const RED1996_PIKACHU = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": -1,
		"y": -1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 0,
		"y": -2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 1,
		"y": -2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": -2,
		"y": 0,
		"name": "The Original Thunder: Power 5",
		"description": "The Original Thunder: Power ↑ 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 11,
		"x": -2,
		"y": 1,
		"name": "The Original Thunder: Power 5",
		"description": "The Original Thunder: Power ↑ 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 12,
		"x": -2,
		"y": 2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 13,
		"x": -1,
		"y": 2,
		"name": "Escape Artist",
		"description": "Prevents the user from becoming trapped.",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 14,
		"x": -3,
		"y": 0,
		"name": "Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": -3,
		"y": 1,
		"name": "Sp. Atk 10",
		"description": "Sp. Atk 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 16,
		"x": -3,
		"y": 2,
		"name": "Unfortuitous 4",
		"description": "Has a chance (50%) of lowering one of the target’s following stats by one stat rank at random when the user’s attack move against it is successful: Attack, Defense, Sp. Atk, Sp. Def, Speed, accuracy, or evasiveness.",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": -3,
		"y": 3,
		"name": "Circle: Attack Move DR 2",
		"description": "Reduces damage when the user is hit by an attack move while a circle applies to the allied field of play.",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": -2,
		"y": 3,
		"name": "Defense 10",
		"description": "Defense 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -4,
		"y": 0,
		"name": "Circle: S-Moves ↑ 5",
		"description": "Powers up the user’s sync move when a circle applies to the allied field of play.",
		"energy": "6",
		"orb": "72",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 20,
		"x": -4,
		"y": 1,
		"name": "Debut: Kanto C (Spec) on Field",
		"description": "Applies Kanto Circle (Special) to the allied field of play the first time the user enters a battle each battle.",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 21,
		"x": -4,
		"y": 2,
		"name": "Debut: Kanto C (Phys) on Field",
		"description": "Applies Kanto Circle (Physical) to the allied field of play the first time the user enters a battle each battle.",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 22,
		"x": -4,
		"y": 3,
		"name": "Debut: Kanto C (Def) on Field",
		"description": "Applies Kanto Circle (Defensive) to the allied field of play the first time the user enters a battle each battle.",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 23,
		"x": 2,
		"y": -2,
		"name": "Glorious Thunder: Power 5",
		"description": "Glorious Thunder: Power ↑ 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 24,
		"x": 2,
		"y": -1,
		"name": "Glorious Thunder: Power 5",
		"description": "Glorious Thunder: Power ↑ 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 25,
		"x": 2,
		"y": 0,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 26,
		"x": 1,
		"y": 1,
		"name": "Clearheaded",
		"description": "Prevents the user from becoming confused.",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": 3,
		"y": -3,
		"name": "Turbo Charge 2",
		"description": "Quickly charges the move gauge when the terrain is Electric Terrain.",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 28,
		"x": 3,
		"y": -2,
		"name": "Sp. Atk 10",
		"description": "Sp. Atk 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": 3,
		"y": -1,
		"name": "Shock Recovery 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action when the terrain is Electric Terrain.",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 30,
		"x": 3,
		"y": 0,
		"name": "Power Induction 1",
		"description": "Powers up the user’s moves when the terrain is Electric Terrain.",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": 2,
		"y": 1,
		"name": "Sp. Def 10",
		"description": "Sp. Def 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 32,
		"x": 4,
		"y": -4,
		"name": "Electric Terrain Extension 3",
		"description": "Extends the duration of Electric Terrain when the terrain turns into Electric Terrain while the user is on the field.",
		"energy": "6",
		"orb": "72",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": 4,
		"y": -3,
		"name": "Charged Immunity",
		"description": "Status conditions cannot be inflicted on the user when the terrain is Electric Terrain.",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": 4,
		"y": -2,
		"name": "Electric Terrain Hit: Stat ↓ 9",
		"description": "Lowers one of the target’s following stats by one stat rank at random when the user’s attack move is successful while the terrain is Electric Terrain: Attack, Defense, Sp. Atk, Sp. Def, Speed, accuracy, or evasiveness.",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 4,
		"y": -1,
		"name": "Everlasting Thunderbolt: 1st Hit: Electric Terrain",
		"description": "Move: Everlasting Thunderbolt",
		"energy": "6",
		"orb": "72",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": -1,
		"y": -2,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": 0,
		"y": -3,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 38,
		"x": 1,
		"y": -3,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -1,
		"y": -3,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": 0,
		"y": -4,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 41,
		"x": 1,
		"y": -4,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 42,
		"x": -1,
		"y": -4,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 43,
		"x": 0,
		"y": -5,
		"name": "Move: Everlasting Thunderbolt",
		"description": "Has a chance (60%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "4",
		"orb": "48",
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": 1,
		"y": -5,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 45,
		"x": -2,
		"y": -5,
		"name": "Unflappable",
		"description": "Prevents the user from flinching.",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -2,
		"y": -4,
		"name": "Everlasting Thunderbolt: Power 4",
		"description": "Everlasting Thunderbolt: Power ↑ 4",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 47,
		"x": -2,
		"y": -3,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 48,
		"x": -3,
		"y": -5,
		"name": "Antitoxin",
		"description": "Prevents the user from getting poisoned or badly poisoned.",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 49,
		"x": -3,
		"y": -4,
		"name": "Everlasting Thunderbolt: Power 4",
		"description": "Everlasting Thunderbolt: Power ↑ 4",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 50,
		"x": -3,
		"y": -3,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 51,
		"x": -3,
		"y": -2,
		"name": "The Original Thunder: Power 5",
		"description": "The Original Thunder: Power ↑ 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 52,
		"x": -3,
		"y": -1,
		"name": "The Original Thunder: Power 5",
		"description": "The Original Thunder: Power ↑ 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 53,
		"x": -4,
		"y": -5,
		"name": "Flameproof",
		"description": "Prevents the user from getting burned.",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 54,
		"x": -4,
		"y": -4,
		"name": "Everlasting Thunderbolt: Power 4",
		"description": "Everlasting Thunderbolt: Power ↑ 4",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 55,
		"x": -5,
		"y": -6,
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 56,
		"x": -5,
		"y": -5,
		"name": "Trip Up 9",
		"description": "Lowers the target’s Speed by one stat rank when the user’s attack move against it is successful.",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 57,
		"x": -5,
		"y": -4,
		"name": "Circle: HP Recovery 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action when a circle applies to the allied field of play.",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 58,
		"x": -5,
		"y": -3,
		"name": "Speed 10",
		"description": "Speed 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 59,
		"x": -4,
		"y": -3,
		"name": "Sp. Atk 10",
		"description": "Sp. Atk 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 60,
		"x": -4,
		"y": -2,
		"name": "HP 20",
		"description": "HP 20",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 61,
		"x": -6,
		"y": -6,
		"name": "I Better Go!: 1st Move: Restore MP 1",
		"description": "Move: I Better Go!",
		"energy": "6",
		"orb": "72",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 62,
		"x": -6,
		"y": -5,
		"name": "Brainpower",
		"description": "The more the user’s Sp. Atk is raised, the more it powers up its sync move.",
		"energy": "6",
		"orb": "72",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 63,
		"x": -6,
		"y": -4,
		"name": "Everlasting Thunderbolt: Chase Down 3",
		"description": "Move: Everlasting Thunderbolt",
		"energy": "6",
		"orb": "72",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 64,
		"x": -6,
		"y": -3,
		"name": "Circle: Team S-Moves ↑ 2",
		"description": "Powers up the sync moves of all allied sync pairs when a circle applies to the allied field of play.",
		"energy": "6",
		"orb": "72",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 65,
		"x": 2,
		"y": -7,
		"name": "Lithe",
		"description": "Prevents the user from getting paralyzed.",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 66,
		"x": 2,
		"y": -6,
		"name": "Everlasting Thunderbolt: Power 4",
		"description": "Everlasting Thunderbolt: Power ↑ 4",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 67,
		"x": 2,
		"y": -5,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 68,
		"x": 3,
		"y": -8,
		"name": "Wide Awake",
		"description": "Prevents the user from falling asleep.",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 69,
		"x": 3,
		"y": -7,
		"name": "Everlasting Thunderbolt: Power 4",
		"description": "Everlasting Thunderbolt: Power ↑ 4",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 70,
		"x": 3,
		"y": -6,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 71,
		"x": 3,
		"y": -5,
		"name": "Glorious Thunder: Power 5",
		"description": "Glorious Thunder: Power ↑ 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 72,
		"x": 3,
		"y": -4,
		"name": "Glorious Thunder: Power 5",
		"description": "Glorious Thunder: Power ↑ 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 73,
		"x": 4,
		"y": -9,
		"name": "Antifreeze",
		"description": "Prevents the user from becoming frozen.",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 74,
		"x": 4,
		"y": -8,
		"name": "Everlasting Thunderbolt: Power 4",
		"description": "Everlasting Thunderbolt: Power ↑ 4",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 75,
		"x": 5,
		"y": -11,
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 76,
		"x": 5,
		"y": -10,
		"name": "Speed 10",
		"description": "Speed 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 77,
		"x": 5,
		"y": -9,
		"name": "Debut Regen",
		"description": "Applies the Gradual Healing effect to the user the first time the user enters a battle each battle.",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 78,
		"x": 5,
		"y": -8,
		"name": "Debut: Special Boost 1",
		"description": "Increases the user’s Special Moves ↑ Next effect by one rank the first time it enters a battle each battle.",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 79,
		"x": 4,
		"y": -7,
		"name": "Sp. Atk 10",
		"description": "Sp. Atk 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 80,
		"x": 4,
		"y": -6,
		"name": "HP 20",
		"description": "HP 20",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 81,
		"x": 6,
		"y": -12,
		"name": "Head Start 2",
		"description": "Reduces the user’s sync move countdown by two the first time it enters a battle each battle.",
		"energy": "7",
		"orb": "84",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 82,
		"x": 6,
		"y": -11,
		"name": "Head Start 1",
		"description": "Reduces the user’s sync move countdown by one the first time it enters a battle each battle.",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 83,
		"x": 6,
		"y": -10,
		"name": "First Aid 4",
		"description": "Restores the user’s HP by approximately 40% of its maximum HP the first time it is in a pinch each battle.",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 84,
		"x": 6,
		"y": -9,
		"name": "Sync Thinker 9",
		"description": "Increases the user’s Special Moves ↑ Next effect by one rank after using its sync move.",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 85,
		"x": -4,
		"y": -1,
		"name": "1st S-Move: Kanto C (3 Kinds) on Field & Extension 3",
		"description": "Applies Kanto Circle (Physical), Kanto Circle (Special), and Kanto Circle (Defensive) to the allied field of play the first time the user’s sync move is used each battle. Extends the duration of the following field effects when they are applied to the allied field of play: - Kanto Circle (Physical) - Kanto Circle (Special) - Kanto Circle (Defensive)",
		"energy": "0",
		"orb": "5",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 86,
		"x": 4,
		"y": -5,
		"name": "Glorious Thunder: Power 500",
		"description": "Glorious Thunder: Power ↑ 500",
		"energy": "0",
		"orb": "5",
		"level": "4",
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 87,
		"x": -1,
		"y": -5,
		"name": "Grown Up So Much Thunderbolt: Power 25",
		"description": "Grown Up So Much Thunderbolt: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 88,
		"x": 0,
		"y": -6,
		"name": "Grown Up So Much Thunderbolt: Power 25",
		"description": "Grown Up So Much Thunderbolt: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 89,
		"x": 1,
		"y": -6,
		"name": "Grown Up So Much Thunderbolt: Power 25",
		"description": "Grown Up So Much Thunderbolt: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 90,
		"x": 0,
		"y": 2,
		"name": "Grown Up So Much Thunderbolt: Power 25",
		"description": "Grown Up So Much Thunderbolt: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const FLORIAN_OGERPON = [
	{
		"id": 1,
		"x": "1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "1",
		"y": "0",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "-1",
		"y": "1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "-1",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "0",
		"y": "-2",
		"name": "Green Jasper Tera Blast: 1st Move: Restore MP 1",
		"description": "Restores one MP of the user’s move the first time that move is successful each battle.",
		"energy": "0",
		"orb": "5",
		"level": "5",
		"color": "red",
		"icon": ""
	},
	{
		"id": 8,
		"x": "0",
		"y": "2",
		"name": "The Teal Mask’s Hidden Power",
		"energy": "0",
		"orb": "5",
		"level": "4",
		"color": "yellow",
		"icon": ""
	},
	{
		"id": 9,
		"x": "1",
		"y": "-2",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": "2",
		"y": "-3",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": "3",
		"y": "-4",
		"name": "Headstrong",
		"description": "Attack cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 12,
		"x": "1",
		"y": "-3",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 13,
		"x": "2",
		"y": "-4",
		"name": "Ivy Cudgel: Power +2",
		"description": "Ivy Cudgel: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 14,
		"x": "3",
		"y": "-5",
		"name": "Ivy Cudgel: Power +2",
		"description": "Ivy Cudgel: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 15,
		"x": "1",
		"y": "-4",
		"name": "Ivy Cudgel: Power +2",
		"description": "Ivy Cudgel: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 16,
		"x": "2",
		"y": "-5",
		"name": "Ivy Cudgel: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": "3",
		"y": "-6",
		"name": "Ivy Cudgel: Gobsmack 9",
		"description": "Leaves the target confused when the user’s attack move against it is successful.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": "1",
		"y": "-5",
		"name": "Ivy Cudgel: Hit: Stat ↓2 9",
		"description": "Lowers one of the target’s following stats by two stat ranks at random when the user’s attack move against it is successful: Attack, Defense, Sp. Atk, Sp. Def, Speed, accuracy, or evasiveness.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 19,
		"x": "2",
		"y": "-6",
		"name": "Haymaker",
		"description": "The more the user’s Attack is raised, the more it powers up the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 20,
		"x": "-1",
		"y": "2",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 21,
		"x": "-2",
		"y": "3",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 22,
		"x": "-3",
		"y": "4",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 23,
		"x": "-1",
		"y": "3",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 24,
		"x": "-2",
		"y": "4",
		"name": "Lush Ivy Cudgel: Power +2",
		"description": "Lush Ivy Cudgel: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 25,
		"x": "-3",
		"y": "5",
		"name": "Lush Ivy Cudgel: Power +2",
		"description": "Lush Ivy Cudgel: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 26,
		"x": "-1",
		"y": "4",
		"name": "Lush Ivy Cudgel: Power +2",
		"description": "Lush Ivy Cudgel: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 27,
		"x": "-2",
		"y": "5",
		"name": "Lush Ivy Cudgel: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 28,
		"x": "-3",
		"y": "6",
		"name": "Grassy Terrain Hit: Free Move Next 4",
		"description": "Has a chance (50%) of applying the Free Move Next effect to the user when its attack move is successful while the terrain is Grassy Terrain.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": "-1",
		"y": "5",
		"name": "Empowering Overgrowth 5",
		"description": "Powers up the user’s moves when the terrain is Grassy Terrain.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 30,
		"x": "-2",
		"y": "6",
		"name": "User Sets Grassy Terrain: Supereffective ↑ Next",
		"description": "Applies the Supereffective ↑ Next effect to the user when it turns the field of play’s terrain into Grassy Terrain.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": "2",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 32,
		"x": "3",
		"y": "-1",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 33,
		"x": "2",
		"y": "0",
		"name": "Green Jasper Tera Blast: Power +2",
		"description": "Green Jasper Tera Blast: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 34,
		"x": "1",
		"y": "1",
		"name": "Green Jasper Tera Blast: Power +2",
		"description": "Green Jasper Tera Blast: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 35,
		"x": "3",
		"y": "0",
		"name": "Green Jasper Tera Blast: Power +2",
		"description": "Green Jasper Tera Blast: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 36,
		"x": "2",
		"y": "1",
		"name": "Green Jasper Tera Blast: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": "1",
		"y": "2",
		"name": "Turbo Turf 2",
		"description": "Quickly charges the move gauge when the terrain is Grassy Terrain.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": "3",
		"y": "1",
		"name": "Impervious",
		"description": "The user’s stats cannot be lowered.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 39,
		"x": "2",
		"y": "2",
		"name": "Shine, Teal Mask!: 1st Move: Restore MP 1",
		"description": "Restores one MP of the user’s move the first time that move is successful each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": "-2",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 41,
		"x": "-3",
		"y": "1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 42,
		"x": "-2",
		"y": "0",
		"name": "Ivy Cudgel: Power +2",
		"description": "Ivy Cudgel: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 43,
		"x": "-1",
		"y": "-1",
		"name": "Green Jasper Tera Blast: Power +2",
		"description": "Green Jasper Tera Blast: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 44,
		"x": "-3",
		"y": "0",
		"name": "Lush Ivy Cudgel: Power +2",
		"description": "Lush Ivy Cudgel: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 45,
		"x": "-2",
		"y": "-1",
		"name": "Shine, Teal Mask!: Brawn Gain 9",
		"description": "Increases the user’s Physical Moves ↑ Next effect by one rank when its move is successful.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": "-1",
		"y": "-2",
		"name": "Grassy Cushion 2",
		"description": "Reduces damage when the user is hit by an attack move while the terrain is Grassy Terrain.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": "-3",
		"y": "-1",
		"name": "Team S-Move: Physical Boost ↑1 9",
		"description": "Increases the user’s Physical Moves ↑ Next effect by one rank after your team’s sync pair uses their sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 48,
		"x": "-2",
		"y": "-2",
		"name": "Shine, Teal Mask!: Durable 9",
		"description": "Applies the Enduring effect to the user when its move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 49,
		"x": "0",
		"y": "-3",
		"name": "Village Teal Mask Tera Blast: Power +25",
		"description": "Village Teal Mask Tera Blast: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 50,
		"x": "0",
		"y": "3",
		"name": "Village Teal Mask Tera Blast: Power +25",
		"description": "Village Teal Mask Tera Blast: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const JULIANA_TERAPAGOS = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 0,
		"y": -2,
		"name": "The Hidden Treasure of Area Zero’s Light",
		"description": "Turns the field of play’s zone into a Normal Zone the first time the user enters a battle each battle. Turns the field of play’s zone into a Normal Zone the first time the user’s Rainbow Jewel Tera Blast is successful each battle. (A Normal Zone powers up Normal-type attacks.) Extends the duration of the Normal Zone when the zone turns into a Normal Zone while the user is on the field.",
		"energy": "0",
		"orb": "5",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 8,
		"x": 0,
		"y": 2,
		"name": "S-Tera & Hit: Free Move Next 9",
		"description": "Applies the Free Move Next effect to the user when its attack move is successful while it is Sync Terastallized.",
		"energy": "0",
		"orb": "5",
		"level": "4",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 9,
		"x": 1,
		"y": -2,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": 2,
		"y": -3,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": 3,
		"y": -4,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 12,
		"x": 1,
		"y": -3,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 13,
		"x": 2,
		"y": -4,
		"name": "Tera Starstorm: Power 2",
		"description": "Tera Starstorm: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 14,
		"x": 3,
		"y": -5,
		"name": "Tera Starstorm: Power 2",
		"description": "Tera Starstorm: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 15,
		"x": 1,
		"y": -4,
		"name": "Tera Starstorm: Power 2",
		"description": "Tera Starstorm: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 16,
		"x": 2,
		"y": -5,
		"name": "Normal Zone: MG → 2",
		"description": "Quickly charges the move gauge when the zone is a Normal Zone.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": 3,
		"y": -6,
		"name": "Potion: MP Refresh 1",
		"description": "Move: Potion",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": 1,
		"y": -5,
		"name": "Tera Starstorm: Hit: Sp. Atk ↓ & Sp. Def ↓ 9",
		"description": "Move: Tera Starstorm",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 19,
		"x": 2,
		"y": -6,
		"name": "Soften Up 1",
		"description": "Critical hits land more easily when the user attacks with a sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 20,
		"x": -1,
		"y": 2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 21,
		"x": -2,
		"y": 3,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 22,
		"x": -3,
		"y": 4,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 23,
		"x": -1,
		"y": 3,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 24,
		"x": -2,
		"y": 4,
		"name": "Kaleidoscopic Tera Starstorm: Power 2",
		"description": "Kaleidoscopic Tera Starstorm: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 25,
		"x": -3,
		"y": 5,
		"name": "Kaleidoscopic Tera Starstorm: Power 2",
		"description": "Kaleidoscopic Tera Starstorm: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 26,
		"x": -1,
		"y": 4,
		"name": "Kaleidoscopic Tera Starstorm: Power 2",
		"description": "Kaleidoscopic Tera Starstorm: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 27,
		"x": -2,
		"y": 5,
		"name": "Kaleidoscopic Tera Starstorm: Move Gauge Refresh 3",
		"description": "Move: Kaleidoscopic Tera Starstorm",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 28,
		"x": -3,
		"y": 6,
		"name": "Normal Zone: HP Recovery 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action when the zone is a Normal Zone.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": -1,
		"y": 5,
		"name": "Kaleidoscopic Tera Starstorm: Move: Special Boost ↑2 9",
		"description": "Move: Kaleidoscopic Tera Starstorm",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 30,
		"x": -2,
		"y": 6,
		"name": "Rainbow Jewel Tera Blast: Power 100",
		"description": "Rainbow Jewel Tera Blast: Power ↑ 100",
		"energy": "8",
		"orb": "96",
		"level": "3",
		"color": "green",
		"icon": "stellar"
	},
	{
		"id": 31,
		"x": 2,
		"y": -1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 32,
		"x": 3,
		"y": -1,
		"name": "Dauntless",
		"description": "Sp. Atk cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": 2,
		"y": 0,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": 1,
		"y": 1,
		"name": "Tera Starstorm: Power 2",
		"description": "Tera Starstorm: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 35,
		"x": 3,
		"y": 0,
		"name": "Kaleidoscopic Tera Starstorm: Power 2",
		"description": "Kaleidoscopic Tera Starstorm: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 36,
		"x": 2,
		"y": 1,
		"name": "Rainbow Jewel Tera Blast: Power 2",
		"description": "Rainbow Jewel Tera Blast: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "stellar"
	},
	{
		"id": 37,
		"x": 1,
		"y": 2,
		"name": "T-Move: Allied Field MG → 9",
		"description": "Applies the Move Gauge Acceleration effect to the allied field of play when the user’s Trainer uses a move.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": 3,
		"y": 1,
		"name": "S-Move: Special Boost ↑2 9",
		"description": "Increases the user’s Special Moves ↑ Next effect by two ranks after using its sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 39,
		"x": 2,
		"y": 2,
		"name": "Brainpower",
		"description": "The more the user’s Sp. Atk is raised, the more it powers up its sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": -2,
		"y": 1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 41,
		"x": -3,
		"y": 1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 42,
		"x": -2,
		"y": 0,
		"name": "Rainbow Jewel Tera Blast: Power 2",
		"description": "Rainbow Jewel Tera Blast: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "stellar"
	},
	{
		"id": 43,
		"x": -1,
		"y": -1,
		"name": "Rainbow Jewel Tera Blast: Power 2",
		"description": "Rainbow Jewel Tera Blast: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "stellar"
	},
	{
		"id": 44,
		"x": -3,
		"y": 0,
		"name": "Rainbow Jewel Tera Blast: Power 2",
		"description": "Rainbow Jewel Tera Blast: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "stellar"
	},
	{
		"id": 45,
		"x": -2,
		"y": -1,
		"name": "Rainbow Jewel Tera Blast: Move Gauge Refresh 3",
		"description": "Move: Rainbow Jewel Tera Blast",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -1,
		"y": -2,
		"name": "Sp. Atk 10",
		"description": "Sp. Atk 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 47,
		"x": -3,
		"y": -1,
		"name": "Endurance",
		"description": "Applies the Enduring effect to the user if its HP is full when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 48,
		"x": -2,
		"y": -2,
		"name": "Normal Zone: Team Moves ↑ 3",
		"description": "Powers up the moves of all allied sync pairs when the zone is a Normal Zone.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 49,
		"x": 0,
		"y": -3,
		"name": "Ancient Indigo Disk Tera Blast: Power 25",
		"description": "Ancient Indigo Disk Tera Blast: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 50,
		"x": 0,
		"y": 3,
		"name": "Ancient Indigo Disk Tera Blast: Power 25",
		"description": "Ancient Indigo Disk Tera Blast: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const MISTY_GOLDUCK = [
	{
		"id": 1,
		"x": "1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "1",
		"y": "0",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "-1",
		"y": "1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "-1",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "1",
		"y": "-2",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": "2",
		"y": "-3",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": "1",
		"y": "-3",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": "3",
		"y": "-4",
		"name": "Dauntless",
		"description": "Sp. Atk cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 11,
		"x": "2",
		"y": "-4",
		"name": "Water Gun: Power +4",
		"description": "Water Gun: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 12,
		"x": "1",
		"y": "-4",
		"name": "Water Gun: Power +4",
		"description": "Water Gun: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 13,
		"x": "3",
		"y": "-5",
		"name": "Water Gun: Power +4",
		"description": "Water Gun: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 14,
		"x": "2",
		"y": "-5",
		"name": "All-Out Offensive!: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": "1",
		"y": "-5",
		"name": "Brainpower",
		"description": "The more the user’s Sp. Atk is raised, the more it powers up its sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": "3",
		"y": "-6",
		"name": "Hypnosis: Accuracy +10",
		"description": "Hypnosis: Accuracy +10",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "green",
		"icon": "psychic"
	},
	{
		"id": 17,
		"x": "2",
		"y": "-6",
		"name": "All-Out Offensive!: Ramp Up 2",
		"description": "Raises the user’s Sp. Atk by two stat ranks when its move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": "-2",
		"y": "1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": "-3",
		"y": "2",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": "-2",
		"y": "2",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 21,
		"x": "-3",
		"y": "3",
		"name": "Water Gun: Power +4",
		"description": "Water Gun: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 22,
		"x": "-1",
		"y": "2",
		"name": "Water Gun: Power +4",
		"description": "Water Gun: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 23,
		"x": "-2",
		"y": "3",
		"name": "Water Gun: Move Gauge Refresh 2",
		"description": "Has a chance (30%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": "-3",
		"y": "4",
		"name": "Hypnosis: Move Gauge Refresh 2",
		"description": "Has a chance (30%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": "-1",
		"y": "3",
		"name": "Charging Infliction 1",
		"description": "Charges the user’s move gauge by one when its Pokémon uses a status move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": "-2",
		"y": "4",
		"name": "1st Use Status P-Move: Team Free Move Next",
		"description": "Applies the Free Move Next effect to all allied sync pairs the first time the user’s Pokémon uses a status move each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": "2",
		"y": "-1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": "3",
		"y": "-1",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": "2",
		"y": "0",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": "1",
		"y": "1",
		"name": "Muddy Water: Power +3",
		"description": "Muddy Water: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 31,
		"x": "3",
		"y": "0",
		"name": "Muddy Water: Power +3",
		"description": "Muddy Water: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 32,
		"x": "2",
		"y": "1",
		"name": "Muddy Water: Move Gauge Refresh 2",
		"description": "Has a chance (30%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": "1",
		"y": "2",
		"name": "First Aid 4",
		"description": "Restores the user’s HP by approximately 40% of its maximum HP the first time it is in a pinch each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": "3",
		"y": "1",
		"name": "Muddy Water: On a Roll 2",
		"description": "Raises the chance of lowering stat values with the additional effects of the user’s moves.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": "2",
		"y": "2",
		"name": "Wide Open",
		"description": "The more the target’s evasiveness is lowered, the more it powers up the user’s moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": "-1",
		"y": "-1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": "-2",
		"y": "-1",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 38,
		"x": "-1",
		"y": "-2",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": "-3",
		"y": "-1",
		"name": "Acuity",
		"description": "Accuracy cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": "-2",
		"y": "-2",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 41,
		"x": "-3",
		"y": "-2",
		"name": "Muddy Water: Power +3",
		"description": "Muddy Water: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 42,
		"x": "-1",
		"y": "-3",
		"name": "Muddy Water: Power +3",
		"description": "Muddy Water: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 43,
		"x": "-2",
		"y": "-3",
		"name": "Muddy Water: Accuracy +15",
		"description": "Muddy Water: Accuracy +15",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 44,
		"x": "-3",
		"y": "-3",
		"name": "Attack Trap 4",
		"description": "Has a chance (50%) of leaving the target trapped when the user’s attack move against it is successful.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": "-1",
		"y": "-4",
		"name": "Stationary Target 3",
		"description": "Powers up the user’s moves when the target is trapped.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": "-2",
		"y": "-4",
		"name": "Hit Trapped Opp: Sp. Def ↓ 9",
		"description": "Lowers the target’s Sp. Def by one stat rank when the user’s attack move is successful against targets that are trapped.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": "0",
		"y": "-3",
		"name": "Open Ocean Dive Water Beam: Power +25",
		"description": "Open Ocean Dive Water Beam: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": "0",
		"y": "3",
		"name": "Open Ocean Dive Water Beam: Power +25",
		"description": "Open Ocean Dive Water Beam: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const MARNIE_GRIMMSNARL = [
	{
		"id": 1,
		"x": "1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "1",
		"y": "0",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "-1",
		"y": "1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "-1",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "0",
		"y": "2",
		"name": "Umbral Tenacity",
		"description": "Prevents the user from flinching, becoming confused, or becoming trapped when the zone is a Dark Zone.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 8,
		"x": "0",
		"y": "4",
		"name": "Max Move: Team Physical & Special Boost 2",
		"description": "Increases the Physical Moves ↑ Next effect and Special Moves ↑ Next effect of all allied sync pairs by two ranks after using the user’s max move.",
		"energy": "10",
		"orb": "120",
		"level": "4",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 9,
		"x": "0",
		"y": "5",
		"name": "Clutch Critical",
		"description": "Except in certain circumstances, successful hits with the user’s following attacks become critical hits: Pokémon’s moves, sync move, or max moves.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 10,
		"x": "0",
		"y": "-2",
		"name": "Umbral Healing 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action when the zone is a Dark Zone.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 11,
		"x": "-1",
		"y": "-3",
		"name": "Dark Zone: Team S-Moves ↑ 3",
		"description": "Powers up the sync moves of all allied sync pairs when the zone is a Dark Zone.",
		"energy": "10",
		"orb": "120",
		"level": "4",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 12,
		"x": "1",
		"y": "-4",
		"name": "1st S-Move: Restore “Super Effective ↑” MP 1",
		"description": "Restores one MP of the user’s SuperEffective ↑ the first time its sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": "2",
		"y": "-1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 14,
		"x": "3",
		"y": "-2",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 15,
		"x": "2",
		"y": "-2",
		"name": "Bite: Power +3",
		"description": "Bite: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 16,
		"x": "1",
		"y": "-2",
		"name": "Bite: Power +3",
		"description": "Bite: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 17,
		"x": "1",
		"y": "-3",
		"name": "Bite: Move Gauge Refresh 9",
		"description": "Charges the user’s move gauge by one when its move is successful.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": "2",
		"y": "-3",
		"name": "Bite: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 19,
		"x": "3",
		"y": "-3",
		"name": "Opp Asleep: Team Moves ↑ 2",
		"description": "Powers up the moves of all allied sync pairs when attacking a target that is asleep.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 20,
		"x": "2",
		"y": "-4",
		"name": "Bite: Aggravation 1",
		"description": "Raises the chance of inflicting the flinching, confused, or trapped condition with the additional effects of moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 21,
		"x": "3",
		"y": "-4",
		"name": "Bite: Move on Opp: Sleep 4",
		"description": "Has a chance (50%) of putting the target to sleep when the user’s move targeting that opponent is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 22,
		"x": "-1",
		"y": "2",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 23,
		"x": "-2",
		"y": "3",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 24,
		"x": "-1",
		"y": "3",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 25,
		"x": "-3",
		"y": "4",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 26,
		"x": "-2",
		"y": "4",
		"name": "Impish False Surrender: Power +3",
		"description": "Impish False Surrender: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 27,
		"x": "-1",
		"y": "4",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": "-3",
		"y": "5",
		"name": "Impish False Surrender: Power +3",
		"description": "Impish False Surrender: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 29,
		"x": "-2",
		"y": "5",
		"name": "Ain’t Goin’ Down Easy!: Move on Ally: Physical Boost ↑1 & Special Boost ↑1 9",
		"description": "When the user’s move targeting an allied sync pair (excluding field effects) is successful, increases the Physical Moves ↑ Next effect and Special Moves ↑ Next effect of the ally affected by the move by one rank.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 30,
		"x": "-1",
		"y": "5",
		"name": "Unfortuitous 9",
		"description": "Lowers one of the target’s following stats by one stat rank at random when the user’s attack move against it is successful: Attack, Defense, Sp. Atk, Sp. Def, Speed, accuracy, or evasiveness.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": "-3",
		"y": "6",
		"name": "G-Max Snooze: Power +100",
		"description": "G-Max Snooze: Power +100",
		"energy": "8",
		"orb": "96",
		"level": "3",
		"color": "dynamax",
		"icon": "dynamax"
	},
	{
		"id": 32,
		"x": "-2",
		"y": "6",
		"name": "Max Move: Team Free Move Next",
		"description": "Applies the Free Move Next effect to all allied sync pairs after using the user’s max move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": "1",
		"y": "1",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": "2",
		"y": "1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 35,
		"x": "1",
		"y": "2",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 36,
		"x": "3",
		"y": "1",
		"name": "Headstrong",
		"description": "Attack cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": "2",
		"y": "2",
		"name": "Impish False Surrender: Power +3",
		"description": "Impish False Surrender: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 38,
		"x": "1",
		"y": "3",
		"name": "Impish False Surrender: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "1",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 39,
		"x": "3",
		"y": "2",
		"name": "Impish False Surrender: Power +3",
		"description": "Impish False Surrender: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 40,
		"x": "2",
		"y": "3",
		"name": "Impish False Surrender: Power +3",
		"description": "Impish False Surrender: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 41,
		"x": "1",
		"y": "4",
		"name": "T-Move: Allied Field MG → 9",
		"description": "Applies the Move Gauge Acceleration effect to the allied field of play when the user’s Trainer uses a move.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 42,
		"x": "3",
		"y": "3",
		"name": "Haymaker",
		"description": "The more the user’s Attack is raised, the more it powers up the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": "2",
		"y": "4",
		"name": "Fierce Entry 2",
		"description": "Raises the user’s Attack by two stat ranks when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": "-2",
		"y": "1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 45,
		"x": "-3",
		"y": "1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 46,
		"x": "-2",
		"y": "0",
		"name": "Bite: Power +3",
		"description": "Bite: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 47,
		"x": "-1",
		"y": "-1",
		"name": "Bite: Power +3",
		"description": "Bite: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 48,
		"x": "-3",
		"y": "0",
		"name": "Bite: Power +3",
		"description": "Bite: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 49,
		"x": "-2",
		"y": "-1",
		"name": "Super Effective ↑: MP Refresh 3",
		"description": "Has a chance (40%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 50,
		"x": "-1",
		"y": "-2",
		"name": "Umbral Acceleration 2",
		"description": "Quickly charges the move gauge when the zone is a Dark Zone.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 51,
		"x": "-3",
		"y": "-1",
		"name": "Adrenaline 1",
		"description": "Reduces the sync move countdown by one the first time the user’s sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 52,
		"x": "-2",
		"y": "-2",
		"name": "Umbral Power 5",
		"description": "Powers up the user’s moves when the zone is a Dark Zone.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 53,
		"x": "0",
		"y": "3",
		"name": "Winning with Everyone’s Cheers Dark Impact: Power +25",
		"description": "Winning with Everyone’s Cheers Dark Impact: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 54,
		"x": "0",
		"y": "-3",
		"name": "Winning with Everyone’s Cheers Dark Impact: Power +25",
		"description": "Winning with Everyone’s Cheers Dark Impact: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const BEDE_RAPIDASH = [
	{
		"id": 1,
		"x": "1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "1",
		"y": "0",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "-1",
		"y": "1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "-1",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "0",
		"y": "-2",
		"name": "Fairy Zone: HP Recovery 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action when the zone is a Fairy Zone.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 8,
		"x": "0",
		"y": "-4",
		"name": "Team Strengthening Status 9",
		"description": "Increases the Physical Moves ↑ Next effect and Special Moves ↑ Next effect of all allied sync pairs by one rank when the user’s Pokémon uses a status move.",
		"energy": "10",
		"orb": "120",
		"level": "4",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 9,
		"x": "-2",
		"y": "-3",
		"name": "1st “Mini Potion All” MP 0: Restore MP 1",
		"description": "Restores one MP of the user’s Mini Potion All the first time the remaining MP for that move is zero each battle.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 10,
		"x": "0",
		"y": "2",
		"name": "Fairy Zone: Attack Move DR 2",
		"description": "Reduces damage when the user is hit by an attack move while the zone is a Fairy Zone.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 11,
		"x": "0",
		"y": "4",
		"name": "Endure Again",
		"description": "Except in certain circumstances, when the user’s Enduring effect activates for the first time and the user has 1 HP remaining, applies the Enduring effect to the user again each battle.",
		"energy": "10",
		"orb": "120",
		"level": "4",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 12,
		"x": "-2",
		"y": "5",
		"name": "S-Move/Max Move: Team Phys & Spec Boost ↑1 9",
		"description": "Increases the Physical Moves ↑ Next effect and Special Moves ↑ Next effect of all allied sync pairs by one rank after using the user’s sync move or max move.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": "1",
		"y": "-2",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 14,
		"x": "2",
		"y": "-3",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 15,
		"x": "1",
		"y": "-3",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 16,
		"x": "3",
		"y": "-4",
		"name": "Unbending",
		"description": "Defense cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": "2",
		"y": "-4",
		"name": "Dazzling Gleam: Power +3",
		"description": "Dazzling Gleam: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 18,
		"x": "1",
		"y": "-4",
		"name": "Dazzling Gleam: Power +3",
		"description": "Dazzling Gleam: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 19,
		"x": "3",
		"y": "-5",
		"name": "Dazzling Gleam: Power +3",
		"description": "Dazzling Gleam: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 20,
		"x": "2",
		"y": "-5",
		"name": "Whimsical Acceleration 2",
		"description": "Quickly charges the move gauge when the zone is a Fairy Zone.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 21,
		"x": "1",
		"y": "-5",
		"name": "MAX Healer 4",
		"description": "Restores the user’s HP by approximately 40% of its maximum HP after using its max move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 22,
		"x": "3",
		"y": "-6",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 23,
		"x": "2",
		"y": "-6",
		"name": "Fairy Zone Extension 3",
		"description": "Extends the duration of the Fairy Zone when the zone turns into a Fairy Zone while the user is on the field.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": "-2",
		"y": "2",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 25,
		"x": "-3",
		"y": "3",
		"name": "Stalwart",
		"description": "Sp. Def cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": "-1",
		"y": "2",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 27,
		"x": "-2",
		"y": "3",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": "-3",
		"y": "4",
		"name": "Idyllic Calm Mind: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": "-1",
		"y": "3",
		"name": "Catalytic Infliction",
		"description": "Applies the Move Gauge Acceleration effect to the allied field of play the first time the user’s Pokémon uses a status move each battle.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 30,
		"x": "-2",
		"y": "4",
		"name": "Defense +10",
		"description": "Defense +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 31,
		"x": "-3",
		"y": "5",
		"name": "Hit: Defense ↓ & Sp. Def ↓ 9",
		"description": "Lowers the target’s Defense and Sp. Def by one stat rank when the user’s attack move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 32,
		"x": "-1",
		"y": "4",
		"name": "Vigilance",
		"description": "Protects the user against critical hits.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": "1",
		"y": "1",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": "2",
		"y": "1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 35,
		"x": "1",
		"y": "2",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 36,
		"x": "3",
		"y": "1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": "2",
		"y": "2",
		"name": "Dazzling Gleam: Power +3",
		"description": "Dazzling Gleam: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 38,
		"x": "1",
		"y": "3",
		"name": "Mini Potion All: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 39,
		"x": "3",
		"y": "2",
		"name": "Dazzling Gleam: Power +3",
		"description": "Dazzling Gleam: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 40,
		"x": "2",
		"y": "3",
		"name": "Gobsmack 9",
		"description": "Leaves the target confused when the user’s attack move against it is successful.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 41,
		"x": "1",
		"y": "4",
		"name": "A Truly Great Pink!: Move: Team Free Move Next 9",
		"description": "Applies the Free Move Next effect to all allied sync pairs when the user’s move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 42,
		"x": "3",
		"y": "3",
		"name": "Max Starfall: Power +100",
		"description": "Max Starfall: Power +100",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "dynamax",
		"icon": "dynamax"
	},
	{
		"id": 43,
		"x": "2",
		"y": "4",
		"name": "Team Sharp Entry 1",
		"description": "Raises the critical-hit rate of all allied sync pairs by one stat rank when the user enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": "-2",
		"y": "0",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 45,
		"x": "-1",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 46,
		"x": "-3",
		"y": "0",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 47,
		"x": "-2",
		"y": "-1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 48,
		"x": "-1",
		"y": "-2",
		"name": "Dazzling Gleam: Move Gauge Refresh 9",
		"description": "Charges the user’s move gauge by one when its move is successful.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 49,
		"x": "-3",
		"y": "-1",
		"name": "Dazzling Gleam: Move Gauge Refresh 2",
		"description": "Has a chance (30%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 50,
		"x": "-2",
		"y": "-2",
		"name": "A Truly Great Pink!: Team Hit and Heal",
		"description": "Applies the Gradual Healing effect to all allied sync pairs when the user’s move is successful.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 51,
		"x": "-1",
		"y": "-3",
		"name": "1st S-Move: Fairy Zone",
		"description": "Turns the field of play’s zone into a Fairy Zone the first time the user’s sync move is used each battle. (A Fairy Zone powers up Fairy-type attacks.)",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 52,
		"x": "-3",
		"y": "-2",
		"name": "Debut: Team Defense ↑ & Sp. Def ↑ 2",
		"description": "Raises the Defense and Sp. Def of all allied sync pairs by two stat ranks the first time the user enters a battle each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 53,
		"x": "0",
		"y": "-3",
		"name": "Pink Legacy Fairy Beam: Power +25",
		"description": "Pink Legacy Fairy Beam: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 54,
		"x": "0",
		"y": "3",
		"name": "Pink Legacy Fairy Beam: Power +25",
		"description": "Pink Legacy Fairy Beam: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]