export const CHASE_PIKACHU = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 0,
		"y": -2,
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 8,
		"x": 0,
		"y": -4,
		"name": "Kanto Analysis: T-Move: Crit Defense 9",
		"description": "Move: Kanto Analysis Applies the Critical-Hit Defense effect to the allied field of play when the user’s Trainer uses a move.",
		"energy": "10",
		"orb": "120",
		"level": "4",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 9,
		"x": -2,
		"y": -3,
		"name": "Sync Burst 1",
		"description": "Restores 1 MP for the user the first time its sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 10,
		"x": 0,
		"y": 2,
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 11,
		"x": 0,
		"y": 4,
		"name": "Staggering 4",
		"description": "Has a chance (50%) of making the target flinch when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "4",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 12,
		"x": -2,
		"y": 5,
		"name": "Mind Games 9",
		"description": "Lowers the target’s Sp. Def by one stat rank when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": 1,
		"y": -2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 14,
		"x": 2,
		"y": -3,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 15,
		"x": 1,
		"y": -3,
		"name": "Thunder Shock: Power 3",
		"description": "Thunder Shock: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 16,
		"x": 3,
		"y": -4,
		"name": "Thunder Shock: Power 3",
		"description": "Thunder Shock: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 17,
		"x": 2,
		"y": -4,
		"name": "Thunder Shock: Power 3",
		"description": "Thunder Shock: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 18,
		"x": 1,
		"y": -4,
		"name": "Circle: MG → 2",
		"description": "Quickly charges the move gauge when a circle applies to the allied field of play.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 19,
		"x": 3,
		"y": -5,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": 2,
		"y": -5,
		"name": "Circle: HP Recovery 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action when a circle applies to the allied field of play.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 21,
		"x": 1,
		"y": -5,
		"name": "Team Sharp Entry 1",
		"description": "Raises the critical-hit rate of all allied sync pairs by 1 stat rank when the user enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 22,
		"x": 3,
		"y": -6,
		"name": "Circle: Attack Move DR 2",
		"description": "Reduces damage when the user is hit by an attack move while a circle applies to the allied field of play.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 23,
		"x": 2,
		"y": -6,
		"name": "Kanto C (Spec) Extension 3",
		"description": "Extends the duration of Kanto Circle (Special) when Kanto Circle (Special) applies to the allied field of play.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -2,
		"y": 2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 25,
		"x": -3,
		"y": 3,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 26,
		"x": -1,
		"y": 2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 27,
		"x": -2,
		"y": 3,
		"name": "Thunder Shock: Power 3",
		"description": "Thunder Shock: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 28,
		"x": -3,
		"y": 4,
		"name": "Thunder Shock: Power 3",
		"description": "Thunder Shock: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 29,
		"x": -1,
		"y": 3,
		"name": "Thunder Shock: Move Gauge Refresh 3",
		"description": "Move: Thunder Shock Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 30,
		"x": -2,
		"y": 4,
		"name": "Thunder Shock: Hostile Environment 9",
		"description": "Move: Thunder Shock Raises the chance of inflicting status conditions with the additional effects of moves.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": -3,
		"y": 5,
		"name": "Team Fist Bump 3",
		"description": "Has a chance (40%) of restoring the HP of all allied sync pairs when the user’s attack move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 32,
		"x": -1,
		"y": 4,
		"name": "Endurance",
		"description": "When the user enters battle with full HP, applies the Enduring effect to it.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": 1,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": 2,
		"y": 1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 35,
		"x": 1,
		"y": 2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 36,
		"x": 3,
		"y": 1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": 2,
		"y": 2,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 38,
		"x": 1,
		"y": 3,
		"name": "Let’s Go, Everyone!: MP Refresh 2",
		"description": "Move: Let’s Go, Everyone! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 39,
		"x": 3,
		"y": 2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": 2,
		"y": 3,
		"name": "Fail Forward 1",
		"description": "Charges the user’s move gauge by 1 when an opponent’s attack move targeting the user misses.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 41,
		"x": 1,
		"y": 4,
		"name": "Adrenaline 1",
		"description": "Reduces the sync move countdown by 1 the first time the user’s sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 42,
		"x": 3,
		"y": 3,
		"name": "Team Sync Regen",
		"description": "Applies the Gradual Healing effect to all allied sync pairs after the user uses a sync move.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": 2,
		"y": 4,
		"name": "Ridicure 3",
		"description": "Has a chance (40%) of restoring the user’s HP by approximately 20% of its maximum HP when an opponent’s attack move targeting the user misses.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -2,
		"y": 0,
		"name": "Lithe",
		"description": "Prevents the user from getting paralyzed.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -1,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 46,
		"x": -3,
		"y": 0,
		"name": "Stalwart",
		"description": "Sp. Def cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": -2,
		"y": -1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 48,
		"x": -1,
		"y": -2,
		"name": "Electric Guard",
		"description": "Reduces damage when the user is attacked by Electric-type moves.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 49,
		"x": -3,
		"y": -1,
		"name": "Unbending",
		"description": "Defense cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 50,
		"x": -2,
		"y": -2,
		"name": "X Sp. Atk All: MP Refresh 2",
		"description": "Move: X Sp. Atk All Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 51,
		"x": -1,
		"y": -3,
		"name": "Team Grand Entry 2",
		"description": "Raises the Sp. Atk of all allied sync pairs by 2 stat ranks when the user enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 52,
		"x": -3,
		"y": -2,
		"name": "X Sp. Atk All: Team Smart Command 9",
		"description": "Move: X Sp. Atk All Increases the Special Moves ↑ Next effect of all allied sync pairs by one rank when the user’s Trainer uses a move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 53,
		"x": 0,
		"y": -3,
		"name": "Running With My Partner Pika Papow: Power 25",
		"description": "Running With My Partner Pika Papow: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 54,
		"x": 0,
		"y": 3,
		"name": "Running With My Partner Pika Papow: Power 25",
		"description": "Running With My Partner Pika Papow: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const WALLY_DELCATTY = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 1,
		"y": -2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 2,
		"y": -3,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 1,
		"y": -3,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": 3,
		"y": -4,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": 2,
		"y": -4,
		"name": "Tackle: Power 4",
		"description": "Tackle: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 12,
		"x": 1,
		"y": -4,
		"name": "Tackle: Power 4",
		"description": "Tackle: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 13,
		"x": 3,
		"y": -5,
		"name": "Tackle: Power 4",
		"description": "Tackle: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 14,
		"x": 2,
		"y": -5,
		"name": "Sp. Def 10",
		"description": "Sp. Def 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 15,
		"x": 1,
		"y": -5,
		"name": "Mini Potion All: MP Refresh 2",
		"description": "Move: Mini Potion All Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": 3,
		"y": -6,
		"name": "On the Ropes 2",
		"description": "Reduces damage when the user is hit by a physical attack move while it is in a pinch.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": 2,
		"y": -6,
		"name": "Mini Potion All: Master Healer 1",
		"description": "Move: Mini Potion All Increases the amount of HP restored by the user’s healing moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": -2,
		"y": 2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -3,
		"y": 3,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": -1,
		"y": 2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 21,
		"x": -2,
		"y": 3,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 22,
		"x": -3,
		"y": 4,
		"name": "Escape Artist",
		"description": "Prevents the user from becoming trapped.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 23,
		"x": -1,
		"y": 3,
		"name": "Growl: Move Gauge Refresh 2",
		"description": "Move: Growl Has a chance (30%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -2,
		"y": 4,
		"name": "Ridicure 1",
		"description": "Has a chance (20%) of restoring the user’s HP by approximately 20% of its maximum HP when an opponent’s attack move targeting the user misses.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": -3,
		"y": 5,
		"name": "Let’s Win For Sure!: Berserk Bunch 1",
		"description": "Move: Let’s Win For Sure! Raises the Attack of all allied sync pairs by 1 stat rank when the user’s move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -1,
		"y": 4,
		"name": "Group Slapdash 9",
		"description": "Raises the Speed of all allied sync pairs by one stat rank when an opponent’s attack move targeting the user misses.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": 1,
		"y": 1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 2,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": 1,
		"y": 2,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": 3,
		"y": 1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 31,
		"x": 2,
		"y": 2,
		"name": "Fast Runner",
		"description": "Evasiveness cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 32,
		"x": 1,
		"y": 3,
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": 3,
		"y": 2,
		"name": "Unbending",
		"description": "Defense cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": 2,
		"y": 3,
		"name": "Defense 10",
		"description": "Defense 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 35,
		"x": 1,
		"y": 4,
		"name": "Let’s Win For Sure!: MP Refresh 2",
		"description": "Move: Let’s Win For Sure! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": 3,
		"y": 3,
		"name": "Revenge Boost 2",
		"description": "Has a chance (30%) of charging the user’s move gauge by one when the user is hit by an attack move.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": 2,
		"y": 4,
		"name": "Let’s Win For Sure!: Hit and Heal 9",
		"description": "Move: Let’s Win For Sure! Applies the Gradual Healing effect to the user when its move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": -2,
		"y": 0,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": -3,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 41,
		"x": -2,
		"y": -1,
		"name": "Tackle: Power 4",
		"description": "Tackle: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 42,
		"x": -1,
		"y": -2,
		"name": "Tackle: Move Gauge Refresh 2",
		"description": "Move: Tackle Has a chance (30%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": -3,
		"y": -1,
		"name": "Tackle: Power 4",
		"description": "Tackle: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 44,
		"x": -2,
		"y": -2,
		"name": "Tackle: Flabbergast 2",
		"description": "Move: Tackle Has a chance (30%) of leaving the target confused when a move targeting that opponent is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -1,
		"y": -3,
		"name": "Enfeeble 1",
		"description": "Lowers the Defense of all opposing sync pairs by 1 stat rank when the user enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -3,
		"y": -2,
		"name": "Catalytic Acceleration",
		"description": "Applies the Move Gauge Acceleration effect to the allied field of play after using the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "Becoming Stronger Normal Impact: Power 25",
		"description": "Becoming Stronger Normal Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "Becoming Stronger Normal Impact: Power 25",
		"description": "Becoming Stronger Normal Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const PETEY_PIKACHU = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 1,
		"y": -2,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 2,
		"y": -3,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 1,
		"y": -3,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": 3,
		"y": -4,
		"name": "Electroweb: Power 3",
		"description": "Electroweb: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 11,
		"x": 2,
		"y": -4,
		"name": "Electroweb: Power 3",
		"description": "Electroweb: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 12,
		"x": 1,
		"y": -4,
		"name": "Electroweb: Power 3",
		"description": "Electroweb: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 13,
		"x": 3,
		"y": -5,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 14,
		"x": 2,
		"y": -5,
		"name": "Sp. Atk 10",
		"description": "Sp. Atk 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 15,
		"x": 1,
		"y": -5,
		"name": "Static Shock 5",
		"description": "Powers up the user’s sync move when the target is paralyzed.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": 3,
		"y": -6,
		"name": "Dauntless",
		"description": "Sp. Atk cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": 2,
		"y": -6,
		"name": "First Aid 2",
		"description": "Restores the user’s HP by approximately 20% of its maximum HP the first time it is in a pinch each battle.",
		"energy": "8",
		"orb": "96",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": -2,
		"y": 1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -3,
		"y": 2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": -2,
		"y": 2,
		"name": "Discharge: Power 2",
		"description": "Discharge: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 21,
		"x": -3,
		"y": 3,
		"name": "Discharge: Power 2",
		"description": "Discharge: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 22,
		"x": -1,
		"y": 2,
		"name": "Discharge: Power 2",
		"description": "Discharge: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 23,
		"x": -2,
		"y": 3,
		"name": "HP 20",
		"description": "HP 20",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 24,
		"x": -3,
		"y": 4,
		"name": "Healthy Healing",
		"description": "Applies the Gradual Healing effect to the user when its HP is full when it enters a battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": -1,
		"y": 3,
		"name": "Hem In 9",
		"description": "Lowers the target’s evasiveness by 1 stat rank when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -2,
		"y": 4,
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": 2,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 3,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": 2,
		"y": 0,
		"name": "Discharge: Power 2",
		"description": "Discharge: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 30,
		"x": 1,
		"y": 1,
		"name": "Discharge: Power 2",
		"description": "Discharge: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 31,
		"x": 3,
		"y": 0,
		"name": "Discharge: Move Gauge Refresh 3",
		"description": "Move: Discharge Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 32,
		"x": 2,
		"y": 1,
		"name": "X Speed: Move Gauge Refresh 9",
		"description": "Move: X Speed Charges the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": 1,
		"y": 2,
		"name": "Paralyzed Opp Fail ↑ 2",
		"description": "Raises the chance that an opponent’s move will fail due to paralysis.",
		"energy": "8",
		"orb": "96",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": 3,
		"y": 1,
		"name": "X Speed: MP Refresh 2",
		"description": "Move: X Speed Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 2,
		"y": 2,
		"name": "Paralysis Synergy 3",
		"description": "Powers up the user’s moves when the target is paralyzed.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": -1,
		"y": -1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": -2,
		"y": -1,
		"name": "Clearheaded",
		"description": "Prevents the user from becoming confused.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": -1,
		"y": -2,
		"name": "Electroweb: Power 3",
		"description": "Electroweb: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 39,
		"x": -3,
		"y": -1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": -2,
		"y": -2,
		"name": "Electroweb: Power 3",
		"description": "Electroweb: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 41,
		"x": -3,
		"y": -2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 42,
		"x": -1,
		"y": -3,
		"name": "Electroweb: Accuracy 5",
		"description": "Electroweb: Accuracy ↑ 5",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 43,
		"x": -2,
		"y": -3,
		"name": "Electroweb: Move Gauge Refresh 3",
		"description": "Move: Electroweb Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -3,
		"y": -3,
		"name": "Pika! Piiika!: MP Refresh 2",
		"description": "Move: Pika! Piiika! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -1,
		"y": -4,
		"name": "Pika! Piiika!: Barricade 1",
		"description": "Move: Pika! Piiika! Raises the user’s Sp. Def by 1 stat rank when its move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -2,
		"y": -4,
		"name": "Sharp Entry 1",
		"description": "Raises the user’s critical-hit rate by 1 stat rank when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "Double Pikachu Electric Beam: Power 25",
		"description": "Double Pikachu Electric Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "Double Pikachu Electric Beam: Power 25",
		"description": "Double Pikachu Electric Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const FALKNER_NOCTOWL = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 1,
		"y": -2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 2,
		"y": -3,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 1,
		"y": -3,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": 3,
		"y": -4,
		"name": "Air Cutter: Power 4",
		"description": "Air Cutter: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 11,
		"x": 2,
		"y": -4,
		"name": "Air Cutter: Power 4",
		"description": "Air Cutter: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 12,
		"x": 1,
		"y": -4,
		"name": "Air Cutter: Power 4",
		"description": "Air Cutter: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 13,
		"x": 3,
		"y": -5,
		"name": "Air Cutter: Accuracy 5",
		"description": "Air Cutter: Accuracy ↑ 5",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 14,
		"x": 2,
		"y": -5,
		"name": "Ghost Guard",
		"description": "Reduces damage when the user is attacked by Ghost-type moves.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 1,
		"y": -5,
		"name": "Hit: Team Attack ↑ 9",
		"description": "Raises the Attack of all allied sync pairs by 1 stat rank when the user’s attack move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": 3,
		"y": -6,
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": 2,
		"y": -6,
		"name": "Hit Inter Opp: HP Recovery 9",
		"description": "Restores the user’s HP when its attack move is successful against a flinching, confused, or trapped opponent.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": -2,
		"y": 2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -3,
		"y": 3,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": -1,
		"y": 2,
		"name": "Air Cutter: Power 4",
		"description": "Air Cutter: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 21,
		"x": -2,
		"y": 3,
		"name": "Air Cutter: Power 4",
		"description": "Air Cutter: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 22,
		"x": -3,
		"y": 4,
		"name": "Air Cutter: Move Gauge Refresh 2",
		"description": "Move: Air Cutter Has a chance (30%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 23,
		"x": -1,
		"y": 3,
		"name": "Revenge Boost 4",
		"description": "Has a chance (50%) of charging the user’s move gauge by one when the user is hit by an attack move.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -2,
		"y": 4,
		"name": "Fast-Track 9",
		"description": "Raises the user’s Speed by one stat rank when its Pokémon uses a move.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": -3,
		"y": 5,
		"name": "Air Cutter: Staggering 3",
		"description": "Move: Air Cutter Has a chance (40%) of making the target flinch when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -1,
		"y": 4,
		"name": "Endurance",
		"description": "When the user enters battle with full HP, applies the Enduring effect to it.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": 1,
		"y": 1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 2,
		"y": 1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": 1,
		"y": 2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": 3,
		"y": 1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 31,
		"x": 2,
		"y": 2,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 32,
		"x": 1,
		"y": 3,
		"name": "Stalwart",
		"description": "Sp. Def cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": 3,
		"y": 2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": 2,
		"y": 3,
		"name": "Potion: Master Healer 1",
		"description": "Move: Potion Increases the amount of HP restored by the user’s healing moves.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 1,
		"y": 4,
		"name": "Potion: Master Healer 1",
		"description": "Move: Potion Increases the amount of HP restored by the user’s healing moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": 3,
		"y": 3,
		"name": "Potion: MP Refresh 2",
		"description": "Move: Potion Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": 2,
		"y": 4,
		"name": "Potion: MP Refresh 2",
		"description": "Move: Potion Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": -2,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -1,
		"y": -1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": -3,
		"y": 0,
		"name": "Acuity",
		"description": "Accuracy cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 41,
		"x": -2,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 42,
		"x": -1,
		"y": -2,
		"name": "We Can Still Fly!: MP Refresh 2",
		"description": "Move: We Can Still Fly! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": -3,
		"y": -1,
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -2,
		"y": -2,
		"name": "Team Sync Regen",
		"description": "Applies the Gradual Healing effect to all allied sync pairs after the user uses a sync move.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -1,
		"y": -3,
		"name": "Hit: Team Sp. Atk ↑ 9",
		"description": "Raises the Sp. Atk of all allied sync pairs by 1 stat rank when the user’s attack move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -3,
		"y": -2,
		"name": "Adrenaline 1",
		"description": "Reduces the sync move countdown by 1 the first time the user’s sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "Silent Wings Flying Beam: Power 25",
		"description": "Silent Wings Flying Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "Silent Wings Flying Beam: Power 25",
		"description": "Silent Wings Flying Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const VICTOR_GREEDENT = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 1,
		"y": -2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 2,
		"y": -3,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 1,
		"y": -3,
		"name": "Tackle: Power 3",
		"description": "Tackle: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 10,
		"x": 3,
		"y": -4,
		"name": "Tackle: Power 3",
		"description": "Tackle: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 11,
		"x": 2,
		"y": -4,
		"name": "Tackle: Power 3",
		"description": "Tackle: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 12,
		"x": 1,
		"y": -4,
		"name": "Tackle: Power 3",
		"description": "Tackle: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 13,
		"x": 3,
		"y": -5,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 14,
		"x": 2,
		"y": -5,
		"name": "Danger Dodge 2",
		"description": "Raises the user’s evasiveness by 2 stat ranks the first time its HP drops to half or below each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 1,
		"y": -5,
		"name": "Hit: Team Attack ↑ 9",
		"description": "Raises the Attack of all allied sync pairs by 1 stat rank when the user’s attack move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": 3,
		"y": -6,
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": 2,
		"y": -6,
		"name": "Hit: Team Sp. Atk ↑ 9",
		"description": "Raises the Sp. Atk of all allied sync pairs by 1 stat rank when the user’s attack move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": -2,
		"y": 2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -3,
		"y": 3,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": -1,
		"y": 2,
		"name": "Tackle: Power 3",
		"description": "Tackle: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 21,
		"x": -2,
		"y": 3,
		"name": "Tackle: Power 3",
		"description": "Tackle: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 22,
		"x": -3,
		"y": 4,
		"name": "Tackle: Move Gauge Refresh 3",
		"description": "Move: Tackle Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 23,
		"x": -1,
		"y": 3,
		"name": "Speed 10",
		"description": "Speed 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 24,
		"x": -2,
		"y": 4,
		"name": "On the Ropes 2",
		"description": "Reduces damage when the user is hit by a physical attack move while it is in a pinch.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": -3,
		"y": 5,
		"name": "Discombobulate 4",
		"description": "Has a chance (50%) of lowering the target’s accuracy by one stat rank when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -1,
		"y": 4,
		"name": "Sitrus Berry: Master Healer 1",
		"description": "Move: Sitrus Berry Increases the amount of HP restored by the user’s healing moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": 1,
		"y": 1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 2,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": 1,
		"y": 2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": 3,
		"y": 1,
		"name": "Hyper Belch: Power 3",
		"description": "Hyper Belch: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 31,
		"x": 2,
		"y": 2,
		"name": "Hyper Belch: Power 3",
		"description": "Hyper Belch: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 32,
		"x": 1,
		"y": 3,
		"name": "Hyper Belch: Power 3",
		"description": "Hyper Belch: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 33,
		"x": 3,
		"y": 2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": 2,
		"y": 3,
		"name": "Gobsmack 4",
		"description": "Has a chance (50%) of leaving the target confused when the user’s attack move against it is successful.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 1,
		"y": 4,
		"name": "Status Immunity",
		"description": "Status conditions cannot be inflicted on the user.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": 3,
		"y": 3,
		"name": "Dashing Team 5",
		"description": "Has a chance (60%) of raising the Speed of all allied sync pairs by one stat rank when the user’s attack move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": 2,
		"y": 4,
		"name": "Revenge Boost 9",
		"description": "Charges the user’s move gauge by one when it is hit by an attack move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": -2,
		"y": 0,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -1,
		"y": -1,
		"name": "Unbending",
		"description": "Defense cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": -3,
		"y": 0,
		"name": "Hyper Belch: Power 3",
		"description": "Hyper Belch: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 41,
		"x": -2,
		"y": -1,
		"name": "Hyper Belch: Power 3",
		"description": "Hyper Belch: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 42,
		"x": -1,
		"y": -2,
		"name": "Hyper Belch: Move Gauge Refresh 3",
		"description": "Move: Hyper Belch Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": -3,
		"y": -1,
		"name": "Ghost Guard",
		"description": "Reduces damage when the user is attacked by Ghost-type moves.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -2,
		"y": -2,
		"name": "Cooking Prep!: MP Refresh 2",
		"description": "Move: Cooking Prep! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -1,
		"y": -3,
		"name": "Cooking Prep!: Move: Team Def ↑ & Sp. Def ↑ 9",
		"description": "Move: Cooking Prep! Raises the Defense and Sp. Def of all allied sync pairs by 1 stat rank when the user’s move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -3,
		"y": -2,
		"name": "Adrenaline 1",
		"description": "Reduces the sync move countdown by 1 the first time the user’s sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "The Joys of Cooking Normal Impact: Power 25",
		"description": "The Joys of Cooking Normal Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "The Joys of Cooking Normal Impact: Power 25",
		"description": "The Joys of Cooking Normal Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const CANDICE_DARMANITAN = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 1,
		"y": -2,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 2,
		"y": -3,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 3,
		"y": -4,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": 1,
		"y": -3,
		"name": "Icicle Crash: Power 3",
		"description": "Icicle Crash: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 11,
		"x": 2,
		"y": -4,
		"name": "Icicle Crash: Power 3",
		"description": "Icicle Crash: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 12,
		"x": 3,
		"y": -5,
		"name": "Icicle Crash: Power 3",
		"description": "Icicle Crash: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 13,
		"x": 1,
		"y": -4,
		"name": "Icicle Crash: Accuracy 10",
		"description": "Icicle Crash: Accuracy ↑ 10",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 14,
		"x": 2,
		"y": -5,
		"name": "Icicle Crash: Move Gauge Refresh 3",
		"description": "Move: Icicle Crash Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 3,
		"y": -6,
		"name": "Entry Freebie",
		"description": "Applies the Free Move Next effect to the user when it enters a battle.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": 1,
		"y": -5,
		"name": "Icicle Crash: Aggravation 1",
		"description": "Move: Icicle Crash Raises the chance of inflicting the flinching, confused, or trapped condition with the additional effects of moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": 2,
		"y": -6,
		"name": "Combo Freebie 3",
		"description": "Has a chance (40%) of applying the Free Move Next effect to the user when its attack move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": -1,
		"y": 2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -2,
		"y": 3,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": -3,
		"y": 4,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 21,
		"x": -1,
		"y": 3,
		"name": "Icicle Crash: Power 3",
		"description": "Icicle Crash: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 22,
		"x": -2,
		"y": 4,
		"name": "Icicle Crash: Power 3",
		"description": "Icicle Crash: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 23,
		"x": -3,
		"y": 5,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 24,
		"x": -1,
		"y": 4,
		"name": "Potion: MP Refresh 2",
		"description": "Move: Potion Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": -2,
		"y": 5,
		"name": "Headstrong",
		"description": "Attack cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -3,
		"y": 6,
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": -1,
		"y": 5,
		"name": "Fierce Entry 2",
		"description": "Raises the user’s Attack by 2 stat ranks when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 28,
		"x": -2,
		"y": 6,
		"name": "Furious Brawn",
		"description": "The more the user’s Attack is raised, the more it powers up the user’s moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": 2,
		"y": -1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": 3,
		"y": -1,
		"name": "Snow Shelter",
		"description": "Protects the user from damage from a hailstorm.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": 2,
		"y": 0,
		"name": "Fighting Spirit Icicle Crash: Power 3",
		"description": "Fighting Spirit Icicle Crash: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 32,
		"x": 1,
		"y": 1,
		"name": "Fighting Spirit Icicle Crash: Power 3",
		"description": "Fighting Spirit Icicle Crash: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 33,
		"x": 3,
		"y": 0,
		"name": "Fighting Spirit Icicle Crash: Power 3",
		"description": "Fighting Spirit Icicle Crash: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 34,
		"x": 2,
		"y": 1,
		"name": "Hasty Hail 2",
		"description": "Quickly charges the move gauge during a hailstorm.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 1,
		"y": 2,
		"name": "Healing Hail 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action during a hailstorm.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": 3,
		"y": 1,
		"name": "Defense Crush 9",
		"description": "Lowers the target’s Defense by one stat rank when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": 2,
		"y": 2,
		"name": "Hit: Physical Boost ↑1 3",
		"description": "Has a chance (40%) of increasing the user’s Physical Moves ↑ Next effect by 1 rank when its attack move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": -2,
		"y": 1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -3,
		"y": 1,
		"name": "Unflappable",
		"description": "Prevents the user from flinching.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": -2,
		"y": 0,
		"name": "Fighting Spirit Icicle Crash: Power 3",
		"description": "Fighting Spirit Icicle Crash: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 41,
		"x": -1,
		"y": -1,
		"name": "Fighting Spirit Icicle Crash: Power 3",
		"description": "Fighting Spirit Icicle Crash: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ice"
	},
	{
		"id": 42,
		"x": -3,
		"y": 0,
		"name": "Double Down 3",
		"description": "Powers up the user’s sync moves that are super effective.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": -2,
		"y": -1,
		"name": "Attack 10",
		"description": "Attack 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 44,
		"x": -1,
		"y": -2,
		"name": "Wrap It Up!: MP Refresh 2",
		"description": "Move: Wrap It Up! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -3,
		"y": -1,
		"name": "Haymaker",
		"description": "The more the user’s Attack is raised, the more it powers up the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -2,
		"y": -2,
		"name": "Vigilance",
		"description": "Protects the user against critical hits.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "Flavor of Memories Ice Impact: Power 25",
		"description": "Flavor of Memories Ice Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "Flavor of Memories Ice Impact: Power 25",
		"description": "Flavor of Memories Ice Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const PLAYER_ALCREMIE = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 1,
		"y": -2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 2,
		"y": -3,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 1,
		"y": -3,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": 3,
		"y": -4,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": 2,
		"y": -4,
		"name": "Tackle: Power 3",
		"description": "Tackle: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 12,
		"x": 1,
		"y": -4,
		"name": "Tackle: Power 3",
		"description": "Tackle: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 13,
		"x": 3,
		"y": -5,
		"name": "Tackle: Power 3",
		"description": "Tackle: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 14,
		"x": 2,
		"y": -5,
		"name": "Tackle: Move Gauge Refresh 2",
		"description": "Move: Tackle Has a chance (30%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 1,
		"y": -5,
		"name": "Dazzling Gleam: Move Gauge Refresh 9",
		"description": "Move: Dazzling Gleam Charges the user’s move gauge by one when its move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": 3,
		"y": -6,
		"name": "Tackle: Trip Up 4",
		"description": "Move: Tackle Has a chance (50%) of lowering the target’s Speed by one stat rank when the user’s attack move against it is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": 2,
		"y": -6,
		"name": "Whip It Up!: Berserk Bunch 1",
		"description": "Move: Whip It Up! Raises the Attack of all allied sync pairs by 1 stat rank when the user’s move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": -2,
		"y": 2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -3,
		"y": 3,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": -1,
		"y": 2,
		"name": "Dazzling Gleam: Power 4",
		"description": "Dazzling Gleam: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 21,
		"x": -2,
		"y": 3,
		"name": "Dazzling Gleam: Power 4",
		"description": "Dazzling Gleam: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 22,
		"x": -3,
		"y": 4,
		"name": "Dazzling Gleam: Power 4",
		"description": "Dazzling Gleam: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 23,
		"x": -1,
		"y": 3,
		"name": "Healthy Healing",
		"description": "Applies the Gradual Healing effect to the user when its HP is full when it enters a battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -2,
		"y": 4,
		"name": "Whip It Up!: MP Refresh 2",
		"description": "Move: Whip It Up! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": -3,
		"y": 5,
		"name": "Whip It Up!: All Ramped Up 1",
		"description": "Move: Whip It Up! Raises the Sp. Atk of all allied sync pairs by 1 stat rank when the user’s move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -1,
		"y": 4,
		"name": "Dazzling Gleam: Gobsmack 4",
		"description": "Move: Dazzling Gleam Has a chance (50%) of leaving the target confused when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": 1,
		"y": 1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 2,
		"y": 1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": 1,
		"y": 2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": 3,
		"y": 1,
		"name": "Dazzling Gleam: Power 4",
		"description": "Dazzling Gleam: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 31,
		"x": 2,
		"y": 2,
		"name": "Dazzling Gleam: Power 4",
		"description": "Dazzling Gleam: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 32,
		"x": 1,
		"y": 3,
		"name": "Defense 10",
		"description": "Defense 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 33,
		"x": 3,
		"y": 2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": 2,
		"y": 3,
		"name": "Dragon Guard",
		"description": "Reduces damage when the user is attacked by Dragon-type moves.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 1,
		"y": 4,
		"name": "Mini Potion All: MP Refresh 2",
		"description": "Move: Mini Potion All Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": 3,
		"y": 3,
		"name": "HP 20",
		"description": "HP 20",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": 2,
		"y": 4,
		"name": "Mini Potion All: Master Healer 1",
		"description": "Move: Mini Potion All Increases the amount of HP restored by the user’s healing moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": -2,
		"y": 0,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -1,
		"y": -1,
		"name": "Tackle: Power 3",
		"description": "Tackle: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 40,
		"x": -3,
		"y": 0,
		"name": "Wide Awake",
		"description": "Prevents the user from falling asleep.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 41,
		"x": -2,
		"y": -1,
		"name": "Tackle: Power 3",
		"description": "Tackle: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 42,
		"x": -1,
		"y": -2,
		"name": "Stalwart",
		"description": "Sp. Def cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": -3,
		"y": -1,
		"name": "Sp. Def 10",
		"description": "Sp. Def 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 44,
		"x": -2,
		"y": -2,
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -1,
		"y": -3,
		"name": "Catalyst",
		"description": "Applies the Move Gauge Acceleration effect to the allied field of play the first time the user’s sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -3,
		"y": -2,
		"name": "First Aid 2",
		"description": "Restores the user’s HP by approximately 20% of its maximum HP the first time it is in a pinch each battle.",
		"energy": "8",
		"orb": "96",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "Favorite Flavor Fairy Beam: Power 25",
		"description": "Favorite Flavor Fairy Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "Favorite Flavor Fairy Beam: Power 25",
		"description": "Favorite Flavor Fairy Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const GLADION_MAGEARNA = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 1,
		"y": -2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 2,
		"y": -3,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 3,
		"y": -4,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": 1,
		"y": -3,
		"name": "Fleur Cannon: Power 2",
		"description": "Fleur Cannon: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 11,
		"x": 2,
		"y": -4,
		"name": "Sand Shelter",
		"description": "Protects the user from damage from a sandstorm.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 12,
		"x": 3,
		"y": -5,
		"name": "Fleur Cannon: Power 2",
		"description": "Fleur Cannon: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 13,
		"x": 1,
		"y": -4,
		"name": "Fleur Cannon: Power 2",
		"description": "Fleur Cannon: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 14,
		"x": 2,
		"y": -5,
		"name": "Fleur Cannon: Accuracy 10",
		"description": "Fleur Cannon: Accuracy ↑ 10",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 15,
		"x": 3,
		"y": -6,
		"name": "Superduper Effective 2",
		"description": "Powers up moves that are super effective.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": 1,
		"y": -5,
		"name": "Discourage 2",
		"description": "Lowers the Sp. Atk of all opposing sync pairs by 2 stat ranks when the user enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": 2,
		"y": -6,
		"name": "S-Move on Opp: Sp. Atk ↓ 4",
		"description": "Lowers the target’s Sp. Atk by 4 stat ranks when the user’s sync move targeting that opponent is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": -1,
		"y": 2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -2,
		"y": 3,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": -3,
		"y": 4,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 21,
		"x": -1,
		"y": 3,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 22,
		"x": -2,
		"y": 4,
		"name": "Piercing Fleur Cannon: Power 3",
		"description": "Piercing Fleur Cannon: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 23,
		"x": -3,
		"y": 5,
		"name": "Piercing Fleur Cannon: Power 3",
		"description": "Piercing Fleur Cannon: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 24,
		"x": -1,
		"y": 4,
		"name": "Piercing Fleur Cannon: Power 3",
		"description": "Piercing Fleur Cannon: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 25,
		"x": -2,
		"y": 5,
		"name": "Super Syncer",
		"description": "Applies the Supereffective ↑ Next effect to the user the first time its sync move is used each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -3,
		"y": 6,
		"name": "Sync Regen",
		"description": "Applies the Gradual Healing effect to the user after using its sync move.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": -1,
		"y": 5,
		"name": "Brainpower",
		"description": "The more the user’s Sp. Atk is raised, the more it powers up the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 28,
		"x": -2,
		"y": 6,
		"name": "1st S-Move: Restore B-Move MP 1",
		"description": "Restores 1 MP of the user’s buddy move the first time its sync move is used each battle.",
		"energy": "12",
		"orb": "144",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": 2,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": 3,
		"y": -1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 31,
		"x": 2,
		"y": 0,
		"name": "Piercing Fleur Cannon: Power 3",
		"description": "Piercing Fleur Cannon: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 32,
		"x": 1,
		"y": 1,
		"name": "Piercing Fleur Cannon: Power 3",
		"description": "Piercing Fleur Cannon: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 33,
		"x": 3,
		"y": 0,
		"name": "Speedster’s Sync 3",
		"description": "Powers up the user’s sync move when its Speed is raised.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": 2,
		"y": 1,
		"name": "X Speed +: MP Refresh 2",
		"description": "Move: X Speed + Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 1,
		"y": 2,
		"name": "My Soul Is Shaking!: MP Refresh 2",
		"description": "Move: My Soul Is Shaking! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": 3,
		"y": 1,
		"name": "X Speed +: BOGO 9",
		"description": "Move: X Speed + Applies the Free Move Next effect to the user when its move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": 2,
		"y": 2,
		"name": "My Soul Is Shaking!: Propulsion 9",
		"description": "Move: My Soul Is Shaking! Reduces the user’s sync move countdown by one when its move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": -2,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -3,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": -2,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 41,
		"x": -1,
		"y": -1,
		"name": "Fleur Cannon: Power 2",
		"description": "Fleur Cannon: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 42,
		"x": -3,
		"y": 0,
		"name": "Fleur Cannon: Power 2",
		"description": "Fleur Cannon: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 43,
		"x": -2,
		"y": -1,
		"name": "Fleur Cannon: Move Gauge Refresh 3",
		"description": "Move: Fleur Cannon Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -1,
		"y": -2,
		"name": "KO Opp: Special Boost ↑2 9",
		"description": "Increases the user’s Special Moves ↑ Next effect by 2 ranks when it knocks out an opponent with a move.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -3,
		"y": -1,
		"name": "T-Move: Special Boost ↑1 9",
		"description": "Increases the user’s Special Moves ↑ Next effect by 1 rank when its Trainer uses a move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -2,
		"y": -2,
		"name": "Overpower",
		"description": "The more the target’s Sp. Atk is lowered, the more it powers up the user’s moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "Gentle Souls Fleur Cannon: Power 25",
		"description": "Gentle Souls Fleur Cannon: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "fairy"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "Gentle Souls Fleur Cannon: Power 25",
		"description": "Gentle Souls Fleur Cannon: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "fairy"
	}
]

export const RILEY_LUCARIO = [
	{
		"id": 1,
		"x": -1,
		"y": 0,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": -1,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": 1,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": 1,
		"y": -1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 2,
		"y": -1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 3,
		"y": -2,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 2,
		"y": -2,
		"name": "Iron Tail: Power 3",
		"description": "Iron Tail: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "steel"
	},
	{
		"id": 10,
		"x": 1,
		"y": -2,
		"name": "Iron Tail: Power 3",
		"description": "Iron Tail: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "steel"
	},
	{
		"id": 11,
		"x": 3,
		"y": -3,
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 12,
		"x": 2,
		"y": -3,
		"name": "Iron Tail: Move Gauge Refresh 3",
		"description": "Move: Iron Tail Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": 1,
		"y": -3,
		"name": "Testing Our Skills!: Shielding Strikes 1",
		"description": "Move: Testing Our Skills! Raises the user’s Defense by 1 stat rank when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 14,
		"x": 3,
		"y": -4,
		"name": "Testing Our Skills!: MP Refresh 2",
		"description": "Move: Testing Our Skills! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 2,
		"y": -4,
		"name": "Brawn Sync 5",
		"description": "Powers up the user’s sync move when its Attack is raised.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": -2,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 17,
		"x": -3,
		"y": 2,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 18,
		"x": -2,
		"y": 2,
		"name": "Close Combat: Power 3",
		"description": "Close Combat: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 19,
		"x": -1,
		"y": 2,
		"name": "Close Combat: Power 3",
		"description": "Close Combat: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 20,
		"x": -3,
		"y": 3,
		"name": "Close Combat: Move Gauge Refresh 3",
		"description": "Move: Close Combat Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 21,
		"x": -2,
		"y": 3,
		"name": "Stalwart",
		"description": "Sp. Def cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 22,
		"x": -1,
		"y": 3,
		"name": "Dire Hit +: MP Refresh 2",
		"description": "Move: Dire Hit + Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 23,
		"x": -3,
		"y": 4,
		"name": "Sharp Entry 1",
		"description": "Raises the user’s critical-hit rate by 1 stat rank when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -2,
		"y": 4,
		"name": "Amped Up 1",
		"description": "Raises the user’s Speed by 1 stat rank when it lands a critical hit.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": 1,
		"y": 1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 26,
		"x": 2,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 27,
		"x": 3,
		"y": 1,
		"name": "Escape Artist",
		"description": "Prevents the user from becoming trapped.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 28,
		"x": 1,
		"y": 2,
		"name": "Close Combat: Power 3",
		"description": "Close Combat: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 29,
		"x": 2,
		"y": 2,
		"name": "Close Combat: Power 3",
		"description": "Close Combat: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 30,
		"x": 3,
		"y": 2,
		"name": "Close Combat: Power 3",
		"description": "Close Combat: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fighting"
	},
	{
		"id": 31,
		"x": 1,
		"y": 3,
		"name": "Unbending",
		"description": "Defense cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 32,
		"x": 2,
		"y": 3,
		"name": "Dire Hit +: Fleet Feet 1",
		"description": "Move: Dire Hit + Raises the user’s Speed by 1 stat rank when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": 3,
		"y": 3,
		"name": "Sync Freebie",
		"description": "Applies the Free Move Next effect to the user after using its sync move.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": 1,
		"y": 4,
		"name": "Max Knuckle: Power 100",
		"description": "Max Knuckle: Power ↑ 100",
		"energy": "8",
		"orb": "96",
		"level": "3",
		"color": "dynamax",
		"icon": "dynamax"
	},
	{
		"id": 35,
		"x": 2,
		"y": 4,
		"name": "Super Syncer",
		"description": "Applies the Supereffective ↑ Next effect to the user the first time its sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": -1,
		"y": -1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": -2,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 38,
		"x": -3,
		"y": -1,
		"name": "Iron Tail: Power 3",
		"description": "Iron Tail: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "steel"
	},
	{
		"id": 39,
		"x": -1,
		"y": -2,
		"name": "Iron Tail: Power 3",
		"description": "Iron Tail: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "steel"
	},
	{
		"id": 40,
		"x": -2,
		"y": -2,
		"name": "Iron Tail: Power 3",
		"description": "Iron Tail: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "steel"
	},
	{
		"id": 41,
		"x": -3,
		"y": -2,
		"name": "Sand Shelter",
		"description": "Protects the user from damage from a sandstorm.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 42,
		"x": -1,
		"y": -3,
		"name": "Iron Tail: Accuracy 10",
		"description": "Iron Tail: Accuracy ↑ 10",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "green",
		"icon": "steel"
	},
	{
		"id": 43,
		"x": -2,
		"y": -3,
		"name": "Iron Tail: On a Roll 1",
		"description": "Move: Iron Tail Raises the chance of lowering stat values with the additional effects of the user’s moves.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -3,
		"y": -3,
		"name": "Pinpoint Entry 1",
		"description": "Raises the user’s accuracy by 1 stat rank when it enters a battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -1,
		"y": -4,
		"name": "Max Steelspike: Power 100",
		"description": "Max Steelspike: Power ↑ 100",
		"energy": "8",
		"orb": "96",
		"level": "3",
		"color": "dynamax",
		"icon": "dynamax"
	},
	{
		"id": 46,
		"x": -2,
		"y": -4,
		"name": "Ramming Speed",
		"description": "The more the user’s Speed is raised, the more it powers up the user’s moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "Aura Driven Fighting Impact: Power 25",
		"description": "Aura Driven Fighting Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "Aura Driven Fighting Impact: Power 25",
		"description": "Aura Driven Fighting Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]