export const ETHAN_LUGIA = [
  {
    id: 1,
    x: 1,
    y: -1,
    name: 'HP 10',
    description: 'HP 10',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 2,
    x: 1,
    y: 0,
    name: 'Sp. Atk 5',
    description: 'Sp. Atk 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 3,
    x: 0,
    y: 1,
    name: 'Defense 5',
    description: 'Defense 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 4,
    x: -1,
    y: 1,
    name: 'Sp. Atk 5',
    description: 'Sp. Atk 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 5,
    x: -1,
    y: 0,
    name: 'Sp. Def 5',
    description: 'Sp. Def 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 6,
    x: 0,
    y: -1,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 7,
    x: 1,
    y: -2,
    name: 'Sp. Atk 5',
    description: 'Sp. Atk 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 8,
    x: 2,
    y: -3,
    name: 'HP 10',
    description: 'HP 10',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 9,
    x: 3,
    y: -4,
    name: 'Aeroblast: Accuracy 5',
    description: 'Aeroblast: Accuracy ↑ 5',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'flying'
  },
  {
    id: 10,
    x: 1,
    y: -3,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 11,
    x: 2,
    y: -4,
    name: 'Aeroblast: Move Gauge Refresh 3',
    description: 'Move: Aeroblast Has a chance (40%) of charging the user’s move gauge by one when a move is successful.',
    energy: '7',
    orb: '84',
    level: 1,
    color: 'red',
    icon: 'passive'
  },
  {
    id: 12,
    x: 3,
    y: -5,
    name: 'Aeroblast: Power 2',
    description: 'Aeroblast: Power ↑ 2',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'flying'
  },
  {
    id: 13,
    x: 1,
    y: -4,
    name: 'Aeroblast: Power 2',
    description: 'Aeroblast: Power ↑ 2',
    energy: '3',
    orb: '36',
    level: '2',
    color: 'green',
    icon: 'flying'
  },
  {
    id: 14,
    x: 2,
    y: -5,
    name: 'Aeroblast: Move Gauge Refresh 3',
    description: 'Move: Aeroblast Has a chance (40%) of charging the user’s move gauge by one when a move is successful.',
    energy: '7',
    orb: '84',
    level: '2',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 15,
    x: 3,
    y: -6,
    name: 'Sp. Atk 20',
    description: 'Sp. Atk 20',
    energy: '7',
    orb: '84',
    level: '2',
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 16,
    x: 1,
    y: -5,
    name: 'Interference Sync 5',
    description: 'Powers up the user’s sync move against targets that are flinching, confused, or trapped.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 17,
    x: 2,
    y: -6,
    name: 'Sync Thinker 9',
    description: 'Increases the user’s Special Moves ↑ Next effect by 1 rank after using its sync move.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 18,
    x: -1,
    y: 2,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 19,
    x: -2,
    y: 3,
    name: 'HP 10',
    description: 'HP 10',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 20,
    x: -3,
    y: 4,
    name: 'Whirlpool: Accuracy 5',
    description: 'Whirlpool: Accuracy ↑ 5',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'water'
  },
  {
    id: 21,
    x: -1,
    y: 3,
    name: 'Whirlpool: Power 4',
    description: 'Whirlpool: Power ↑ 4',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'water'
  },
  {
    id: 22,
    x: -2,
    y: 4,
    name: 'Whirlpool: Move Gauge Refresh 3',
    description: 'Move: Whirlpool Has a chance (40%) of charging the user’s move gauge by one when a move is successful.',
    energy: '7',
    orb: '84',
    level: 1,
    color: 'red',
    icon: 'passive'
  },
  {
    id: 23,
    x: -3,
    y: 5,
    name: 'Whirlpool: Power 4',
    description: 'Whirlpool: Power ↑ 4',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'water'
  },
  {
    id: 24,
    x: -1,
    y: 4,
    name: 'Foul Fighting 2',
    description: 'Powers up the user’s moves against targets that are flinching, confused, or trapped.',
    energy: '8',
    orb: '96',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 25,
    x: -2,
    y: 5,
    name: 'Whirlpool: Accuracy 10',
    description: 'Whirlpool: Accuracy ↑ 10',
    energy: '5',
    orb: '60',
    level: '2',
    color: 'green',
    icon: 'water'
  },
  {
    id: 26,
    x: -3,
    y: 6,
    name: 'Racing Rain 2',
    description: 'Quickly charges the move gauge when the weather is rainy.',
    energy: '7',
    orb: '84',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 27,
    x: -1,
    y: 5,
    name: 'Piercing Gaze',
    description: 'Moves never miss.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 28,
    x: -2,
    y: 6,
    name: 'Shower Power 3',
    description: 'Powers up the user’s sync move when the weather is rainy.',
    energy: '8',
    orb: '96',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 29,
    x: 2,
    y: -1,
    name: 'Defense 5',
    description: 'Defense 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 30,
    x: 3,
    y: -1,
    name: 'Whirlpool: Power 4',
    description: 'Whirlpool: Power ↑ 4',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'water'
  },
  {
    id: 31,
    x: 2,
    y: 0,
    name: 'Whirlpool: Power 4',
    description: 'Whirlpool: Power ↑ 4',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'water'
  },
  {
    id: 32,
    x: 1,
    y: 1,
    name: 'Whirlpool: Power 4',
    description: 'Whirlpool: Power ↑ 4',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'water'
  },
  {
    id: 33,
    x: 3,
    y: 0,
    name: 'Refreshing Rain 1',
    description: 'Restores the user’s HP whenever its Pokémon takes an action while the weather is rainy.',
    energy: '8',
    orb: '96',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 34,
    x: 2,
    y: 1,
    name: 'X Sp. Atk: MP Refresh 2',
    description: 'Move: X Sp. Atk Has a chance (30%) of restoring one MP of the user’s move when that move is successful.',
    energy: '7',
    orb: '84',
    level: '2',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 35,
    x: 1,
    y: 2,
    name: 'Shining Soul Aeroblast: Power 25',
    description: 'Shining Soul Aeroblast: Power ↑ 25',
    energy: '5',
    orb: '60',
    level: '2',
    color: 'sync',
    icon: 'sync'
  },
  {
    id: 36,
    x: 3,
    y: 1,
    name: 'Grand Entry 2',
    description: 'Raises the user’s Sp. Atk by 2 stat ranks when it enters a battle.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 37,
    x: 2,
    y: 2,
    name: 'Healthy Benefits 5',
    description: 'Reduces damage when the user is hit by an attack move or sync move when its HP is full.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 38,
    x: -2,
    y: 1,
    name: 'Sp. Def 5',
    description: 'Sp. Def 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 39,
    x: -3,
    y: 1,
    name: 'HP 10',
    description: 'HP 10',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 40,
    x: -2,
    y: 0,
    name: 'Aeroblast: Power 2',
    description: 'Aeroblast: Power ↑ 2',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'flying'
  },
  {
    id: 41,
    x: -1,
    y: -1,
    name: 'Aeroblast: Power 2',
    description: 'Aeroblast: Power ↑ 2',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'flying'
  },
  {
    id: 42,
    x: -3,
    y: 0,
    name: 'Aeroblast: Power 2',
    description: 'Aeroblast: Power ↑ 2',
    energy: '3',
    orb: '36',
    level: '2',
    color: 'green',
    icon: 'flying'
  },
  {
    id: 43,
    x: -2,
    y: -1,
    name: 'This Is It!: Fleet Feet 1',
    description: 'Move: This Is It! Raises the user’s Speed by 1 stat rank when its move is successful.',
    energy: '7',
    orb: '84',
    level: '2',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 44,
    x: -1,
    y: -2,
    name: 'Shining Soul Aeroblast: Power 25',
    description: 'Shining Soul Aeroblast: Power ↑ 25',
    energy: '5',
    orb: '60',
    level: '2',
    color: 'sync',
    icon: 'sync'
  },
  {
    id: 45,
    x: -3,
    y: -1,
    name: 'This Is It!: BOGO 4',
    description: 'Move: This Is It! Has a chance (50%) of applying the Free Move Next effect to the user when its move is successful.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 46,
    x: -2,
    y: -2,
    name: 'This Is It!: Brawn Gain 2',
    description: 'Move: This Is It! Has a chance (30%) of increasing the user’s Special Moves ↑ Next effect by 1 rank when its move is successful.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 47,
    x: 0,
    y: -3,
    name: 'Shining Soul Aeroblast: Power 25',
    description: 'Shining Soul Aeroblast: Power ↑ 25',
    energy: '5',
    orb: '60',
    level: '3',
    color: 'sync',
    icon: 'sync'
  },
  {
    id: 48,
    x: 0,
    y: 3,
    name: 'Shining Soul Aeroblast: Power 25',
    description: 'Shining Soul Aeroblast: Power ↑ 25',
    energy: '5',
    orb: '60',
    level: '3',
    color: 'sync',
    icon: 'sync'
  }
]

export const LYRA_CELEBI = [
  {
    id: 1,
    x: 1,
    y: -1,
    name: 'HP 10',
    description: 'HP 10',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 2,
    x: 1,
    y: 0,
    name: 'Attack 5',
    description: 'Attack 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 3,
    x: 0,
    y: 1,
    name: 'Defense 5',
    description: 'Defense 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 4,
    x: -1,
    y: 1,
    name: 'Sp. Atk 5',
    description: 'Sp. Atk 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 5,
    x: -1,
    y: 0,
    name: 'Sp. Def 5',
    description: 'Sp. Def 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 6,
    x: 0,
    y: -1,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 7,
    x: 1,
    y: -2,
    name: 'Attack 5',
    description: 'Attack 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 8,
    x: 2,
    y: -3,
    name: 'HP 10',
    description: 'HP 10',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 9,
    x: 1,
    y: -3,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 10,
    x: 3,
    y: -4,
    name: 'Attack 5',
    description: 'Attack 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 11,
    x: 2,
    y: -4,
    name: 'Grassy Glide: Move Gauge Refresh 3',
    description: 'Move: Grassy Glide Has a chance (40%) of charging the user’s move gauge by one when a move is successful.',
    energy: '7',
    orb: '84',
    level: 1,
    color: 'red',
    icon: 'passive'
  },
  {
    id: 12,
    x: 1,
    y: -4,
    name: 'Grassy Glide: Power 3',
    description: 'Grassy Glide: Power ↑ 3',
    energy: '3',
    orb: '36',
    level: '2',
    color: 'green',
    icon: 'grass'
  },
  {
    id: 13,
    x: 3,
    y: -5,
    name: 'Grassy Glide: Power 3',
    description: 'Grassy Glide: Power ↑ 3',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'grass'
  },
  {
    id: 14,
    x: 2,
    y: -5,
    name: 'Attack 20',
    description: 'Attack 20',
    energy: '7',
    orb: '84',
    level: '2',
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 15,
    x: 1,
    y: -5,
    name: 'Stationary Target 3',
    description: 'Powers up the user’s moves when the target is trapped.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 16,
    x: 3,
    y: -6,
    name: 'Fierce Entry 2',
    description: 'Raises the user’s Attack by 2 stat ranks when it enters a battle.',
    energy: '10',
    orb: '120',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 17,
    x: 2,
    y: -6,
    name: 'Adrenaline 1',
    description: 'Reduces the sync move countdown by 1 the first time the user’s sync move is used each battle.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 18,
    x: -2,
    y: 1,
    name: 'HP 10',
    description: 'HP 10',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 19,
    x: -3,
    y: 2,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 20,
    x: -2,
    y: 2,
    name: 'Dire Hit All +: MP Refresh 2',
    description: 'Move: Dire Hit All + Has a chance (30%) of restoring one MP of the user’s move when that move is successful.',
    energy: '7',
    orb: '84',
    level: 1,
    color: 'red',
    icon: 'passive'
  },
  {
    id: 21,
    x: -3,
    y: 3,
    name: 'Quick Cure',
    description: 'Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.',
    energy: '7',
    orb: '84',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 22,
    x: -1,
    y: 2,
    name: 'Attack 5',
    description: 'Attack 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 23,
    x: -2,
    y: 3,
    name: 'Speed 20',
    description: 'Speed 20',
    energy: '7',
    orb: '84',
    level: '2',
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 24,
    x: -3,
    y: 4,
    name: 'Voice of the Forest!: MP Refresh 2',
    description: 'Move: Voice of the Forest! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.',
    energy: '7',
    orb: '84',
    level: '2',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 25,
    x: -1,
    y: 3,
    name: 'Voice of the Forest!: Mighty Friend 9',
    description: 'Move: Voice of the Forest! When the user’s move targeting an allied sync pair (excluding field effects) is successful, increases the Physical Moves ↑ Next effect of the allied sync pair affected by the move by one rank.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 26,
    x: -2,
    y: 4,
    name: 'Defense Crush 4',
    description: 'Has a chance (50%) of lowering the target’s Defense by one stat rank when the user’s attack move against it is successful.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 27,
    x: 2,
    y: -1,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 28,
    x: 3,
    y: -1,
    name: 'HP 10',
    description: 'HP 10',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 29,
    x: 2,
    y: 0,
    name: 'Grassy Terrain: Move Gauge Refresh 3',
    description: 'Move: Grassy Terrain Has a chance (40%) of charging the user’s move gauge by one when a move is successful.',
    energy: '7',
    orb: '84',
    level: 1,
    color: 'red',
    icon: 'passive'
  },
  {
    id: 30,
    x: 1,
    y: 1,
    name: 'Sp. Atk 5',
    description: 'Sp. Atk 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 31,
    x: 3,
    y: 0,
    name: 'Verdant Immunity',
    description: 'Status conditions cannot be inflicted on the user when the terrain is Grassy Terrain.',
    energy: '8',
    orb: '96',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 32,
    x: 2,
    y: 1,
    name: 'HP 30',
    description: 'HP 30',
    energy: '5',
    orb: '60',
    level: '2',
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 33,
    x: 1,
    y: 2,
    name: 'Grassy Terrain: MP Refresh 2',
    description: 'Move: Grassy Terrain Has a chance (30%) of restoring one MP of the user’s move when that move is successful.',
    energy: '7',
    orb: '84',
    level: '3',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 34,
    x: 3,
    y: 1,
    name: 'Verdant Recovery 1',
    description: 'Restores the user’s HP whenever its Pokémon takes an action when the terrain is Grassy Terrain.',
    energy: '8',
    orb: '96',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 35,
    x: 2,
    y: 2,
    name: 'Mind Games 4',
    description: 'Has a chance (50%) of lowering the target’s Sp. Def by one stat rank when the user’s attack move against it is successful.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 36,
    x: -1,
    y: -1,
    name: 'Sp. Atk 5',
    description: 'Sp. Atk 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 37,
    x: -2,
    y: -1,
    name: 'Defense 5',
    description: 'Defense 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 38,
    x: -1,
    y: -2,
    name: 'Sp. Def 5',
    description: 'Sp. Def 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 39,
    x: -3,
    y: -1,
    name: 'Sp. Atk 5',
    description: 'Sp. Atk 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 40,
    x: -2,
    y: -2,
    name: 'Grassy Glide: Power 3',
    description: 'Grassy Glide: Power ↑ 3',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'grass'
  },
  {
    id: 41,
    x: -3,
    y: -2,
    name: 'Grassy Glide: Power 3',
    description: 'Grassy Glide: Power ↑ 3',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'grass'
  },
  {
    id: 42,
    x: -1,
    y: -3,
    name: 'Grassy Glide: Power 3',
    description: 'Grassy Glide: Power ↑ 3',
    energy: '3',
    orb: '36',
    level: '2',
    color: 'green',
    icon: 'grass'
  },
  {
    id: 43,
    x: -2,
    y: -3,
    name: 'Sp. Atk 20',
    description: 'Sp. Atk 20',
    energy: '7',
    orb: '84',
    level: '2',
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 44,
    x: -3,
    y: -3,
    name: 'Grand Entry 2',
    description: 'Raises the user’s Sp. Atk by 2 stat ranks when it enters a battle.',
    energy: '10',
    orb: '120',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 45,
    x: -1,
    y: -4,
    name: 'Confusion Synergy 3',
    description: 'Powers up the user’s moves when the target is confused.',
    energy: '8',
    orb: '96',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 46,
    x: -2,
    y: -4,
    name: 'Power Play',
    description: 'The more the target’s stats are lowered, the more it powers up the user’s sync move.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 47,
    x: 0,
    y: -3,
    name: 'Time-Transcending Magical Leaf: Power 25',
    description: 'Time-Transcending Magical Leaf: Power ↑ 25',
    energy: '5',
    orb: '60',
    level: '3',
    color: 'sync',
    icon: 'sync'
  },
  {
    id: 48,
    x: 0,
    y: 3,
    name: 'Time-Transcending Magical Leaf: Power 25',
    description: 'Time-Transcending Magical Leaf: Power ↑ 25',
    energy: '5',
    orb: '60',
    level: '3',
    color: 'sync',
    icon: 'sync'
  }
]

export const KRIS_SUICUNE = [
  {
    id: 1,
    x: 1,
    y: -1,
    name: 'HP 10',
    description: 'HP 10',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 2,
    x: 1,
    y: 0,
    name: 'Sp. Atk 5',
    description: 'Sp. Atk 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 3,
    x: 0,
    y: 1,
    name: 'Defense 5',
    description: 'Defense 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 4,
    x: -1,
    y: 1,
    name: 'Sp. Atk 5',
    description: 'Sp. Atk 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 5,
    x: -1,
    y: 0,
    name: 'Sp. Def 5',
    description: 'Sp. Def 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 6,
    x: 0,
    y: -1,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 7,
    x: 1,
    y: -2,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 8,
    x: 2,
    y: -3,
    name: 'Brine: Power 4',
    description: 'Brine: Power ↑ 4',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'water'
  },
  {
    id: 9,
    x: 1,
    y: -3,
    name: 'Brine: Power 4',
    description: 'Brine: Power ↑ 4',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'water'
  },
  {
    id: 10,
    x: 3,
    y: -4,
    name: 'Sp. Atk 5',
    description: 'Sp. Atk 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 11,
    x: 2,
    y: -4,
    name: 'Brine: Move Gauge Refresh 3',
    description: 'Move: Brine Has a chance (40%) of charging the user’s move gauge by one when a move is successful.',
    energy: '7',
    orb: '84',
    level: 1,
    color: 'red',
    icon: 'passive'
  },
  {
    id: 12,
    x: 1,
    y: -4,
    name: 'Staggering 2',
    description: 'Has a chance (30%) of making the target flinch when the user’s attack move against it is successful.',
    energy: '8',
    orb: '96',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 13,
    x: 3,
    y: -5,
    name: 'Brine: Power 4',
    description: 'Brine: Power ↑ 4',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'water'
  },
  {
    id: 14,
    x: 2,
    y: -5,
    name: 'Team Swift Reaction 4',
    description: 'Has a chance (50%) of raising the Speed of all allied sync pairs by one stat rank when the user is hit by an attack move.',
    energy: '8',
    orb: '96',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 15,
    x: 1,
    y: -5,
    name: 'Brine: Team Stoic 4',
    description: 'Move: Brine Has a chance (50%) of raising the Defense of all allied sync pairs by one stat rank when the user’s Pokémon uses a move.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 16,
    x: 3,
    y: -6,
    name: 'Sp. Def 20',
    description: 'Sp. Def 20',
    energy: '7',
    orb: '84',
    level: '2',
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 17,
    x: 2,
    y: -6,
    name: 'Team Sync Think 9',
    description: 'Once per battle, increases the Special Moves ↑ Next effect of all allied sync pairs by one rank after using the user’s sync move.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 18,
    x: -2,
    y: 2,
    name: 'Defense 5',
    description: 'Defense 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 19,
    x: -3,
    y: 3,
    name: 'HP 10',
    description: 'HP 10',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 20,
    x: -1,
    y: 2,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 21,
    x: -2,
    y: 3,
    name: 'Brine: Power 4',
    description: 'Brine: Power ↑ 4',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'water'
  },
  {
    id: 22,
    x: -3,
    y: 4,
    name: 'Mini Potion All: Lockstep 9',
    description: 'Move: Mini Potion All Charges the user’s move gauge by one for each allied sync pair on the field when the user’s move is successful. When used in a co-op battle, charges the move gauges of all allied players by one instead when the user’s move is successful.',
    energy: '8',
    orb: '96',
    level: '2',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 23,
    x: -1,
    y: 3,
    name: 'Brine: Power 4',
    description: 'Brine: Power ↑ 4',
    energy: '3',
    orb: '36',
    level: '2',
    color: 'green',
    icon: 'water'
  },
  {
    id: 24,
    x: -2,
    y: 4,
    name: 'Mini Potion All: Master Healer 1',
    description: 'Move: Mini Potion All Increases the amount of HP restored by the user’s healing moves.',
    energy: '10',
    orb: '120',
    level: '2',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 25,
    x: -3,
    y: 5,
    name: 'Mini Potion All: Master Healer 1',
    description: 'Move: Mini Potion All Increases the amount of HP restored by the user’s healing moves.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 26,
    x: -1,
    y: 4,
    name: 'Mini Potion All: MP Refresh 3',
    description: 'Move: Mini Potion All Has a chance (40%) of restoring one MP of the user’s move when that move is successful.',
    energy: '7',
    orb: '84',
    level: '3',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 27,
    x: 1,
    y: 1,
    name: 'Sp. Def 5',
    description: 'Sp. Def 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 28,
    x: 2,
    y: 1,
    name: 'Flameproof',
    description: 'Prevents the user from getting burned.',
    energy: '5',
    orb: '60',
    level: 1,
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 29,
    x: 1,
    y: 2,
    name: 'HP 10',
    description: 'HP 10',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 30,
    x: 3,
    y: 1,
    name: 'Defense 5',
    description: 'Defense 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 31,
    x: 2,
    y: 2,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 32,
    x: 1,
    y: 3,
    name: 'HP 20',
    description: 'HP 20',
    energy: '4',
    orb: '48',
    level: '2',
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 33,
    x: 3,
    y: 2,
    name: 'Sp. Atk 5',
    description: 'Sp. Atk 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 34,
    x: 2,
    y: 3,
    name: 'Racing Rain 1',
    description: 'Quickly charges the move gauge when the weather is rainy.',
    energy: '8',
    orb: '96',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 35,
    x: 1,
    y: 4,
    name: 'Rain Dance: Catalyzing Infliction',
    description: 'Move: Rain Dance Applies the Move Gauge Acceleration effect to the allied field of play when the user’s Pokémon uses a status move.',
    energy: '9',
    orb: '108',
    level: '3',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 36,
    x: 3,
    y: 3,
    name: 'Refreshing Rain 1',
    description: 'Restores the user’s HP whenever its Pokémon takes an action while the weather is rainy.',
    energy: '8',
    orb: '96',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 37,
    x: 2,
    y: 4,
    name: 'Rain Dance: MP Refresh 2',
    description: 'Move: Rain Dance Has a chance (30%) of restoring one MP of the user’s move when that move is successful.',
    energy: '7',
    orb: '84',
    level: '3',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 38,
    x: -2,
    y: 0,
    name: 'Unflappable',
    description: 'Prevents the user from flinching.',
    energy: '5',
    orb: '60',
    level: 1,
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 39,
    x: -1,
    y: -1,
    name: 'Defense 5',
    description: 'Defense 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 40,
    x: -3,
    y: 0,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 41,
    x: -2,
    y: -1,
    name: 'Sp. Atk 5',
    description: 'Sp. Atk 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 42,
    x: -1,
    y: -2,
    name: 'Spring of Knowledge!: MP Refresh 2',
    description: 'Move: Spring of Knowledge! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.',
    energy: '7',
    orb: '84',
    level: '2',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 43,
    x: -3,
    y: -1,
    name: 'Endurance',
    description: 'When the user enters battle with full HP, applies the Enduring effect to it.',
    energy: '9',
    orb: '108',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 44,
    x: -2,
    y: -2,
    name: 'Natural Remedy',
    description: 'Removes all status conditions from the user the first time it is inflicted by any status condition each battle.',
    energy: '7',
    orb: '84',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 45,
    x: -1,
    y: -3,
    name: 'Spring of Knowledge!: Barricade Buddies 1',
    description: 'Move: Spring of Knowledge! Raises the Sp. Def of all allied sync pairs by 1 stat rank when the user’s move is successful.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 46,
    x: -3,
    y: -2,
    name: 'Team Limited Special Boost 2',
    description: 'Has a chance (30%) of increasing the Special Moves ↑ Next effect of all allied sync pairs by one rank when the user uses a move with a limited number of uses.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 47,
    x: 0,
    y: -3,
    name: 'Crystal Clear Surf: Power 25',
    description: 'Crystal Clear Surf: Power ↑ 25',
    energy: '5',
    orb: '60',
    level: '3',
    color: 'sync',
    icon: 'sync'
  },
  {
    id: 48,
    x: 0,
    y: 3,
    name: 'Crystal Clear Surf: Power 25',
    description: 'Crystal Clear Surf: Power ↑ 25',
    energy: '5',
    orb: '60',
    level: '3',
    color: 'sync',
    icon: 'sync'
  }
]

export const BEDE_HATTERENE = [
  {
    id: 1,
    x: 1,
    y: -1,
    name: 'HP 10',
    description: 'HP 10',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 2,
    x: 1,
    y: 0,
    name: 'Sp. Atk 5',
    description: 'Sp. Atk 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 3,
    x: 0,
    y: 1,
    name: 'Defense 5',
    description: 'Defense 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 4,
    x: -1,
    y: 1,
    name: 'Sp. Atk 5',
    description: 'Sp. Atk 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 5,
    x: -1,
    y: 0,
    name: 'Sp. Def 5',
    description: 'Sp. Def 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 6,
    x: 0,
    y: -1,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 7,
    x: 1,
    y: -2,
    name: 'Defense 5',
    description: 'Defense 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 8,
    x: 2,
    y: -3,
    name: 'HP 10',
    description: 'HP 10',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 9,
    x: 1,
    y: -3,
    name: 'Dazzling Gleam: Power 4',
    description: 'Dazzling Gleam: Power ↑ 4',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'fairy'
  },
  {
    id: 10,
    x: 3,
    y: -4,
    name: 'Dazzling Gleam: Power 4',
    description: 'Dazzling Gleam: Power ↑ 4',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'fairy'
  },
  {
    id: 11,
    x: 2,
    y: -4,
    name: 'Dazzling Gleam: Move Gauge Refresh 3',
    description: 'Move: Dazzling Gleam Has a chance (40%) of charging the user’s move gauge by one when a move is successful.',
    energy: '7',
    orb: '84',
    level: 1,
    color: 'red',
    icon: 'passive'
  },
  {
    id: 12,
    x: 1,
    y: -4,
    name: 'Dazzling Gleam: Power 4',
    description: 'Dazzling Gleam: Power ↑ 4',
    energy: '3',
    orb: '36',
    level: '2',
    color: 'green',
    icon: 'fairy'
  },
  {
    id: 13,
    x: 3,
    y: -5,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 14,
    x: 2,
    y: -5,
    name: 'Gobsmack 4',
    description: 'Has a chance (50%) of leaving the target confused when the user’s attack move against it is successful.',
    energy: '8',
    orb: '96',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 15,
    x: 1,
    y: -5,
    name: 'Confusion Synergy 9',
    description: 'Powers up the user’s moves when the target is confused.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 16,
    x: 3,
    y: -6,
    name: 'Sp. Atk 10',
    description: 'Sp. Atk 10',
    energy: '4',
    orb: '48',
    level: '2',
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 17,
    x: 2,
    y: -6,
    name: 'G-Max Smite: Power 100',
    description: 'G-Max Smite: Power ↑ 100',
    energy: '8',
    orb: '96',
    level: '3',
    color: 'dynamax',
    icon: 'dynamax'
  },
  {
    id: 18,
    x: -2,
    y: 1,
    name: 'Psybeam: Power 4',
    description: 'Psybeam: Power ↑ 4',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'psychic'
  },
  {
    id: 19,
    x: -3,
    y: 2,
    name: 'Defense 5',
    description: 'Defense 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 20,
    x: -2,
    y: 2,
    name: 'Psybeam: Move Gauge Refresh 3',
    description: 'Move: Psybeam Has a chance (40%) of charging the user’s move gauge by one when a move is successful.',
    energy: '7',
    orb: '84',
    level: 1,
    color: 'red',
    icon: 'passive'
  },
  {
    id: 21,
    x: -3,
    y: 3,
    name: 'Psybeam: Power 4',
    description: 'Psybeam: Power ↑ 4',
    energy: '3',
    orb: '36',
    level: '2',
    color: 'green',
    icon: 'psychic'
  },
  {
    id: 22,
    x: -1,
    y: 2,
    name: 'Psybeam: Power 4',
    description: 'Psybeam: Power ↑ 4',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'psychic'
  },
  {
    id: 23,
    x: -2,
    y: 3,
    name: 'Precognition 2',
    description: 'Quickly charges the user’s move gauge when the terrain is Psychic Terrain.',
    energy: '8',
    orb: '96',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 24,
    x: -3,
    y: 4,
    name: 'Weird Recovery 1',
    description: 'Restores the user’s HP whenever its Pokémon takes an action when the terrain is Psychic Terrain.',
    energy: '8',
    orb: '96',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 25,
    x: -1,
    y: 3,
    name: 'Stupefier 4',
    description: 'Has a chance (50%) of lowering the target’s Sp. Def by 1 stat rank when a move, sync move, or max move used by the user’s Pokémon targeting that opponent is successful.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 26,
    x: -2,
    y: 4,
    name: 'Max Mindstorm: Power 100',
    description: 'Max Mindstorm: Power ↑ 100',
    energy: '8',
    orb: '96',
    level: '3',
    color: 'dynamax',
    icon: 'dynamax'
  },
  {
    id: 27,
    x: 2,
    y: -1,
    name: 'Clearheaded',
    description: 'Prevents the user from becoming confused.',
    energy: '5',
    orb: '60',
    level: 1,
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 28,
    x: 3,
    y: -1,
    name: 'HP 10',
    description: 'HP 10',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 29,
    x: 2,
    y: 0,
    name: 'Sp. Def 5',
    description: 'Sp. Def 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 30,
    x: 1,
    y: 1,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 31,
    x: 3,
    y: 0,
    name: 'Back to You!: MP Refresh 3',
    description: 'Move: Back to You! Has a chance (40%) of restoring one MP of the user’s move when that move is successful.',
    energy: '7',
    orb: '84',
    level: '2',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 32,
    x: 2,
    y: 1,
    name: 'Superduper Effective 2',
    description: 'Powers up moves that are super effective.',
    energy: '9',
    orb: '108',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 33,
    x: 1,
    y: 2,
    name: 'Back to You!: Ramp Up 1',
    description: 'Move: Back to You! Raises the user’s Sp. Atk by 1 stat rank when its move is successful.',
    energy: '9',
    orb: '108',
    level: '3',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 34,
    x: 3,
    y: 1,
    name: 'Back to You!: Group Therapy',
    description: 'Move: Back to You! Removes all status conditions from all allied sync pairs when a move is successful.',
    energy: '8',
    orb: '96',
    level: '2',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 35,
    x: 2,
    y: 2,
    name: 'Fuzzy Strike 5',
    description: 'Powers up the user’s sync move when the target is confused.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 36,
    x: -1,
    y: -1,
    name: 'Sp. Atk 5',
    description: 'Sp. Atk 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 37,
    x: -2,
    y: -1,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 38,
    x: -1,
    y: -2,
    name: 'Sp. Def 5',
    description: 'Sp. Def 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 39,
    x: -3,
    y: -1,
    name: 'Mystical Fire: Power 4',
    description: 'Mystical Fire: Power ↑ 4',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'fire'
  },
  {
    id: 40,
    x: -2,
    y: -2,
    name: 'Mystical Fire: Move Gauge Refresh 3',
    description: 'Move: Mystical Fire Has a chance (40%) of charging the user’s move gauge by one when a move is successful.',
    energy: '7',
    orb: '84',
    level: 1,
    color: 'red',
    icon: 'passive'
  },
  {
    id: 41,
    x: -3,
    y: -2,
    name: 'Mystical Fire: Power 4',
    description: 'Mystical Fire: Power ↑ 4',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'fire'
  },
  {
    id: 42,
    x: -1,
    y: -3,
    name: 'Mystical Fire: Power 4',
    description: 'Mystical Fire: Power ↑ 4',
    energy: '3',
    orb: '36',
    level: '2',
    color: 'green',
    icon: 'fire'
  },
  {
    id: 43,
    x: -2,
    y: -3,
    name: 'Speeding Sun 2',
    description: 'Quickly charges the move gauge when the weather is sunny.',
    energy: '8',
    orb: '96',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 44,
    x: -3,
    y: -3,
    name: 'Healing Sun 1',
    description: 'Restores the user’s HP whenever its Pokémon takes an action while the weather is sunny.',
    energy: '8',
    orb: '96',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 45,
    x: -1,
    y: -4,
    name: 'Hard Knocks 9',
    description: 'Lowers one of the target’s following stats by 1 stat rank at random when a move, sync move, or max move used by the user’s Pokémon targeting that opponent is successful: Attack, Defense, Sp. Atk, Sp. Def, Speed, accuracy, or evasiveness.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 46,
    x: -2,
    y: -4,
    name: 'Max Flare: Power 100',
    description: 'Max Flare: Power ↑ 100',
    energy: '8',
    orb: '96',
    level: '3',
    color: 'dynamax',
    icon: 'dynamax'
  },
  {
    id: 47,
    x: 0,
    y: -3,
    name: 'Most Elite Fairy Beam: Power 25',
    description: 'Most Elite Fairy Beam: Power ↑ 25',
    energy: '5',
    orb: '60',
    level: '3',
    color: 'sync',
    icon: 'sync'
  },
  {
    id: 48,
    x: 0,
    y: 3,
    name: 'Most Elite Fairy Beam: Power 25',
    description: 'Most Elite Fairy Beam: Power ↑ 25',
    energy: '5',
    orb: '60',
    level: '3',
    color: 'sync',
    icon: 'sync'
  }
]