export const MORTY_HOOH = [
  {
    id: 1,
    x: 1,
    y: -1,
    name: 'HP 10',
    description: 'HP 10',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 2,
    x: 1,
    y: 0,
    name: 'Attack 5',
    description: 'Attack 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 3,
    x: 0,
    y: 1,
    name: 'Defense 5',
    description: 'Defense 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 4,
    x: -1,
    y: 1,
    name: 'Attack 5',
    description: 'Attack 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 5,
    x: -1,
    y: 0,
    name: 'Sp. Def 5',
    description: 'Sp. Def 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 6,
    x: 0,
    y: -1,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 7,
    x: 1,
    y: -2,
    name: 'Defense 5',
    description: 'Defense 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 8,
    x: 2,
    y: -3,
    name: 'Flameproof',
    description: 'Prevents the user from getting burned.',
    energy: '5',
    orb: '60',
    level: 1,
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 9,
    x: 1,
    y: -3,
    name: 'Sp. Def 5',
    description: 'Sp. Def 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 10,
    x: 3,
    y: -4,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 11,
    x: 2,
    y: -4,
    name: 'Flame Charge: Power 4',
    description: 'Flame Charge: Power ↑ 4',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'fire'
  },
  {
    id: 12,
    x: 1,
    y: -4,
    name: 'Flame Charge: Power 4',
    description: 'Flame Charge: Power ↑ 4',
    energy: '3',
    orb: '36',
    level: '2',
    color: 'green',
    icon: 'fire'
  },
  {
    id: 13,
    x: 3,
    y: -5,
    name: 'Flame Charge: Power 4',
    description: 'Flame Charge: Power ↑ 4',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'fire'
  },
  {
    id: 14,
    x: 2,
    y: -5,
    name: 'Flame Charge: Move Gauge Refresh 3',
    description: 'Move: Flame Charge Has a chance (40%) of charging the user’s move gauge by one when a move is successful.',
    energy: '7',
    orb: '84',
    level: '2',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 15,
    x: 1,
    y: -5,
    name: 'Team Gimme Five 1',
    description: 'Raises the Attack, Defense, Sp. Atk, Sp. Def, and Speed of all allied sync pairs by 1 stat rank the first time the user’s sync move is used each battle.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 16,
    x: 3,
    y: -6,
    name: 'Flame Charge: Dashing Team 9',
    description: 'Move: Flame Charge Raises the Speed of all allied sync pairs by one stat rank when the user’s attack move is successful.',
    energy: '9',
    orb: '108',
    level: '2',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 17,
    x: 2,
    y: -6,
    name: 'Adrenaline 1',
    description: 'Reduces the sync move countdown by 1 the first time the user’s sync move is used each battle.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 18,
    x: -2,
    y: 2,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 19,
    x: -3,
    y: 3,
    name: 'Sp. Def 5',
    description: 'Sp. Def 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 20,
    x: -1,
    y: 2,
    name: 'Defense 5',
    description: 'Defense 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 21,
    x: -2,
    y: 3,
    name: 'Flame Charge: Power 4',
    description: 'Flame Charge: Power ↑ 4',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'fire'
  },
  {
    id: 22,
    x: -3,
    y: 4,
    name: 'HP 20',
    description: 'HP 20',
    energy: '4',
    orb: '48',
    level: '2',
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 23,
    x: -1,
    y: 3,
    name: 'Flame Charge: Power 4',
    description: 'Flame Charge: Power ↑ 4',
    energy: '3',
    orb: '36',
    level: '2',
    color: 'green',
    icon: 'fire'
  },
  {
    id: 24,
    x: -2,
    y: 4,
    name: 'Sunny Day: MP Refresh 3',
    description: 'Move: Sunny Day Has a chance (40%) of restoring one MP of the user’s move when that move is successful.',
    energy: '7',
    orb: '84',
    level: '2',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 25,
    x: -3,
    y: 5,
    name: 'Sunny Day: Team Body-Bracing Infliction 2',
    description: 'Move: Sunny Day Raises the Defense of all allied sync pairs by 2 stat ranks the first time the user’s Pokémon uses a status move each battle.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 26,
    x: -1,
    y: 4,
    name: 'Sunny Day: Team Mind-Bracing Infliction 2',
    description: 'Move: Sunny Day Raises the Sp. Def of all allied sync pairs by 2 stat ranks the first time the user’s Pokémon uses a status move each battle.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 27,
    x: 1,
    y: 1,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 28,
    x: 2,
    y: 1,
    name: 'Unflappable',
    description: 'Prevents the user from flinching.',
    energy: '5',
    orb: '60',
    level: 1,
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 29,
    x: 1,
    y: 2,
    name: 'Sp. Def 5',
    description: 'Sp. Def 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 30,
    x: 3,
    y: 1,
    name: 'Attack 5',
    description: 'Attack 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 31,
    x: 2,
    y: 2,
    name: 'Defense 5',
    description: 'Defense 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 32,
    x: 1,
    y: 3,
    name: 'Potion: Master Healer 1',
    description: 'Move: Potion Increases the amount of HP restored by the user’s healing moves.',
    energy: '10',
    orb: '120',
    level: '2',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 33,
    x: 3,
    y: 2,
    name: 'HP 10',
    description: 'HP 10',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 34,
    x: 2,
    y: 3,
    name: 'Potion: Friend Mend 9',
    description: 'Move: Potion When a move targeting an allied sync pair (excluding field effects) is successful, removes all status conditions from the allied sync pair affected by the move.',
    energy: '8',
    orb: '96',
    level: '2',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 35,
    x: 1,
    y: 4,
    name: 'Potion: MP Refresh 3',
    description: 'Move: Potion Has a chance (40%) of restoring one MP of the user’s move when that move is successful.',
    energy: '7',
    orb: '84',
    level: '3',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 36,
    x: 3,
    y: 3,
    name: 'Potion: Friend Care 9',
    description: 'Move: Potion When the user’s move targeting an allied sync pair (excluding field effects) is successful, removes the flinching, confused, and trapped conditions from the allied sync pair affected by the move.',
    energy: '8',
    orb: '96',
    level: '2',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 37,
    x: 2,
    y: 4,
    name: 'Potion: Master Healer 1',
    description: 'Move: Potion Increases the amount of HP restored by the user’s healing moves.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 38,
    x: -2,
    y: 0,
    name: 'HP 10',
    description: 'HP 10',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 39,
    x: -1,
    y: -1,
    name: 'Defense 5',
    description: 'Defense 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 40,
    x: -3,
    y: 0,
    name: 'Attack 5',
    description: 'Attack 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 41,
    x: -2,
    y: -1,
    name: 'Believe!: MP Refresh 3',
    description: 'Move: Believe! Has a chance (40%) of restoring one MP of the user’s move when that move is successful.',
    energy: '7',
    orb: '84',
    level: 1,
    color: 'red',
    icon: 'passive'
  },
  {
    id: 42,
    x: -1,
    y: -2,
    name: 'Sp. Def 10',
    description: 'Sp. Def 10',
    energy: '4',
    orb: '48',
    level: '2',
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 43,
    x: -3,
    y: -1,
    name: 'Sunny Disposition ',
    description: 'Stats cannot be lowered when the weather is sunny.',
    energy: '8',
    orb: '96',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 44,
    x: -2,
    y: -2,
    name: 'Speeding Sun 2',
    description: 'Quickly charges the move gauge when the weather is sunny.',
    energy: '8',
    orb: '96',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 45,
    x: -1,
    y: -3,
    name: 'Sunbathe 9',
    description: 'Restores the user’s HP when it uses a move while the weather is sunny.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 46,
    x: -3,
    y: -2,
    name: 'Vigilance',
    description: 'Protects the user against critical hits.',
    energy: '9',
    orb: '108',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 47,
    x: 0,
    y: -3,
    name: 'Rainbow-Hued Sacred Fire: Power 25',
    description: 'Rainbow-Hued Sacred Fire: Power ↑ 25',
    energy: '5',
    orb: '60',
    level: '3',
    color: 'sync',
    icon: 'sync'
  },
  {
    id: 48,
    x: 0,
    y: 3,
    name: 'Rainbow-Hued Sacred Fire: Power 25',
    description: 'Rainbow-Hued Sacred Fire: Power ↑ 25',
    energy: '5',
    orb: '60',
    level: '3',
    color: 'sync',
    icon: 'sync'
  }
]

export const AARON_VESPIQUEN = [
  {
    id: 1,
    x: 1,
    y: -1,
    name: 'HP 10',
    description: 'HP 10',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 2,
    x: 1,
    y: 0,
    name: 'Attack 5',
    description: 'Attack 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 3,
    x: 0,
    y: 1,
    name: 'Defense 5',
    description: 'Defense 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 4,
    x: -1,
    y: 1,
    name: 'Attack 5',
    description: 'Attack 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 5,
    x: -1,
    y: 0,
    name: 'Sp. Def 5',
    description: 'Sp. Def 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 6,
    x: 0,
    y: -1,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 7,
    x: 1,
    y: -2,
    name: 'Attack 5',
    description: 'Attack 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 8,
    x: 2,
    y: -3,
    name: 'Lithe',
    description: 'Prevents the user from getting paralyzed.',
    energy: '5',
    orb: '60',
    level: 1,
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 9,
    x: 1,
    y: -3,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 10,
    x: 3,
    y: -4,
    name: 'HP 10',
    description: 'HP 10',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 11,
    x: 2,
    y: -4,
    name: 'Sp. Def 5',
    description: 'Sp. Def 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 12,
    x: 1,
    y: -4,
    name: 'Sp. Def 10',
    description: 'Sp. Def 10',
    energy: '4',
    orb: '48',
    level: '2',
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 13,
    x: 3,
    y: -5,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 14,
    x: 2,
    y: -5,
    name: 'Defend Order: Move Gauge Refresh 3',
    description: 'Move: Defend Order Has a chance (40%) of charging the user’s move gauge by one when a move is successful.',
    energy: '7',
    orb: '84',
    level: '2',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 15,
    x: 1,
    y: -5,
    name: 'Team Full-Bracing Infliction 1',
    description: 'Raises the Defense and Sp. Def of all allied sync pairs by 1 stat rank the first time the user’s Pokémon uses a status move each battle.',
    energy: '9',
    orb: '108',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 16,
    x: 3,
    y: -6,
    name: 'Insect Healing 1',
    description: 'Restores the user’s HP whenever its Pokémon takes an action when the zone is a Bug Zone.',
    energy: '10',
    orb: '120',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 17,
    x: 2,
    y: -6,
    name: 'Team Strengthening Heal 9',
    description: 'Once per battle, increases the Physical Moves ↑ Next effect and Special Moves ↑ Next effect of all allied sync pairs by one rank when the user uses a move that has the heal effect tag.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 18,
    x: -2,
    y: 2,
    name: 'Defense 5',
    description: 'Defense 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 19,
    x: -3,
    y: 3,
    name: 'Attack 5',
    description: 'Attack 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 20,
    x: -1,
    y: 2,
    name: 'Attack Order: Power 3',
    description: 'Attack Order: Power ↑ 3',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'bug'
  },
  {
    id: 21,
    x: -2,
    y: 3,
    name: 'Attack Order: Power 3',
    description: 'Attack Order: Power ↑ 3',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'bug'
  },
  {
    id: 22,
    x: -3,
    y: 4,
    name: 'Insect Acceleration 2',
    description: 'Quickly charges the move gauge when the zone is Bug Zone.',
    energy: '9',
    orb: '108',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 23,
    x: -1,
    y: 3,
    name: 'Attack Order: Power 3',
    description: 'Attack Order: Power ↑ 3',
    energy: '3',
    orb: '36',
    level: '2',
    color: 'green',
    icon: 'bug'
  },
  {
    id: 24,
    x: -2,
    y: 4,
    name: 'Cool, Right?!: MP Refresh 3',
    description: 'Move: Cool, Right?! Has a chance (40%) of restoring one MP of the user’s move when that move is successful.',
    energy: '7',
    orb: '84',
    level: '2',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 25,
    x: -3,
    y: 5,
    name: 'HP 40',
    description: 'HP 40',
    energy: '7',
    orb: '84',
    level: '3',
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 26,
    x: -1,
    y: 4,
    name: 'Cool, Right?!: Precision Pals 1',
    description: 'Move: Cool, Right?! Raises the accuracy of all allied sync pairs by 1 stat rank when the user’s move is successful.',
    energy: '8',
    orb: '96',
    level: '3',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 27,
    x: 1,
    y: 1,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 28,
    x: 2,
    y: 1,
    name: 'Stalwart',
    description: 'Sp. Def cannot be lowered.',
    energy: '5',
    orb: '60',
    level: 1,
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 29,
    x: 1,
    y: 2,
    name: 'Sp. Def 5',
    description: 'Sp. Def 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 30,
    x: 3,
    y: 1,
    name: 'Attack 5',
    description: 'Attack 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 31,
    x: 2,
    y: 2,
    name: 'HP 10',
    description: 'HP 10',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 32,
    x: 1,
    y: 3,
    name: 'Quick Cure',
    description: 'Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.',
    energy: '7',
    orb: '84',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 33,
    x: 3,
    y: 2,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 34,
    x: 2,
    y: 3,
    name: 'Heal Order: Move Gauge Refresh 3',
    description: 'Move: Heal Order Has a chance (40%) of charging the user’s move gauge by one when a move is successful.',
    energy: '7',
    orb: '84',
    level: '2',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 35,
    x: 1,
    y: 4,
    name: 'Natural Remedy',
    description: 'Removes all status conditions from the user the first time it is inflicted by any status condition each battle.',
    energy: '7',
    orb: '84',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 36,
    x: 3,
    y: 3,
    name: 'Defense 10',
    description: 'Defense 10',
    energy: '4',
    orb: '48',
    level: '2',
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 37,
    x: 2,
    y: 4,
    name: 'Healthy Buffer 5',
    description: 'Reduces damage when the user is hit by an attack move when its HP is full.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 38,
    x: -2,
    y: 0,
    name: 'Unbending',
    description: 'Defense cannot be lowered.',
    energy: '5',
    orb: '60',
    level: 1,
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 39,
    x: -1,
    y: -1,
    name: 'Defense 5',
    description: 'Defense 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 40,
    x: -3,
    y: 0,
    name: 'Attack 5',
    description: 'Attack 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 41,
    x: -2,
    y: -1,
    name: 'Attack Order: Power 3',
    description: 'Attack Order: Power ↑ 3',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'bug'
  },
  {
    id: 42,
    x: -1,
    y: -2,
    name: 'Attack Order: Power 3',
    description: 'Attack Order: Power ↑ 3',
    energy: '3',
    orb: '36',
    level: '2',
    color: 'green',
    icon: 'bug'
  },
  {
    id: 43,
    x: -3,
    y: -1,
    name: 'Speed 10',
    description: 'Speed 10',
    energy: '4',
    orb: '48',
    level: '2',
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 44,
    x: -2,
    y: -2,
    name: 'Attack Order: Move Gauge Refresh 9',
    description: 'Move: Attack Order Charges the user’s move gauge by one when its move is successful.',
    energy: '8',
    orb: '96',
    level: '2',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 45,
    x: -1,
    y: -3,
    name: 'Catalyst',
    description: 'Applies the Move Gauge Acceleration effect to the allied field of play the first time the user’s sync move is used each battle.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 46,
    x: -3,
    y: -2,
    name: 'Attack Order: Staggering 4',
    description: 'Move: Attack Order Has a chance (50%) of making the target flinch when the user’s attack move against it is successful.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 47,
    x: 0,
    y: -3,
    name: 'Perfect Swarm Attack Order: Power 25',
    description: 'Perfect Swarm Attack Order: Power ↑ 25',
    energy: '5',
    orb: '60',
    level: '3',
    color: 'sync',
    icon: 'sync'
  },
  {
    id: 48,
    x: 0,
    y: 3,
    name: 'Perfect Swarm Attack Order: Power 25',
    description: 'Perfect Swarm Attack Order: Power ↑ 25',
    energy: '5',
    orb: '60',
    level: '3',
    color: 'sync',
    icon: 'sync'
  }
]

export const BERTHA_HIPPOWDON = [
  {
    id: 1,
    x: 1,
    y: -1,
    name: 'HP 10',
    description: 'HP 10',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 2,
    x: 1,
    y: 0,
    name: 'Attack 5',
    description: 'Attack 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 3,
    x: 0,
    y: 1,
    name: 'Defense 5',
    description: 'Defense 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 4,
    x: -1,
    y: 1,
    name: 'Attack 5',
    description: 'Attack 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 5,
    x: -1,
    y: 0,
    name: 'Sp. Def 5',
    description: 'Sp. Def 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 6,
    x: 0,
    y: -1,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 7,
    x: 1,
    y: -2,
    name: 'Defense 5',
    description: 'Defense 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 8,
    x: 2,
    y: -3,
    name: 'Sand Tomb: Power 4',
    description: 'Sand Tomb: Power ↑ 4',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'ground'
  },
  {
    id: 9,
    x: 1,
    y: -3,
    name: 'Sp. Def 5',
    description: 'Sp. Def 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 10,
    x: 3,
    y: -4,
    name: 'Sand Tomb: Power 4',
    description: 'Sand Tomb: Power ↑ 4',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'ground'
  },
  {
    id: 11,
    x: 2,
    y: -4,
    name: 'Sand Tomb: Accuracy 5',
    description: 'Sand Tomb: Accuracy ↑ 5',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'ground'
  },
  {
    id: 12,
    x: 1,
    y: -4,
    name: 'Sand Tomb: Accuracy 10',
    description: 'Sand Tomb: Accuracy ↑ 10',
    energy: '5',
    orb: '60',
    level: '2',
    color: 'green',
    icon: 'ground'
  },
  {
    id: 13,
    x: 3,
    y: -5,
    name: 'HP 10',
    description: 'HP 10',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 14,
    x: 2,
    y: -5,
    name: 'Sand Tomb: Move Gauge Refresh 3',
    description: 'Move: Sand Tomb Has a chance (40%) of charging the user’s move gauge by one when a move is successful.',
    energy: '7',
    orb: '84',
    level: '2',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 15,
    x: 1,
    y: -5,
    name: 'Gritty Guardian 3',
    description: 'Has a chance (40%) of raising the user’s Defense and Sp. Def by one stat rank when its Pokémon uses a move during a sandstorm.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 16,
    x: 3,
    y: -6,
    name: 'HP 20',
    description: 'HP 20',
    energy: '4',
    orb: '48',
    level: '2',
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 17,
    x: 2,
    y: -6,
    name: 'Sand Tomb: Sand Slinger 9',
    description: 'Move: Sand Tomb Lowers the target’s Attack by one stat rank when the user’s attack move against it is successful during a sandstorm.',
    energy: '8',
    orb: '96',
    level: '3',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 18,
    x: -2,
    y: 1,
    name: 'Wide Awake',
    description: 'Prevents the user from falling asleep.',
    energy: '5',
    orb: '60',
    level: 1,
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 19,
    x: -3,
    y: 2,
    name: 'Attack 5',
    description: 'Attack 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 20,
    x: -2,
    y: 2,
    name: 'Defense 5',
    description: 'Defense 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 21,
    x: -3,
    y: 3,
    name: 'Shifting Sand',
    description: 'Raises the user’s evasiveness by 1 stat rank during a sandstorm.',
    energy: '7',
    orb: '84',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 22,
    x: -1,
    y: 2,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 23,
    x: -2,
    y: 3,
    name: 'Stealth Rock: MP Refresh 2',
    description: 'Move: Stealth Rock Has a chance (30%) of restoring one MP of the user’s move when that move is successful.',
    energy: '7',
    orb: '84',
    level: '2',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 24,
    x: -3,
    y: 4,
    name: 'Sands of Time 2',
    description: 'Quickly charges the move gauge during a sandstorm.',
    energy: '8',
    orb: '96',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 25,
    x: -1,
    y: 3,
    name: 'Trap and Sync 5',
    description: 'Powers up the user’s sync move against targets that are trapped.',
    energy: '8',
    orb: '96',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 26,
    x: -2,
    y: 4,
    name: 'Endurance',
    description: 'When the user enters battle with full HP, applies the Enduring effect to it.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 27,
    x: 2,
    y: -1,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 28,
    x: 3,
    y: -1,
    name: 'HP 10',
    description: 'HP 10',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 29,
    x: 2,
    y: 0,
    name: 'Sp. Def 5',
    description: 'Sp. Def 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 30,
    x: 1,
    y: 1,
    name: 'Sp. Def 5',
    description: 'Sp. Def 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 31,
    x: 3,
    y: 0,
    name: 'Defense 10',
    description: 'Defense 10',
    energy: '4',
    orb: '48',
    level: '2',
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 32,
    x: 2,
    y: 1,
    name: 'Quite Something!: MP Refresh 2',
    description: 'Move: Quite Something! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.',
    energy: '7',
    orb: '84',
    level: '2',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 33,
    x: 1,
    y: 2,
    name: 'Sand Blaster 9',
    description: 'Powers up sync moves during a sandstorm.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 34,
    x: 3,
    y: 1,
    name: 'Quite Something!: Hit and Heal 9',
    description: 'Move: Quite Something! Applies the Gradual Healing effect to the user when its move is successful.',
    energy: '8',
    orb: '96',
    level: '2',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 35,
    x: 2,
    y: 2,
    name: 'Team Sharp Entry 1',
    description: 'Raises the critical-hit rate of all allied sync pairs by 1 stat rank when the user enters a battle.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 36,
    x: -1,
    y: -1,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 37,
    x: -2,
    y: -1,
    name: 'Escape Artist',
    description: 'Prevents the user from becoming trapped.',
    energy: '5',
    orb: '60',
    level: 1,
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 38,
    x: -1,
    y: -2,
    name: 'Sp. Def 5',
    description: 'Sp. Def 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 39,
    x: -3,
    y: -1,
    name: 'Defense 5',
    description: 'Defense 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 40,
    x: -2,
    y: -2,
    name: 'Attack 5',
    description: 'Attack 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 41,
    x: -3,
    y: -2,
    name: 'Sand Tomb: Power 4',
    description: 'Sand Tomb: Power ↑ 4',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'ground'
  },
  {
    id: 42,
    x: -1,
    y: -3,
    name: 'Sand Tomb: Power 4',
    description: 'Sand Tomb: Power ↑ 4',
    energy: '3',
    orb: '36',
    level: '2',
    color: 'green',
    icon: 'ground'
  },
  {
    id: 43,
    x: -2,
    y: -3,
    name: 'Sand Tomb: Power 4',
    description: 'Sand Tomb: Power ↑ 4',
    energy: '3',
    orb: '36',
    level: '2',
    color: 'green',
    icon: 'ground'
  },
  {
    id: 44,
    x: -3,
    y: -3,
    name: 'Soothing Sand 1',
    description: 'Restores the user’s HP whenever its Pokémon takes an action during a sandstorm.',
    energy: '8',
    orb: '96',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 45,
    x: -1,
    y: -4,
    name: 'Sand Castle 2',
    description: 'Reduces damage when the user is hit by an attack move during a sandstorm.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 46,
    x: -2,
    y: -4,
    name: 'Sandstorm: MP Refresh 2',
    description: 'Move: Sandstorm Has a chance (30%) of restoring one MP of the user’s move when that move is successful.',
    energy: '7',
    orb: '84',
    level: '3',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 47,
    x: 0,
    y: -3,
    name: 'Team Effort Earthquake: Power 25',
    description: 'Team Effort Earthquake: Power ↑ 25',
    energy: '5',
    orb: '60',
    level: '3',
    color: 'sync',
    icon: 'sync'
  },
  {
    id: 48,
    x: 0,
    y: 3,
    name: 'Team Effort Earthquake: Power 25',
    description: 'Team Effort Earthquake: Power ↑ 25',
    energy: '5',
    orb: '60',
    level: '3',
    color: 'sync',
    icon: 'sync'
  }
]

export const LUCIAN_GIRAFARIG = [
  {
    id: 1,
    x: 1,
    y: -1,
    name: 'HP 10',
    description: 'HP 10',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 2,
    x: 1,
    y: 0,
    name: 'Sp. Atk 5',
    description: 'Sp. Atk 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 3,
    x: 0,
    y: 1,
    name: 'Defense 5',
    description: 'Defense 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 4,
    x: -1,
    y: 1,
    name: 'Sp. Atk 5',
    description: 'Sp. Atk 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 5,
    x: -1,
    y: 0,
    name: 'Sp. Def 5',
    description: 'Sp. Def 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 6,
    x: 0,
    y: -1,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 7,
    x: 1,
    y: -2,
    name: 'Defense 5',
    description: 'Defense 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 8,
    x: 2,
    y: -3,
    name: 'Unflappable',
    description: 'Prevents the user from flinching.',
    energy: '5',
    orb: '60',
    level: 1,
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 9,
    x: 1,
    y: -3,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 10,
    x: 3,
    y: -4,
    name: 'HP 10',
    description: 'HP 10',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 11,
    x: 2,
    y: -4,
    name: 'Confusion: Power 4',
    description: 'Confusion: Power ↑ 4',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'psychic'
  },
  {
    id: 12,
    x: 1,
    y: -4,
    name: 'Confusion: Power 4',
    description: 'Confusion: Power ↑ 4',
    energy: '3',
    orb: '36',
    level: '2',
    color: 'green',
    icon: 'psychic'
  },
  {
    id: 13,
    x: 3,
    y: -5,
    name: 'Confusion: Power 4',
    description: 'Confusion: Power ↑ 4',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'psychic'
  },
  {
    id: 14,
    x: 2,
    y: -5,
    name: 'Confusion: Move Gauge Refresh 3',
    description: 'Move: Confusion Has a chance (40%) of charging the user’s move gauge by one when a move is successful.',
    energy: '7',
    orb: '84',
    level: '2',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 15,
    x: 1,
    y: -5,
    name: 'Psychic Epilogue: Power 25',
    description: 'Psychic Epilogue: Power ↑ 25',
    energy: '5',
    orb: '60',
    level: '3',
    color: 'green',
    icon: 'sync'
  },
  {
    id: 16,
    x: 3,
    y: -6,
    name: 'Confusion: Foul Fighting 9',
    description: 'Move: Confusion Powers up the user’s moves against targets that are flinching, confused, or trapped.',
    energy: '9',
    orb: '108',
    level: '2',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 17,
    x: 2,
    y: -6,
    name: 'Confusion: Aggravation 4',
    description: 'Move: Confusion Raises the chance of inflicting the flinching, confused, or trapped condition with the additional effects of moves.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 18,
    x: -2,
    y: 1,
    name: 'Defense 5',
    description: 'Defense 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 19,
    x: -3,
    y: 2,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 20,
    x: -2,
    y: 2,
    name: 'Confusion: Power 4',
    description: 'Confusion: Power ↑ 4',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'psychic'
  },
  {
    id: 21,
    x: -3,
    y: 3,
    name: 'Confusion: Power 4',
    description: 'Confusion: Power ↑ 4',
    energy: '3',
    orb: '36',
    level: '2',
    color: 'green',
    icon: 'psychic'
  },
  {
    id: 22,
    x: -1,
    y: 2,
    name: 'Confusion: Power 4',
    description: 'Confusion: Power ↑ 4',
    energy: '3',
    orb: '36',
    level: 1,
    color: 'green',
    icon: 'psychic'
  },
  {
    id: 23,
    x: -2,
    y: 3,
    name: 'Dominating Sync 2',
    description: 'Powers up the user’s sync moves when the target’s Attack is lowered.',
    energy: '8',
    orb: '96',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 24,
    x: -3,
    y: 4,
    name: 'Sp. Atk 20',
    description: 'Sp. Atk 20',
    energy: '7',
    orb: '84',
    level: '2',
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 25,
    x: -1,
    y: 3,
    name: 'Psychic Epilogue: Power 25',
    description: 'Psychic Epilogue: Power ↑ 25',
    energy: '5',
    orb: '60',
    level: '3',
    color: 'green',
    icon: 'sync'
  },
  {
    id: 26,
    x: -2,
    y: 4,
    name: 'Growl: Charging Infliction 2',
    description: 'Move: Growl Charges the user’s move gauge by 2 when its Pokémon uses a status move.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 27,
    x: 2,
    y: -1,
    name: 'Dauntless',
    description: 'Sp. Atk cannot be lowered.',
    energy: '5',
    orb: '60',
    level: 1,
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 28,
    x: 3,
    y: -1,
    name: 'Sp. Def 5',
    description: 'Sp. Def 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 29,
    x: 2,
    y: 0,
    name: 'Read It and Weep!: MP Refresh 2',
    description: 'Move: Read It and Weep! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.',
    energy: '7',
    orb: '84',
    level: 1,
    color: 'red',
    icon: 'passive'
  },
  {
    id: 30,
    x: 1,
    y: 1,
    name: 'Haste',
    description: 'Speed cannot be lowered.',
    energy: '5',
    orb: '60',
    level: 1,
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 31,
    x: 3,
    y: 0,
    name: 'HP 10',
    description: 'HP 10',
    energy: '2',
    orb: '24',
    level: '2',
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 32,
    x: 2,
    y: 1,
    name: 'Psychic Epilogue: Power 25',
    description: 'Psychic Epilogue: Power ↑ 25',
    energy: '5',
    orb: '60',
    level: '2',
    color: 'green',
    icon: 'sync'
  },
  {
    id: 33,
    x: 1,
    y: 2,
    name: 'Adrenaline 1',
    description: 'Reduces the sync move countdown by 1 the first time the user’s sync move is used each battle.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 34,
    x: 3,
    y: 1,
    name: 'Burst In',
    description: 'Applies the Critical Hit Next effect to the user when it enters a battle.',
    energy: '7',
    orb: '84',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 35,
    x: 2,
    y: 2,
    name: 'Healthy Superhit',
    description: 'Applies the Supereffective ↑ Next effect to the user if its HP is full when it enters a battle.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 36,
    x: -1,
    y: -1,
    name: 'Sp. Def 5',
    description: 'Sp. Def 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 37,
    x: -2,
    y: -1,
    name: 'Wide Awake',
    description: 'Prevents the user from falling asleep.',
    energy: '5',
    orb: '60',
    level: 1,
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 38,
    x: -1,
    y: -2,
    name: 'Sp. Def 5',
    description: 'Sp. Def 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 39,
    x: -3,
    y: -1,
    name: 'Defense 5',
    description: 'Defense 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 40,
    x: -2,
    y: -2,
    name: 'X Sp. Atk: MP Refresh 2',
    description: 'Move: X Sp. Atk Has a chance (30%) of restoring one MP of the user’s move when that move is successful.',
    energy: '7',
    orb: '84',
    level: 1,
    color: 'red',
    icon: 'passive'
  },
  {
    id: 41,
    x: -3,
    y: -2,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 42,
    x: -1,
    y: -3,
    name: 'Weird Recovery 1',
    description: 'Restores the user’s HP whenever its Pokémon takes an action when the terrain is Psychic Terrain.',
    energy: '8',
    orb: '96',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 43,
    x: -2,
    y: -3,
    name: 'Psychic Epilogue: Power 25',
    description: 'Psychic Epilogue: Power ↑ 25',
    energy: '5',
    orb: '60',
    level: '2',
    color: 'green',
    icon: 'sync'
  },
  {
    id: 44,
    x: -3,
    y: -3,
    name: 'Precognition 2',
    description: 'Quickly charges the user’s move gauge when the terrain is Psychic Terrain.',
    energy: '10',
    orb: '120',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 45,
    x: -1,
    y: -4,
    name: 'X Sp. Atk: Ramp Up 1',
    description: 'Move: X Sp. Atk Raises the user’s Sp. Atk by 1 stat rank when its move is successful.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 46,
    x: -2,
    y: -4,
    name: 'Catalyst',
    description: 'Applies the Move Gauge Acceleration effect to the allied field of play the first time the user’s sync move is used each battle.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 47,
    x: 0,
    y: -3,
    name: 'Psychic Epilogue: Power 25',
    description: 'Psychic Epilogue: Power ↑ 25',
    energy: '5',
    orb: '60',
    level: '3',
    color: 'sync',
    icon: 'sync'
  },
  {
    id: 48,
    x: 0,
    y: 3,
    name: 'Psychic Epilogue: Power 25',
    description: 'Psychic Epilogue: Power ↑ 25',
    energy: '5',
    orb: '60',
    level: '3',
    color: 'sync',
    icon: 'sync'
  }
]

export const GIOVANNI_NIDOKING = [
  {
    id: 1,
    x: 1,
    y: -1,
    name: 'HP 10',
    description: 'HP 10',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 2,
    x: 1,
    y: 0,
    name: 'Attack 5',
    description: 'Attack 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 3,
    x: 0,
    y: 1,
    name: 'Defense 5',
    description: 'Defense 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 4,
    x: -1,
    y: 1,
    name: 'Attack 5',
    description: 'Attack 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 5,
    x: -1,
    y: 0,
    name: 'Sp. Def 5',
    description: 'Sp. Def 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 6,
    x: 0,
    y: -1,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '0',
    orb: '5',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 7,
    x: 1,
    y: -2,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 8,
    x: 2,
    y: -3,
    name: 'Antitoxin',
    description: 'Prevents the user from getting poisoned or badly poisoned.',
    energy: '5',
    orb: '60',
    level: 1,
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 9,
    x: 3,
    y: -4,
    name: 'Defense 5',
    description: 'Defense 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 10,
    x: 1,
    y: -3,
    name: 'Mega Kick: Power 3',
    description: 'Mega Kick: Power ↑ 3',
    energy: '4',
    orb: '48',
    level: 1,
    color: 'green',
    icon: 'ground'
  },
  {
    id: 11,
    x: 2,
    y: -4,
    name: 'Mega Kick: Power 3',
    description: 'Mega Kick: Power ↑ 3',
    energy: '4',
    orb: '48',
    level: 1,
    color: 'green',
    icon: 'ground'
  },
  {
    id: 12,
    x: 3,
    y: -5,
    name: 'Mega Kick: Power 3',
    description: 'Mega Kick: Power ↑ 3',
    energy: '4',
    orb: '48',
    level: 1,
    color: 'green',
    icon: 'ground'
  },
  {
    id: 13,
    x: 1,
    y: -4,
    name: 'Superduper Effective 2',
    description: 'Powers up moves that are super effective.',
    energy: '10',
    orb: '120',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 14,
    x: 2,
    y: -5,
    name: 'Mega Kick: Move Gauge Refresh 3',
    description: 'Move: Mega Kick Has a chance (40%) of charging the user’s move gauge by one when a move is successful.',
    energy: '7',
    orb: '84',
    level: '2',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 15,
    x: 3,
    y: -6,
    name: 'Attack 20',
    description: 'Attack 20',
    energy: '7',
    orb: '84',
    level: '2',
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 16,
    x: 1,
    y: -5,
    name: 'Critical Crit 9',
    description: 'Applies the Critical Hit Next effect to the user when it lands a critical hit.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 17,
    x: 2,
    y: -6,
    name: 'Max Quake: Power 100',
    description: 'Max Quake: Power ↑ 100',
    energy: '8',
    orb: '96',
    level: '3',
    color: 'dynamax',
    icon: 'dynamax'
  },
  {
    id: 18,
    x: -1,
    y: 2,
    name: 'Defense 5',
    description: 'Defense 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 19,
    x: -2,
    y: 3,
    name: 'Sp. Def 5',
    description: 'Sp. Def 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 20,
    x: -3,
    y: 4,
    name: 'Headstrong',
    description: 'Attack cannot be lowered.',
    energy: '5',
    orb: '60',
    level: 1,
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 21,
    x: -1,
    y: 3,
    name: 'Poison Jab: Power 3',
    description: 'Poison Jab: Power ↑ 3',
    energy: '4',
    orb: '48',
    level: 1,
    color: 'green',
    icon: 'poison'
  },
  {
    id: 22,
    x: -2,
    y: 4,
    name: 'Poison Jab: Move Gauge Refresh 3',
    description: 'Move: Poison Jab Has a chance (40%) of charging the user’s move gauge by one when a move is successful.',
    energy: '7',
    orb: '84',
    level: 1,
    color: 'red',
    icon: 'passive'
  },
  {
    id: 23,
    x: -3,
    y: 5,
    name: 'Poison Jab: Power 3',
    description: 'Poison Jab: Power ↑ 3',
    energy: '4',
    orb: '48',
    level: 1,
    color: 'green',
    icon: 'poison'
  },
  {
    id: 24,
    x: -1,
    y: 4,
    name: 'Poison Jab: Superduper Effective 3',
    description: 'Move: Poison Jab Powers up moves that are super effective.',
    energy: '7',
    orb: '84',
    level: '2',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 25,
    x: -2,
    y: 5,
    name: 'Poison Jab: Power 3',
    description: 'Poison Jab: Power ↑ 3',
    energy: '4',
    orb: '48',
    level: '2',
    color: 'green',
    icon: 'poison'
  },
  {
    id: 26,
    x: -3,
    y: 6,
    name: 'HP 20',
    description: 'HP 20',
    energy: '4',
    orb: '48',
    level: '2',
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 27,
    x: -1,
    y: 5,
    name: 'Poison Jab: Furious Brawn',
    description: 'Move: Poison Jab The more the user’s Attack is raised, the more it powers up the user’s moves.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 28,
    x: -2,
    y: 6,
    name: 'Max Ooze: Power 100',
    description: 'Max Ooze: Power ↑ 100',
    energy: '8',
    orb: '96',
    level: '3',
    color: 'dynamax',
    icon: 'dynamax'
  },
  {
    id: 29,
    x: 2,
    y: -1,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 30,
    x: 3,
    y: -1,
    name: 'Iron Tail: Power 3',
    description: 'Iron Tail: Power ↑ 3',
    energy: '4',
    orb: '48',
    level: 1,
    color: 'green',
    icon: 'steel'
  },
  {
    id: 31,
    x: 2,
    y: 0,
    name: 'Iron Tail: Move Gauge Refresh 3',
    description: 'Move: Iron Tail Has a chance (40%) of charging the user’s move gauge by one when a move is successful.',
    energy: '7',
    orb: '84',
    level: 1,
    color: 'red',
    icon: 'passive'
  },
  {
    id: 32,
    x: 1,
    y: 1,
    name: 'Iron Tail: Power 3',
    description: 'Iron Tail: Power ↑ 3',
    energy: '4',
    orb: '48',
    level: 1,
    color: 'green',
    icon: 'steel'
  },
  {
    id: 33,
    x: 3,
    y: 0,
    name: 'Iron Tail: Power 3',
    description: 'Iron Tail: Power ↑ 3',
    energy: '4',
    orb: '48',
    level: '2',
    color: 'green',
    icon: 'steel'
  },
  {
    id: 34,
    x: 2,
    y: 1,
    name: 'Iron Tail: On a Roll 1',
    description: 'Move: Iron Tail Raises the chance of lowering stat values with the additional effects of moves.',
    energy: '8',
    orb: '96',
    level: '2',
    color: 'red',
    icon: 'passive'
  },
  {
    id: 35,
    x: 1,
    y: 2,
    name: 'Double Down 3',
    description: 'Powers up sync moves that are super effective.',
    energy: '8',
    orb: '96',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 36,
    x: 3,
    y: 1,
    name: 'Max Steelspike: Power 100',
    description: 'Max Steelspike: Power ↑ 100',
    energy: '8',
    orb: '96',
    level: '3',
    color: 'dynamax',
    icon: 'dynamax'
  },
  {
    id: 37,
    x: 2,
    y: 2,
    name: 'Super Syncer',
    description: 'Applies the Supereffective ↑ Next effect to the user the first time its sync move is used each battle.',
    energy: '9',
    orb: '108',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 38,
    x: -2,
    y: 1,
    name: 'Sand Shelter',
    description: 'Protects the user from damage from a sandstorm.',
    energy: '5',
    orb: '60',
    level: 1,
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 39,
    x: -3,
    y: 1,
    name: 'Speed 5',
    description: 'Speed 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 40,
    x: -2,
    y: 0,
    name: 'World of Pain!: MP Refresh 2',
    description: 'Move: World of Pain! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.',
    energy: '7',
    orb: '84',
    level: 1,
    color: 'red',
    icon: 'passive'
  },
  {
    id: 41,
    x: -1,
    y: -1,
    name: 'Sp. Def 5',
    description: 'Sp. Def 5',
    energy: '2',
    orb: '24',
    level: 1,
    color: 'blue',
    icon: 'stat'
  },
  {
    id: 42,
    x: -3,
    y: 0,
    name: 'Sands of Time 2',
    description: 'Quickly charges the move gauge during a sandstorm.',
    energy: '8',
    orb: '96',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 43,
    x: -2,
    y: -1,
    name: 'Surging Sand 2',
    description: 'Powers up the user’s moves during a sandstorm.',
    energy: '10',
    orb: '120',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 44,
    x: -1,
    y: -2,
    name: 'MAX Super Preparation',
    description: 'Applies the Supereffective ↑ Next effect to the user after using its max move.',
    energy: '9',
    orb: '108',
    level: '2',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 45,
    x: -3,
    y: -1,
    name: 'Haymaker',
    description: 'The more the user’s Attack is raised, the more it powers up the user’s sync moves.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 46,
    x: -2,
    y: -2,
    name: 'Rejuvenate 6',
    description: 'Charges the user’s move gauge by 6 after using a sync move.',
    energy: '10',
    orb: '120',
    level: '3',
    color: 'yellow',
    icon: 'passive'
  },
  {
    id: 47,
    x: 0,
    y: -3,
    name: 'Unstoppable Ambition Ground Impact: Power 25',
    description: 'Unstoppable Ambition Ground Impact: Power ↑ 25',
    energy: '5',
    orb: '60',
    level: '3',
    color: 'sync',
    icon: 'sync'
  },
  {
    id: 48,
    x: 0,
    y: 3,
    name: 'Unstoppable Ambition Ground Impact: Power 25',
    description: 'Unstoppable Ambition Ground Impact: Power ↑ 25',
    energy: '5',
    orb: '60',
    level: '3',
    color: 'sync',
    icon: 'sync'
  }
]