export const CYNTHIA_MILOTIC = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 1,
		"y": -2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 2,
		"y": -3,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 1,
		"y": -3,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": 3,
		"y": -4,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": 2,
		"y": -4,
		"name": "Peak Summer Muddy Water: Power 3",
		"description": "Peak Summer Muddy Water: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "water"
	},
	{
		"id": 12,
		"x": 1,
		"y": -4,
		"name": "Peak Summer Muddy Water: Power 3",
		"description": "Peak Summer Muddy Water: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 13,
		"x": 3,
		"y": -5,
		"name": "Peak Summer Muddy Water: Power 3",
		"description": "Peak Summer Muddy Water: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "water"
	},
	{
		"id": 14,
		"x": 2,
		"y": -5,
		"name": "Circle: HP Recovery 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action when a circle applies to the allied field of play.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 1,
		"y": -5,
		"name": "Sinnoh Solidarity: Initial Propulsion 1",
		"description": "Move: Sinnoh Solidarity",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": 3,
		"y": -6,
		"name": "Circle: MG → 2",
		"description": "Quickly charges the move gauge when a circle applies to the allied field of play.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": 2,
		"y": -6,
		"name": "Sinnoh C (Defensive) Extension 3",
		"description": "Extends the duration of Sinnoh Circle (Defensive) when Sinnoh Circle (Defensive) is applied to the allied field of play.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": -2,
		"y": 2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -3,
		"y": 3,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": -1,
		"y": 2,
		"name": "Water Gun: Power 4",
		"description": "Water Gun: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "water"
	},
	{
		"id": 21,
		"x": -2,
		"y": 3,
		"name": "Water Gun: Power 4",
		"description": "Water Gun: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "water"
	},
	{
		"id": 22,
		"x": -3,
		"y": 4,
		"name": "Water Gun: Power 4",
		"description": "Water Gun: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 23,
		"x": -1,
		"y": 3,
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -2,
		"y": 4,
		"name": "Defense 10",
		"description": "Defense 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 25,
		"x": -3,
		"y": 5,
		"name": "Focus Group 9",
		"description": "Raises the critical-hit rate of all allied sync pairs by one stat rank when the user’s Pokémon uses a move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -1,
		"y": 4,
		"name": "Water Gun: Staggering 2",
		"description": "Move: Water Gun",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": 1,
		"y": 1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 2,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": 1,
		"y": 2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": 3,
		"y": 1,
		"name": "Water Gun: Power 4",
		"description": "Water Gun: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "water"
	},
	{
		"id": 31,
		"x": 2,
		"y": 2,
		"name": "Water Gun: Power 4",
		"description": "Water Gun: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "water"
	},
	{
		"id": 32,
		"x": 1,
		"y": 3,
		"name": "Water Gun: Move Gauge Refresh 3",
		"description": "Move: Water Gun",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": 3,
		"y": 2,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": 2,
		"y": 3,
		"name": "Racing Rain 2",
		"description": "Quickly charges the move gauge when the weather is rainy.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 1,
		"y": 4,
		"name": "Entry: Team Evasiveness ↑ 2",
		"description": "Raises the evasiveness of all allied sync pairs by two stat ranks when the user enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": 3,
		"y": 3,
		"name": "Refreshing Rain 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action while the weather is rainy.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": 2,
		"y": 4,
		"name": "Vigilance",
		"description": "Protects the user against critical hits.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": -2,
		"y": 0,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -1,
		"y": -1,
		"name": "Clearheaded",
		"description": "Prevents the user from becoming confused.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": -3,
		"y": 0,
		"name": "Peak Summer Muddy Water: Power 3",
		"description": "Peak Summer Muddy Water: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "water"
	},
	{
		"id": 41,
		"x": -2,
		"y": -1,
		"name": "Peak Summer Muddy Water: Power 3",
		"description": "Peak Summer Muddy Water: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "water"
	},
	{
		"id": 42,
		"x": -1,
		"y": -2,
		"name": "Peak Summer Muddy Water: Move Gauge Refresh 3",
		"description": "Move: Peak Summer Muddy Water",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": -3,
		"y": -1,
		"name": "Sp. Def 10",
		"description": "Sp. Def 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 44,
		"x": -2,
		"y": -2,
		"name": "Team Hit Me Up 9",
		"description": "Raises one of the following stats of all allied sync pairs by one stat rank at random when the user is hit by an attack move: Attack, Defense, Sp. Atk, Sp. Def, or Speed.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -1,
		"y": -3,
		"name": "S-Move: Team Phys & Spec Boost ↑1 9",
		"description": "Increases the Physical Moves ↑ Next effect and Special Moves ↑ Next effect of all allied sync pairs by one rank after using the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -3,
		"y": -2,
		"name": "Burned Hit: MG ↑2 9",
		"description": "Charges the user’s move gauge by two when its attack move is successful while burned.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "Rumored Seaside Beauty Water Beam: Power 25",
		"description": "Rumored Seaside Beauty Water Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "Rumored Seaside Beauty Water Beam: Power 25",
		"description": "Rumored Seaside Beauty Water Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const LEON_SEISMITOAD = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 1,
		"y": -2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 2,
		"y": -3,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 1,
		"y": -3,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": 3,
		"y": -4,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": 2,
		"y": -4,
		"name": "Acid: Power 4",
		"description": "Acid: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 12,
		"x": 1,
		"y": -4,
		"name": "Acid: Power 4",
		"description": "Acid: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 13,
		"x": 3,
		"y": -5,
		"name": "Acid: Power 4",
		"description": "Acid: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 14,
		"x": 2,
		"y": -5,
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 1,
		"y": -5,
		"name": "Acid: On a Roll 9",
		"description": "Move: Acid",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": 3,
		"y": -6,
		"name": "Sp. Def 10",
		"description": "Sp. Def 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 17,
		"x": 2,
		"y": -6,
		"name": "Team Underhanded Heal 9",
		"description": "Restores the HP of all allied sync pairs when the user’s attack move is successful against targets that are affected by a status condition.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": -2,
		"y": 2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -3,
		"y": 3,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": -1,
		"y": 2,
		"name": "Bulldoze: Power 3",
		"description": "Bulldoze: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 21,
		"x": -2,
		"y": 3,
		"name": "Bulldoze: Power 3",
		"description": "Bulldoze: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 22,
		"x": -3,
		"y": 4,
		"name": "Bulldoze: Power 3",
		"description": "Bulldoze: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 23,
		"x": -1,
		"y": 3,
		"name": "Unbending",
		"description": "Defense cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -2,
		"y": 4,
		"name": "Defense 10",
		"description": "Defense 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 25,
		"x": -3,
		"y": 5,
		"name": "Vigilance",
		"description": "Protects the user against critical hits.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -1,
		"y": 4,
		"name": "Team Sync Regen",
		"description": "Applies the Gradual Healing effect to all allied sync pairs after the user uses a sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": 1,
		"y": 1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 2,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": 1,
		"y": 2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": 3,
		"y": 1,
		"name": "Acid: Power 4",
		"description": "Acid: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 31,
		"x": 2,
		"y": 2,
		"name": "Acid: Power 4",
		"description": "Acid: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 32,
		"x": 1,
		"y": 3,
		"name": "Acid: Move Gauge Refresh 3",
		"description": "Move: Acid",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": 3,
		"y": 2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": 2,
		"y": 3,
		"name": "So Excited!: Catalytic Kick 9",
		"description": "Move: So Excited!",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 1,
		"y": 4,
		"name": "First Aid 4",
		"description": "Restores the user’s HP by approximately 40% of its maximum HP the first time it is in a pinch each battle.",
		"energy": "8",
		"orb": "96",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": 3,
		"y": 3,
		"name": "So Excited!: MP Refresh 2",
		"description": "Move: So Excited!",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": 2,
		"y": 4,
		"name": "Interference Immunity",
		"description": "Prevents the user from flinching, becoming confused, or becoming trapped.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": -2,
		"y": 0,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -1,
		"y": -1,
		"name": "Lithe",
		"description": "Prevents the user from getting paralyzed.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": -3,
		"y": 0,
		"name": "Bulldoze: Power 3",
		"description": "Bulldoze: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 41,
		"x": -2,
		"y": -1,
		"name": "Bulldoze: Power 3",
		"description": "Bulldoze: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 42,
		"x": -1,
		"y": -2,
		"name": "Bulldoze: Move Gauge Refresh 3",
		"description": "Move: Bulldoze",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": -3,
		"y": -1,
		"name": "HP 20",
		"description": "HP 20",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 44,
		"x": -2,
		"y": -2,
		"name": "Dire Hit All +: MP Refresh 2",
		"description": "Move: Dire Hit All +",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -1,
		"y": -3,
		"name": "Dire Hit All +: Shielded 1",
		"description": "Move: Dire Hit All +",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -3,
		"y": -2,
		"name": "Dire Hit All +: Barricade Buddies 1",
		"description": "Move: Dire Hit All +",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "Enjoying the Hype of the Crowd Ground Impact: Power 25",
		"description": "Enjoying the Hype of the Crowd Ground Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "Enjoying the Hype of the Crowd Ground Impact: Power 25",
		"description": "Enjoying the Hype of the Crowd Ground Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const SKYLA_JUMPLUFF = [
	{
		"id": 1,
		"x": -1,
		"y": 0,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": -1,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": 1,
		"y": 0,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": 1,
		"y": -1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 2,
		"y": -1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 3,
		"y": -2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 2,
		"y": -2,
		"name": "Sunny Solar Beam: Power 4",
		"description": "Sunny Solar Beam: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 10,
		"x": 1,
		"y": -2,
		"name": "Sunny Solar Beam: Power 4",
		"description": "Sunny Solar Beam: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 11,
		"x": 3,
		"y": -3,
		"name": "Sunny Solar Beam: Power 4",
		"description": "Sunny Solar Beam: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 12,
		"x": 2,
		"y": -3,
		"name": "Solar Shield",
		"description": "Status conditions cannot be inflicted on the user when the weather is sunny.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": 1,
		"y": -3,
		"name": "Sunny Day: Brain Gain 9",
		"description": "Move: Sunny Day",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 14,
		"x": 3,
		"y": -4,
		"name": "Sync Burst 1",
		"description": "Restores one MP for the user the first time its sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 2,
		"y": -4,
		"name": "Sunny Day: Use Status P-Move: Sync CD ↓ 9",
		"description": "Move: Sunny Day",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": -2,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 17,
		"x": -3,
		"y": 2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 18,
		"x": -2,
		"y": 2,
		"name": "Bullet Seed: Power 1",
		"description": "Bullet Seed: Power ↑ 1",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 19,
		"x": -1,
		"y": 2,
		"name": "Bullet Seed: Power 1",
		"description": "Bullet Seed: Power ↑ 1",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 20,
		"x": -3,
		"y": 3,
		"name": "Bullet Seed: Power 1",
		"description": "Bullet Seed: Power ↑ 1",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 21,
		"x": -2,
		"y": 3,
		"name": "Bullet Seed: Move Gauge Refresh 3",
		"description": "Move: Bullet Seed",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 22,
		"x": -1,
		"y": 3,
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 23,
		"x": -3,
		"y": 4,
		"name": "Bullet Seed: Guaranteed Triple",
		"description": "Move: Bullet Seed",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -2,
		"y": 4,
		"name": "Bullet Seed: Unfortunate Strike 5",
		"description": "Move: Bullet Seed",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": 1,
		"y": 1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 26,
		"x": 2,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 27,
		"x": 3,
		"y": 1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 1,
		"y": 2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": 2,
		"y": 2,
		"name": "Bullet Seed: Power 1",
		"description": "Bullet Seed: Power ↑ 1",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 30,
		"x": 3,
		"y": 2,
		"name": "Bullet Seed: Power 1",
		"description": "Bullet Seed: Power ↑ 1",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 31,
		"x": 1,
		"y": 3,
		"name": "Sp. Atk 10",
		"description": "Sp. Atk 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 32,
		"x": 2,
		"y": 3,
		"name": "To the Skies!: Berserker 2",
		"description": "Move: To the Skies!",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": 3,
		"y": 3,
		"name": "To the Skies!: Hit and Heal 9",
		"description": "Move: To the Skies!",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": 1,
		"y": 4,
		"name": "To the Skies!: Team Brain Gain 9",
		"description": "Move: To the Skies!",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 2,
		"y": 4,
		"name": "Furious Brain",
		"description": "The more the user’s Sp. Atk is raised, the more it powers up the user’s moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": -1,
		"y": -1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": -2,
		"y": -1,
		"name": "Dauntless",
		"description": "Sp. Atk cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": -3,
		"y": -1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -1,
		"y": -2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": -2,
		"y": -2,
		"name": "Sunny Solar Beam: Power 4",
		"description": "Sunny Solar Beam: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 41,
		"x": -3,
		"y": -2,
		"name": "Sunny Solar Beam: Power 4",
		"description": "Sunny Solar Beam: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 42,
		"x": -1,
		"y": -3,
		"name": "Sunny Solar Beam: Move Gauge Refresh 3",
		"description": "Move: Sunny Solar Beam",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": -2,
		"y": -3,
		"name": "Healing Sun 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action while the weather is sunny.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -3,
		"y": -3,
		"name": "Speeding Sun 2",
		"description": "Quickly charges the move gauge when the weather is sunny.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -1,
		"y": -4,
		"name": "Solar Flare 9",
		"description": "Powers up the user’s sync move when the weather is sunny.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -2,
		"y": -4,
		"name": "Dashing Team 9",
		"description": "Raises the Speed of all allied sync pairs by one stat rank when the user’s attack move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "Floating Around the World Grass Beam: Power 25",
		"description": "Floating Around the World Grass Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "Floating Around the World Grass Beam: Power 25",
		"description": "Floating Around the World Grass Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const AS_SILVER_HOOH = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 0,
		"y": -2,
		"name": "HP 40",
		"description": "HP 40",
		"energy": "0",
		"orb": "5",
		"level": "2",
		"color": "divine",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 0,
		"y": -3,
		"name": "Golden Rule Divine Sacred Fire: Power 50",
		"description": "Golden Rule Divine Sacred Fire: Power ↑ 50",
		"energy": "0",
		"orb": "5",
		"level": "3",
		"color": "divine",
		"icon": "sync"
	},
	{
		"id": 9,
		"x": 0,
		"y": -4,
		"name": "Team Sharp Entry 3",
		"description": "Raises the critical-hit rate of all allied sync pairs by three stat ranks when the user enters a battle.",
		"energy": "0",
		"orb": "5",
		"level": "4",
		"color": "divine",
		"icon": "passive"
	},
	{
		"id": 10,
		"x": 0,
		"y": -5,
		"name": "Drought Alert 3",
		"description": "Extends the duration of sunny weather when the weather turns sunny while the user is on the field.",
		"energy": "0",
		"orb": "5",
		"level": "5",
		"color": "divine",
		"icon": "passive"
	},
	{
		"id": 11,
		"x": 1,
		"y": -2,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 12,
		"x": 2,
		"y": -2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 13,
		"x": 3,
		"y": -2,
		"name": "Sacred Fire: Power 3",
		"description": "Sacred Fire: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 14,
		"x": 2,
		"y": -3,
		"name": "Sacred Fire: Power 3",
		"description": "Sacred Fire: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 15,
		"x": 3,
		"y": -3,
		"name": "Sacred Fire: Power 3",
		"description": "Sacred Fire: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 16,
		"x": 2,
		"y": -4,
		"name": "Sacred Fire: Accuracy 5",
		"description": "Sacred Fire: Accuracy ↑ 5",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 17,
		"x": 3,
		"y": -4,
		"name": "Attack 10",
		"description": "Attack 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 18,
		"x": 3,
		"y": -5,
		"name": "Furious Brawn",
		"description": "The more the user’s Attack is raised, the more it powers up the user’s moves.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 19,
		"x": 1,
		"y": -4,
		"name": "Solar Flare 9",
		"description": "Powers up the user’s sync move when the weather is sunny.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 20,
		"x": 2,
		"y": -5,
		"name": "Hit Burned Opp: Stat ↓ 9",
		"description": "Lowers one of the target’s following stats by one stat rank at random when the user’s attack move is successful against a burned opponent: Attack, Defense, Sp. Atk, Sp. Def, Speed, accuracy, or evasiveness.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 21,
		"x": -2,
		"y": 2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 22,
		"x": -1,
		"y": 2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 23,
		"x": -2,
		"y": 3,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 24,
		"x": -1,
		"y": 3,
		"name": "Almighty Skies Sacred Fire: Power 3",
		"description": "Almighty Skies Sacred Fire: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 25,
		"x": -1,
		"y": 4,
		"name": "Almighty Skies Sacred Fire: Power 3",
		"description": "Almighty Skies Sacred Fire: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 26,
		"x": -3,
		"y": 3,
		"name": "Almighty Skies Sacred Fire: Power 3",
		"description": "Almighty Skies Sacred Fire: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 27,
		"x": -3,
		"y": 4,
		"name": "Pure and Strong!: Team Hit and Heal",
		"description": "Move: Pure and Strong!",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 28,
		"x": -2,
		"y": 4,
		"name": "Quick Tempo",
		"description": "Applies the Move Gauge Acceleration effect to the allied field of play the first time the user enters a battle each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": -3,
		"y": 5,
		"name": "Pure and Strong!: Move: Take Next “All” Move 9",
		"description": "Move: Pure and Strong!",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 30,
		"x": -2,
		"y": 5,
		"name": "Pure and Strong!: Berserk Bunch 4",
		"description": "Move: Pure and Strong!",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": 2,
		"y": 0,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 32,
		"x": 1,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 33,
		"x": 2,
		"y": 1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": 1,
		"y": 2,
		"name": "Almighty Skies Sacred Fire: Power 3",
		"description": "Almighty Skies Sacred Fire: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 35,
		"x": 1,
		"y": 3,
		"name": "Almighty Skies Sacred Fire: Power 3",
		"description": "Almighty Skies Sacred Fire: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 36,
		"x": 3,
		"y": 0,
		"name": "Almighty Skies Sacred Fire: Move Gauge Refresh 3",
		"description": "Move: Almighty Skies Sacred Fire",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": 3,
		"y": 1,
		"name": "Speeding Sun 2",
		"description": "Quickly charges the move gauge when the weather is sunny.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": 2,
		"y": 2,
		"name": "Healing Sun 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action while the weather is sunny.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 39,
		"x": 3,
		"y": 2,
		"name": "Team Solar Immunity",
		"description": "When the weather is sunny, status conditions cannot be inflicted on any allied sync pairs and prevents all allies from flinching, becoming confused, or becoming trapped.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": 2,
		"y": 3,
		"name": "Sunny: Team Attack Move DR 2",
		"description": "Reduces attack move damage taken by allies when the weather is sunny.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 41,
		"x": -2,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 42,
		"x": -1,
		"y": -1,
		"name": "Stalwart",
		"description": "Sp. Def cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": -3,
		"y": 1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 44,
		"x": -3,
		"y": 0,
		"name": "Sacred Fire: Power 3",
		"description": "Sacred Fire: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 45,
		"x": -2,
		"y": -1,
		"name": "Sacred Fire: Power 3",
		"description": "Sacred Fire: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "fire"
	},
	{
		"id": 46,
		"x": -3,
		"y": -1,
		"name": "Sacred Fire: Move Gauge Refresh 3",
		"description": "Move: Sacred Fire",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": -2,
		"y": -2,
		"name": "1st S-Move: Team Physical & Special Boost 1",
		"description": "Increases the Physical Moves ↑ Next effect and Special Moves ↑ Next effect of all allied sync pairs by one rank the first time the user’s sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 48,
		"x": -3,
		"y": -2,
		"name": "HP 20",
		"description": "HP 20",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 49,
		"x": -1,
		"y": -3,
		"name": "Adrenaline 1",
		"description": "Reduces the sync move countdown by one the first time the user’s sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 50,
		"x": -2,
		"y": -3,
		"name": "Endure Again",
		"description": "Except in certain circumstances, when the user’s Enduring effect activates for the first time and the user has 1 HP remaining, applies the Enduring effect to the user again each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 51,
		"x": 3,
		"y": -1,
		"name": "Golden Rule Divine Sacred Fire: Power 25",
		"description": "Golden Rule Divine Sacred Fire: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 52,
		"x": -3,
		"y": 2,
		"name": "Golden Rule Divine Sacred Fire: Power 25",
		"description": "Golden Rule Divine Sacred Fire: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const AS_ETHAN_LUGIA = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 0,
		"y": -2,
		"name": "Sp. Atk 20",
		"description": "Sp. Atk 20",
		"energy": "0",
		"orb": "5",
		"level": "2",
		"color": "divine",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 0,
		"y": -3,
		"name": "Silver Torrents Divine Aeroblast: Power 50",
		"description": "Silver Torrents Divine Aeroblast: Power ↑ 50",
		"energy": "0",
		"orb": "5",
		"level": "3",
		"color": "divine",
		"icon": "sync"
	},
	{
		"id": 9,
		"x": 0,
		"y": -4,
		"name": "1st S-Move: Restore B-Move MP 1",
		"description": "Restores one MP of the user’s buddy move the first time its sync move is used each battle.",
		"energy": "0",
		"orb": "5",
		"level": "4",
		"color": "divine",
		"icon": "passive"
	},
	{
		"id": 10,
		"x": 0,
		"y": -5,
		"name": "Flying Zone Extension 3",
		"description": "Extends the duration of the Flying Zone when the zone turns into a Flying Zone while the user is on the field.",
		"energy": "0",
		"orb": "5",
		"level": "5",
		"color": "divine",
		"icon": "passive"
	},
	{
		"id": 11,
		"x": 1,
		"y": -2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 12,
		"x": 2,
		"y": -2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 13,
		"x": 3,
		"y": -2,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 14,
		"x": 2,
		"y": -3,
		"name": "Aeroblast: Power 2",
		"description": "Aeroblast: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 15,
		"x": 3,
		"y": -3,
		"name": "Aeroblast: Power 2",
		"description": "Aeroblast: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 16,
		"x": 2,
		"y": -4,
		"name": "Aeroblast: Power 2",
		"description": "Aeroblast: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 17,
		"x": 3,
		"y": -4,
		"name": "Aeroblast: Move Gauge Refresh 3",
		"description": "Move: Aeroblast",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": 3,
		"y": -5,
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 19,
		"x": 1,
		"y": -4,
		"name": "Piercing Gaze",
		"description": "Moves never miss.",
		"energy": "9",
		"orb": "108",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 20,
		"x": 2,
		"y": -5,
		"name": "Debut: Sync Move Boost 4",
		"description": "Increases the user’s Sync Move ↑ Next effect by four ranks the first time it enters a battle each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 21,
		"x": -2,
		"y": 2,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 22,
		"x": -1,
		"y": 2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 23,
		"x": -2,
		"y": 3,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 24,
		"x": -1,
		"y": 3,
		"name": "Almighty Seas Aeroblast: Power 2",
		"description": "Almighty Seas Aeroblast: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 25,
		"x": -1,
		"y": 4,
		"name": "Almighty Seas Aeroblast: Power 2",
		"description": "Almighty Seas Aeroblast: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 26,
		"x": -3,
		"y": 3,
		"name": "Almighty Seas Aeroblast: Power 2",
		"description": "Almighty Seas Aeroblast: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 27,
		"x": -3,
		"y": 4,
		"name": "Shocking Slowdown 9",
		"description": "Lowers the target’s Speed by one stat rank when the user’s attack move is successful against a paralyzed opponent.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 28,
		"x": -2,
		"y": 4,
		"name": "Thunder Wave: Move Gauge Refresh 3",
		"description": "Move: Thunder Wave",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": -3,
		"y": 5,
		"name": "1st Use Status P-Move: Team Special Boost 1",
		"description": "Increases the Special Moves ↑ Next effect of all allied sync pairs by one rank the first time the user’s Pokémon uses a status move each battle.",
		"energy": "9",
		"orb": "108",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 30,
		"x": -2,
		"y": 5,
		"name": "1st Use Status P-Move: Damage Guard Next",
		"description": "Applies the Damage Guard Next effect to the user the first time its Pokémon uses a status move each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": 2,
		"y": 0,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 32,
		"x": 1,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 33,
		"x": 2,
		"y": 1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": 1,
		"y": 2,
		"name": "Aeroblast: Power 2",
		"description": "Aeroblast: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 35,
		"x": 1,
		"y": 3,
		"name": "Aeroblast: Power 2",
		"description": "Aeroblast: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 36,
		"x": 3,
		"y": 0,
		"name": "Aeroblast: Accuracy 5",
		"description": "Aeroblast: Accuracy ↑ 5",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 37,
		"x": 3,
		"y": 1,
		"name": "Thunder Wave: Super Preparation 9",
		"description": "Move: Thunder Wave",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": 2,
		"y": 2,
		"name": "Thunder Wave: Accuracy 10",
		"description": "Thunder Wave: Accuracy ↑ 10",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "green",
		"icon": "electric"
	},
	{
		"id": 39,
		"x": 3,
		"y": 2,
		"name": "Paralysis Synergy 3",
		"description": "Powers up the user’s moves when the target is paralyzed.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": 2,
		"y": 3,
		"name": "Aeroblast: Staggering 4",
		"description": "Move: Aeroblast",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 41,
		"x": -2,
		"y": 0,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 42,
		"x": -1,
		"y": -1,
		"name": "Unflappable",
		"description": "Prevents the user from flinching.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": -3,
		"y": 1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 44,
		"x": -3,
		"y": 0,
		"name": "Almighty Seas Aeroblast: Power 2",
		"description": "Almighty Seas Aeroblast: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 45,
		"x": -2,
		"y": -1,
		"name": "Almighty Seas Aeroblast: Power 2",
		"description": "Almighty Seas Aeroblast: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 46,
		"x": -3,
		"y": -1,
		"name": "Shining Soul!: Hit and Heal 9",
		"description": "Move: Shining Soul!",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": -2,
		"y": -2,
		"name": "Flying Zone: HP Recovery 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action when the zone is a Flying Zone.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 48,
		"x": -3,
		"y": -2,
		"name": "Aerial Acceleration 2",
		"description": "Quickly charges the move gauge when the zone is a Flying Zone.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 49,
		"x": -1,
		"y": -3,
		"name": "Adrenaline 1",
		"description": "Reduces the sync move countdown by one the first time the user’s sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 50,
		"x": -2,
		"y": -3,
		"name": "Static Shock 9",
		"description": "Powers up the user’s sync move when the target is paralyzed.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 51,
		"x": 3,
		"y": -1,
		"name": "Silver Torrents Divine Aeroblast: Power 25",
		"description": "Silver Torrents Divine Aeroblast: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 52,
		"x": -3,
		"y": 2,
		"name": "Silver Torrents Divine Aeroblast: Power 25",
		"description": "Silver Torrents Divine Aeroblast: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]