export const AKARI_MANAPHY = [
	{
		"id": 1,
		"x": "1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "1",
		"y": "0",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "-1",
		"y": "1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "-1",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "1",
		"y": "-2",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": "2",
		"y": "-3",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": "1",
		"y": "-3",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": "3",
		"y": "-4",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": "2",
		"y": "-4",
		"name": "Bubble: Power +4",
		"description": "Bubble: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 12,
		"x": "1",
		"y": "-4",
		"name": "Bubble: Power +4",
		"description": "Bubble: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 13,
		"x": "3",
		"y": "-5",
		"name": "Bubble: Power +4",
		"description": "Bubble: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 14,
		"x": "2",
		"y": "-5",
		"name": "Beautifully Flowing!: Team Hit and Heal",
		"description": "Applies the Gradual Healing effect to all allied sync pairs when the user’s move is successful.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": "1",
		"y": "-5",
		"name": "Bubble: Satisfied Snicker 9",
		"description": "Lowers the target’s Sp. Atk by one stat rank when the user’s attack move against it is successful.",
		"energy": "8",
		"orb": "96",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": "3",
		"y": "-6",
		"name": "Bubble: On a Roll 9",
		"description": "Raises the chance of lowering stat values with the additional effects of the user’s moves.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": "2",
		"y": "-6",
		"name": "Bubble: Overwhelm 9",
		"description": "Lowers the target’s Attack by one stat rank when the user’s attack move against it is successful.",
		"energy": "8",
		"orb": "96",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": "-2",
		"y": "2",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": "-3",
		"y": "3",
		"name": "Stalwart",
		"description": "Sp. Def cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 20,
		"x": "-1",
		"y": "2",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 21,
		"x": "-2",
		"y": "3",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 22,
		"x": "-3",
		"y": "4",
		"name": "Sitrus Berry: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 23,
		"x": "-1",
		"y": "3",
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": "-2",
		"y": "4",
		"name": "Racing Rain 2",
		"description": "Quickly charges the move gauge when the weather is rainy.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": "-3",
		"y": "5",
		"name": "1st Hit: Rainy",
		"description": "Makes the weather rainy the first time the user’s attack move is successful each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": "-1",
		"y": "4",
		"name": "Debut: Team Defense ↑ & Sp. Def ↑ 2",
		"description": "Raises the Defense and Sp. Def of all allied sync pairs by two stat ranks the first time the user enters a battle each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": "1",
		"y": "1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": "2",
		"y": "1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": "1",
		"y": "2",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": "3",
		"y": "1",
		"name": "Unbending",
		"description": "Defense cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": "2",
		"y": "2",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 32,
		"x": "1",
		"y": "3",
		"name": "HP +20",
		"description": "HP +20",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 33,
		"x": "3",
		"y": "2",
		"name": "Unflappable",
		"description": "Prevents the user from flinching.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": "2",
		"y": "3",
		"name": "Blue Seas Take Heart: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": "1",
		"y": "4",
		"name": "Team Rain Coat",
		"description": "Protects all allied sync pairs against critical hits when the weather is rainy.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": "3",
		"y": "3",
		"name": "Refreshing Rain 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action while the weather is rainy.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": "2",
		"y": "4",
		"name": "First Aid 4",
		"description": "Restores the user’s HP by approximately 40% of its maximum HP the first time it is in a pinch each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": "-2",
		"y": "0",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": "-1",
		"y": "-1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": "-3",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 41,
		"x": "-2",
		"y": "-1",
		"name": "Bubble: Power +4",
		"description": "Bubble: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 42,
		"x": "-1",
		"y": "-2",
		"name": "Bubble: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": "-3",
		"y": "-1",
		"name": "Bubble: Power +4",
		"description": "Bubble: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 44,
		"x": "-2",
		"y": "-2",
		"name": "Rain Gear 2",
		"description": "Reduces damage when the user is hit by an attack move while the weather is rainy.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": "-1",
		"y": "-3",
		"name": "Rainy: Team Moves ↑ 2",
		"description": "Powers up the moves of all allied sync pairs when the weather is rainy.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": "-3",
		"y": "-2",
		"name": "1st “Berry” MP 0: Restore “Berry” MP 1",
		"description": "Restores one MP of the user’s moves that have the Berry effect tag the first time the remaining MP for its moves that have the Berry effect tag is zero each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": "0",
		"y": "-3",
		"name": "Legend of the Sea Water Beam: Power +25",
		"description": "Legend of the Sea Water Beam: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": "0",
		"y": "3",
		"name": "Legend of the Sea Water Beam: Power +25",
		"description": "Legend of the Sea Water Beam: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const HAU_TAUROS = [
	{
		"id": 1,
		"x": "1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "1",
		"y": "0",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "-1",
		"y": "1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "-1",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "1",
		"y": "-2",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": "2",
		"y": "-3",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": "1",
		"y": "-3",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": "3",
		"y": "-4",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": "2",
		"y": "-4",
		"name": "Headbutt: Power +4",
		"description": "Headbutt: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 12,
		"x": "1",
		"y": "-4",
		"name": "Headbutt: Power +4",
		"description": "Headbutt: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 13,
		"x": "3",
		"y": "-5",
		"name": "Headbutt: Power +4",
		"description": "Headbutt: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 14,
		"x": "2",
		"y": "-5",
		"name": "Fail Forward 1",
		"description": "Charges the user’s move gauge by one when an opponent’s attack move targeting the user misses.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": "1",
		"y": "-5",
		"name": "Team Healing Entry",
		"description": "Applies the Gradual Healing effect to all allied sync pairs when the user enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": "3",
		"y": "-6",
		"name": "Sp. Def +10",
		"description": "Sp. Def +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 17,
		"x": "2",
		"y": "-6",
		"name": "Double Team: Team Mind-Bracing Infliction 2",
		"description": "Raises the Sp. Def of all allied sync pairs by two stat ranks the first time the user’s Pokémon uses a status move each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": "-2",
		"y": "2",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": "-3",
		"y": "3",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": "-1",
		"y": "2",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 21,
		"x": "-2",
		"y": "3",
		"name": "Headbutt: Power +4",
		"description": "Headbutt: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 22,
		"x": "-3",
		"y": "4",
		"name": "Headbutt: Move Gauge Refresh 2",
		"description": "Has a chance (30%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 23,
		"x": "-1",
		"y": "3",
		"name": "Headbutt: Power +4",
		"description": "Headbutt: Power +4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 24,
		"x": "-2",
		"y": "4",
		"name": "HP +20",
		"description": "HP +20",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 25,
		"x": "-3",
		"y": "5",
		"name": "Headbutt: Aggravation 1",
		"description": "Raises the chance of inflicting the flinching, confused, or trapped condition with the additional effects of moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": "-1",
		"y": "4",
		"name": "Headbutt: Overwhelm 9",
		"description": "Lowers the target’s Attack by one stat rank when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": "1",
		"y": "1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": "2",
		"y": "1",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": "1",
		"y": "2",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": "3",
		"y": "1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 31,
		"x": "2",
		"y": "2",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 32,
		"x": "1",
		"y": "3",
		"name": "Waiting for Ages!: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": "3",
		"y": "2",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": "2",
		"y": "3",
		"name": "Double Team: Move Gauge Refresh 9",
		"description": "Charges the user’s move gauge by one when its move is successful.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": "1",
		"y": "4",
		"name": "Slippery Slope 9",
		"description": "Raises the user’s evasiveness by one stat rank when an opponent’s attack move targeting the user misses.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": "3",
		"y": "3",
		"name": "Defense +10",
		"description": "Defense +10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": "2",
		"y": "4",
		"name": "Double Team: Team Body-Bracing Infliction 2",
		"description": "Raises the Defense of all allied sync pairs by two stat ranks the first time the user’s Pokémon uses a status move each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": "-2",
		"y": "0",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": "-1",
		"y": "-1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": "-3",
		"y": "0",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 41,
		"x": "-2",
		"y": "-1",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 42,
		"x": "-1",
		"y": "-2",
		"name": "Fast Runner",
		"description": "Evasiveness cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": "-3",
		"y": "-1",
		"name": "Dire Hit All +: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": "-2",
		"y": "-2",
		"name": "Catalyst",
		"description": "Applies the Move Gauge Acceleration effect to the allied field of play the first time the user’s sync move is used each battle.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": "-1",
		"y": "-3",
		"name": "Status Immunity",
		"description": "Status conditions cannot be inflicted on the user.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": "-3",
		"y": "-2",
		"name": "First Aid 4",
		"description": "Restores the user’s HP by approximately 40% of its maximum HP the first time it is in a pinch each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": "0",
		"y": "-3",
		"name": "Super Thrilling Ride Normal Impact: Power +25",
		"description": "Super Thrilling Ride Normal Impact: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": "0",
		"y": "3",
		"name": "Super Thrilling Ride Normal Impact: Power +25",
		"description": "Super Thrilling Ride Normal Impact: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const AREZU_BASCULEGION = [
	{
		"id": 1,
		"x": "1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "1",
		"y": "0",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "-1",
		"y": "1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "-1",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "1",
		"y": "-2",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": "2",
		"y": "-3",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": "1",
		"y": "-3",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": "3",
		"y": "-4",
		"name": "Normal Guard",
		"description": "Reduces damage when the user is attacked by Normal-type moves.",
		"energy": "8",
		"orb": "96",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 11,
		"x": "2",
		"y": "-4",
		"name": "Shadow Ball: Power +3",
		"description": "Shadow Ball: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 12,
		"x": "1",
		"y": "-4",
		"name": "Shadow Ball: Power +3",
		"description": "Shadow Ball: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 13,
		"x": "3",
		"y": "-5",
		"name": "Shadow Ball: Power +3",
		"description": "Shadow Ball: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 14,
		"x": "2",
		"y": "-5",
		"name": "Protect: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": "1",
		"y": "-5",
		"name": "Vigilance",
		"description": "Protects the user against critical hits.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": "3",
		"y": "-6",
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": "2",
		"y": "-6",
		"name": "Own Ally Faints: Sync Move Boost ↑10",
		"description": "Increases the user’s Sync Move ↑ Next effect by 10 ranks when an ally on your team faints.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": "-2",
		"y": "1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": "-3",
		"y": "2",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": "-2",
		"y": "2",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 21,
		"x": "-3",
		"y": "3",
		"name": "Souls’ Repose Last Respects: Power +2",
		"description": "Souls’ Repose Last Respects: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 22,
		"x": "-1",
		"y": "2",
		"name": "Souls’ Repose Last Respects: Power +2",
		"description": "Souls’ Repose Last Respects: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 23,
		"x": "-2",
		"y": "3",
		"name": "Souls’ Repose Last Respects: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": "-3",
		"y": "4",
		"name": "I Pack Quite a Punch!: Catalytic Kick 9",
		"description": "Applies the Move Gauge Acceleration effect to the allied field of play when the user’s move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": "-1",
		"y": "3",
		"name": "Furious Brawn",
		"description": "The more the user’s Attack is raised, the more it powers up the user’s moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": "-2",
		"y": "4",
		"name": "Endurance",
		"description": "Applies the Enduring effect to the user if its HP is full when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": "2",
		"y": "-1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": "3",
		"y": "-1",
		"name": "Headstrong",
		"description": "Attack cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": "2",
		"y": "0",
		"name": "Souls’ Repose Last Respects: Power +2",
		"description": "Souls’ Repose Last Respects: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 30,
		"x": "1",
		"y": "1",
		"name": "Souls’ Repose Last Respects: Power +2",
		"description": "Souls’ Repose Last Respects: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 31,
		"x": "3",
		"y": "0",
		"name": "Souls’ Repose Last Respects: Power +2",
		"description": "Souls’ Repose Last Respects: Power +2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 32,
		"x": "2",
		"y": "1",
		"name": "Interference Immunity",
		"description": "Prevents the user from flinching, becoming confused, or becoming trapped.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": "1",
		"y": "2",
		"name": "Brainpower",
		"description": "The more the user’s Sp. Atk is raised, the more it powers up its sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": "3",
		"y": "1",
		"name": "Healthy Healing",
		"description": "Applies the Gradual Healing effect to the user if its HP is full when it enters a battle.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": "2",
		"y": "2",
		"name": "Move: MG ↑2 9",
		"description": "Charges the user’s move gauge by two when its move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": "-1",
		"y": "-1",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": "-2",
		"y": "-1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 38,
		"x": "-1",
		"y": "-2",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": "-3",
		"y": "-1",
		"name": "Dauntless",
		"description": "Sp. Atk cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": "-2",
		"y": "-2",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 41,
		"x": "-3",
		"y": "-2",
		"name": "Shadow Ball: Power +3",
		"description": "Shadow Ball: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 42,
		"x": "-1",
		"y": "-3",
		"name": "Shadow Ball: Power +3",
		"description": "Shadow Ball: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 43,
		"x": "-2",
		"y": "-3",
		"name": "Shadow Ball: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": "-3",
		"y": "-3",
		"name": "Shadow Ball: On a Roll 4",
		"description": "Raises the chance of lowering stat values with the additional effects of the user’s moves.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": "-1",
		"y": "-4",
		"name": "Shadow Ball: Mind Games 9",
		"description": "Lowers the target’s Sp. Def by one stat rank when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": "-2",
		"y": "-4",
		"name": "Head Start 1",
		"description": "Reduces the user’s sync move countdown by one the first time it enters a battle each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": "0",
		"y": "-3",
		"name": "Raging Soul Carrier Ghost Impact: Power +25",
		"description": "Raging Soul Carrier Ghost Impact: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": "0",
		"y": "3",
		"name": "Raging Soul Carrier Ghost Impact: Power +25",
		"description": "Raging Soul Carrier Ghost Impact: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const AS_DIANTHA_GARDEVOIR = [
	{
		"id": 1,
		"x": "1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "1",
		"y": "0",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "-1",
		"y": "1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "-1",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "0",
		"y": "-2",
		"name": "Sp. Atk +20",
		"description": "Sp. Atk +20",
		"energy": "0",
		"orb": "5",
		"level": "2",
		"color": "divine",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": "0",
		"y": "-3",
		"name": "Sudden Light Divine Moonblast: Power +50",
		"description": "Sudden Light Divine Moonblast: Power +50",
		"energy": "0",
		"orb": "5",
		"level": "3",
		"color": "divine",
		"icon": "sync"
	},
	{
		"id": 9,
		"x": "0",
		"y": "-4",
		"name": "Almighty Moonblast: 1st Move: Restore MP 1",
		"description": "Restores one MP of the user’s move the first time that move is successful each battle.",
		"energy": "0",
		"orb": "5",
		"level": "4",
		"color": "divine",
		"icon": "passive"
	},
	{
		"id": 10,
		"x": "0",
		"y": "-5",
		"name": "1st S-Move: Sync Buff ↑ 1",
		"description": "Raises the sync buff of the user’s team by one rank the first time its sync move is used each battle.",
		"energy": "0",
		"orb": "5",
		"level": "5",
		"color": "divine",
		"icon": "passive"
	},
	{
		"id": 11,
		"x": "1",
		"y": "-2",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 12,
		"x": "2",
		"y": "-2",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 13,
		"x": "3",
		"y": "-2",
		"name": "Dauntless",
		"description": "Sp. Atk cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 14,
		"x": "2",
		"y": "-3",
		"name": "Almighty Dazzling Gleam: Power +3",
		"description": "Almighty Dazzling Gleam: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 15,
		"x": "3",
		"y": "-3",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 16,
		"x": "2",
		"y": "-4",
		"name": "Whimsical Acceleration 2",
		"description": "Quickly charges the move gauge when the zone is a Fairy Zone.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": "3",
		"y": "-4",
		"name": "Almighty Dazzling Gleam: Power +3",
		"description": "Almighty Dazzling Gleam: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 18,
		"x": "3",
		"y": "-5",
		"name": "Almighty Dazzling Gleam: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 19,
		"x": "1",
		"y": "-4",
		"name": "Almighty Dazzling Gleam: 1 on Opp Field & Hit: Special Boost ↑1 9",
		"description": "Increases the user’s Special Moves ↑ Next effect by one rank when its attack move is successful while there is only one Pokémon on the opponent’s field of play.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 20,
		"x": "2",
		"y": "-5",
		"name": "Brainpower",
		"description": "The more the user’s Sp. Atk is raised, the more it powers up its sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 21,
		"x": "-2",
		"y": "2",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 22,
		"x": "-1",
		"y": "2",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 23,
		"x": "-2",
		"y": "3",
		"name": "Almighty Moonblast: Power +3",
		"description": "Almighty Moonblast: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 24,
		"x": "-1",
		"y": "3",
		"name": "Almighty Moonblast: Power +3",
		"description": "Almighty Moonblast: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 25,
		"x": "-1",
		"y": "4",
		"name": "Almighty Moonblast: Power +3",
		"description": "Almighty Moonblast: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 26,
		"x": "-3",
		"y": "3",
		"name": "Quick Tempo",
		"description": "Applies the Move Gauge Acceleration effect to the allied field of play the first time the user enters a battle each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": "-3",
		"y": "4",
		"name": "Fairy Wish: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 28,
		"x": "-2",
		"y": "4",
		"name": "Fairy Zone: Attack Move DR 2",
		"description": "Reduces damage when the user is hit by an attack move while the zone is a Fairy Zone.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": "-3",
		"y": "5",
		"name": "1st S-Move: Kalos C (Spec) on Field",
		"description": "Applies Kalos Circle (Special) to the allied field of play the first time the user’s sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 30,
		"x": "-2",
		"y": "5",
		"name": "Kalos C (Spec) Extension 5",
		"description": "Extends the duration of Kalos Circle (Special) when Kalos Circle (Special) is applied to the allied field of play.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": "2",
		"y": "0",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 32,
		"x": "1",
		"y": "1",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 33,
		"x": "2",
		"y": "1",
		"name": "Almighty Dazzling Gleam: Power +3",
		"description": "Almighty Dazzling Gleam: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 34,
		"x": "1",
		"y": "2",
		"name": "Almighty Dazzling Gleam: Power +3",
		"description": "Almighty Dazzling Gleam: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 35,
		"x": "1",
		"y": "3",
		"name": "Almighty Dazzling Gleam: Power +3",
		"description": "Almighty Dazzling Gleam: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 36,
		"x": "3",
		"y": "0",
		"name": "HP +20",
		"description": "HP +20",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 37,
		"x": "3",
		"y": "1",
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": "2",
		"y": "2",
		"name": "Entry Freebie",
		"description": "Applies the Free Move Next effect to the user when it enters a battle.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 39,
		"x": "3",
		"y": "2",
		"name": "Hit: Sp. Atk ↓2 9",
		"description": "Lowers the target’s Sp. Atk by two stat ranks when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": "2",
		"y": "3",
		"name": "Brainteaser",
		"description": "The more the target’s Sp. Def is lowered, the more it powers up the user’s moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 41,
		"x": "-2",
		"y": "0",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 42,
		"x": "-1",
		"y": "-1",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 43,
		"x": "-3",
		"y": "1",
		"name": "Dragon Guard",
		"description": "Reduces damage when the user is attacked by Dragon-type moves.",
		"energy": "8",
		"orb": "96",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": "-3",
		"y": "0",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 45,
		"x": "-2",
		"y": "-1",
		"name": "Almighty Moonblast: Power +3",
		"description": "Almighty Moonblast: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 46,
		"x": "-3",
		"y": "-1",
		"name": "Almighty Moonblast: Power +3",
		"description": "Almighty Moonblast: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "fairy"
	},
	{
		"id": 47,
		"x": "-2",
		"y": "-2",
		"name": "Fairy Zone: HP Recovery 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action when the zone is a Fairy Zone.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 48,
		"x": "-3",
		"y": "-2",
		"name": "Almighty Moonblast: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 49,
		"x": "-1",
		"y": "-3",
		"name": "Sync Thinker 9",
		"description": "Increases the user’s Special Moves ↑ Next effect by one rank after using its sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 50,
		"x": "-2",
		"y": "-3",
		"name": "Ethereal Entrance",
		"description": "Turns the field of play’s zone into a Fairy Zone the first time the user enters a battle each battle. (A Fairy Zone powers up Fairy-type attacks.)",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 51,
		"x": "3",
		"y": "-1",
		"name": "Sudden Light Divine Moonblast: Power +25",
		"description": "Sudden Light Divine Moonblast: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 52,
		"x": "-3",
		"y": "2",
		"name": "Sudden Light Divine Moonblast: Power +25",
		"description": "Sudden Light Divine Moonblast: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const AS_GEETA_GLIMMORA = [
	{
		"id": 1,
		"x": "1",
		"y": "-1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": "1",
		"y": "0",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": "0",
		"y": "1",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": "-1",
		"y": "1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": "-1",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": "0",
		"y": "-1",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "0",
		"orb": "5",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": "0",
		"y": "-2",
		"name": "HP +40",
		"description": "HP +40",
		"energy": "0",
		"orb": "5",
		"level": "2",
		"color": "divine",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": "0",
		"y": "-3",
		"name": "Dazzling Brilliance Divine Mortal Spin: Power +50",
		"description": "Dazzling Brilliance Divine Mortal Spin: Power +50",
		"energy": "0",
		"orb": "5",
		"level": "3",
		"color": "divine",
		"icon": "sync"
	},
	{
		"id": 9,
		"x": "0",
		"y": "-4",
		"name": "Poison Zone Extension 3",
		"description": "Extends the duration of the Poison Zone when the zone turns into a Poison Zone while the user is on the field.",
		"energy": "0",
		"orb": "5",
		"level": "4",
		"color": "divine",
		"icon": "passive"
	},
	{
		"id": 10,
		"x": "0",
		"y": "-5",
		"name": "Almighty Venoshock: 1st Move: Sync CD ↓3 & Team Supereffective ↑ Next",
		"description": "Reduces the user’s sync move countdown by three the first time its move is successful each battle. Applies the Supereffective ↑ Next effect to all allied sync pairs the first time the user’s move is successful each battle.",
		"energy": "0",
		"orb": "5",
		"level": "5",
		"color": "divine",
		"icon": "passive"
	},
	{
		"id": 11,
		"x": "1",
		"y": "-2",
		"name": "Attack +5",
		"description": "Attack +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 12,
		"x": "2",
		"y": "-2",
		"name": "Defense +5",
		"description": "Defense +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 13,
		"x": "3",
		"y": "-2",
		"name": "Poison Guard",
		"description": "Reduces damage when the user is attacked by Poison-type moves.",
		"energy": "8",
		"orb": "96",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 14,
		"x": "2",
		"y": "-3",
		"name": "Almighty Mortal Spin: Power +3",
		"description": "Almighty Mortal Spin: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 15,
		"x": "3",
		"y": "-3",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 16,
		"x": "2",
		"y": "-4",
		"name": "Almighty Mortal Spin: Attack Trap 9",
		"description": "Leaves the target trapped when the user’s attack move against it is successful.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": "3",
		"y": "-4",
		"name": "Almighty Mortal Spin: Power +3",
		"description": "Almighty Mortal Spin: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 18,
		"x": "3",
		"y": "-5",
		"name": "Almighty Mortal Spin: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 19,
		"x": "1",
		"y": "-4",
		"name": "Impervious",
		"description": "The user’s stats cannot be lowered.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 20,
		"x": "2",
		"y": "-5",
		"name": "Opp Poisoned: Team Moves ↑ 2",
		"description": "Powers up the moves of all allied sync pairs when attacking a target that is poisoned or badly poisoned.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 21,
		"x": "-2",
		"y": "2",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 22,
		"x": "-1",
		"y": "2",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 23,
		"x": "-2",
		"y": "3",
		"name": "Almighty Venoshock: Power +3",
		"description": "Almighty Venoshock: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 24,
		"x": "-1",
		"y": "3",
		"name": "Almighty Venoshock: Power +3",
		"description": "Almighty Venoshock: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 25,
		"x": "-1",
		"y": "4",
		"name": "Almighty Venoshock: Power +3",
		"description": "Almighty Venoshock: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 26,
		"x": "-3",
		"y": "3",
		"name": "HP +20",
		"description": "HP +20",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 27,
		"x": "-3",
		"y": "4",
		"name": "Potion: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 28,
		"x": "-2",
		"y": "4",
		"name": "Potion: Master Healer 1",
		"description": "Increases the amount of HP restored by the user’s healing moves.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": "-3",
		"y": "5",
		"name": "Potion: Master Healer 1",
		"description": "Increases the amount of HP restored by the user’s healing moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 30,
		"x": "-2",
		"y": "5",
		"name": "Potion: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": "2",
		"y": "0",
		"name": "Speed +5",
		"description": "Speed +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 32,
		"x": "1",
		"y": "1",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 33,
		"x": "2",
		"y": "1",
		"name": "Almighty Mortal Spin: Power +3",
		"description": "Almighty Mortal Spin: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 34,
		"x": "1",
		"y": "2",
		"name": "Almighty Mortal Spin: Power +3",
		"description": "Almighty Mortal Spin: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 35,
		"x": "1",
		"y": "3",
		"name": "Almighty Mortal Spin: Power +3",
		"description": "Almighty Mortal Spin: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 36,
		"x": "3",
		"y": "0",
		"name": "The Guiding Light!: MP Refresh 2",
		"description": "Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": "3",
		"y": "1",
		"name": "Hit Poisoned Opp: HP Recovery 9",
		"description": "Restores the user’s HP when its attack move is successful against a poisoned or badly poisoned opponent.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": "2",
		"y": "2",
		"name": "Toxic Hit (Speed ↑) 9",
		"description": "Raises the user’s Speed by one stat rank when its attack move is successful against a poisoned or badly poisoned opponent.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 39,
		"x": "3",
		"y": "2",
		"name": "Safety Net",
		"description": "Applies the Enduring effect to all allied sync pairs the first time the user’s sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": "2",
		"y": "3",
		"name": "1st S-Move: Poison Zone",
		"description": "Turns the field of play’s zone into a Poison Zone the first time the user’s sync move is used each battle. (A Poison Zone powers up Poison-type attacks.)",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 41,
		"x": "-2",
		"y": "0",
		"name": "Sp. Def +5",
		"description": "Sp. Def +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 42,
		"x": "-1",
		"y": "-1",
		"name": "Sp. Atk +5",
		"description": "Sp. Atk +5",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 43,
		"x": "-3",
		"y": "1",
		"name": "Antitoxin",
		"description": "Prevents the user from getting poisoned or badly poisoned.",
		"energy": "5",
		"orb": "60",
		"level": "1",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": "-3",
		"y": "0",
		"name": "HP +10",
		"description": "HP +10",
		"energy": "2",
		"orb": "24",
		"level": "1",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 45,
		"x": "-2",
		"y": "-1",
		"name": "Almighty Venoshock: Power +3",
		"description": "Almighty Venoshock: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "1",
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 46,
		"x": "-3",
		"y": "-1",
		"name": "Almighty Venoshock: Power +3",
		"description": "Almighty Venoshock: Power +3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 47,
		"x": "-2",
		"y": "-2",
		"name": "Poisonous Acceleration 2",
		"description": "Quickly charges the move gauge when the zone is a Poison Zone.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 48,
		"x": "-3",
		"y": "-2",
		"name": "Almighty Venoshock: Move Gauge Refresh 3",
		"description": "Has a chance (40%) of charging the user’s move gauge by one when its move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 49,
		"x": "-1",
		"y": "-3",
		"name": "Poison Zone: Team Status Immunity",
		"description": "Status conditions cannot be inflicted on any allied sync pairs when the zone is a Poison Zone.",
		"energy": "9",
		"orb": "108",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 50,
		"x": "-2",
		"y": "-3",
		"name": "Poison Zone: Team S-Moves ↑ 3",
		"description": "Powers up the sync moves of all allied sync pairs when the zone is a Poison Zone.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 51,
		"x": "3",
		"y": "-1",
		"name": "Dazzling Brilliance Divine Mortal Spin: Power +25",
		"description": "Dazzling Brilliance Divine Mortal Spin: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 52,
		"x": "-3",
		"y": "2",
		"name": "Dazzling Brilliance Divine Mortal Spin: Power +25",
		"description": "Dazzling Brilliance Divine Mortal Spin: Power +25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]