export const GEETA_GLIMMORA = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 2,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 3,
		"y": -2,
		"name": "Mortal Spin: Power 2",
		"description": "Mortal Spin: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 9,
		"x": 2,
		"y": -2,
		"name": "Mortal Spin: Move Gauge Refresh 3",
		"description": "Move: Mortal Spin Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 10,
		"x": 1,
		"y": -2,
		"name": "Mortal Spin: Power 2",
		"description": "Mortal Spin: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 11,
		"x": 1,
		"y": -3,
		"name": "Mortal Spin: Power 2",
		"description": "Mortal Spin: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 12,
		"x": 2,
		"y": -3,
		"name": "Virulent Toxin 3",
		"description": "Powers up the user’s sync move when the target is poisoned or badly poisoned.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": 3,
		"y": -3,
		"name": "Potent Toxin 2",
		"description": "Increases the amount of damage an opponent takes from being poisoned or badly poisoned.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 14,
		"x": 2,
		"y": -4,
		"name": "Toxic Power 5",
		"description": "Powers up the user’s moves when the target is poisoned or badly poisoned.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 3,
		"y": -4,
		"name": "Ally Sets WTZ: Physical Boost ↑1 9",
		"description": "Increases the user’s Physical Moves ↑ Next effect by one rank when an ally activates a weather, terrain, or zone effect.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": -1,
		"y": 2,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 17,
		"x": -2,
		"y": 3,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 18,
		"x": -1,
		"y": 3,
		"name": "Antitoxin",
		"description": "Prevents the user from getting poisoned or badly poisoned.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 19,
		"x": -3,
		"y": 4,
		"name": "Sand Shelter",
		"description": "Protects the user from damage from a sandstorm.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 20,
		"x": -2,
		"y": 4,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 21,
		"x": -1,
		"y": 4,
		"name": "Mortal Spin: Power 2",
		"description": "Mortal Spin: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 22,
		"x": -3,
		"y": 5,
		"name": "Rock Slide: Power 3",
		"description": "Rock Slide: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 23,
		"x": -2,
		"y": 5,
		"name": "Poisonous Acceleration 2",
		"description": "Quickly charges the move gauge when the zone is a Poison Zone.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -1,
		"y": 5,
		"name": "Poison Zone: HP Recovery 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action when the zone is a Poison Zone.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": -3,
		"y": 6,
		"name": "Ruthless Toxin 9",
		"description": "Lowers one of the target’s following stats by two stat ranks at random when the user’s attack move is successful against a poisoned or badly poisoned opponent: Attack, Defense, Sp. Atk, Sp. Def, Speed, accuracy, or evasiveness.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -2,
		"y": 6,
		"name": "Blooming Mortal Spin: Propulsion 9",
		"description": "Move: Blooming Mortal Spin Reduces the user’s sync move countdown by one when its move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": 1,
		"y": 1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 2,
		"y": 1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": 1,
		"y": 2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": 3,
		"y": 1,
		"name": "Rock Slide: Power 3",
		"description": "Rock Slide: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 31,
		"x": 2,
		"y": 2,
		"name": "Rock Slide: Move Gauge Refresh 3",
		"description": "Move: Rock Slide Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 32,
		"x": 1,
		"y": 3,
		"name": "Rock Slide: Power 3",
		"description": "Rock Slide: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 33,
		"x": 3,
		"y": 2,
		"name": "Rock Slide: Accuracy 10",
		"description": "Rock Slide: Accuracy ↑ 10",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 34,
		"x": 2,
		"y": 3,
		"name": "Rock Slide: Aggravation 1",
		"description": "Move: Rock Slide Raises the chance of inflicting the flinching, confused, or trapped condition with the additional effects of moves.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 1,
		"y": 4,
		"name": "Rock Slide: Power 3",
		"description": "Rock Slide: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 36,
		"x": 3,
		"y": 3,
		"name": "Rock Slide: Superduper Effective 9",
		"description": "Move: Rock Slide Powers up moves that are super effective.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": 2,
		"y": 4,
		"name": "Impervious",
		"description": "The user’s stats cannot be lowered.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": -2,
		"y": 1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -3,
		"y": 1,
		"name": "Blooming Mortal Spin: Power 3",
		"description": "Blooming Mortal Spin: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 40,
		"x": -2,
		"y": 0,
		"name": "Blooming Mortal Spin: Power 3",
		"description": "Blooming Mortal Spin: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 41,
		"x": -1,
		"y": -1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 42,
		"x": -3,
		"y": 0,
		"name": "Poison Guard",
		"description": "Reduces damage when the user is attacked by Poison-type moves.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": -2,
		"y": -1,
		"name": "I’ll Guide You!: MP Refresh 2",
		"description": "Move: I’ll Guide You! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -1,
		"y": -2,
		"name": "Blooming Mortal Spin: Power 3",
		"description": "Blooming Mortal Spin: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "poison"
	},
	{
		"id": 45,
		"x": -3,
		"y": -1,
		"name": "I’ll Guide You!: Mighty Friend 9",
		"description": "Move: I’ll Guide You! When the user’s move targeting an allied sync pair (excluding field effects) is successful, increases the Physical Moves ↑ Next effect of the allied sync pair affected by the move by one rank.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -2,
		"y": -2,
		"name": "Haymaker",
		"description": "The more the user’s Attack is raised, the more it powers up the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": 3,
		"name": "Top Champion’s Guidance Mortal Spin: Power 25",
		"description": "Top Champion’s Guidance Mortal Spin: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": -3,
		"name": "Top Champion’s Guidance Mortal Spin: Power 25",
		"description": "Top Champion’s Guidance Mortal Spin: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const SKYLA_UNFEZANT = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 1,
		"y": -2,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 2,
		"y": -3,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 3,
		"y": -4,
		"name": "Unbending",
		"description": "Defense cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 10,
		"x": 1,
		"y": -3,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": 2,
		"y": -4,
		"name": "Brave Bird: Power 3",
		"description": "Brave Bird: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 12,
		"x": 3,
		"y": -5,
		"name": "Brave Bird: Power 3",
		"description": "Brave Bird: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 13,
		"x": 1,
		"y": -4,
		"name": "Brave Bird: Power 3",
		"description": "Brave Bird: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 14,
		"x": 2,
		"y": -5,
		"name": "Brave Bird: Move Gauge Refresh 3",
		"description": "Move: Brave Bird Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 3,
		"y": -6,
		"name": "Brawn Sync 3",
		"description": "Powers up the user’s sync move when its Attack is raised.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": 1,
		"y": -5,
		"name": "Furious Brawn",
		"description": "The more the user’s Attack is raised, the more it powers up the user’s moves.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": 2,
		"y": -6,
		"name": "Super Syncer",
		"description": "Applies the Supereffective ↑ Next effect to the user the first time its sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": -1,
		"y": 2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -2,
		"y": 3,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": -3,
		"y": 4,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 21,
		"x": -1,
		"y": 3,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 22,
		"x": -2,
		"y": 4,
		"name": "Aerial Ace: Power 4",
		"description": "Aerial Ace: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 23,
		"x": -3,
		"y": 5,
		"name": "Aerial Ace: Power 4",
		"description": "Aerial Ace: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 24,
		"x": -1,
		"y": 4,
		"name": "Aerial Ace: Power 4",
		"description": "Aerial Ace: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 25,
		"x": -2,
		"y": 5,
		"name": "Aerial Ace: Move Gauge Refresh 3",
		"description": "Move: Aerial Ace Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -3,
		"y": 6,
		"name": "Fast-Track 4",
		"description": "Has a chance (50%) of raising the user’s Speed by one stat rank when its Pokémon uses a move.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": -1,
		"y": 5,
		"name": "Aerial Ace: Berserker 1",
		"description": "Move: Aerial Ace Raises the user’s Attack by one stat rank when its move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 28,
		"x": -2,
		"y": 6,
		"name": "Aerial Ace: Flabbergast 4",
		"description": "Move: Aerial Ace Has a chance (50%) of leaving the target confused when a move targeting that opponent is successful.",
		"energy": "8",
		"orb": "96",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": 2,
		"y": -1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": 3,
		"y": -1,
		"name": "Aerial Ace: Power 4",
		"description": "Aerial Ace: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 31,
		"x": 2,
		"y": 0,
		"name": "Aerial Ace: Power 4",
		"description": "Aerial Ace: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 32,
		"x": 1,
		"y": 1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 33,
		"x": 3,
		"y": 0,
		"name": "Attack 10",
		"description": "Attack 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": 2,
		"y": 1,
		"name": "Takeoff Time!: Move Gauge Refresh 3",
		"description": "Move: Takeoff Time! Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 1,
		"y": 2,
		"name": "Headstrong",
		"description": "Attack cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": 3,
		"y": 1,
		"name": "Sky-High Joy Flying Impact: Power 25",
		"description": "Sky-High Joy Flying Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 37,
		"x": 2,
		"y": 2,
		"name": "Takeoff Time!: MP Refresh 2",
		"description": "Move: Takeoff Time! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": -2,
		"y": 1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -3,
		"y": 1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": -2,
		"y": 0,
		"name": "Brave Bird: Power 3",
		"description": "Brave Bird: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 41,
		"x": -1,
		"y": -1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 42,
		"x": -3,
		"y": 0,
		"name": "Brave Bird: Power 3",
		"description": "Brave Bird: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "flying"
	},
	{
		"id": 43,
		"x": -2,
		"y": -1,
		"name": "Dire Hit +: MP Refresh 2",
		"description": "Move: Dire Hit + Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -1,
		"y": -2,
		"name": "Super Freebie 2",
		"description": "Has a chance (30%) of applying the Free Move Next effect to the user when its move is super effective.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -3,
		"y": -1,
		"name": "Sky-High Joy Flying Impact: Power 25",
		"description": "Sky-High Joy Flying Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 46,
		"x": -2,
		"y": -2,
		"name": "Double Down 5",
		"description": "Powers up the user’s sync moves that are super effective.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "Sky-High Joy Flying Impact: Power 25",
		"description": "Sky-High Joy Flying Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "Sky-High Joy Flying Impact: Power 25",
		"description": "Sky-High Joy Flying Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const SILVER_TYRANITAR = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 1,
		"y": -2,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 2,
		"y": -3,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 3,
		"y": -4,
		"name": "Stone Edge: Accuracy 10",
		"description": "Stone Edge: Accuracy ↑ 10",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 10,
		"x": 1,
		"y": -3,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": 2,
		"y": -4,
		"name": "Stone Edge: Power 3",
		"description": "Stone Edge: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 12,
		"x": 3,
		"y": -5,
		"name": "Stone Edge: Power 3",
		"description": "Stone Edge: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 13,
		"x": 1,
		"y": -4,
		"name": "Stone Edge: Power 3",
		"description": "Stone Edge: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 14,
		"x": 2,
		"y": -5,
		"name": "Stone Edge: Move Gauge Refresh 3",
		"description": "Move: Stone Edge Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 3,
		"y": -6,
		"name": "Attack 10",
		"description": "Attack 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 16,
		"x": 1,
		"y": -5,
		"name": "Piercing Gaze",
		"description": "Moves never miss.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": 2,
		"y": -6,
		"name": "Sandstorm: Team Special DR 3",
		"description": "Reduces special attack move damage taken by allies during a sandstorm.",
		"energy": "9",
		"orb": "108",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": -1,
		"y": 2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -2,
		"y": 3,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": -3,
		"y": 4,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 21,
		"x": -1,
		"y": 3,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 22,
		"x": -2,
		"y": 4,
		"name": "Stone Edge: Power 3",
		"description": "Stone Edge: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 23,
		"x": -3,
		"y": 5,
		"name": "Stone Edge: Power 3",
		"description": "Stone Edge: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 24,
		"x": -1,
		"y": 4,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 25,
		"x": -2,
		"y": 5,
		"name": "Circle: MG → 2",
		"description": "Quickly charges the move gauge when a circle applies to the allied field of play.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -3,
		"y": 6,
		"name": "Circle: HP Recovery 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action when a circle applies to the allied field of play.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": -1,
		"y": 5,
		"name": "Johto C (Phys): S-Moves ↑ 9",
		"description": "Powers up the user’s sync move when Johto Circle (Physical) is applied to the allied field of play.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 28,
		"x": -2,
		"y": 6,
		"name": "Johto C (Phys) Extension 3",
		"description": "Extends the duration of Johto Circle (Physical) when Johto Circle (Physical) applies to the allied field of play.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": 2,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": 3,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 31,
		"x": 2,
		"y": 0,
		"name": "Massive Rock Slide: Power 3",
		"description": "Massive Rock Slide: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 32,
		"x": 1,
		"y": 1,
		"name": "Massive Rock Slide: Power 3",
		"description": "Massive Rock Slide: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 33,
		"x": 3,
		"y": 0,
		"name": "Sand Castle 2",
		"description": "Reduces damage when the user is hit by an attack move during a sandstorm.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": 2,
		"y": 1,
		"name": "Soothing Sand 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action during a sandstorm.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 1,
		"y": 2,
		"name": "Massive Rock Slide: Power 3",
		"description": "Massive Rock Slide: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 36,
		"x": 3,
		"y": 1,
		"name": "Sandstorm Hit: Physical Boost ↑1 9",
		"description": "Increases the user’s Physical Moves ↑ Next effect by one rank when its attack move is successful during a sandstorm.",
		"energy": "9",
		"orb": "108",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": 2,
		"y": 2,
		"name": "Sand Blaster 9",
		"description": "Powers up the user’s sync move during a sandstorm.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": -2,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -3,
		"y": 1,
		"name": "Headstrong",
		"description": "Attack cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": -2,
		"y": 0,
		"name": "Massive Rock Slide: Power 3",
		"description": "Massive Rock Slide: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 41,
		"x": -1,
		"y": -1,
		"name": "Massive Rock Slide: Power 3",
		"description": "Massive Rock Slide: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "rock"
	},
	{
		"id": 42,
		"x": -3,
		"y": 0,
		"name": "Attack 10",
		"description": "Attack 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 43,
		"x": -2,
		"y": -1,
		"name": "Eyes on Glory!: MP Refresh 2",
		"description": "Move: Eyes on Glory! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -1,
		"y": -2,
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -3,
		"y": -1,
		"name": "Entry: Physical Boost 2",
		"description": "Increases the user’s Physical Moves ↑ Next effect by two ranks when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -2,
		"y": -2,
		"name": "Eyes on Glory!: Propulsion 9",
		"description": "Move: Eyes on Glory! Reduces the user’s sync move countdown by one when its move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "Emotional Resolve Rock Slide: Power 25",
		"description": "Emotional Resolve Rock Slide: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "Emotional Resolve Rock Slide: Power 25",
		"description": "Emotional Resolve Rock Slide: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const ADAMAN_URSALUNA = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 1,
		"y": -2,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 2,
		"y": -3,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 3,
		"y": -4,
		"name": "Antitoxin",
		"description": "Prevents the user from getting poisoned or badly poisoned.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 10,
		"x": 1,
		"y": -3,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": 2,
		"y": -4,
		"name": "Hazy Headlong Rush: Power 4",
		"description": "Hazy Headlong Rush: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 12,
		"x": 3,
		"y": -5,
		"name": "Hazy Headlong Rush: Power 4",
		"description": "Hazy Headlong Rush: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 13,
		"x": 1,
		"y": -4,
		"name": "Hazy Headlong Rush: Power 4",
		"description": "Hazy Headlong Rush: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 14,
		"x": 2,
		"y": -5,
		"name": "Hazy Headlong Rush: Move Gauge Refresh 3",
		"description": "Move: Hazy Headlong Rush Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 3,
		"y": -6,
		"name": "Lessen Burn 9",
		"description": "Reduces damage from being burned. Mitigates the reduction of Attack due to being burned.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": 1,
		"y": -5,
		"name": "Haymaker",
		"description": "The more the user’s Attack is raised, the more it powers up the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": 2,
		"y": -6,
		"name": "Attack 30",
		"description": "Attack 30",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 18,
		"x": -1,
		"y": 2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -2,
		"y": 3,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 20,
		"x": -3,
		"y": 4,
		"name": "Facade: Power 4",
		"description": "Facade: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 21,
		"x": -1,
		"y": 3,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 22,
		"x": -2,
		"y": 4,
		"name": "Facade: Move Gauge Refresh 3",
		"description": "Move: Facade Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 23,
		"x": -3,
		"y": 5,
		"name": "Facade: Power 4",
		"description": "Facade: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 24,
		"x": -1,
		"y": 4,
		"name": "Facade: Power 4",
		"description": "Facade: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 25,
		"x": -2,
		"y": 5,
		"name": "Facade: Flabbergast 4",
		"description": "Move: Facade Has a chance (50%) of leaving the target confused when a move targeting that opponent is successful.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -3,
		"y": 6,
		"name": "Times Are Changing!: MP Refresh 2",
		"description": "Move: Times Are Changing! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": -1,
		"y": 5,
		"name": "Burned Hit: MG ↑2 9",
		"description": "Charges the user’s move gauge by two when its attack move is successful while burned.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 28,
		"x": -2,
		"y": 6,
		"name": "Burned Hit: Physical Boost ↑1 9",
		"description": "Increases the user’s Physical Moves ↑ Next effect by one rank when its attack move is successful while burned.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": 2,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": 3,
		"y": -1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 31,
		"x": 2,
		"y": 0,
		"name": "Hazy Headlong Rush: Power 4",
		"description": "Hazy Headlong Rush: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 32,
		"x": 1,
		"y": 1,
		"name": "Hazy Headlong Rush: Power 4",
		"description": "Hazy Headlong Rush: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ground"
	},
	{
		"id": 33,
		"x": 3,
		"y": 0,
		"name": "Initial Pinch Physical Boost 3",
		"description": "Increases the user’s Physical Moves ↑ Next effect by three ranks the first time it is in a pinch each battle.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 34,
		"x": 2,
		"y": 1,
		"name": "Potion: Master Healer 1",
		"description": "Move: Potion Increases the amount of HP restored by the user’s healing moves.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 1,
		"y": 2,
		"name": "Potion: MP Refresh 2",
		"description": "Move: Potion Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": 3,
		"y": 1,
		"name": "Pinch Push 3",
		"description": "Reduces the sync move countdown by three the first time the user is in a pinch each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": 2,
		"y": 2,
		"name": "Danger Damage Guard",
		"description": "Applies the Damage Guard Next effect to the user the first time its HP drops to half or below each battle.",
		"energy": "9",
		"orb": "108",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": -2,
		"y": 1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -3,
		"y": 1,
		"name": "Lithe",
		"description": "Prevents the user from getting paralyzed.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": -2,
		"y": 0,
		"name": "Facade: Power 4",
		"description": "Facade: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 41,
		"x": -1,
		"y": -1,
		"name": "Facade: Power 4",
		"description": "Facade: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "normal"
	},
	{
		"id": 42,
		"x": -3,
		"y": 0,
		"name": "Endurance",
		"description": "When the user enters battle with full HP, applies the Enduring effect to it.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": -2,
		"y": -1,
		"name": "Facade: Defense Crush 9",
		"description": "Move: Facade Lowers the target’s Defense by one stat rank when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -1,
		"y": -2,
		"name": "Pinch-Burned Hit: HP Recovery (M) 9",
		"description": "Restores the user’s HP when its attack move is successful while burned and in a pinch.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -3,
		"y": -1,
		"name": "Gritty 3",
		"description": "Powers up the user’s moves when it is affected by a status condition.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -2,
		"y": -2,
		"name": "Wounded Sync-Up 9",
		"description": "Powers up the user’s sync move when its HP is reduced.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "Moonlit Moves Ground Impact: Power 25",
		"description": "Moonlit Moves Ground Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "Moonlit Moves Ground Impact: Power 25",
		"description": "Moonlit Moves Ground Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const IRIDA_ZOROARK = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 1,
		"y": -2,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 2,
		"y": -3,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 3,
		"y": -4,
		"name": "Bitter Malice: Power 2",
		"description": "Bitter Malice: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 10,
		"x": 1,
		"y": -3,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": 2,
		"y": -4,
		"name": "Bitter Malice: Move Gauge Refresh 3",
		"description": "Move: Bitter Malice Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 12,
		"x": 3,
		"y": -5,
		"name": "Bitter Malice: Power 2",
		"description": "Bitter Malice: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 13,
		"x": 1,
		"y": -4,
		"name": "Bitter Malice: Power 2",
		"description": "Bitter Malice: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 14,
		"x": 2,
		"y": -5,
		"name": "Pokey Trap 2",
		"description": "Increases the amount of damage an opponent takes from being trapped.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 3,
		"y": -6,
		"name": "Hit Inter Opp: Supereffective ↑ Next 2",
		"description": "Has a chance (30%) of applying the Supereffective ↑ Next effect to the user when its attack move is successful against a flinching, confused, or trapped opponent.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": 1,
		"y": -5,
		"name": "Stationary Target 3",
		"description": "Powers up the user’s moves when the target is trapped.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": 2,
		"y": -6,
		"name": "Hit: Special Boost ↑1 4",
		"description": "Has a chance (50%) of increasing the user’s Special Moves ↑ Next effect by one rank when its attack move is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": -1,
		"y": 2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -2,
		"y": 3,
		"name": "Escape Artist",
		"description": "Prevents the user from becoming trapped.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 20,
		"x": -3,
		"y": 4,
		"name": "Mystifying Bitter Malice: Power 3",
		"description": "Mystifying Bitter Malice: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 21,
		"x": -1,
		"y": 3,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 22,
		"x": -2,
		"y": 4,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 23,
		"x": -3,
		"y": 5,
		"name": "Mystifying Bitter Malice: Power 3",
		"description": "Mystifying Bitter Malice: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 24,
		"x": -1,
		"y": 4,
		"name": "Mystifying Bitter Malice: Power 3",
		"description": "Mystifying Bitter Malice: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 25,
		"x": -2,
		"y": 5,
		"name": "Sync Thinker 9",
		"description": "Increases the user’s Special Moves ↑ Next effect by one rank after using its sync move.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -3,
		"y": 6,
		"name": "Fighting Guard",
		"description": "Reduces damage when the user is attacked by Fighting-type moves.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": -1,
		"y": 5,
		"name": "Pecking Order",
		"description": "The more the target’s Attack is lowered, the more it powers up the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 28,
		"x": -2,
		"y": 6,
		"name": "Terrify 2",
		"description": "Lowers the Attack of all opposing sync pairs by two stat ranks when the user enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 29,
		"x": 2,
		"y": -1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": 3,
		"y": -1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 31,
		"x": 2,
		"y": 0,
		"name": "Bitter Malice: Power 2",
		"description": "Bitter Malice: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 32,
		"x": 1,
		"y": 1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 33,
		"x": 3,
		"y": 0,
		"name": "Bitter Malice: Power 2",
		"description": "Bitter Malice: Power ↑ 2",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 34,
		"x": 2,
		"y": 1,
		"name": "Battle from the Heart!: MP Refresh 2",
		"description": "Move: Battle from the Heart! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 1,
		"y": 2,
		"name": "Group Slapdash 9",
		"description": "Raises the Speed of all allied sync pairs by one stat rank when an opponent’s attack move targeting the user misses.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": 3,
		"y": 1,
		"name": "Battle from the Heart!: Ramp Up 2",
		"description": "Move: Battle from the Heart! Raises the user’s Sp. Atk by two stat ranks when its move is successful.",
		"energy": "9",
		"orb": "108",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": 2,
		"y": 2,
		"name": "Battle from the Heart!: Slippery 2",
		"description": "Move: Battle from the Heart! Raises the user’s evasiveness by two stat ranks when its move is successful.",
		"energy": "9",
		"orb": "108",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": -2,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -3,
		"y": 1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": -2,
		"y": 0,
		"name": "Mystifying Bitter Malice: Power 3",
		"description": "Mystifying Bitter Malice: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 41,
		"x": -1,
		"y": -1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 42,
		"x": -3,
		"y": 0,
		"name": "Mystifying Bitter Malice: Power 3",
		"description": "Mystifying Bitter Malice: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "ghost"
	},
	{
		"id": 43,
		"x": -2,
		"y": -1,
		"name": "Dire Hit All +: MP Refresh 2",
		"description": "Move: Dire Hit All + Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -1,
		"y": -2,
		"name": "Ridicure 1",
		"description": "Has a chance (20%) of restoring the user’s HP by approximately 20% of its maximum HP when an opponent’s attack move targeting the user misses.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -3,
		"y": -1,
		"name": "Mind Boggler 9",
		"description": "Lowers the target’s Sp. Def by one stat rank when the user’s attack move is successful against a flinching, confused, or trapped opponent.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -2,
		"y": -2,
		"name": "Soften Up 1",
		"description": "Critical hits land more easily when the user attacks with a sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "Dancing to the Flute Ghost Beam: Power 25",
		"description": "Dancing to the Flute Ghost Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "Dancing to the Flute Ghost Beam: Power 25",
		"description": "Dancing to the Flute Ghost Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const TIERNO_CRAWDAUNT = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 1,
		"y": -2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 8,
		"x": 2,
		"y": -3,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 9,
		"x": 1,
		"y": -3,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 10,
		"x": 3,
		"y": -4,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 11,
		"x": 2,
		"y": -4,
		"name": "Night Slash: Power 4",
		"description": "Night Slash: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 12,
		"x": 1,
		"y": -4,
		"name": "Night Slash: Power 4",
		"description": "Night Slash: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 13,
		"x": 3,
		"y": -5,
		"name": "Night Slash: Power 4",
		"description": "Night Slash: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 14,
		"x": 2,
		"y": -5,
		"name": "Night Slash: Move Gauge Refresh 3",
		"description": "Move: Night Slash Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 15,
		"x": 1,
		"y": -5,
		"name": "Night Slash: Attack Trap 4",
		"description": "Move: Night Slash Has a chance (50%) of leaving the target trapped when the user’s attack move against it is successful.",
		"energy": "8",
		"orb": "96",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 16,
		"x": 3,
		"y": -6,
		"name": "Psychic Guard",
		"description": "Reduces damage when the user is attacked by Psychic-type moves.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 17,
		"x": 2,
		"y": -6,
		"name": "Night Slash: Trip Up 9",
		"description": "Move: Night Slash Lowers the target’s Speed by one stat rank when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 18,
		"x": -2,
		"y": 2,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 19,
		"x": -3,
		"y": 3,
		"name": "Flameproof",
		"description": "Prevents the user from getting burned.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 20,
		"x": -1,
		"y": 2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 21,
		"x": -2,
		"y": 3,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 22,
		"x": -3,
		"y": 4,
		"name": "Defense 10",
		"description": "Defense 10",
		"energy": "4",
		"orb": "48",
		"level": "2",
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 23,
		"x": -1,
		"y": 3,
		"name": "Unbending",
		"description": "Defense cannot be lowered.",
		"energy": "5",
		"orb": "60",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -2,
		"y": 4,
		"name": "X Defense All: MP Refresh 2",
		"description": "Move: X Defense All Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 25,
		"x": -3,
		"y": 5,
		"name": "Sterner Stuff 2",
		"description": "Reduces damage when the user is hit by a physical attack move.",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -1,
		"y": 4,
		"name": "Safety Tether",
		"description": "Applies the Enduring effect to the user the first time its sync move is used each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 27,
		"x": 1,
		"y": 1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 28,
		"x": 2,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 29,
		"x": 1,
		"y": 2,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 30,
		"x": 3,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 31,
		"x": 2,
		"y": 2,
		"name": "Night Slash: Power 4",
		"description": "Night Slash: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 32,
		"x": 1,
		"y": 3,
		"name": "Night Slash: Power 4",
		"description": "Night Slash: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "dark"
	},
	{
		"id": 33,
		"x": 3,
		"y": 2,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": 2,
		"y": 3,
		"name": "All Right!: MP Refresh 2",
		"description": "Move: All Right! Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 35,
		"x": 1,
		"y": 4,
		"name": "All Right!: Pep Rally 2",
		"description": "Move: All Right! Raises the Speed of all allied sync pairs by two stat ranks when the user’s move is successful.",
		"energy": "9",
		"orb": "108",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": 3,
		"y": 3,
		"name": "All Right!: Group Moral Support 9",
		"description": "Move: All Right! Raises the Sp. Def of all allied sync pairs by one stat rank when the user’s Trainer uses a move.",
		"energy": "10",
		"orb": "120",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 37,
		"x": 2,
		"y": 4,
		"name": "Synchro Healing 1",
		"description": "Restores the HP of all allied sync pairs by approximately 20% of their maximum HP after using the user’s sync move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": -2,
		"y": 0,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 39,
		"x": -1,
		"y": -1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 40,
		"x": -3,
		"y": 0,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 41,
		"x": -2,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 42,
		"x": -1,
		"y": -2,
		"name": "Quick Cure",
		"description": "Removes the confused, flinching, and trapped conditions from the user the first time they are inflicted each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 43,
		"x": -3,
		"y": -1,
		"name": "Natural Remedy",
		"description": "Removes all status conditions from the user the first time it is inflicted by any status condition each battle.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 44,
		"x": -2,
		"y": -2,
		"name": "Leer: Move Gauge Refresh 9",
		"description": "Move: Leer Charges the user’s move gauge by one when its move is successful.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 45,
		"x": -1,
		"y": -3,
		"name": "Leer: Catalytic Infliction",
		"description": "Move: Leer Applies the Move Gauge Acceleration effect to the allied field of play the first time the user’s Pokémon uses a status move each battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 46,
		"x": -3,
		"y": -2,
		"name": "Team Triage Tank 2",
		"description": "Has a chance (30%) of restoring the HP of all allied sync pairs when the user is hit by an attack move.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": 0,
		"y": -3,
		"name": "Best Dance Team Dark Impact: Power 25",
		"description": "Best Dance Team Dark Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 48,
		"x": 0,
		"y": 3,
		"name": "Best Dance Team Dark Impact: Power 25",
		"description": "Best Dance Team Dark Impact: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]

export const DAHLIA_LUDICOLO = [
	{
		"id": 1,
		"x": 1,
		"y": -1,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 2,
		"x": 1,
		"y": 0,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 3,
		"x": 0,
		"y": 1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 4,
		"x": -1,
		"y": 1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 5,
		"x": -1,
		"y": 0,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 6,
		"x": 0,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "0",
		"orb": "5",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 7,
		"x": 0,
		"y": -2,
		"name": "Racing Rain 2",
		"description": "Quickly charges the move gauge when the weather is rainy.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 8,
		"x": 0,
		"y": -4,
		"name": "MAX Countdown 2",
		"description": "Reduces the user’s sync move countdown by two after using its max move.",
		"energy": "10",
		"orb": "120",
		"level": "4",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 9,
		"x": 0,
		"y": -5,
		"name": "Discombobulate 9",
		"description": "Lowers the target’s accuracy by one stat rank when the user’s attack move against it is successful.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 10,
		"x": 0,
		"y": 2,
		"name": "Turbo Turf 2",
		"description": "Quickly charges the move gauge when the terrain is Grassy Terrain.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 11,
		"x": -1,
		"y": 4,
		"name": "Easy Pickings 9",
		"description": "Lowers one of the target’s following stats by one stat rank at random when the user’s attack move is successful against a confused opponent: Attack, Defense, Sp. Atk, Sp. Def, Speed, accuracy, or evasiveness.",
		"energy": "10",
		"orb": "120",
		"level": "4",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 12,
		"x": 1,
		"y": 3,
		"name": "Piercing Gaze",
		"description": "Moves never miss.",
		"energy": "10",
		"orb": "120",
		"level": "5",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 13,
		"x": 1,
		"y": -2,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 14,
		"x": 2,
		"y": -3,
		"name": "HP 10",
		"description": "HP 10",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 15,
		"x": 1,
		"y": -3,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 16,
		"x": 3,
		"y": -4,
		"name": "Muddy Water: Power 3",
		"description": "Muddy Water: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "water"
	},
	{
		"id": 17,
		"x": 2,
		"y": -4,
		"name": "Muddy Water: Power 3",
		"description": "Muddy Water: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "water"
	},
	{
		"id": 18,
		"x": 1,
		"y": -4,
		"name": "Muddy Water: Power 3",
		"description": "Muddy Water: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "water"
	},
	{
		"id": 19,
		"x": 3,
		"y": -5,
		"name": "Muddy Water: Accuracy 10",
		"description": "Muddy Water: Accuracy ↑ 10",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 20,
		"x": 2,
		"y": -5,
		"name": "Muddy Water: On a Roll 1",
		"description": "Move: Muddy Water Raises the chance of lowering stat values with the additional effects of the user’s moves.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 21,
		"x": 1,
		"y": -5,
		"name": "Max Move: Team Physical & Special Boost 1",
		"description": "Increases the Physical Moves ↑ Next effect and Special Moves ↑ Next effect of all allied sync pairs by one rank after using the user’s max move.",
		"energy": "9",
		"orb": "108",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 22,
		"x": 3,
		"y": -6,
		"name": "No Need to Worry ♪: MP Refresh 2",
		"description": "Move: No Need to Worry ♪ Has a chance (30%) of restoring one MP of the user’s move when that move is successful.",
		"energy": "7",
		"orb": "84",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 23,
		"x": 2,
		"y": -6,
		"name": "Sharp Entry 1",
		"description": "Raises the user’s critical-hit rate by one stat rank when it enters a battle.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 24,
		"x": -2,
		"y": 1,
		"name": "Attack 5",
		"description": "Attack 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 25,
		"x": -3,
		"y": 2,
		"name": "Clearheaded",
		"description": "Prevents the user from becoming confused.",
		"energy": "5",
		"orb": "60",
		"level": 1,
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 26,
		"x": -2,
		"y": 2,
		"name": "Razor Leaf: Power 4",
		"description": "Razor Leaf: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 27,
		"x": -3,
		"y": 3,
		"name": "Razor Leaf: Power 4",
		"description": "Razor Leaf: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 28,
		"x": -1,
		"y": 2,
		"name": "Razor Leaf: Power 4",
		"description": "Razor Leaf: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 29,
		"x": -2,
		"y": 3,
		"name": "Razor Leaf: Accuracy 5",
		"description": "Razor Leaf: Accuracy ↑ 5",
		"energy": "3",
		"orb": "36",
		"level": "2",
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 30,
		"x": -3,
		"y": 4,
		"name": "Teeter Dance: Move Gauge Refresh 9",
		"description": "Move: Teeter Dance Charges the user’s move gauge by one when its move is successful.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 31,
		"x": -1,
		"y": 3,
		"name": "Interference Sync 9",
		"description": "Powers up the user’s sync move against targets that are flinching, confused, or trapped.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 32,
		"x": -2,
		"y": 4,
		"name": "Razor Leaf: Confusion Synergy 9",
		"description": "Move: Razor Leaf Powers up the user’s moves when the target is confused.",
		"energy": "8",
		"orb": "96",
		"level": "3",
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 33,
		"x": 2,
		"y": -1,
		"name": "Speed 5",
		"description": "Speed 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 34,
		"x": 3,
		"y": -1,
		"name": "Razor Leaf: Power 4",
		"description": "Razor Leaf: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 35,
		"x": 2,
		"y": 0,
		"name": "Razor Leaf: Move Gauge Refresh 3",
		"description": "Move: Razor Leaf Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 36,
		"x": 1,
		"y": 1,
		"name": "Razor Leaf: Power 4",
		"description": "Razor Leaf: Power ↑ 4",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "grass"
	},
	{
		"id": 37,
		"x": 3,
		"y": 0,
		"name": "Empowering Overgrowth 5",
		"description": "Powers up the user’s moves when the terrain is Grassy Terrain.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 38,
		"x": 2,
		"y": 1,
		"name": "Grassy Cushion 2",
		"description": "Reduces damage when the user is hit by an attack move while the terrain is Grassy Terrain.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 39,
		"x": 1,
		"y": 2,
		"name": "Superduper 4",
		"description": "Has a chance (50%) of applying the Supereffective ↑ Next effect to the user when its move is super effective.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 40,
		"x": 3,
		"y": 1,
		"name": "Max Overgrowth: Power 100",
		"description": "Max Overgrowth: Power ↑ 100",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "dynamax",
		"icon": "dynamax"
	},
	{
		"id": 41,
		"x": 2,
		"y": 2,
		"name": "Grassy Terrain Extension 5",
		"description": "Extends the duration of Grassy Terrain when the terrain turns into Grassy Terrain while the user is on the field.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 42,
		"x": -1,
		"y": -1,
		"name": "Sp. Atk 5",
		"description": "Sp. Atk 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 43,
		"x": -2,
		"y": -1,
		"name": "Defense 5",
		"description": "Defense 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 44,
		"x": -1,
		"y": -2,
		"name": "Muddy Water: Power 3",
		"description": "Muddy Water: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "water"
	},
	{
		"id": 45,
		"x": -3,
		"y": -1,
		"name": "Sp. Def 5",
		"description": "Sp. Def 5",
		"energy": "2",
		"orb": "24",
		"level": 1,
		"color": "blue",
		"icon": "stat"
	},
	{
		"id": 46,
		"x": -2,
		"y": -2,
		"name": "Muddy Water: Move Gauge Refresh 3",
		"description": "Move: Muddy Water Has a chance (40%) of charging the user’s move gauge by one when a move is successful.",
		"energy": "7",
		"orb": "84",
		"level": 1,
		"color": "red",
		"icon": "passive"
	},
	{
		"id": 47,
		"x": -3,
		"y": -2,
		"name": "Muddy Water: Power 3",
		"description": "Muddy Water: Power ↑ 3",
		"energy": "3",
		"orb": "36",
		"level": 1,
		"color": "green",
		"icon": "water"
	},
	{
		"id": 48,
		"x": -1,
		"y": -3,
		"name": "Rainy Immunity",
		"description": "Status conditions cannot be inflicted on the user when the weather is rainy.",
		"energy": "9",
		"orb": "108",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 49,
		"x": -2,
		"y": -3,
		"name": "Refreshing Rain 1",
		"description": "Restores the user’s HP whenever its Pokémon takes an action while the weather is rainy.",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 50,
		"x": -3,
		"y": -3,
		"name": "Max Geyser: Power 100",
		"description": "Max Geyser: Power ↑ 100",
		"energy": "8",
		"orb": "96",
		"level": "2",
		"color": "dynamax",
		"icon": "dynamax"
	},
	{
		"id": 51,
		"x": -1,
		"y": -4,
		"name": "Raging Rain 5",
		"description": "Powers up the user’s moves when the weather is rainy.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 52,
		"x": -2,
		"y": -4,
		"name": "Flood Alert 5",
		"description": "Extends the duration of rainy weather when the weather turns rainy while the user is on the field.",
		"energy": "10",
		"orb": "120",
		"level": "3",
		"color": "yellow",
		"icon": "passive"
	},
	{
		"id": 53,
		"x": 0,
		"y": -3,
		"name": "Smiling Arcade Star Water Beam: Power 25",
		"description": "Smiling Arcade Star Water Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	},
	{
		"id": 54,
		"x": 0,
		"y": 3,
		"name": "Smiling Arcade Star Water Beam: Power 25",
		"description": "Smiling Arcade Star Water Beam: Power ↑ 25",
		"energy": "5",
		"orb": "60",
		"level": "3",
		"color": "sync",
		"icon": "sync"
	}
]